module

public import Mathlib.CategoryTheory.Sites.EqualizerSheafCondition
public import Mathlib.CategoryTheory.Sites.Pretopology
public import Mathlib.CategoryTheory.Sites.Sheaf
public import Mathlib.CategoryTheory.Sites.Spaces
public import Mathlib.Topology.Sheaves.SheafCondition.EqualizerProducts

/-!
# Presheaves and sheaves

This module formalizes the "Definitions" subsection of §3.3 (Presheaves and sheaves) of
*Stacks and Moduli*, section
label `sec:sheaves` (the subsection itself is unlabeled): presheaves on a category
(`def:presheaf`), representable presheaves (`ex:representable-presheaves`), and sheaves on
a site (`def:sheaf`, `eqn:sheaf-axiom`).

All of this material is available in Mathlib, so this file consists of `example`
declarations recalling the corresponding Mathlib declarations.

Main results:

- a presheaf is a functor `𝒮ᵒᵖ ⥤ Type w`, and `yoneda.obj S` is the presheaf represented
  by `S`;
- the sheaf condition is `CategoryTheory.Presieve.IsSheaf` (with respect to a Grothendieck
  topology) and `CategoryTheory.Presieve.IsSheafFor` (with respect to a single covering);
  its equalizer formulation is `CategoryTheory.Equalizer.Presieve.Arrows.sheaf_condition`;
- sheaves form the category `CategoryTheory.Sheaf`.

-/

@[expose] public section

-- These files were written when Lean's backward-compat defeq options were on by default.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

section DefPresheaf

open CategoryTheory

universe w v u

/- Result of the unlabeled opening discussion in Section 3.3: for a presheaf of
sets on a topological space, the sheaf axiom is equivalent to requiring, for every open
cover, that
$F(U) \to \prod_i F(U_i) \rightrightarrows \prod_{i,j} F(U_i \cap U_j)$
be an equalizer diagram. -/
example {X : TopCat.{u}} (F : TopCat.Presheaf (Type u) X) :
    F.IsSheaf ↔ F.IsSheafEqualizerProducts :=
  TopCat.Presheaf.isSheaf_iff_isSheafEqualizerProducts F

/- Background observation from Section 3.3 (the unlabeled opening discussion):
the intersection of two open subsets is their fiber product over the whole space. -/
example (X : Type u) [TopologicalSpace X] (U V : TopologicalSpace.Opens X) :
    Limits.pullback (homOfLE le_top : U ⟶ (⊤ : TopologicalSpace.Opens X))
      (homOfLE le_top : V ⟶ (⊤ : TopologicalSpace.Opens X)) = U ⊓ V :=
  Limits.CompleteLattice.pullback_eq_inf _ _

/- **Definition 3.3.1** (`def:presheaf`): a presheaf on a category $\cS$ is a contravariant
functor $\cS \to \Sets$; in Mathlib it is a functor `𝒮ᵒᵖ ⥤ Type w`. -/
example (𝒮 : Type u) [Category.{v} 𝒮] := 𝒮ᵒᵖ ⥤ Type w

/- Background example following Definition 3.3.1: if $F$ is a presheaf and
$f \colon S \to T$ is a map in $\cS$, the
pullback of an element $b \in F(T)$, denoted $f^* b$ or $b|_S$ in the book, is
`F.map f.op b`. -/
example {𝒮 : Type u} [Category.{v} 𝒮] (F : 𝒮ᵒᵖ ⥤ Type w) {S T : 𝒮} (f : S ⟶ T)
    (b : F.obj (Opposite.op T)) : F.obj (Opposite.op S) :=
  F.map f.op b

end DefPresheaf

section ExRepresentablePresheaves

open CategoryTheory

universe v u

/- **Example 3.3.3** (`ex:representable-presheaves`): for an object $S$ of a category $\cS$,
the assignment $T \mapsto \Mor_{\cS}(T, S)$ defines a presheaf on $\cS$: the Yoneda
embedding evaluated at `S`. -/
example {𝒮 : Type u} [Category.{v} 𝒮] (S : 𝒮) : 𝒮ᵒᵖ ⥤ Type v :=
  yoneda.obj S

end ExRepresentablePresheaves

section DefSheaf

open CategoryTheory

universe w t v u

/- **Definition 3.3.4** (`def:sheaf`): a sheaf on a site $(\cS, J)$ is a presheaf satisfying
the sheaf condition with respect to every covering. In Mathlib, `Presieve.IsSheafFor F R`
is the sheaf condition for a single covering `R`, and `Presieve.IsSheaf J F` imposes it for
all covering sieves of the Grothendieck topology `J`. -/
example {𝒮 : Type u} [Category.{v} 𝒮] (J : GrothendieckTopology 𝒮)
    (F : 𝒮ᵒᵖ ⥤ Type w) :
    Prop :=
  Presieve.IsSheaf J F

/- **Definition 3.3.4** (`def:sheaf`) (reduction to a pretopology): for the topology
generated by a pretopology — the book's sites are given by covering families — the sheaf
condition need only be checked on the covering families of the pretopology. -/
example {𝒮 : Type u} [Category.{v} 𝒮] [Limits.HasPullbacks 𝒮] (K : Pretopology 𝒮)
    (F : 𝒮ᵒᵖ ⥤ Type w) :
    Presieve.IsSheaf K.toGrothendieck F ↔
      ∀ {X : 𝒮} (R : Presieve X), R ∈ K X → Presieve.IsSheafFor F R :=
  Presieve.isSheaf_pretopology K

/- **Equation 3.3.5** (`eqn:sheaf-axiom`) (the sheaf axiom of Definition 3.3.4):
the sheaf condition for a covering $\{S_i \to S\}$ is the exactness of
$F(S) \to \prod_i F(S_i) \rightrightarrows \prod_{i,j} F(S_i \times_S S_j)$, i.e. that this
fork is an equalizer diagram. -/
example {𝒮 : Type u} [Category.{v} 𝒮] (F : 𝒮ᵒᵖ ⥤ Type w) {S : 𝒮}
    {ι : Type t} [Small.{w} ι]
    (X : ι → 𝒮) (π : ∀ i, X i ⟶ S) [(Presieve.ofArrows X π).HasPairwisePullbacks] :
    (Presieve.ofArrows X π).IsSheafFor F ↔
      Nonempty (Limits.IsLimit (Limits.Fork.ofι (Equalizer.Presieve.Arrows.forkMap F X π)
        (Equalizer.Presieve.Arrows.w F X π))) :=
  Equalizer.Presieve.Arrows.sheaf_condition F X π

/- Background example from Section 3.3 (unlabeled prose following Definition 3.3.4): a morphism of
presheaves or sheaves is by definition a natural transformation, i.e. a morphism in the
functor category. -/
example {𝒮 : Type u} [Category.{v} 𝒮] (F G : 𝒮ᵒᵖ ⥤ Type w) := F ⟶ G

/- Background example following Definition 3.3.4: the exactness of the sheaf sequence
means concretely that every compatible
family of elements $(a_i \in F(S_i))$ — one whose two restrictions to the "intersections"
agree — arises from a unique element of $F(S)$. This is literally Mathlib's definition of
`IsSheafFor`. -/
example {𝒮 : Type u} [Category.{v} 𝒮] (F : 𝒮ᵒᵖ ⥤ Type w) {S : 𝒮}
    (R : Presieve S) :
    R.IsSheafFor F ↔
      ∀ x : Presieve.FamilyOfElements F R, x.Compatible → ∃! t, x.IsAmalgamation t :=
  Iff.rfl

/- Background construction associated to Definition 3.3.4 (the category of sheaves): sheaves of sets on a site
form a category, whose morphisms are the morphisms of the underlying presheaves, i.e.
natural transformations (the unlabeled prose following the definition). -/
example {𝒮 : Type u} [Category.{v} 𝒮] (J : GrothendieckTopology 𝒮) :=
  Sheaf J (Type w)

example {𝒮 : Type u} [Category.{v} 𝒮] {J : GrothendieckTopology 𝒮}
    (F G : Sheaf J (Type w)) :
    (F ⟶ G) ≃ (F.obj ⟶ G.obj) :=
  ⟨fun f ↦ f.hom, fun f ↦ ⟨f⟩, fun _ ↦ rfl, fun _ ↦ rfl⟩

end DefSheaf
