module

public import StacksAndModuli.API.RepresentablePresheafDiagonal
public import StacksAndModuli.API.CoproductNonimmersion
public import StacksAndModuli.API.PresheafGroupoidCoequalizer
public import StacksAndModuli.API.PresheafGroupoidOfSchemesRelation
public import StacksAndModuli.API.PresheafSheafificationHom
public import StacksAndModuli.«Section4.4-Equivalence-Relations».«part4.4.4-algebraicity»
public import StacksAndModuli.«Section4.1-Definitions».«part4.1.1-representable-morphisms-and-algebraic-spaces»
public import Mathlib.AlgebraicGeometry.AffineSpace
public import Mathlib.AlgebraicGeometry.Limits
public import Mathlib.AlgebraicGeometry.Morphisms.Immersion
public import Mathlib.CategoryTheory.Sites.LocallyInjective
public import Mathlib.CategoryTheory.Sites.LocallySurjective
public import Mathlib.Data.Complex.Basic

/-!
# Examples of algebraic spaces

This module formalizes Subsection 4.9.1, "Examples of algebraic spaces"
(`subsec:examples-of-algebraic-spaces`), of §4.9 (Further examples) of *Stacks and
Moduli*, section label
`subsec:examples`. It covers `ex:smooth-three-fold-not-scheme` (Example 4.9.1),
`ex:bug-eyed-cover` (Example 4.9.2), `exer:bug-eyed-cover` (Exercise 4.9.4),
`exer:nodal-affine-line` (Exercise 4.9.5), `ex:affine-line-where-residue-field-jumps`
(Exercise 4.9.7 — an `exercise` environment despite the `ex:` prefix, see COMMENTARY.md)
and `rmk:typical-constructions-are-not-schemes` (Remark 4.9.9).

The flagship example is the *bug-eyed cover* (`ex:bug-eyed-cover`): the quotient of the
affine line $\bA^1$ over a field $\kk$ with $\operatorname{char} \kk \neq 2$ by the étale
equivalence relation $R = (\bZ/2 \times \bA^1) \setminus \{(-1, 0)\} \rightrightarrows
\bA^1$ obtained by restricting the sign involution; the quotient sheaf is an algebraic
space which is not a scheme. The same template with complex conjugation on $\bA^1_{\bC}$
over $\Spec \bR$ gives an affine line whose residue field jumps at the origin
(`ex:affine-line-where-residue-field-jumps`).

Main declarations:
- the bug-eyed cover's étale sheafification is an algebraic space whose diagonal is not
  an immersion, and hence is not a scheme;
- the squaring map from the bug-eyed cover is a universal homeomorphism, while the affine
  line is the categorical quotient among schemes;
- the conjugation quotient is an algebraic space that is not a scheme and whose diagonal
  is an immersion.
-/

@[expose] public section

-- These files were written when Lean's backward-compat defeq options were on by default.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

section ExSmoothThreeFoldNotScheme

/- LEDGER — **Example 4.9.1** (`ex:smooth-three-fold-not-scheme`): there exists a smooth
proper complex 3-fold $U$ with a free action of $\bZ/2$ such that some orbit is not
contained in an affine open (Hironaka's example,
`ex:quotients-by-free-actions-of-finite-groups`, Example 1.5.8, not formalized). The
quotient sheaf $X = U/(\bZ/2)$ is an algebraic space by
`cor:finite-quotient-algebraic-space` (Corollary 4.1.14), but is not a scheme: an affine
open around the image of the bad orbit would pull back, under the finite morphism
$U \to X$, to an affine open containing the orbit. Blocked on Hironaka's 3-fold (no
construction of it in Mathlib) and on the free-finite-group-quotient theory of §4.1
(Corollary 4.1.14); recorded as prose only. -/

end ExSmoothThreeFoldNotScheme

section ExBugEyedCover

open CategoryTheory Limits AlgebraicGeometry Topology

universe v u

namespace AlgebraicGeometry

variable {X : Scheme.{u}} {I : Type v} [Small.{u} I]

/-- Let $X$ be a scheme and let $(U_i)_{i \in I}$ be a family of open subschemes of $X$.
The disjoint union $R = \coprod_i U_i$, the total space of the relation on $X$ relating
$u \in U_i$ with $\sigma_i(u)$ for a family of morphisms $\sigma_i \colon X \to X$ (see
`AlgebraicGeometry.Scheme.partialEndRelFst` and
`AlgebraicGeometry.Scheme.partialEndRelSnd`). -/
noncomputable def Scheme.partialEndRel (U : I → X.Opens) : Scheme.{u} :=
  ∐ fun i ↦ (U i).toScheme

/-- Let $X$ be a scheme and let $(U_i)_{i \in I}$ be a family of open subschemes of $X$.
The first projection $\coprod_i U_i \to X$ of the relation generated by morphisms
restricted to the $U_i$: on each component the open immersion $U_i \to X$. -/
noncomputable def Scheme.partialEndRelFst (U : I → X.Opens) : Scheme.partialEndRel U ⟶ X :=
  Sigma.desc fun i ↦ (U i).ι

/-- Let $X$ be a scheme, $(U_i)_{i \in I}$ a family of open subschemes of $X$ and
$(\sigma_i \colon X \to X)_{i \in I}$ a family of morphisms. The second projection
$\coprod_i U_i \to X$ of the relation relating $u \in U_i$ with $\sigma_i(u)$: on the
$i$-th component the restriction of $\sigma_i$ to $U_i$. -/
noncomputable def Scheme.partialEndRelSnd (U : I → X.Opens) (σ : I → (X ⟶ X)) :
    Scheme.partialEndRel U ⟶ X :=
  Sigma.desc fun i ↦ (U i).ι ≫ σ i

/- The first projection of a partial-endomorphism relation is étale (it is an open
immersion on each component). Registered as an instance: it is keyed to the specific head
symbol `Scheme.partialEndRelFst`, so it cannot pollute general instance searches. -/
instance (U : I → X.Opens) : Etale (Scheme.partialEndRelFst U) :=
  IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance

/-- Let $X$ be a scheme, $(U_i)_{i \in I}$ open subschemes and
$(\sigma_i \colon X \to X)_{i \in I}$ morphisms. If every $\sigma_i$ is étale, then the
second projection $\coprod_i U_i \to X$, $u \mapsto \sigma_i(u)$, is étale. -/
lemma Scheme.etale_partialEndRelSnd (U : I → X.Opens) (σ : I → (X ⟶ X))
    (hσ : ∀ i, Etale (σ i)) : Etale (Scheme.partialEndRelSnd U σ) :=
  IsZariskiLocalAtSource.sigmaDesc fun i ↦
    have := hσ i
    inferInstance

/-- Let $X$ be a scheme, $(U_i)_{i \in I}$ a family of open subschemes and
$(\sigma_i \colon X \to X)_{i \in I}$ a family of morphisms. The quotient presheaf of the
relation relating $u \in U_i$ with $\sigma_i(u)$: the coequalizer, in presheaves on
$\Sch$, of the two projections $\coprod_i U_i \rightrightarrows X$. Its étale
sheafification is the quotient sheaf $X/R$. -/
noncomputable def Scheme.partialEndQuotientPresheaf (U : I → X.Opens) (σ : I → (X ⟶ X)) :
    Scheme.{u}ᵒᵖ ⥤ Type u :=
  coequalizer (yoneda.map (Scheme.partialEndRelFst U))
    (yoneda.map (Scheme.partialEndRelSnd U σ))

namespace AffineSpace

variable (n : Type u) (S : Scheme.{u})

/-- Let $S$ be a scheme. The coordinatewise negation $x \mapsto -x$ of the affine space
$\bA(n; S)$ over $S$. -/
noncomputable def neg : 𝔸(n; S) ⟶ 𝔸(n; S) :=
  homOfVector (𝔸(n; S) ↘ S) fun i ↦ -coord S i

/-- Coordinatewise negation of affine space is an involution. -/
@[reassoc]
lemma neg_comp_neg : neg n S ≫ neg n S = 𝟙 𝔸(n; S) := by
  apply hom_ext
  · simp [neg]
  · intro i
    simp [neg]

/- Coordinatewise negation of affine space is an isomorphism (it is its own inverse). -/
instance : IsIso (neg n S) :=
  ⟨neg n S, neg_comp_neg n S, neg_comp_neg n S⟩

/-- Let $S$ be a scheme and $m$ a natural number. The coordinatewise $m$-th power map
$x \mapsto x^m$ of the affine space $\bA(n; S)$ over $S$. -/
noncomputable def pow (m : ℕ) : 𝔸(n; S) ⟶ 𝔸(n; S) :=
  homOfVector (𝔸(n; S) ↘ S) fun i ↦ coord S i ^ m

/-- The coordinatewise squaring map of affine space is invariant under negation:
$(-x)^2 = x^2$. -/
@[reassoc]
lemma neg_comp_pow_two : neg n S ≫ pow n S 2 = pow n S 2 := by
  apply hom_ext
  · simp [neg, pow]
  · intro i
    simp [neg, pow]

end AffineSpace

variable (S : Scheme.{u})

/-- Background construction for Example 4.9.2: the family of open subschemes of
$\bA^1_S$ underlying the bug-eyed equivalence
relation $R = (\bZ/2 \times \bA^1) \setminus \{(-1, 0)\}$: the component of the identity
(`false`) is all of $\bA^1_S$, and the component of the sign involution (`true`) is the
complement $D(x)$ of the zero locus of the coordinate. -/
noncomputable def bugEyedRelOpens : Bool → (𝔸(PUnit.{u + 1}; S)).Opens
  | false => ⊤
  | true => (𝔸(PUnit.{u + 1}; S)).basicOpen (AffineSpace.coord S PUnit.unit)

/-- Background construction for Example 4.9.2: the identity on all of $\bA^1_S$ (`false`)
and the sign involution
$x \mapsto -x$ on the complement of the origin (`true`). -/
noncomputable def bugEyedRelAut : Bool → (𝔸(PUnit.{u + 1}; S) ⟶ 𝔸(PUnit.{u + 1}; S))
  | false => 𝟙 _
  | true => AffineSpace.neg PUnit.{u + 1} S

/- The second projection of the bug-eyed relation is étale: the identity and the sign
involution are isomorphisms. Registered as an instance (keyed to the specific defs, so it
cannot pollute general instance searches). -/
instance : Etale (Scheme.partialEndRelSnd (bugEyedRelOpens S) (bugEyedRelAut S)) :=
  Scheme.etale_partialEndRelSnd _ _ fun b ↦ by
    cases b <;> dsimp only [bugEyedRelAut] <;> infer_instance

/-- Background definition used in Example 4.9.2: for a scheme $S$, the quotient presheaf
$\bA^1_S/R$ of the bug-eyed
equivalence relation $(p_2, \sigma) \colon R = (\bZ/2 \times \bA^1) \setminus \{(-1, 0)\}
\rightrightarrows \bA^1$ obtained by restricting the sign involution $(-1) \cdot x = -x$
(the component over $-1 \in \bZ/2$ is the complement of the origin). Over a field of
characteristic $\neq 2$, its étale sheafification is the bug-eyed cover: an algebraic
space which is not a scheme. -/
noncomputable abbrev bugEyedCoverPresheaf : Scheme.{u}ᵒᵖ ⥤ Type u :=
  Scheme.partialEndQuotientPresheaf (bugEyedRelOpens S) (bugEyedRelAut S)

/- The projections of the bug-eyed relation $R \rightrightarrows \bA^1$ are étale (both
proved above). The supporting namespace `BugEyedCover` below supplies the remaining
groupoid operations and proves the monomorphism condition on
$R \to \bA^1 \times \bA^1$, packaging the relation as the étale equivalence relation of
`ex:equivalence-relation-bug-eyed-cover` (Example 4.4.4). -/

variable {k : Type u} [Field k]

/-- Supporting non-immersion theorem for Example 4.9.2: over a field, the morphism
$R = \bA^1 \amalg (\bA^1 \setminus 0) \to \bA^1 \times \bA^1$ given by the diagonal on
the first component and the graph of negation on the second is not a locally closed
immersion.  Indeed, the generic point on the second component specializes in the target
to the origin on the first component, although points in distinct coproduct components
cannot specialize to one another. -/
theorem not_isImmersion_bugEyedRelation :
    ¬ IsImmersion
      (prod.lift
        (Scheme.partialEndRelFst
          (bugEyedRelOpens (Spec (CommRingCat.of k))))
        (Scheme.partialEndRelSnd
          (bugEyedRelOpens (Spec (CommRingCat.of k)))
          (bugEyedRelAut (Spec (CommRingCat.of k))))) := by
  let S : Scheme.{u} := Spec (CommRingCat.of k)
  let A : Scheme.{u} := 𝔸(PUnit.{u + 1}; S)
  let U : Bool → A.Opens := bugEyedRelOpens S
  let σ : Bool → (A ⟶ A) := bugEyedRelAut S
  let zero : S ⟶ A := AffineSpace.homOfVector (𝟙 S) fun _ ↦ 0
  let one : S ⟶ A := AffineSpace.homOfVector (𝟙 S) fun _ ↦ 1
  have hzero_coord (i : PUnit.{u + 1}) :
      zero.appTop (AffineSpace.coord S i) = 0 := by
    dsimp only [zero]
    rw [AffineSpace.homOfVector_appTop_coord]
  have hzero_neg : zero ≫ AffineSpace.neg PUnit.{u + 1} S = zero := by
    rw [AffineSpace.neg, AffineSpace.comp_homOfVector]
    apply AffineSpace.hom_ext
    · simp [zero]
    · intro i
      rw [AffineSpace.homOfVector_appTop_coord]
      change zero.appTop (-AffineSpace.coord S i) = zero.appTop (AffineSpace.coord S i)
      rw [map_neg, hzero_coord]
      simp
  have hone : one default ∈ A.basicOpen (AffineSpace.coord S PUnit.unit) := by
    rw [← Scheme.Hom.mem_preimage]
    rw [Scheme.preimage_basicOpen_top, AffineSpace.homOfVector_appTop_coord]
    simp
  have hgeneric : genericPoint A ∈ A.basicOpen (AffineSpace.coord S PUnit.unit) :=
    (genericPoint_specializes (one default)).mem_open
      (A.basicOpen (AffineSpace.coord S PUnit.unit)).isOpen hone
  let x : (U true).toScheme := ⟨genericPoint A, hgeneric⟩
  let y : (U false).toScheme := ⟨zero default, by simp [U, bugEyedRelOpens]⟩
  let f : ∀ b, (U b).toScheme ⟶ A ⨯ A := fun b ↦
    prod.lift (U b).ι ((U b).ι ≫ σ b)
  let graphNeg : A ⟶ A ⨯ A :=
    prod.lift (𝟙 A) (AffineSpace.neg PUnit.{u + 1} S)
  let graphId : A ⟶ A ⨯ A := prod.lift (𝟙 A) (𝟙 A)
  have htrue : (U true).ι ≫ graphNeg = f true := by
    apply prod.hom_ext <;>
      simp [f, graphNeg, U, σ, bugEyedRelAut]
  have hfalse : (U false).ι ≫ graphId = f false := by
    apply prod.hom_ext
    · simp only [graphId, f, U, σ, bugEyedRelAut, Category.assoc,
        prod.lift_fst, Category.comp_id]
    · simp only [graphId, f, U, σ, bugEyedRelAut, Category.assoc,
        prod.lift_snd, Category.comp_id]
      exact (Category.comp_id _).symm
  have hgraph_zero : zero ≫ graphNeg = zero ≫ graphId := by
    apply prod.hom_ext
    · simp only [graphNeg, graphId, Category.assoc, prod.lift_fst]
    · simp only [graphNeg, graphId, Category.assoc, prod.lift_snd, hzero_neg]
      exact (Category.comp_id _).symm
  have hxy : f true x ⤳ f false y := by
    have hmap := (genericPoint_specializes (zero default)).map graphNeg.continuous
    have hx : f true x = graphNeg (genericPoint A) := by
      rw [← htrue, Scheme.Hom.comp_apply, Scheme.Opens.ι_apply]
    have hy : f false y = graphNeg (zero default) := by
      calc
        f false y = ((U false).ι ≫ graphId) y := by rw [hfalse]
        _ = graphId (zero default) := by
          simp only [Scheme.Hom.comp_apply]
          rfl
        _ = (zero ≫ graphId) default := by rw [Scheme.Hom.comp_apply]
        _ = (zero ≫ graphNeg) default := by rw [hgraph_zero]
        _ = graphNeg (zero default) := by rw [Scheme.Hom.comp_apply]
    rw [hx, hy]
    exact hmap
  have hf : ¬ IsImmersion (Sigma.desc f) :=
    not_isImmersion_sigmaDesc_of_specializes _ f (by decide : true ≠ false) hxy
  have heq : Sigma.desc f = prod.lift
      (Sigma.desc fun b ↦ (U b).ι) (Sigma.desc fun b ↦ (U b).ι ≫ σ b) := by
    apply Sigma.hom_ext
    intro b
    rw [Sigma.ι_desc]
    apply prod.hom_ext
    · rw [prod.lift_fst]
      rw [Category.assoc, prod.lift_fst, Sigma.ι_desc]
    · rw [prod.lift_snd]
      rw [Category.assoc, prod.lift_snd, Sigma.ι_desc]
  change ¬ IsImmersion (prod.lift
    (Sigma.desc fun b ↦ (U b).ι) (Sigma.desc fun b ↦ (U b).ι ≫ σ b))
  rw [← heq]
  exact hf

namespace BugEyedCover

/- The remaining construction equips the two-component relation with its groupoid
structure.  The identity component is all of the affine line, while negation restricts
to an involution of the punctured component. -/

lemma neg_preserves_relOpen :
    bugEyedRelOpens (Spec (CommRingCat.of k)) true ≤
      (AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k))) ⁻¹ᵁ
        bugEyedRelOpens (Spec (CommRingCat.of k)) true := by
  rw [show bugEyedRelOpens (Spec (CommRingCat.of k)) true =
    (AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k))).basicOpen
      (AffineSpace.coord (Spec (CommRingCat.of k)) PUnit.unit) by rfl]
  rw [Scheme.preimage_basicOpen_top]
  rw [AffineSpace.neg, AffineSpace.homOfVector_appTop_coord]
  rw [show -AffineSpace.coord (Spec (CommRingCat.of k)) PUnit.unit =
    (-1) * AffineSpace.coord (Spec (CommRingCat.of k)) PUnit.unit by simp]
  rw [Scheme.basicOpen_mul]
  rw [(AffineSpace PUnit.{u + 1}
    (Spec (CommRingCat.of k))).basicOpen_of_isUnit isUnit_neg_one]
  intro x hx
  exact ⟨Set.mem_univ x, hx⟩

noncomputable def identity :
    AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k)) ⟶
      ∐ fun b ↦ (bugEyedRelOpens
        (Spec (CommRingCat.of k)) b).toScheme :=
  (((AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k))).isoOfEq
    (show bugEyedRelOpens (Spec (CommRingCat.of k)) false = ⊤ by rfl)).trans
      (AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k))).topIso).inv ≫
        Sigma.ι (fun b ↦
          (bugEyedRelOpens (Spec (CommRingCat.of k)) b).toScheme) false

noncomputable def negRestriction :
    (bugEyedRelOpens (Spec (CommRingCat.of k)) true).toScheme ⟶
      (bugEyedRelOpens (Spec (CommRingCat.of k)) true).toScheme :=
  Scheme.Hom.resLE (AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k)))
    (bugEyedRelOpens (Spec (CommRingCat.of k)) true)
    (bugEyedRelOpens (Spec (CommRingCat.of k)) true)
    neg_preserves_relOpen

noncomputable def inverse :
    (∐ fun b ↦ (bugEyedRelOpens (Spec (CommRingCat.of k)) b).toScheme) ⟶
      ∐ fun b ↦ (bugEyedRelOpens (Spec (CommRingCat.of k)) b).toScheme :=
  Sigma.desc fun b ↦ match b with
    | false => Sigma.ι (fun b ↦
        (bugEyedRelOpens (Spec (CommRingCat.of k)) b).toScheme) false
    | true => negRestriction ≫ Sigma.ι (fun b ↦
        (bugEyedRelOpens (Spec (CommRingCat.of k)) b).toScheme) true

lemma identity_source : identity (k := k) ≫
    Scheme.partialEndRelFst (bugEyedRelOpens (Spec (CommRingCat.of k))) = 𝟙 _ := by
  simp [identity, Scheme.partialEndRelFst]
  simpa only [bugEyedRelOpens] using
    Scheme.toIso_inv_ι (AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k)))

lemma identity_target : identity (k := k) ≫
    Scheme.partialEndRelSnd (bugEyedRelOpens (Spec (CommRingCat.of k)))
      (bugEyedRelAut (Spec (CommRingCat.of k))) = 𝟙 _ := by
  simp [identity, Scheme.partialEndRelSnd, bugEyedRelAut]
  simpa only [bugEyedRelOpens] using
    Scheme.toIso_inv_ι (AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k)))

@[reassoc]
lemma negRestriction_comp_ι : negRestriction (k := k) ≫
    (bugEyedRelOpens (Spec (CommRingCat.of k)) true).ι =
      (bugEyedRelOpens (Spec (CommRingCat.of k)) true).ι ≫
        AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k)) := by
  simpa only [negRestriction] using
    Scheme.Hom.resLE_comp_ι
      (AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k)))
      neg_preserves_relOpen

lemma inverse_source : inverse (k := k) ≫
    Scheme.partialEndRelFst (bugEyedRelOpens (Spec (CommRingCat.of k))) =
      Scheme.partialEndRelSnd (bugEyedRelOpens (Spec (CommRingCat.of k)))
        (bugEyedRelAut (Spec (CommRingCat.of k))) := by
  dsimp only [Scheme.partialEndRelFst, Scheme.partialEndRelSnd,
    Scheme.partialEndRel]
  apply Sigma.hom_ext
  intro b
  cases b <;>
    simp [inverse, bugEyedRelAut, negRestriction_comp_ι (k := k)]

lemma inverse_target : inverse (k := k) ≫
    Scheme.partialEndRelSnd (bugEyedRelOpens (Spec (CommRingCat.of k)))
      (bugEyedRelAut (Spec (CommRingCat.of k))) =
      Scheme.partialEndRelFst (bugEyedRelOpens (Spec (CommRingCat.of k))) := by
  dsimp only [Scheme.partialEndRelFst, Scheme.partialEndRelSnd,
    Scheme.partialEndRel]
  apply Sigma.hom_ext
  intro b
  cases b <;>
    simp [inverse, bugEyedRelAut, negRestriction_comp_ι_assoc (k := k),
      AffineSpace.neg_comp_neg]

noncomputable abbrev A : Scheme.{u} :=
  AffineSpace PUnit.{u + 1} (Spec (CommRingCat.of k))

noncomputable abbrev U (b : Bool) : (A (k := k)).Opens :=
  bugEyedRelOpens (Spec (CommRingCat.of k)) b

noncomputable abbrev sourceComponent (b : Bool) :
    (U (k := k) b).toScheme ⟶ A (k := k) :=
  (U (k := k) b).ι

noncomputable abbrev targetComponent (b : Bool) :
    (U (k := k) b).toScheme ⟶ A (k := k) :=
  (U (k := k) b).ι ≫ bugEyedRelAut (Spec (CommRingCat.of k)) b

noncomputable def pullbackComparison :
    (∐ fun p : Bool × Bool ↦
      pullback (sourceComponent (k := k) p.1)
        (targetComponent (k := k) p.2)) ⟶
      pullback (Sigma.desc (sourceComponent (k := k)))
        (Sigma.desc (targetComponent (k := k))) :=
  Sigma.desc fun p ↦
    pullback.map (sourceComponent (k := k) p.1)
      (targetComponent (k := k) p.2)
      (Sigma.desc (sourceComponent (k := k)))
      (Sigma.desc (targetComponent (k := k)))
      (Sigma.ι (fun b ↦ (U (k := k) b).toScheme) p.1)
      (Sigma.ι (fun b ↦ (U (k := k) b).toScheme) p.2)
      (𝟙 _) (by simp) (by simp)

instance : IsIso (pullbackComparison (k := k)) := by
  apply CategoryTheory.FinitaryPreExtensive.isIso_sigmaDesc_map

noncomputable def toIdentityComponent :
    (U (k := k) true).toScheme ⟶ (U (k := k) false).toScheme :=
  (U (k := k) true).ι ≫
    (((A (k := k)).isoOfEq (show U (k := k) false = ⊤ by rfl)).trans
      (A (k := k)).topIso).inv

@[reassoc]
lemma toIdentityComponent_comp_ι : toIdentityComponent (k := k) ≫
    (U (k := k) false).ι = (U (k := k) true).ι := by
  simp [toIdentityComponent]
  change (U (k := k) true).ι ≫ (A (k := k)).topIso.inv ≫
    (⊤ : (A (k := k)).Opens).ι = (U (k := k) true).ι
  simp

noncomputable def compositionComponent (p : Bool × Bool) :
    pullback (sourceComponent (k := k) p.1)
      (targetComponent (k := k) p.2) ⟶
      ∐ fun b ↦ (U (k := k) b).toScheme :=
  match p with
  | (false, false) =>
      pullback.snd _ _ ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) false
  | (false, true) =>
      pullback.snd _ _ ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) true
  | (true, false) =>
      pullback.fst _ _ ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) true
  | (true, true) =>
      pullback.snd _ _ ≫ toIdentityComponent ≫
        Sigma.ι (fun b ↦ (U (k := k) b).toScheme) false

noncomputable def composition :
    pullback (Sigma.desc (sourceComponent (k := k)))
      (Sigma.desc (targetComponent (k := k))) ⟶
      ∐ fun b ↦ (U (k := k) b).toScheme :=
  inv pullbackComparison ≫ Sigma.desc (compositionComponent (k := k))

lemma composition_source : composition (k := k) ≫
    Sigma.desc (sourceComponent (k := k)) =
      pullback.snd (Sigma.desc (sourceComponent (k := k)))
        (Sigma.desc (targetComponent (k := k))) ≫
          Sigma.desc (sourceComponent (k := k)) := by
  rw [← cancel_epi (pullbackComparison (k := k))]
  apply Sigma.hom_ext
  rintro ⟨a, b⟩
  cases a <;> cases b <;>
    simp [composition, pullbackComparison, compositionComponent,
      sourceComponent, targetComponent, toIdentityComponent_comp_ι,
      bugEyedRelAut, Category.assoc, pullback.condition]

lemma composition_target : composition (k := k) ≫
    Sigma.desc (targetComponent (k := k)) =
      pullback.fst (Sigma.desc (sourceComponent (k := k)))
        (Sigma.desc (targetComponent (k := k))) ≫
          Sigma.desc (targetComponent (k := k)) := by
  rw [← cancel_epi (pullbackComparison (k := k))]
  apply Sigma.hom_ext
  rintro ⟨a, b⟩
  cases a <;> cases b <;>
    simp [composition, pullbackComparison, compositionComponent,
      sourceComponent, targetComponent, toIdentityComponent_comp_ι,
      bugEyedRelAut, Category.assoc, pullback.condition, pullback.condition_assoc,
      AffineSpace.neg_comp_neg]

/- A morphism from the spectrum of a field to the finite coproduct relation factors
through one component.  Reindexing by `ULift` puts the finite index in the universe
required by the point-level coproduct equivalence. -/

noncomputable def reindex :
    (∐ ((fun b : Bool ↦ (U (k := k) b).toScheme) ∘
      (Equiv.ulift : ULift.{u} Bool ≃ Bool))) ≅
      ∐ fun b : Bool ↦ (U (k := k) b).toScheme :=
  Sigma.reindex Equiv.ulift (fun b : Bool ↦ (U (k := k) b).toScheme)

noncomputable def component {K : Type u} [Field K]
    (x : Spec (CommRingCat.of K) ⟶ ∐ fun b ↦ (U (k := k) b).toScheme) : Bool :=
  ((sigmaMk (fun b : ULift.{u} Bool ↦
      (U (k := k) (Equiv.ulift b)).toScheme)).symm
    ((reindex (k := k)).inv (x default))).1 |> Equiv.ulift

noncomputable def componentLift {K : Type u} [Field K]
    (x : Spec (CommRingCat.of K) ⟶ ∐ fun b ↦ (U (k := k) b).toScheme) :
    Spec (CommRingCat.of K) ⟶ (U (k := k) (component x)).toScheme :=
  IsOpenImmersion.lift
    (Sigma.ι (fun b ↦ (U (k := k) b).toScheme) (component x)) x (by
      rintro y ⟨z, rfl⟩
      rw [show z = default from Subsingleton.elim _ _]
      let F : ULift.{u} Bool → Scheme.{u} :=
        (fun b : Bool ↦ (U (k := k) b).toScheme) ∘ Equiv.ulift
      let q := (sigmaMk F).symm ((reindex (k := k)).inv (x default))
      refine ⟨q.2, ?_⟩
      change (Sigma.ι (fun b ↦ (U (k := k) b).toScheme)
        (Equiv.ulift q.1)) q.2 = x default
      have hι : Sigma.ι F q.1 ≫ (reindex (k := k)).hom =
          Sigma.ι (fun b ↦ (U (k := k) b).toScheme) (Equiv.ulift q.1) := by
        simpa only [reindex, F] using
          Sigma.ι_reindex_hom Equiv.ulift
            (fun b : Bool ↦ (U (k := k) b).toScheme) q.1
      rw [← hι]
      rw [Scheme.Hom.comp_apply]
      have hmk : (Sigma.ι F q.1) q.2 = (sigmaMk F) q :=
        (sigmaMk_mk F q.1 q.2).symm
      calc
        _ = (reindex (k := k)).hom ((sigmaMk F) q) := congrArg _ hmk
        _ = (reindex (k := k)).hom ((reindex (k := k)).inv (x default)) := by
          rw [(sigmaMk F).apply_symm_apply]
        _ = x default := Scheme.inv_hom_apply (reindex (k := k)) (x default))

@[reassoc (attr := simp)]
lemma componentLift_fac {K : Type u} [Field K]
    (x : Spec (CommRingCat.of K) ⟶ ∐ fun b ↦ (U (k := k) b).toScheme) :
    componentLift x ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme)
      (component x) = x :=
  IsOpenImmersion.lift_fac _ _ _

noncomputable def componentLiftAt {K : Type u} [Field K]
    (x : Spec (CommRingCat.of K) ⟶ ∐ fun b ↦ (U (k := k) b).toScheme)
    (b : Bool) (h : component x = b) :
    Spec (CommRingCat.of K) ⟶ (U (k := k) b).toScheme :=
  componentLift x ≫ eqToHom (congrArg (fun b ↦ (U (k := k) b).toScheme) h)

@[reassoc (attr := simp)]
lemma componentLiftAt_fac {K : Type u} [Field K]
    (x : Spec (CommRingCat.of K) ⟶ ∐ fun b ↦ (U (k := k) b).toScheme)
    (b : Bool) (h : component x = b) :
    componentLiftAt x b h ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) b = x := by
  subst b
  simp [componentLiftAt]

lemma two_ne_zero_of_point [NeZero (2 : k)] {K : Type u} [Field K]
    (f : Spec (CommRingCat.of K) ⟶ A (k := k)) : (2 : K) ≠ 0 := by
  let φ : CommRingCat.of k ⟶ CommRingCat.of K :=
    (Scheme.ΓSpecIso (CommRingCat.of k)).inv ≫
      (f ≫ (A (k := k) ↘ Spec (CommRingCat.of k))).appTop ≫
      (Scheme.ΓSpecIso (CommRingCat.of K)).hom
  intro h
  have hmap : φ.hom (2 : k) = φ.hom 0 := by
    simpa only [map_ofNat, map_zero] using h
  have hkzero : (2 : k) = 0 := (RingHom.injective φ.hom) hmap
  exact NeZero.ne (2 : k) hkzero

lemma no_fixed_point [NeZero (2 : k)] {K : Type u} [Field K]
    (f : Spec (CommRingCat.of K) ⟶ A (k := k))
    (hD : ∃ g : Spec (CommRingCat.of K) ⟶ (U (k := k) true).toScheme,
      g ≫ (U (k := k) true).ι = f)
    (hfix : f ≫ AffineSpace.neg PUnit.{u + 1}
      (Spec (CommRingCat.of k)) = f) : False := by
  let coord : Γ(A (k := k), ⊤) :=
    AffineSpace.coord (Spec (CommRingCat.of k)) PUnit.unit
  have hneg_coord :
      (AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k))).appTop coord =
        -coord := by
    dsimp only [coord, AffineSpace.neg]
    rw [AffineSpace.homOfVector_appTop_coord]
  have hcoord : f.appTop coord = -f.appTop coord := by
    have h := congrArg (fun q : Spec (CommRingCat.of K) ⟶ A (k := k) ↦
      q.appTop coord) hfix
    rw [Scheme.Hom.comp_appTop, CommRingCat.comp_apply, hneg_coord, map_neg] at h
    exact h.symm
  let a : K := (Scheme.ΓSpecIso (CommRingCat.of K)).hom (f.appTop coord)
  have ha_neg : a = -a := by
    dsimp only [a]
    simpa only [map_neg] using congrArg
      (Scheme.ΓSpecIso (CommRingCat.of K)).hom.hom hcoord
  have ha : a = 0 := by
    have hmul : (2 : K) * a = 0 := by
      calc
        (2 : K) * a = a + a := two_mul a
        _ = -a + a := congrArg (fun x ↦ x + a) ha_neg
        _ = 0 := neg_add_cancel a
    rcases mul_eq_zero.mp hmul with htwo | ha
    · exact (two_ne_zero_of_point f htwo).elim
    · exact ha
  have hcoord_zero : f.appTop coord = 0 := by
    apply (ConcreteCategory.bijective_of_isIso
      (Scheme.ΓSpecIso (CommRingCat.of K)).hom).1
    dsimp only [a] at ha
    simpa only [map_zero] using ha
  obtain ⟨g, hg⟩ := hD
  have hmem : f default ∈ U (k := k) true := by
    rw [← hg, Scheme.Hom.comp_apply]
    exact (g default).2
  rw [← Scheme.Hom.mem_preimage] at hmem
  change default ∈ f ⁻¹ᵁ (A (k := k)).basicOpen coord at hmem
  rw [Scheme.preimage_basicOpen_top, hcoord_zero, Scheme.basicOpen_zero] at hmem
  exact hmem

noncomputable abbrev relationMap :
    (∐ fun b ↦ (U (k := k) b).toScheme) ⟶ A (k := k) ⨯ A (k := k) :=
  prod.lift (Sigma.desc (sourceComponent (k := k)))
    (Sigma.desc (targetComponent (k := k)))

lemma field_injective [NeZero (2 : k)] (K : Type u) [Field K] :
    Function.Injective (fun x : Spec (CommRingCat.of K) ⟶
      ∐ fun b ↦ (U (k := k) b).toScheme ↦ x ≫ relationMap (k := k)) := by
  intro x y hxy
  have hs : x ≫ Sigma.desc (sourceComponent (k := k)) =
      y ≫ Sigma.desc (sourceComponent (k := k)) := by
    simpa [relationMap] using congrArg (fun q ↦ q ≫ prod.fst) hxy
  have ht : x ≫ Sigma.desc (targetComponent (k := k)) =
      y ≫ Sigma.desc (targetComponent (k := k)) := by
    simpa [relationMap] using congrArg (fun q ↦ q ≫ prod.snd) hxy
  generalize hbx : component x = bx
  generalize hby : component y = cy
  let xl := componentLiftAt x bx hbx
  let yl := componentLiftAt y cy hby
  have hxf := componentLiftAt_fac x bx hbx
  have hyf := componentLiftAt_fac y cy hby
  rw [← hxf, ← hyf] at hs ht
  simp only [Category.assoc, Sigma.ι_desc] at hs ht
  cases bx <;> cases cy
  · have hLift : xl = yl := by
      apply (cancel_mono (U (k := k) false).ι).mp
      exact hs
    rw [← hxf, ← hyf]
    change xl ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) false =
      yl ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) false
    rw [hLift]
  · have hfix : (yl ≫ (U (k := k) true).ι) ≫
        AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k)) =
          yl ≫ (U (k := k) true).ι := by
      rw [Category.assoc]
      exact (by simpa only [targetComponent, bugEyedRelAut, Category.comp_id] using
        ht.symm.trans hs)
    exact (no_fixed_point (yl ≫ (U (k := k) true).ι) ⟨yl, rfl⟩ hfix).elim
  · have hfix : (xl ≫ (U (k := k) true).ι) ≫
        AffineSpace.neg PUnit.{u + 1} (Spec (CommRingCat.of k)) =
          xl ≫ (U (k := k) true).ι := by
      rw [Category.assoc]
      exact (by simpa only [targetComponent, bugEyedRelAut, Category.comp_id] using
        ht.trans hs.symm)
    exact (no_fixed_point (xl ≫ (U (k := k) true).ι) ⟨xl, rfl⟩ hfix).elim
  · have hLift : xl = yl := by
      apply (cancel_mono (U (k := k) true).ι).mp
      exact hs
    rw [← hxf, ← hyf]
    change xl ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) true =
      yl ≫ Sigma.ι (fun b ↦ (U (k := k) b).toScheme) true
    rw [hLift]

lemma universallyInjective_relationMap [NeZero (2 : k)] :
    UniversallyInjective (relationMap (k := k)) := by
  exact ((tfae_universallyInjective (relationMap (k := k))).out 0 1).mpr
    (field_injective (k := k))

lemma mono_relationMap [NeZero (2 : k)] : Mono (relationMap (k := k)) := by
  let f := relationMap (k := k)
  have hf_fst : f ≫ prod.fst = Sigma.desc (sourceComponent (k := k)) := by
    simp [f, relationMap]
  haveI : UniversallyInjective f := universallyInjective_relationMap (k := k)
  haveI : LocallyOfFiniteType (f ≫ prod.fst) := by
    rw [hf_fst]
    exact IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance
  haveI : LocallyOfFiniteType f := locallyOfFiniteType_of_comp f prod.fst
  haveI : FormallyUnramified (f ≫ prod.fst) := by
    rw [hf_fst]
    exact IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance
  haveI : FormallyUnramified f := FormallyUnramified.of_comp f prod.fst
  haveI : Surjective (pullback.diagonal f) :=
    ((tfae_universallyInjective f).out 0 3).mp
      (universallyInjective_relationMap (k := k))
  haveI : IsIso (pullback.diagonal f) :=
    (isIso_iff_isOpenImmersion_and_surjective _).mpr ⟨inferInstance, inferInstance⟩
  exact (pullback.isIso_diagonal_iff f).mp inferInstance

lemma relation_unique [NeZero (2 : k)] {T : Scheme.{u}}
    (x y : T ⟶ ∐ fun b ↦ (U (k := k) b).toScheme)
    (hs : x ≫ Sigma.desc (sourceComponent (k := k)) =
      y ≫ Sigma.desc (sourceComponent (k := k)))
    (ht : x ≫ Sigma.desc (targetComponent (k := k)) =
      y ≫ Sigma.desc (targetComponent (k := k))) : x = y := by
  haveI : Mono (relationMap (k := k)) := mono_relationMap (k := k)
  apply (cancel_mono (relationMap (k := k))).mp
  apply prod.hom_ext
  · simpa [relationMap] using hs
  · simpa [relationMap] using ht

noncomputable def groupoid [NeZero (2 : k)] : PresheafGroupoid.{u} :=
  PresheafGroupoid.ofSchemesOfRelation
    (Sigma.desc (sourceComponent (k := k)))
    (Sigma.desc (targetComponent (k := k)))
    (composition (k := k)) (identity (k := k)) (inverse (k := k))
    (composition_source (k := k)) (composition_target (k := k))
    (identity_source (k := k)) (identity_target (k := k))
    (inverse_source (k := k)) (inverse_target (k := k))
    (relation_unique (k := k))

lemma groupoid_isEquivalenceRelation [NeZero (2 : k)] :
    (groupoid (k := k)).IsEquivalenceRelation :=
  PresheafGroupoid.ofSchemesOfRelation_isEquivalenceRelation
    (Sigma.desc (sourceComponent (k := k)))
    (Sigma.desc (targetComponent (k := k)))
    (composition (k := k)) (identity (k := k)) (inverse (k := k))
    (composition_source (k := k)) (composition_target (k := k))
    (identity_source (k := k)) (identity_target (k := k))
    (inverse_source (k := k)) (inverse_target (k := k))
    (relation_unique (k := k))

instance [NeZero (2 : k)] : (groupoid (k := k)).IsEtale := by
  letI : Etale (Sigma.desc (sourceComponent (k := k))) :=
    IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance
  letI : Etale (Sigma.desc (targetComponent (k := k))) :=
    IsZariskiLocalAtSource.sigmaDesc fun b ↦ by
      cases b <;> dsimp only [targetComponent, bugEyedRelAut] <;> infer_instance
  exact PresheafGroupoid.ofSchemesOfRelation_isEtale
    (Sigma.desc (sourceComponent (k := k)))
    (Sigma.desc (targetComponent (k := k)))
    (composition (k := k)) (identity (k := k)) (inverse (k := k))
    (composition_source (k := k)) (composition_target (k := k))
    (identity_source (k := k)) (identity_target (k := k))
    (inverse_source (k := k)) (inverse_target (k := k))
    (relation_unique (k := k))

instance [NeZero (2 : k)] : (groupoid (k := k)).U.IsRepresentable := by
  change (yoneda.obj (A (k := k))).IsRepresentable
  infer_instance

instance [NeZero (2 : k)] : (groupoid (k := k)).R.IsRepresentable := by
  change (yoneda.obj (∐ fun b ↦ (U (k := k) b).toScheme)).IsRepresentable
  infer_instance

end BugEyedCover

/-- **Example 4.9.2** (`ex:bug-eyed-cover`) (the quotient is an algebraic space): let
$\kk$ be a field of characteristic $\neq 2$ and let $X$ be an étale sheafification of the
quotient presheaf of the bug-eyed equivalence relation
$R = (\bZ/2 \times \bA^1) \setminus \{(-1, 0)\} \rightrightarrows \bA^1$ over $\kk$. Then
$X$ is an algebraic space (the bug-eyed cover); it is smooth of dimension one. -/
theorem isAlgebraicSpace_of_isSheafificationHom_bugEyedCoverPresheaf [NeZero (2 : k)]
    {X : Scheme.{u}ᵒᵖ ⥤ Type u}
    (η : bugEyedCoverPresheaf (Spec (CommRingCat.of k)) ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    IsAlgebraicSpace X := by
  let G := BugEyedCover.groupoid (k := k)
  change coequalizer G.s G.t ⟶ X at η
  change Presheaf.IsSheafificationHom Scheme.etaleTopology η at hη
  have hq := G.isQuotientSheaf_of_isSheafificationHom_coequalizer η hη
  exact G.isAlgebraicSpace_of_isQuotientSheaf
    (BugEyedCover.groupoid_isEquivalenceRelation (k := k)) hq

/-- **Example 4.9.2** (`ex:bug-eyed-cover`) (the diagonal is not a locally closed
immersion): let $\kk$ be a field of characteristic $\neq 2$ and let $X$ be an étale
sheafification of the quotient presheaf of the bug-eyed equivalence relation
$R = (\bZ/2 \times \bA^1) \setminus \{(-1, 0)\} \rightrightarrows \bA^1$ over $\kk$. Then
the diagonal $X \to X \times X$ is not representable by schemes by locally closed
immersions: its base change along $\bA^1 \to X \times X$, $t \mapsto (t, -t)$, is
$(\bA^1 \setminus 0) \amalg \{0\} \to \bA^1$, which is not a locally closed immersion. -/
theorem not_presheaf_isImmersion_diagonal_of_isSheafificationHom_bugEyedCoverPresheaf
    [NeZero (2 : k)] {X : Scheme.{u}ᵒᵖ ⥤ Type u}
    (η : bugEyedCoverPresheaf (Spec (CommRingCat.of k)) ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    ¬ MorphismProperty.presheaf (@IsImmersion : MorphismProperty Scheme.{u})
      (prod.lift (𝟙 X) (𝟙 X)) := by
  intro hdiag
  let G := BugEyedCover.groupoid (k := k)
  change coequalizer G.s G.t ⟶ X at η
  change Presheaf.IsSheafificationHom Scheme.etaleTopology η at hη
  have hq := G.isQuotientSheaf_of_isSheafificationHom_coequalizer η hη
  have hpb := G.isPullback_relation_quotientSheafDiagonal
    (BugEyedCover.groupoid_isEquivalenceRelation (k := k)) hq
  have hst : MorphismProperty.presheaf
      (@IsImmersion : MorphismProperty Scheme.{u}) (prod.lift G.s G.t) :=
    (MorphismProperty.relative_isStableUnderBaseChange
      (@IsImmersion : MorphismProperty Scheme.{u})).of_isPullback hpb hdiag
  let A := BugEyedCover.A (k := k)
  let e : yoneda.obj (A ⨯ A) ≅ yoneda.obj A ⨯ yoneda.obj A :=
    asIso (prodComparison yoneda A A)
  let s₀ := Sigma.desc (BugEyedCover.sourceComponent (k := k))
  let t₀ := Sigma.desc (BugEyedCover.targetComponent (k := k))
  let r₀ := prod.lift s₀ t₀
  let st₀ := prod.lift (yoneda.map s₀) (yoneda.map t₀)
  change MorphismProperty.presheaf
    (@IsImmersion : MorphismProperty Scheme.{u}) st₀ at hst
  have hst₀ : MorphismProperty.presheaf
      (@IsImmersion : MorphismProperty Scheme.{u}) st₀ := hst
  have her : yoneda.map r₀ ≫ e.hom = st₀ := by
    apply prod.hom_ext
    · calc
        (yoneda.map r₀ ≫ e.hom) ≫ prod.fst =
            yoneda.map r₀ ≫ yoneda.map prod.fst := by
              simp only [e, asIso_hom, Category.assoc, prodComparison_fst]
              rfl
        _ = yoneda.map (r₀ ≫ prod.fst) := rfl
        _ = yoneda.map s₀ := by dsimp only [r₀]; rw [prod.lift_fst]
        _ = st₀ ≫ prod.fst := by exact (prod.lift_fst _ _).symm
    · calc
        (yoneda.map r₀ ≫ e.hom) ≫ prod.snd =
            yoneda.map r₀ ≫ yoneda.map prod.snd := by
              simp only [e, asIso_hom, Category.assoc, prodComparison_snd]
              rfl
        _ = yoneda.map (r₀ ≫ prod.snd) := rfl
        _ = yoneda.map t₀ := by dsimp only [r₀]; rw [prod.lift_snd]
        _ = st₀ ≫ prod.snd := by exact (prod.lift_snd _ _).symm
  have hrcomp : MorphismProperty.presheaf
      (@IsImmersion : MorphismProperty Scheme.{u}) (yoneda.map r₀ ≫ e.hom) := by
    rw [her]
    exact hst₀
  have hrmap : MorphismProperty.presheaf
      (@IsImmersion : MorphismProperty Scheme.{u}) (yoneda.map r₀) := by
    let _ : (MorphismProperty.presheaf
        (@IsImmersion : MorphismProperty Scheme.{u})).RespectsIso :=
      (MorphismProperty.relative_isStableUnderBaseChange
        (@IsImmersion : MorphismProperty Scheme.{u})).respectsIso
    have h := MorphismProperty.RespectsIso.postcomp
      (MorphismProperty.presheaf (@IsImmersion : MorphismProperty Scheme.{u}))
      e.inv (yoneda.map r₀ ≫ e.hom) hrcomp
    simpa using h
  have hrel : IsImmersion r₀ := MorphismProperty.of_relative_map hrmap
  change IsImmersion (BugEyedCover.relationMap (k := k)) at hrel
  exact not_isImmersion_bugEyedRelation (k := k) hrel

/-- **Example 4.9.2** (`ex:bug-eyed-cover`) (the quotient is not a scheme): let $\kk$ be
a field of characteristic $\neq 2$ and let $X$ be an étale sheafification of the quotient
presheaf of the bug-eyed equivalence relation
$R = (\bZ/2 \times \bA^1) \setminus \{(-1, 0)\} \rightrightarrows \bA^1$ over $\kk$. Then
the bug-eyed cover $X$ is not representable by a scheme: its diagonal is not a locally
closed immersion (see
`AlgebraicGeometry.not_presheaf_isImmersion_diagonal_of_isSheafificationHom_bugEyedCoverPresheaf`).
-/
theorem not_isRepresentable_of_isSheafificationHom_bugEyedCoverPresheaf [NeZero (2 : k)]
    {X : Scheme.{u}ᵒᵖ ⥤ Type u}
    (η : bugEyedCoverPresheaf (Spec (CommRingCat.of k)) ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    ¬ X.IsRepresentable := by
  intro hX
  exact not_presheaf_isImmersion_diagonal_of_isSheafificationHom_bugEyedCoverPresheaf
    η hη (@presheaf_isImmersion_diag_of_isRepresentable _ hX)

end AlgebraicGeometry

end ExBugEyedCover

section ExerBugEyedCover

open CategoryTheory Limits AlgebraicGeometry

universe u

namespace AlgebraicGeometry

variable (S : Scheme.{u})

/-- The two projections of the bug-eyed relation on $\bA^1_S$ are coequalized by the
coordinatewise squaring map: $x^2 = (-x)^2$. -/
@[reassoc]
lemma bugEyedRel_fst_comp_pow_two :
    Scheme.partialEndRelFst (bugEyedRelOpens S) ≫ AffineSpace.pow PUnit.{u + 1} S 2 =
      Scheme.partialEndRelSnd (bugEyedRelOpens S) (bugEyedRelAut S) ≫
        AffineSpace.pow PUnit.{u + 1} S 2 := by
  dsimp only [Scheme.partialEndRelFst, Scheme.partialEndRelSnd]
  apply Sigma.hom_ext
  intro b
  simp only [colimit.ι_desc_assoc, Cofan.mk_pt, Cofan.mk_ι_app]
  cases b
  · dsimp only [bugEyedRelAut]
    rw [Category.comp_id]
  · dsimp only [bugEyedRelAut]
    rw [Category.assoc, AffineSpace.neg_comp_pow_two]

/-- Background construction used in part (b) of Exercise 4.9.4: for a scheme $S$, the
morphism $\bA^1_S/R \to \bA^1_S$ from the
quotient presheaf of the bug-eyed equivalence relation induced by the squaring map
$x \mapsto x^2$. At the level of étale sheafifications it is the universal homeomorphism
from the bug-eyed cover to the affine line of part (b). -/
noncomputable def bugEyedCoverPresheafToLine :
    bugEyedCoverPresheaf S ⟶ yoneda.obj 𝔸(PUnit.{u + 1}; S) :=
  coequalizer.desc (yoneda.map (AffineSpace.pow PUnit.{u + 1} S 2))
    (by rw [← Functor.map_comp, ← Functor.map_comp, bugEyedRel_fst_comp_pow_two])

variable {k : Type u} [Field k]

/-- **Exercise 4.9.4** (`exer:bug-eyed-cover`) (part (b)): let $\kk$ be a field of
characteristic $\neq 2$ and let $X$ be an étale sheafification of the quotient presheaf
of the bug-eyed equivalence relation over $\kk$. The morphism $X \to \bA^1$ induced by
$x \mapsto x^2$ is a universal homeomorphism (it is moreover an isomorphism away from the
origin, and ramified over the origin). -/
theorem exists_universally_isHomeomorph_of_isSheafificationHom_bugEyedCoverPresheaf
    [NeZero (2 : k)] {X : Scheme.{u}ᵒᵖ ⥤ Type u}
    (η : bugEyedCoverPresheaf (Spec (CommRingCat.of k)) ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    ∃ q : X ⟶ yoneda.obj 𝔸(PUnit.{u + 1}; Spec (CommRingCat.of k)),
      η ≫ q = bugEyedCoverPresheafToLine (Spec (CommRingCat.of k)) ∧
        MorphismProperty.presheaf
          ((topologically @IsHomeomorph).universally :
            MorphismProperty Scheme.{u}) q := by
  sorry

/-- **Exercise 4.9.4** (`exer:bug-eyed-cover`) (part (c)): let $\kk$ be a field of
characteristic $\neq 2$. Every morphism from $\bA^1$ to a scheme $Z$ coequalizing the
bug-eyed relation factors uniquely through the squaring map $\bA^1 \to \bA^1$: the affine
line is the categorical quotient of the bug-eyed relation in the category of schemes
(though not in algebraic spaces, where the quotient is the bug-eyed cover). -/
theorem existsUnique_pow_two_comp_of_bugEyedRel_comp_eq [NeZero (2 : k)]
    {Z : Scheme.{u}} (g : 𝔸(PUnit.{u + 1}; Spec (CommRingCat.of k)) ⟶ Z)
    (hg : Scheme.partialEndRelFst (bugEyedRelOpens (Spec (CommRingCat.of k))) ≫ g =
      Scheme.partialEndRelSnd (bugEyedRelOpens (Spec (CommRingCat.of k)))
        (bugEyedRelAut (Spec (CommRingCat.of k))) ≫ g) :
    ∃! h : 𝔸(PUnit.{u + 1}; Spec (CommRingCat.of k)) ⟶ Z,
      AffineSpace.pow PUnit.{u + 1} (Spec (CommRingCat.of k)) 2 ≫ h = g := by
  sorry

/- LEDGER — **Exercise 4.9.4** (`exer:bug-eyed-cover`) (remaining items).
- (a) (item label `exer:bug-eyed-cover1`, not in the book's .aux): the identification
  $X \cong U/(\bZ/2)$ with the quotient of the free $\bZ/2$-action on the non-separated
  affine line $U = \bA^1 \cup_{\bA^1 \setminus 0} \bA^1$ swapping the origins; blocked on
  quotients by free finite group actions on algebraic spaces
  (`cor:finite-quotient-algebraic-space`, Corollary 4.1.14). The non-separated affine
  line itself is constructed at the presheaf level in part 4.9.3
  (`AlgebraicGeometry.nonseparatedAffineLinePresheaf`).
- (d) (item label `exer:bug-eyed-cover4`): the identification $X \cong W/\SL_2$ for the free
  $\SL_2$-action on the locally closed subscheme $W \subseteq V_1 \times V_4$ of pairs
  $(L, F)$ with $F$ the square of a quadratic form of discriminant 1; blocked on group
  scheme actions ($\SL_2$-actions are absent from Mathlib) and quotients.
- (e) (item label `exer:bug-eyed-cover5`): the representability by $X$ of the functor of
  simultaneous resolutions of a family of surfaces with an isolated nodal singularity
  $z^2 + xy = t$; blocked on resolutions of singularities (absent from Mathlib).
Figure 4.9.3 (`fig:bug-eyed-cover`) of Example 4.9.2 (`ex:bug-eyed-cover`) is an
illustration only. -/

end AlgebraicGeometry

end ExerBugEyedCover

section ExerNodalAffineLine

/- LEDGER — **Exercise 4.9.5** (`exer:nodal-affine-line`): let $V = \Spec \kk[x,y]/(xy)$
and let $U = V \cup_{V \setminus 0} V$ be the non-separated union, with $\bZ/2$ acting by
exchanging the branches and swapping the origins; $X = U/(\bZ/2)$ is the affine line with
a nodal singularity at the origin (Figure 4.9.6, `fig:nodal-affine-line`, is an
illustration).
(a) the diagonal of $X$ is not a locally closed immersion and $X$ is not a scheme;
(b) $X$ is one dimensional, singular at the origin, and admits a universal homeomorphism
to $\bA^1$ which is an isomorphism away from the origin; (c) the variant with an $A_k$
singularity $y^2 = x^{k+1}$; (d) the variant with the non-lci singularity
$\kk[[x,y,z]]/(xy, yz, xz)$. The ingredients (the nodal curve $V$, the doubled presheaf
$V \cup_{V \setminus 0} V$ via `AlgebraicGeometry.Scheme.Opens.doublePresheaf` of part
4.9.3, and the branch-swapping involution) are constructible with the tools of this
section, but the quotient statements are blocked on the free-finite-group-quotient theory
of §4.1 (`cor:finite-quotient-algebraic-space`, Corollary 4.1.14); the whole exercise is
recorded as prose. -/

end ExerNodalAffineLine

section ExAffineLineWhereResidueFieldJumps

open CategoryTheory Limits AlgebraicGeometry

namespace AlgebraicGeometry

/-- Complex conjugation on the affine line $\bA^1_{\bC}$ over $\Spec \bR$: the morphism
induced by functoriality of affine space from the conjugation automorphism of
$\Spec \bC$. It fixes the coordinate and conjugates the scalars; it is an automorphism of
$\bA^1_{\bC}$ over $\Spec \bR$ (but not over $\Spec \bC$). -/
noncomputable def complexConjAffineLine :
    𝔸(PUnit; Spec (CommRingCat.of ℂ)) ⟶ 𝔸(PUnit; Spec (CommRingCat.of ℂ)) :=
  AffineSpace.map PUnit (Spec.map (CommRingCat.ofHom (starRingEnd ℂ)))

/-- Complex conjugation on the affine line $\bA^1_{\bC}$ is an involution. -/
@[reassoc]
lemma complexConjAffineLine_comp_self :
    complexConjAffineLine ≫ complexConjAffineLine = 𝟙 _ := by
  have h : CommRingCat.ofHom (starRingEnd ℂ) ≫ CommRingCat.ofHom (starRingEnd ℂ) =
      𝟙 (CommRingCat.of ℂ) := by
    ext z
    exact star_star z
  rw [complexConjAffineLine, ← AffineSpace.map_comp, ← Spec.map_comp, h, Spec.map_id,
    AffineSpace.map_id]

/- Complex conjugation on the affine line is an isomorphism (its own inverse). -/
instance : IsIso complexConjAffineLine :=
  ⟨complexConjAffineLine, complexConjAffineLine_comp_self,
    complexConjAffineLine_comp_self⟩

/-- Background construction used in Exercise 4.9.7: the family of open subschemes of
$\bA^1_{\bC}$ underlying the
conjugation equivalence relation $R = (\bZ/2 \times \bA^1_{\bC}) \setminus \{(-1, 0)\}$:
all of $\bA^1_{\bC}$ for the identity component (`false`), and the complement of the
origin for the conjugation component (`true`). -/
noncomputable def complexConjRelOpens : Bool → (𝔸(PUnit; Spec (CommRingCat.of ℂ))).Opens
  | false => ⊤
  | true =>
    (𝔸(PUnit; Spec (CommRingCat.of ℂ))).basicOpen
      (AffineSpace.coord (Spec (CommRingCat.of ℂ)) PUnit.unit)

/-- Background construction used in Exercise 4.9.7: the identity on all of
$\bA^1_{\bC}$ (`false`)
and complex conjugation on the complement of the origin (`true`). -/
noncomputable def complexConjRelAut :
    Bool → (𝔸(PUnit; Spec (CommRingCat.of ℂ)) ⟶ 𝔸(PUnit; Spec (CommRingCat.of ℂ)))
  | false => 𝟙 _
  | true => complexConjAffineLine

/- The second projection of the conjugation relation is étale. Registered as an instance
(keyed to the specific defs). -/
instance : Etale (Scheme.partialEndRelSnd complexConjRelOpens complexConjRelAut) :=
  Scheme.etale_partialEndRelSnd _ _ fun b ↦ by
    cases b <;> dsimp only [complexConjRelAut] <;> infer_instance

/-- Background definition used in Exercise 4.9.7: the quotient presheaf
$\bA^1_{\bC}/R$ of the
conjugation equivalence relation
$R = (\bZ/2 \times \bA^1_{\bC}) \setminus \{(-1, 0)\} \rightrightarrows \bA^1_{\bC}$
induced by the $\bZ/2$-action on $\bA^1_{\bC}$ by conjugation over $\Spec \bR$. Its étale
sheafification is an algebraic space which looks like $\bA^1_{\bR}$ except that the
origin has residue field $\bC$ (Figure 4.9.8); it is not a
scheme. -/
noncomputable abbrev complexConjQuotientPresheaf : Scheme.{0}ᵒᵖ ⥤ Type :=
  Scheme.partialEndQuotientPresheaf complexConjRelOpens complexConjRelAut

namespace ComplexConjCover

/- The following construction equips the two-component conjugation relation with its
groupoid structure.  The identity component is the affine line, while conjugation
restricts to an involution of the punctured component. -/

lemma conj_preserves_relOpen :
    complexConjRelOpens true ≤
      complexConjAffineLine ⁻¹ᵁ complexConjRelOpens true := by
  rw [show complexConjRelOpens true =
    (𝔸(PUnit; Spec (CommRingCat.of ℂ))).basicOpen
      (AffineSpace.coord (Spec (CommRingCat.of ℂ)) PUnit.unit) by rfl]
  rw [Scheme.preimage_basicOpen_top]
  rw [complexConjAffineLine, AffineSpace.map_appTop_coord]

noncomputable def identity :
    𝔸(PUnit; Spec (CommRingCat.of ℂ)) ⟶
      ∐ fun b ↦ (complexConjRelOpens b).toScheme :=
  (((𝔸(PUnit; Spec (CommRingCat.of ℂ))).isoOfEq
    (show complexConjRelOpens false = ⊤ by rfl)).trans
      (𝔸(PUnit; Spec (CommRingCat.of ℂ))).topIso).inv ≫
        Sigma.ι (fun b ↦ (complexConjRelOpens b).toScheme) false

noncomputable def conjRestriction :
    (complexConjRelOpens true).toScheme ⟶
      (complexConjRelOpens true).toScheme :=
  Scheme.Hom.resLE complexConjAffineLine
    (complexConjRelOpens true) (complexConjRelOpens true)
    conj_preserves_relOpen

noncomputable def inverse :
    (∐ fun b ↦ (complexConjRelOpens b).toScheme) ⟶
      ∐ fun b ↦ (complexConjRelOpens b).toScheme :=
  Sigma.desc fun b ↦ match b with
    | false => Sigma.ι (fun b ↦ (complexConjRelOpens b).toScheme) false
    | true => conjRestriction ≫
        Sigma.ι (fun b ↦ (complexConjRelOpens b).toScheme) true

lemma identity_source : identity ≫
    Scheme.partialEndRelFst complexConjRelOpens = 𝟙 _ := by
  simp [identity, Scheme.partialEndRelFst]
  simpa only [complexConjRelOpens] using
    Scheme.toIso_inv_ι (𝔸(PUnit; Spec (CommRingCat.of ℂ)))

lemma identity_target : identity ≫
    Scheme.partialEndRelSnd complexConjRelOpens complexConjRelAut = 𝟙 _ := by
  simp [identity, Scheme.partialEndRelSnd, complexConjRelAut]
  simpa only [complexConjRelOpens] using
    Scheme.toIso_inv_ι (𝔸(PUnit; Spec (CommRingCat.of ℂ)))

@[reassoc]
lemma conjRestriction_comp_ι : conjRestriction ≫
    (complexConjRelOpens true).ι =
      (complexConjRelOpens true).ι ≫ complexConjAffineLine := by
  simpa only [conjRestriction] using
    Scheme.Hom.resLE_comp_ι complexConjAffineLine conj_preserves_relOpen

lemma inverse_source : inverse ≫
    Scheme.partialEndRelFst complexConjRelOpens =
      Scheme.partialEndRelSnd complexConjRelOpens complexConjRelAut := by
  dsimp only [Scheme.partialEndRelFst, Scheme.partialEndRelSnd,
    Scheme.partialEndRel]
  apply Sigma.hom_ext
  intro b
  cases b <;>
    simp [inverse, complexConjRelAut, conjRestriction_comp_ι]

lemma inverse_target : inverse ≫
    Scheme.partialEndRelSnd complexConjRelOpens complexConjRelAut =
      Scheme.partialEndRelFst complexConjRelOpens := by
  dsimp only [Scheme.partialEndRelFst, Scheme.partialEndRelSnd,
    Scheme.partialEndRel]
  apply Sigma.hom_ext
  intro b
  cases b <;>
    simp [inverse, complexConjRelAut, conjRestriction_comp_ι_assoc,
      complexConjAffineLine_comp_self]

noncomputable abbrev A : Scheme :=
  𝔸(PUnit; Spec (CommRingCat.of ℂ))

noncomputable abbrev U (b : Bool) : A.Opens :=
  complexConjRelOpens b

noncomputable abbrev sourceComponent (b : Bool) :
    (U b).toScheme ⟶ A :=
  (U b).ι

noncomputable abbrev targetComponent (b : Bool) :
    (U b).toScheme ⟶ A :=
  (U b).ι ≫ complexConjRelAut b

noncomputable def pullbackComparison :
    (∐ fun p : Bool × Bool ↦
      pullback (sourceComponent p.1) (targetComponent p.2)) ⟶
      pullback (Sigma.desc sourceComponent) (Sigma.desc targetComponent) :=
  Sigma.desc fun p ↦
    pullback.map (sourceComponent p.1) (targetComponent p.2)
      (Sigma.desc sourceComponent) (Sigma.desc targetComponent)
      (Sigma.ι (fun b ↦ (U b).toScheme) p.1)
      (Sigma.ι (fun b ↦ (U b).toScheme) p.2)
      (𝟙 _) (by simp) (by simp)

instance : IsIso pullbackComparison := by
  apply CategoryTheory.FinitaryPreExtensive.isIso_sigmaDesc_map

noncomputable def toIdentityComponent :
    (U true).toScheme ⟶ (U false).toScheme :=
  (U true).ι ≫
    ((A.isoOfEq (show U false = ⊤ by rfl)).trans A.topIso).inv

@[reassoc]
lemma toIdentityComponent_comp_ι : toIdentityComponent ≫
    (U false).ι = (U true).ι := by
  simp [toIdentityComponent]
  change (U true).ι ≫ A.topIso.inv ≫ (⊤ : A.Opens).ι = (U true).ι
  simp

noncomputable def compositionComponent (p : Bool × Bool) :
    pullback (sourceComponent p.1) (targetComponent p.2) ⟶
      ∐ fun b ↦ (U b).toScheme :=
  match p with
  | (false, false) =>
      pullback.snd _ _ ≫ Sigma.ι (fun b ↦ (U b).toScheme) false
  | (false, true) =>
      pullback.snd _ _ ≫ Sigma.ι (fun b ↦ (U b).toScheme) true
  | (true, false) =>
      pullback.fst _ _ ≫ Sigma.ι (fun b ↦ (U b).toScheme) true
  | (true, true) =>
      pullback.snd _ _ ≫ toIdentityComponent ≫
        Sigma.ι (fun b ↦ (U b).toScheme) false

noncomputable def composition :
    pullback (Sigma.desc sourceComponent) (Sigma.desc targetComponent) ⟶
      ∐ fun b ↦ (U b).toScheme :=
  inv pullbackComparison ≫ Sigma.desc compositionComponent

lemma composition_source : composition ≫ Sigma.desc sourceComponent =
    pullback.snd (Sigma.desc sourceComponent) (Sigma.desc targetComponent) ≫
      Sigma.desc sourceComponent := by
  rw [← cancel_epi pullbackComparison]
  apply Sigma.hom_ext
  rintro ⟨a, b⟩
  cases a <;> cases b <;>
    simp [composition, pullbackComparison, compositionComponent,
      sourceComponent, targetComponent, toIdentityComponent_comp_ι,
      complexConjRelAut, Category.assoc, pullback.condition]

lemma composition_target : composition ≫ Sigma.desc targetComponent =
    pullback.fst (Sigma.desc sourceComponent) (Sigma.desc targetComponent) ≫
      Sigma.desc targetComponent := by
  rw [← cancel_epi pullbackComparison]
  apply Sigma.hom_ext
  rintro ⟨a, b⟩
  cases a <;> cases b <;>
    simp [composition, pullbackComparison, compositionComponent,
      sourceComponent, targetComponent, toIdentityComponent_comp_ι,
      complexConjRelAut, Category.assoc, pullback.condition,
      pullback.condition_assoc, complexConjAffineLine_comp_self]

/- Complex conjugation has no fixed geometric point: a fixed map would induce an
injective field homomorphism from $\mathbb C$ on which conjugation acts trivially. -/
lemma no_fixed_point {K : Type} [Field K]
    (f : Spec (CommRingCat.of K) ⟶ A)
    (hfix : f ≫ complexConjAffineLine = f) : False := by
  let p : A ⟶ Spec (CommRingCat.of ℂ) := A ↘ Spec (CommRingCat.of ℂ)
  have hp := congrArg (fun q : Spec (CommRingCat.of K) ⟶ A ↦ q ≫ p) hfix
  have hp' : (f ≫ p) ≫ Spec.map (CommRingCat.ofHom (starRingEnd ℂ)) = f ≫ p := by
    simpa [A, p, complexConjAffineLine, Category.assoc] using hp
  have happ := congrArg Scheme.Hom.appTop hp'
  change (Spec.map (CommRingCat.ofHom (starRingEnd ℂ))).appTop ≫
    (f ≫ p).appTop = (f ≫ p).appTop at happ
  let φ : CommRingCat.of ℂ ⟶ CommRingCat.of K :=
    (Scheme.ΓSpecIso (CommRingCat.of ℂ)).inv ≫
      (f ≫ p).appTop ≫ (Scheme.ΓSpecIso (CommRingCat.of K)).hom
  have hφ : CommRingCat.ofHom (starRingEnd ℂ) ≫ φ = φ := by
    dsimp only [φ]
    simp only [← Category.assoc]
    rw [Scheme.ΓSpecIso_inv_naturality]
    rw [Category.assoc (Scheme.ΓSpecIso (CommRingCat.of ℂ)).inv]
    rw [happ]
  have hφI := ConcreteCategory.congr_hom hφ (Complex.I : ℂ)
  have hstar : starRingEnd ℂ Complex.I = Complex.I := by
    apply RingHom.injective φ.hom
    exact hφI
  have him := congrArg Complex.im hstar
  norm_num at him

noncomputable abbrev relationMap :
    (∐ fun b ↦ (U b).toScheme) ⟶ A ⨯ A :=
  prod.lift (Sigma.desc sourceComponent) (Sigma.desc targetComponent)

lemma field_injective (K : Type) [Field K] :
    Function.Injective (fun x : Spec (CommRingCat.of K) ⟶
      ∐ fun b ↦ (U b).toScheme ↦ x ≫ relationMap) := by
  intro x y hxy
  have hs : x ≫ Sigma.desc sourceComponent =
      y ≫ Sigma.desc sourceComponent := by
    simpa [relationMap] using congrArg (fun q ↦ q ≫ prod.fst) hxy
  have ht : x ≫ Sigma.desc targetComponent =
      y ≫ Sigma.desc targetComponent := by
    simpa [relationMap] using congrArg (fun q ↦ q ≫ prod.snd) hxy
  -- At `k = ℂ` the two open families are definitionally the same; reuse the
  -- universe-safe finite-coproduct component decomposition constructed above.
  generalize hbx : BugEyedCover.component (k := ℂ) x = bx
  generalize hby : BugEyedCover.component (k := ℂ) y = cy
  let xl := BugEyedCover.componentLiftAt (k := ℂ) x bx hbx
  let yl := BugEyedCover.componentLiftAt (k := ℂ) y cy hby
  have hxf := BugEyedCover.componentLiftAt_fac (k := ℂ) x bx hbx
  have hyf := BugEyedCover.componentLiftAt_fac (k := ℂ) y cy hby
  rw [← hxf, ← hyf] at hs ht
  simp only [Category.assoc, Sigma.ι_desc] at hs ht
  cases bx <;> cases cy
  · have hLift : xl = yl := by
      apply (cancel_mono (U false).ι).mp
      exact hs
    rw [← hxf, ← hyf]
    change xl ≫ Sigma.ι (fun b ↦ (U b).toScheme) false =
      yl ≫ Sigma.ι (fun b ↦ (U b).toScheme) false
    rw [hLift]
  · have hfix : (yl ≫ (U true).ι) ≫ complexConjAffineLine =
        yl ≫ (U true).ι := by
      rw [Category.assoc]
      exact (by simpa only [targetComponent, complexConjRelAut,
        Category.comp_id] using ht.symm.trans hs)
    exact (no_fixed_point (yl ≫ (U true).ι) hfix).elim
  · have hfix : (xl ≫ (U true).ι) ≫ complexConjAffineLine =
        xl ≫ (U true).ι := by
      rw [Category.assoc]
      exact (by simpa only [targetComponent, complexConjRelAut,
        Category.comp_id] using ht.trans hs.symm)
    exact (no_fixed_point (xl ≫ (U true).ι) hfix).elim
  · have hLift : xl = yl := by
      apply (cancel_mono (U true).ι).mp
      exact hs
    rw [← hxf, ← hyf]
    change xl ≫ Sigma.ι (fun b ↦ (U b).toScheme) true =
      yl ≫ Sigma.ι (fun b ↦ (U b).toScheme) true
    rw [hLift]

lemma universallyInjective_relationMap :
    UniversallyInjective relationMap := by
  exact ((tfae_universallyInjective relationMap).out 0 1).mpr field_injective

lemma mono_relationMap : Mono relationMap := by
  let f := relationMap
  have hf_fst : f ≫ prod.fst = Sigma.desc sourceComponent := by
    simp [f, relationMap]
  haveI : UniversallyInjective f := universallyInjective_relationMap
  haveI : LocallyOfFiniteType (f ≫ prod.fst) := by
    rw [hf_fst]
    exact IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance
  haveI : LocallyOfFiniteType f := locallyOfFiniteType_of_comp f prod.fst
  haveI : FormallyUnramified (f ≫ prod.fst) := by
    rw [hf_fst]
    exact IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance
  haveI : FormallyUnramified f := FormallyUnramified.of_comp f prod.fst
  haveI : Surjective (pullback.diagonal f) :=
    ((tfae_universallyInjective f).out 0 3).mp universallyInjective_relationMap
  haveI : IsIso (pullback.diagonal f) :=
    (isIso_iff_isOpenImmersion_and_surjective _).mpr ⟨inferInstance, inferInstance⟩
  exact (pullback.isIso_diagonal_iff f).mp inferInstance

lemma relation_unique {T : Scheme}
    (x y : T ⟶ ∐ fun b ↦ (U b).toScheme)
    (hs : x ≫ Sigma.desc sourceComponent = y ≫ Sigma.desc sourceComponent)
    (ht : x ≫ Sigma.desc targetComponent = y ≫ Sigma.desc targetComponent) : x = y := by
  haveI : Mono relationMap := mono_relationMap
  apply (cancel_mono relationMap).mp
  apply prod.hom_ext
  · simpa [relationMap] using hs
  · simpa [relationMap] using ht

noncomputable def groupoid : PresheafGroupoid.{0} :=
  PresheafGroupoid.ofSchemesOfRelation
    (Sigma.desc sourceComponent) (Sigma.desc targetComponent)
    composition identity inverse composition_source composition_target
    identity_source identity_target inverse_source inverse_target relation_unique

lemma groupoid_isEquivalenceRelation : groupoid.IsEquivalenceRelation :=
  PresheafGroupoid.ofSchemesOfRelation_isEquivalenceRelation
    (Sigma.desc sourceComponent) (Sigma.desc targetComponent)
    composition identity inverse composition_source composition_target
    identity_source identity_target inverse_source inverse_target relation_unique

instance : groupoid.IsEtale := by
  letI : Etale (Sigma.desc sourceComponent) :=
    IsZariskiLocalAtSource.sigmaDesc fun _ ↦ inferInstance
  letI : Etale (Sigma.desc targetComponent) :=
    IsZariskiLocalAtSource.sigmaDesc fun b ↦ by
      cases b <;> dsimp only [targetComponent, complexConjRelAut] <;> infer_instance
  exact PresheafGroupoid.ofSchemesOfRelation_isEtale
    (Sigma.desc sourceComponent) (Sigma.desc targetComponent)
    composition identity inverse composition_source composition_target
    identity_source identity_target inverse_source inverse_target relation_unique

instance : groupoid.U.IsRepresentable := by
  change (yoneda.obj A).IsRepresentable
  infer_instance

instance : groupoid.R.IsRepresentable := by
  change (yoneda.obj (∐ fun b ↦ (U b).toScheme)).IsRepresentable
  infer_instance

end ComplexConjCover

/-- **Exercise 4.9.7** (`ex:affine-line-where-residue-field-jumps`) (the quotient is an
algebraic space): let $X$ be an étale sheafification of the quotient presheaf of the
conjugation equivalence relation $R = (\bZ/2 \times \bA^1_{\bC}) \setminus \{(-1, 0)\}
\rightrightarrows \bA^1_{\bC}$ over $\Spec \bR$. Then $X$ is an algebraic space. -/
theorem isAlgebraicSpace_of_isSheafificationHom_complexConjQuotientPresheaf
    {X : Scheme.{0}ᵒᵖ ⥤ Type} (η : complexConjQuotientPresheaf ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    IsAlgebraicSpace X := by
  let G := ComplexConjCover.groupoid
  change coequalizer G.s G.t ⟶ X at η
  change Presheaf.IsSheafificationHom Scheme.etaleTopology η at hη
  have hq := G.isQuotientSheaf_of_isSheafificationHom_coequalizer η hη
  exact G.isAlgebraicSpace_of_isQuotientSheaf
    ComplexConjCover.groupoid_isEquivalenceRelation hq

/-- **Exercise 4.9.7** (`ex:affine-line-where-residue-field-jumps`) (the quotient is not
a scheme): let $X$ be an étale sheafification of the quotient presheaf of the conjugation
equivalence relation on $\bA^1_{\bC}$ over $\Spec \bR$. Then $X$ is not representable by
a scheme: identifying $X$ with the quotient of the non-separated affine line
$U = \bA^1_{\bC} \cup_{\bA^1_{\bC} \setminus 0} \bA^1_{\bC}$ by the $\bZ/2$-action which
conjugates and swaps the origins, an affine neighborhood of the origin of $X$ would pull
back to an affine open of $U$ containing both origins. -/
theorem not_isRepresentable_of_isSheafificationHom_complexConjQuotientPresheaf
    {X : Scheme.{0}ᵒᵖ ⥤ Type} (η : complexConjQuotientPresheaf ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    ¬ X.IsRepresentable := by
  sorry

/-- **Exercise 4.9.7** (`ex:affine-line-where-residue-field-jumps`) (the diagonal *is* a
locally closed immersion): let $X$ be an étale sheafification of the quotient presheaf of
the conjugation equivalence relation on $\bA^1_{\bC}$ over $\Spec \bR$. Unlike the
bug-eyed cover, the diagonal of $X$ is representable by schemes by locally closed
immersions ($X$ is *locally separated*): the conjugation action of $\bZ/2$ on
$\bA^1_{\bC}$ over $\bR$ is free, so
$\bZ/2 \times \bA^1_{\bC} \to \bA^1_{\bC} \times_{\bR} \bA^1_{\bC}$ is a closed immersion
and $R$ is locally closed in the product. -/
theorem presheaf_isImmersion_diagonal_of_isSheafificationHom_complexConjQuotientPresheaf
    {X : Scheme.{0}ᵒᵖ ⥤ Type} (η : complexConjQuotientPresheaf ⟶ X)
    (hη : Presheaf.IsSheafificationHom Scheme.etaleTopology η) :
    MorphismProperty.presheaf (@IsImmersion : MorphismProperty Scheme.{0})
      (prod.lift (𝟙 X) (𝟙 X)) := by
  sorry

/- Figure 4.9.8 (`fig:residue-field-jumps`) is an illustration only. -/

end AlgebraicGeometry

end ExAffineLineWhereResidueFieldJumps

section RmkTypicalConstructionsAreNotSchemes

/- LEDGER — **Remark 4.9.9** (`rmk:typical-constructions-are-not-schemes`): typical
constructions in algebraic geometry often only exist in the category of algebraic spaces:
quotients of free actions of finite groups on schemes
(`exer:finite-group-quotient-scheme`, Exercise 5.2.14, and
`ex:smooth-three-fold-not-scheme`, Example 4.9.1); pushouts $X \amalg_{X_0} Y_0$ of a
closed immersion $X_0 \hookrightarrow X$ and a finite (or affine) morphism $X_0 \to Y_0$
(Ferrand pushouts, `thm:ferrand-pushout`, Theorem B.4.1, and Artin's
[Thm. 6.1, artin-algebraizationII]); contractions of curves in higher dimensions
(Castelnuovo's contraction theorem, `thm:castelnuovo-contraction-theorem`, Theorem B.2.6,
fails to generalize within schemes, Artin [Thm. 3.1, artin-algebraizationII]); and
simultaneous resolutions of singularities of families of surfaces (Exercise 4.9.4(e),
item label `exer:bug-eyed-cover5`, Artin [Thm. 1, artin-brieskorn]). All of these
constructions (Ferrand pushouts, Artin contractions, resolution functors) are far outside
the current scope of Mathlib and are recorded as prose only. -/

-- The remark's own content is a list of pointers — to Exercise 5.2.14, Example 4.9.1,
-- Theorem B.4.1, Theorem B.2.6 and Artin's papers — with nothing of its own to state in
-- §4.9. It is therefore deliberately part-prose in the sense of AGENTS.md.
-- STATUS: remark-complete

end RmkTypicalConstructionsAreNotSchemes
