module

public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
public import Mathlib.RingTheory.Localization.Ideal
public import Mathlib.RingTheory.Regular.RegularSequence
public import Mathlib.RingTheory.Spectrum.Prime.Topology

/-!
# Determinantal ideals and grade-witness loci

For a finite matrix, this file defines the ideal generated by its minors of a fixed size.
It proves that this ideal commutes with arbitrary change of coefficients and characterizes
when its extension to a local ring is the unit ideal: precisely when one of the corresponding
minors avoids the prime.

The second half isolates the topological patching step in the determinantal proof of openness
of exactness loci.  Let `I` be a determinantal ideal.  At a prime, the Buchsbaum--Eisenbud
condition has two alternatives: either `I` becomes the unit ideal, or `I` contains a sequence
of a prescribed length satisfying a fibrewise regularity predicate.  If, for each fixed
sequence in `I`, that predicate is relatively open on the sequence's zero locus, then the
union of the two alternatives is open.  This is the step which turns the fixed-sequence
openness theorem of Stacks Project tag 00RA into the grade-locus input for tag 00RB.

The file also handles the localization bookkeeping hidden in the paper proof: a finite
regular sequence in the extension of an ideal to a localization can be replaced by images
of elements of the original ideal.  The replacement terms differ by units, and regularity
is proved invariant under such termwise rescaling.

No theorem identifying these grade witnesses with exactness is assumed.  Thus the API is
usable independently of the eventual Cohen--Macaulay fibre and Buchsbaum--Eisenbud layers.

Main declarations:

* `Ideal.map_atPrime_eq_top_iff_not_le`;
* `RingTheory.Sequence.isRegular_iff_of_forall₂_isUnitMultiple`;
* `Ideal.exists_family_mem_and_isRegular_map_of_isRegular`;
* `Matrix.minorIdeal`;
* `Matrix.minorIdeal_map`;
* `Matrix.minorIdeal_map_atPrime_eq_top_iff`;
* `Ideal.gradeWitnessLocus`;
* `Ideal.isOpen_gradeWitnessLocus`;
* `Ideal.isOpen_gradeWitnessLocus_of_isOpen_subtype`;
* `Matrix.determinantalGradeLocus`;
* `Matrix.isOpen_determinantalGradeLocus`.
-/

@[expose] public section

noncomputable section

universe u v w x

namespace Ideal

variable {R : Type u} [CommRing R]

/-- An ideal extends to the unit ideal in the local ring at `p` exactly when it is not
contained in `p`. -/
theorem map_atPrime_eq_top_iff_not_le (I : Ideal R) (p : Ideal R) [p.IsPrime] :
    I.map (algebraMap R (Localization.AtPrime p)) = ⊤ ↔ ¬ I ≤ p := by
  constructor
  · intro h hle
    have hdisjoint : Disjoint (p.primeCompl : Set R) (I : Set R) := by
      rw [Set.disjoint_left]
      intro x hxp hxI
      exact hxp (hle hxI)
    exact (IsLocalization.map_algebraMap_ne_top_iff_disjoint
      p.primeCompl (Localization.AtPrime p) I).mpr hdisjoint h
  · intro hnotle
    by_contra hne
    have hdisjoint := (IsLocalization.map_algebraMap_ne_top_iff_disjoint
      p.primeCompl (Localization.AtPrime p) I).mp hne
    apply hnotle
    intro x hxI
    by_contra hxp
    exact Set.disjoint_left.mp hdisjoint hxp hxI

end Ideal

namespace RingTheory.Sequence

variable {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]

/-- `b` is a unit multiple of `a`.  The orientation records the unit explicitly and is
convenient when clearing denominators in a localization. -/
def IsUnitMultiple (a b : R) : Prop :=
  ∃ u : R, IsUnit u ∧ b = u * a

/-- Pointwise unit multiples of two finite families give termwise unit multiples of their
`List.ofFn` enumerations. -/
theorem forall₂_isUnitMultiple_ofFn {n : ℕ} {f g : Fin n → R}
    (h : ∀ i, IsUnitMultiple (f i) (g i)) :
    List.Forall₂ IsUnitMultiple (List.ofFn f) (List.ofFn g) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [List.ofFn_succ, List.ofFn_succ]
    exact .cons (h 0) (ih (fun i => h i.succ))

/-- Termwise multiplication by units does not change the ideal generated by a list. -/
theorem ofList_eq_of_forall₂_isUnitMultiple {as bs : List R}
    (h : List.Forall₂ IsUnitMultiple as bs) :
    Ideal.ofList bs = Ideal.ofList as := by
  induction h with
  | nil => simp
  | @cons a b as bs hab _ ih =>
    obtain ⟨u, hu, rfl⟩ := hab
    rw [Ideal.ofList_cons, Ideal.ofList_cons,
      Ideal.span_singleton_mul_left_unit hu, ih]

/-- Weak regularity is invariant under multiplying the terms of a sequence by possibly
different units. -/
theorem isWeaklyRegular_iff_of_forall₂_isUnitMultiple {as bs : List R}
    (h : List.Forall₂ IsUnitMultiple as bs) :
    IsWeaklyRegular M as ↔ IsWeaklyRegular M bs := by
  rw [isWeaklyRegular_iff, isWeaklyRegular_iff]
  constructor
  · intro ha i hib
    have hia : i < as.length := h.length_eq ▸ hib
    obtain ⟨u, hu, hterm⟩ := h.get hia hib
    have hterm' : bs[i] = u * as[i] := by
      simpa only [List.get_eq_getElem] using hterm
    have hprefix : Ideal.ofList (bs.take i) = Ideal.ofList (as.take i) :=
      ofList_eq_of_forall₂_isUnitMultiple (List.forall₂_take i h)
    rw [hprefix, hterm']
    exact (hu.isSMulRegular _).mul_iff_right.mpr (ha i hia)
  · intro hb i hia
    have hib : i < bs.length := h.length_eq ▸ hia
    obtain ⟨u, hu, hterm⟩ := h.get hia hib
    have hterm' : bs[i] = u * as[i] := by
      simpa only [List.get_eq_getElem] using hterm
    have hprefix : Ideal.ofList (bs.take i) = Ideal.ofList (as.take i) :=
      ofList_eq_of_forall₂_isUnitMultiple (List.forall₂_take i h)
    have hb' := hb i hib
    rw [hprefix, hterm'] at hb'
    exact (hu.isSMulRegular _).mul_iff_right.mp hb'

/-- Regularity is invariant under multiplying the terms of a sequence by possibly
different units. -/
theorem isRegular_iff_of_forall₂_isUnitMultiple {as bs : List R}
    (h : List.Forall₂ IsUnitMultiple as bs) :
    IsRegular M as ↔ IsRegular M bs := by
  rw [isRegular_iff, isRegular_iff,
    ofList_eq_of_forall₂_isUnitMultiple h]
  exact and_congr (isWeaklyRegular_iff_of_forall₂_isUnitMultiple h) Iff.rfl

end RingTheory.Sequence

namespace Ideal

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]

/-- An element of an ideal extended to a localization is a unit multiple of the image of
an element of the original ideal. -/
theorem exists_mem_and_isUnitMultiple_algebraMap_of_mem_map
    (W : Submonoid R) [IsLocalization W S]
    (I : Ideal R) {z : S} (hz : z ∈ I.map (algebraMap R S)) :
    ∃ x : R, x ∈ I ∧ RingTheory.Sequence.IsUnitMultiple z (algebraMap R S x) := by
  obtain ⟨⟨⟨x, hx⟩, w⟩, h⟩ :=
    (IsLocalization.mem_map_algebraMap_iff W S).mp hz
  refine ⟨x, hx, algebraMap R S w, IsLocalization.map_units S w, ?_⟩
  simpa [mul_comm] using h.symm

/-- A finite regular sequence contained in the extension of an ideal to a localization can
be replaced by images of elements of the original ideal without losing regularity.

Each denominator contributes a possibly different unit factor.  Regularity survives these
factors by `RingTheory.Sequence.isRegular_iff_of_forall₂_isUnitMultiple`; no common
denominator is required. -/
theorem exists_family_mem_and_isRegular_map_of_isRegular
    (W : Submonoid R) [IsLocalization W S]
    {M : Type w} [AddCommGroup M] [Module S M]
    (I : Ideal R) (d : ℕ) (g : Fin d → S)
    (hgI : ∀ i, g i ∈ I.map (algebraMap R S))
    (hreg : RingTheory.Sequence.IsRegular M (List.ofFn g)) :
    ∃ f : Fin d → R, (∀ i, f i ∈ I) ∧
      RingTheory.Sequence.IsRegular M
        (List.ofFn fun i => algebraMap R S (f i)) := by
  let hw (i : Fin d) :=
    exists_mem_and_isUnitMultiple_algebraMap_of_mem_map W I (hgI i)
  let f : Fin d → R := fun i => (hw i).choose
  have hfI (i : Fin d) : f i ∈ I := (hw i).choose_spec.1
  have hunit (i : Fin d) : RingTheory.Sequence.IsUnitMultiple
      (g i) (algebraMap R S (f i)) := (hw i).choose_spec.2
  refine ⟨f, hfI, ?_⟩
  exact (RingTheory.Sequence.isRegular_iff_of_forall₂_isUnitMultiple
    (RingTheory.Sequence.forall₂_isUnitMultiple_ofFn hunit)).mp hreg

end Ideal

namespace Matrix

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S]
variable {m : Type w} {n : Type x}

/-- The set of determinants of the `r × r` submatrices of `A`.

Rows and columns are selected by embeddings from `Fin r`; this excludes repeated rows and
columns and hence records the usual minors rather than redundant zero determinants. -/
def minorDeterminants (A : Matrix m n R) (r : ℕ) : Set R :=
  Set.range fun e : (Fin r ↪ m) × (Fin r ↪ n) ↦
    (A.submatrix e.1 e.2).det

/-- The ideal generated by the `r × r` minors of a matrix. -/
def minorIdeal (A : Matrix m n R) (r : ℕ) : Ideal R :=
  Ideal.span (minorDeterminants A r)

/-- A selected minor belongs to the corresponding minor ideal. -/
theorem minorDeterminant_mem_minorIdeal (A : Matrix m n R) (r : ℕ)
    (rows : Fin r ↪ m) (cols : Fin r ↪ n) :
    (A.submatrix rows cols).det ∈ minorIdeal A r := by
  apply Ideal.subset_span
  exact ⟨(rows, cols), rfl⟩

/-- An ideal contains the minor ideal exactly when it contains every selected minor. -/
theorem minorIdeal_le_iff (A : Matrix m n R) (r : ℕ) (I : Ideal R) :
    minorIdeal A r ≤ I ↔
      ∀ (rows : Fin r ↪ m) (cols : Fin r ↪ n),
        (A.submatrix rows cols).det ∈ I := by
  rw [minorIdeal, Ideal.span_le]
  constructor
  · intro h rows cols
    exact h ⟨(rows, cols), rfl⟩
  · rintro h _ ⟨⟨rows, cols⟩, rfl⟩
    exact h rows cols

/-- Formation of the set of fixed-size minors commutes with a ring homomorphism. -/
theorem minorDeterminants_map (A : Matrix m n R) (r : ℕ) (f : R →+* S) :
    minorDeterminants (A.map f) r = f '' minorDeterminants A r := by
  ext x
  constructor
  · rintro ⟨⟨rows, cols⟩, rfl⟩
    refine ⟨(A.submatrix rows cols).det, ⟨⟨rows, cols⟩, rfl⟩, ?_⟩
    change f (A.submatrix rows cols).det =
      ((A.submatrix rows cols).map f).det
    rw [RingHom.map_det, RingHom.mapMatrix_apply]
  · rintro ⟨_, ⟨⟨rows, cols⟩, rfl⟩, rfl⟩
    refine ⟨⟨rows, cols⟩, ?_⟩
    change ((A.submatrix rows cols).map f).det =
      f (A.submatrix rows cols).det
    rw [RingHom.map_det, RingHom.mapMatrix_apply]

/-- Formation of fixed-size minor ideals commutes with arbitrary change of coefficients. -/
theorem minorIdeal_map (A : Matrix m n R) (r : ℕ) (f : R →+* S) :
    minorIdeal (A.map f) r = (minorIdeal A r).map f := by
  rw [minorIdeal, minorIdeal, Ideal.map_span, minorDeterminants_map]

/-- A prime lies in the zero locus of a minor ideal exactly when it contains every minor. -/
theorem mem_zeroLocus_minorIdeal_iff (A : Matrix m n R) (r : ℕ)
    (p : PrimeSpectrum R) :
    p ∈ PrimeSpectrum.zeroLocus (minorIdeal A r : Set R) ↔
      ∀ (rows : Fin r ↪ m) (cols : Fin r ↪ n),
        (A.submatrix rows cols).det ∈ p.asIdeal := by
  rw [PrimeSpectrum.mem_zeroLocus]
  exact minorIdeal_le_iff A r p.asIdeal

/-- The complement of the determinantal zero locus is witnessed by one minor. -/
theorem notMem_zeroLocus_minorIdeal_iff (A : Matrix m n R) (r : ℕ)
    (p : PrimeSpectrum R) :
    p ∉ PrimeSpectrum.zeroLocus (minorIdeal A r : Set R) ↔
      ∃ (rows : Fin r ↪ m) (cols : Fin r ↪ n),
        (A.submatrix rows cols).det ∉ p.asIdeal := by
  rw [mem_zeroLocus_minorIdeal_iff]
  push Not
  rfl

/-- The locus on which at least one `r × r` minor is nonvanishing. -/
def rankAtLeastLocus (A : Matrix m n R) (r : ℕ) : Set (PrimeSpectrum R) :=
  (PrimeSpectrum.zeroLocus (minorIdeal A r : Set R))ᶜ

/-- Membership in the rank-at-least locus is witnessed by a nonvanishing minor. -/
theorem mem_rankAtLeastLocus_iff (A : Matrix m n R) (r : ℕ)
    (p : PrimeSpectrum R) :
    p ∈ rankAtLeastLocus A r ↔
      ∃ (rows : Fin r ↪ m) (cols : Fin r ↪ n),
        (A.submatrix rows cols).det ∉ p.asIdeal := by
  exact notMem_zeroLocus_minorIdeal_iff A r p

/-- The locus on which a matrix has a nonvanishing minor of a fixed size is open. -/
theorem isOpen_rankAtLeastLocus (A : Matrix m n R) (r : ℕ) :
    IsOpen (rankAtLeastLocus A r) :=
  (PrimeSpectrum.isClosed_zeroLocus (minorIdeal A r : Set R)).isOpen_compl

/-- After localization at a prime, the minor ideal is the unit ideal exactly when one of
the corresponding minors avoids the prime. -/
theorem minorIdeal_map_atPrime_eq_top_iff (A : Matrix m n R) (r : ℕ)
    (p : Ideal R) [p.IsPrime] :
    minorIdeal (A.map (algebraMap R (Localization.AtPrime p))) r = ⊤ ↔
      ∃ (rows : Fin r ↪ m) (cols : Fin r ↪ n),
        (A.submatrix rows cols).det ∉ p := by
  rw [minorIdeal_map, Ideal.map_atPrime_eq_top_iff_not_le,
    minorIdeal_le_iff]
  push Not
  rfl

end Matrix

namespace Ideal

variable {R : Type u} [CommRing R]

/-- The locus where an ideal either becomes the unit ideal at the point or contains a
fixed-length witness satisfying `P` there.

For the application to grade, `P q f` says that `f` becomes a regular sequence in the
localized fibre at `q`. -/
def gradeWitnessLocus (I : Ideal R) (d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop) : Set (PrimeSpectrum R) :=
  {q | ¬ I ≤ q.asIdeal ∨ ∃ f : Fin d → R, (∀ i, f i ∈ I) ∧ P q f}

@[simp]
theorem mem_gradeWitnessLocus (I : Ideal R) (d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop) (q : PrimeSpectrum R) :
    q ∈ gradeWitnessLocus I d P ↔
      ¬ I ≤ q.asIdeal ∨ ∃ f : Fin d → R, (∀ i, f i ∈ I) ∧ P q f :=
  Iff.rfl

/-- Topological patching for one ideal and fixed-length grade witnesses.

The hypothesis is the exact relative-openness output expected from tag 00RA: for every
fixed sequence `f` in `I`, its `P`-locus inside `V(f)` is the intersection of `V(f)` with
an ambient open set.  The conclusion is the open locus used by the determinantal
Buchsbaum--Eisenbud argument: either `I` is a unit locally, or it contains such a witness.
-/
theorem isOpen_gradeWitnessLocus (I : Ideal R) (d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop)
    (hopen : ∀ (f : Fin d → R), (∀ i, f i ∈ I) →
      ∃ U : Set (PrimeSpectrum R), IsOpen U ∧
        U ∩ PrimeSpectrum.zeroLocus (Set.range f) =
          {q | q ∈ PrimeSpectrum.zeroLocus (Set.range f) ∧ P q f}) :
    IsOpen (gradeWitnessLocus I d P) := by
  rw [isOpen_iff_forall_mem_open]
  intro q hq
  by_cases hunit : ¬ I ≤ q.asIdeal
  · let U : Set (PrimeSpectrum R) :=
      (PrimeSpectrum.zeroLocus (I : Set R))ᶜ
    refine ⟨U, ?_, (PrimeSpectrum.isClosed_zeroLocus (I : Set R)).isOpen_compl, hunit⟩
    intro q' hq'
    exact Or.inl hq'
  · obtain ⟨f, hfI, hPf⟩ := hq.resolve_left hunit
    obtain ⟨U, hUopen, hUeq⟩ := hopen f hfI
    let W : Set (PrimeSpectrum R) :=
      U ∪ (PrimeSpectrum.zeroLocus (I : Set R))ᶜ
    have hqzero : q ∈ PrimeSpectrum.zeroLocus (Set.range f) := by
      intro x hx
      obtain ⟨i, rfl⟩ := hx
      exact (show I ≤ q.asIdeal from not_not.mp hunit) (hfI i)
    have hqU : q ∈ U := by
      have : q ∈ U ∩ PrimeSpectrum.zeroLocus (Set.range f) := by
        rw [hUeq]
        exact ⟨hqzero, hPf⟩
      exact this.1
    refine ⟨W, ?_, hUopen.union
      (PrimeSpectrum.isClosed_zeroLocus (I : Set R)).isOpen_compl, Or.inl hqU⟩
    intro q' hq'W
    rcases hq'W with hq'U | hq'unit
    · by_cases hIq : I ≤ q'.asIdeal
      · refine Or.inr ⟨f, hfI, ?_⟩
        have hq'zero : q' ∈ PrimeSpectrum.zeroLocus (Set.range f) := by
          intro x hx
          obtain ⟨i, rfl⟩ := hx
          exact hIq (hfI i)
        have : q' ∈ U ∩ PrimeSpectrum.zeroLocus (Set.range f) :=
          ⟨hq'U, hq'zero⟩
        rw [hUeq] at this
        exact this.2
      · exact Or.inl hIq
    · exact Or.inl hq'unit

/-- Subtype-topology form of `Ideal.isOpen_gradeWitnessLocus`.

This accepts the natural formulation of fixed-sequence relative openness: the `P`-locus is
open in the zero locus of the sequence. -/
theorem isOpen_gradeWitnessLocus_of_isOpen_subtype (I : Ideal R) (d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop)
    (hopen : ∀ (f : Fin d → R), (∀ i, f i ∈ I) →
      IsOpen {q : PrimeSpectrum.zeroLocus (Set.range f) | P q.1 f}) :
    IsOpen (gradeWitnessLocus I d P) := by
  apply isOpen_gradeWitnessLocus I d P
  intro f hfI
  obtain ⟨U, hUopen, hUeq⟩ := (hopen f hfI).image_val
  refine ⟨U, hUopen, ?_⟩
  rw [← hUeq]
  ext q
  simp [and_comm]

end Ideal

namespace Matrix

variable {R : Type u} [CommRing R]
variable {m : Type v} {n : Type w}

/-- The determinant-and-grade locus associated to the `r × r` minor ideal of a matrix. -/
def determinantalGradeLocus (A : Matrix m n R) (r d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop) : Set (PrimeSpectrum R) :=
  Ideal.gradeWitnessLocus (minorIdeal A r) d P

@[simp]
theorem mem_determinantalGradeLocus (A : Matrix m n R) (r d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop) (q : PrimeSpectrum R) :
    q ∈ determinantalGradeLocus A r d P ↔
      ¬ minorIdeal A r ≤ q.asIdeal ∨
        ∃ f : Fin d → R, (∀ i, f i ∈ minorIdeal A r) ∧ P q f :=
  Iff.rfl

/-- A concrete determinantal specialization of `Ideal.isOpen_gradeWitnessLocus`. -/
theorem isOpen_determinantalGradeLocus (A : Matrix m n R) (r d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop)
    (hopen : ∀ (f : Fin d → R), (∀ i, f i ∈ minorIdeal A r) →
      ∃ U : Set (PrimeSpectrum R), IsOpen U ∧
        U ∩ PrimeSpectrum.zeroLocus (Set.range f) =
          {q | q ∈ PrimeSpectrum.zeroLocus (Set.range f) ∧ P q f}) :
    IsOpen (determinantalGradeLocus A r d P) :=
  Ideal.isOpen_gradeWitnessLocus (minorIdeal A r) d P hopen

/-- Subtype-topology form of `Matrix.isOpen_determinantalGradeLocus`. -/
theorem isOpen_determinantalGradeLocus_of_isOpen_subtype
    (A : Matrix m n R) (r d : ℕ)
    (P : PrimeSpectrum R → (Fin d → R) → Prop)
    (hopen : ∀ (f : Fin d → R), (∀ i, f i ∈ minorIdeal A r) →
      IsOpen {q : PrimeSpectrum.zeroLocus (Set.range f) | P q.1 f}) :
    IsOpen (determinantalGradeLocus A r d P) :=
  Ideal.isOpen_gradeWitnessLocus_of_isOpen_subtype
    (minorIdeal A r) d P hopen

end Matrix

end

end
