module

public import Mathlib.RingTheory.Ideal.Span
public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
public import Mathlib.LinearAlgebra.Matrix.Adjugate
public import Mathlib.RingTheory.Ideal.Maps
public import Mathlib.LinearAlgebra.Span.Basic

/-!
# Fitting ideals of a presented quotient

Ring-level groundwork for **Stacks 07Z8–07ZD** (`more-algebra.tex`,
§`07Z6` *Fitting ideals*), in the presentation-free form used by the Grassmannian
chart machinery of §2.2: instead of a finite module with a chosen presentation, the
input is a submodule `W ⊆ (Fin n → R)` — the kernel data — and the `k`-th Fitting
ideal of the quotient `(Fin n → R) ⧸ W` is the ideal generated by the
`(n - k) × (n - k)` minors of matrices whose columns lie in `W`.

With this definition presentation-independence (Stacks 07Z8/07Z9) is not needed for
the chart machinery; what is needed is functoriality in the ring, which is
`fittingIdeal_span_image_map` below: the Fitting ideal of the coordinatewise image
span is the image ideal. That is the affine-local content of
`PiSubmoduleData.fittingIdealSheaf_ideal_of_span`.

Main declarations:
- `Submodule.fittingIdeal`;
- `Submodule.fittingIdeal_mono`;
- `Submodule.fittingIdeal_span_image_map`.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

universe u v

namespace Submodule

variable {R : Type u} [CommRing R] {S : Type v} [CommRing S]

/-- The `k`-th Fitting ideal of the quotient of `Fin n → R` by `W`: the ideal
generated by all `m × m` determinants, `m = n - k`, of matrices whose `m` columns lie
in `W`, evaluated on an arbitrary choice of `m` rows.

Stacks 07Z8/07ZB (`more-algebra-definition-fitting-ideal`), in the kernel-column form
of the proof of `more-algebra-lemma-fitting-ideal`. -/
def fittingIdeal {n : ℕ} (W : Submodule R (Fin n → R)) (k : ℕ) : Ideal R :=
  Ideal.span { r : R | ∃ z : Fin (n - k) → (Fin n → R), (∀ j, z j ∈ W) ∧
    ∃ rows : Fin (n - k) → Fin n,
      r = Matrix.det (Matrix.of fun i j ↦ z j (rows i)) }

/-- Fitting ideals are monotone in the submodule. -/
theorem fittingIdeal_mono {n : ℕ} {W W' : Submodule R (Fin n → R)} (h : W ≤ W')
    (k : ℕ) : W.fittingIdeal k ≤ W'.fittingIdeal k := by
  apply Ideal.span_mono
  rintro r ⟨z, hz, rows, rfl⟩
  exact ⟨z, fun j ↦ h (hz j), rows, rfl⟩

/-- The Fitting ideal of the full submodule is `⊤` (for `k ≤ n` the identity columns
give determinant `1`; for `k > n` the empty determinant is `1`). -/
theorem fittingIdeal_top {n : ℕ} (k : ℕ) :
    (⊤ : Submodule R (Fin n → R)).fittingIdeal k = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  apply Ideal.subset_span
  classical
  refine ⟨fun j i ↦ if i = Fin.castLE (Nat.sub_le n k) j then 1 else 0,
    fun j ↦ trivial, fun i ↦ Fin.castLE (Nat.sub_le n k) i, ?_⟩
  rw [show (Matrix.of fun i j ↦ (fun j (i : Fin n) ↦
      if i = Fin.castLE (Nat.sub_le n k) j then (1 : R) else 0) j
        ((fun i ↦ Fin.castLE (Nat.sub_le n k) i) i)) = 1 from ?_, Matrix.det_one]
  ext i j
  simp only [Matrix.of_apply, Matrix.one_apply, Fin.castLE_inj]

/-- Functoriality along a ring map: the Fitting ideal of the span of the
coordinatewise image of `W` is the image ideal of the Fitting ideal of `W`.

This is the affine-local content of the compatibility of the Fitting-ideal sheaf with
restriction (`PiSubmoduleData.fittingIdealSheaf_ideal_of_span`). -/
theorem fittingIdeal_span_image_map {n : ℕ} (φ : R →+* S)
    (W : Submodule R (Fin n → R)) (k : ℕ) :
    (Submodule.span S ((fun w (i : Fin n) ↦ φ (w i)) '' (W : Set (Fin n → R)))).fittingIdeal k
      = Ideal.map φ (W.fittingIdeal k) := by
  apply le_antisymm
  · -- a determinant of columns in the span is an `S`-combination of images of
    -- determinants of columns in `W`, by multilinearity of the determinant
    rw [fittingIdeal, Ideal.span_le]
    rintro r ⟨z, hz, rows, rfl⟩
    -- each column decomposes as an `S`-combination of image columns; expand the
    -- determinant multilinearly
    -- We prove the statement by induction on the columns using
    -- `Submodule.span_induction` for each column in turn; packaged as a claim on
    -- arbitrary matrices with columns in the span.
    have key : ∀ (m : ℕ) (M : Fin m → (Fin n → S)),
        (∀ j, M j ∈ Submodule.span S
          ((fun w (i : Fin n) ↦ φ (w i)) '' (W : Set (Fin n → R)))) →
        ∀ rows : Fin m → Fin n,
          Matrix.det (Matrix.of fun i j ↦ M j (rows i)) ∈
            Ideal.map φ (Ideal.span { r : R | ∃ z : Fin m → (Fin n → R),
              (∀ j, z j ∈ W) ∧ ∃ rows : Fin m → Fin n,
                r = Matrix.det (Matrix.of fun i j ↦ z j (rows i)) }) := by
      intro m M hM rows
      classical
      rw [show (Matrix.of fun i j ↦ M j (rows i)) =
          (Matrix.of fun j i ↦ M j (rows i)).transpose from rfl,
        Matrix.det_transpose]
      set T : Set (Fin m → S) :=
        ((fun w ↦ fun i ↦ φ (w (rows i))) '' (W : Set (Fin n → R))) with hT
      have hrow : ∀ j, (fun i ↦ M j (rows i)) ∈ Submodule.span S T := by
        intro j
        have h1 : (fun i ↦ M j (rows i)) = (LinearMap.funLeft S S rows) (M j) := rfl
        rw [h1]
        have h2 := Submodule.mem_map_of_mem (f := LinearMap.funLeft S S rows) (hM j)
        rw [Submodule.map_span] at h2
        refine Submodule.span_mono ?_ h2
        rintro _ ⟨_, ⟨w, hw, rfl⟩, rfl⟩
        exact ⟨w, hw, rfl⟩
      choose N c g hg using fun j ↦ Submodule.mem_span_set'.mp (hrow j)
      have hdet : (Matrix.of fun j i ↦ M j (rows i)).det =
          ∑ r ∈ Fintype.piFinset (fun j : Fin m ↦ (Finset.univ : Finset (Fin (N j)))),
            (∏ j, c j (r j)) *
              Matrix.detRowAlternating (fun j ↦ ((g j (r j) : Fin m → S))) := by
        calc (Matrix.of fun j i ↦ M j (rows i)).det
            = Matrix.detRowAlternating (fun j ↦ (fun i ↦ M j (rows i))) := rfl
          _ = Matrix.detRowAlternating
                (fun j ↦ ∑ t, c j t • ((g j t : Fin m → S))) := by
              congr 1
              funext j
              exact (hg j).symm
          _ = ∑ r ∈ Fintype.piFinset (fun j : Fin m ↦ (Finset.univ : Finset (Fin (N j)))),
                Matrix.detRowAlternating
                  (fun j ↦ c j (r j) • ((g j (r j) : Fin m → S))) :=
              (Matrix.detRowAlternating).toMultilinearMap.map_sum_finset _ _
          _ = _ := by
              refine Finset.sum_congr rfl fun r _ ↦ ?_
              exact ((Matrix.detRowAlternating).toMultilinearMap.map_smul_univ
                (fun j ↦ c j (r j))
                (fun j ↦ ((g j (r j) : Fin m → S)))).trans (smul_eq_mul _ _)
      rw [hdet]
      refine Submodule.sum_mem _ fun r _ ↦ Ideal.mul_mem_left _ _ ?_
      -- each pure term is the image of a generator
      have hpure : Matrix.detRowAlternating (fun j ↦ ((g j (r j) : Fin m → S))) =
          φ ((Matrix.of fun i j ↦ (Classical.choose ((g j (r j)).2)) (rows i)).det) := by
        have hval : ∀ j, ((g j (r j) : Fin m → S)) =
            fun i ↦ φ ((Classical.choose ((g j (r j)).2)) (rows i)) := by
          intro j
          exact (Classical.choose_spec ((g j (r j)).2)).2.symm
        calc Matrix.detRowAlternating (fun j ↦ ((g j (r j) : Fin m → S)))
            = (Matrix.of fun j i ↦
                φ ((Classical.choose ((g j (r j)).2)) (rows i))).det := by
              congr 1
              funext j
              exact hval j
          _ = ((φ.mapMatrix (Matrix.of fun j i ↦
                (Classical.choose ((g j (r j)).2)) (rows i))) : Matrix _ _ S).det := rfl
          _ = φ ((Matrix.of fun j i ↦
                (Classical.choose ((g j (r j)).2)) (rows i)).det) :=
              (RingHom.map_det φ _).symm
          _ = φ ((Matrix.of fun i j ↦
                (Classical.choose ((g j (r j)).2)) (rows i)).det) := by
              rw [show (Matrix.of fun j i ↦
                  (Classical.choose ((g j (r j)).2)) (rows i)) =
                (Matrix.of fun i j ↦
                  (Classical.choose ((g j (r j)).2)) (rows i)).transpose from rfl,
                Matrix.det_transpose]
      rw [hpure]
      refine Ideal.mem_map_of_mem φ (Ideal.subset_span ?_)
      exact ⟨fun j ↦ Classical.choose ((g j (r j)).2),
        fun j ↦ (Classical.choose_spec ((g j (r j)).2)).1, rows, rfl⟩
    -- specialize to `m = n - k`
    have := key (n - k) z hz rows
    -- the inner span is definitionally the Fitting ideal
    exact this
  · rw [Ideal.map_le_iff_le_comap, fittingIdeal, Ideal.span_le]
    rintro r ⟨z, hz, rows, rfl⟩
    show φ _ ∈ (Submodule.span S _).fittingIdeal k
    apply Ideal.subset_span
    refine ⟨fun j i ↦ φ (z j i), fun j ↦ Submodule.subset_span ⟨z j, hz j, rfl⟩,
      rows, ?_⟩
    exact (RingHom.map_det φ (Matrix.of fun i j ↦ z j (rows i))).trans rfl

/-- The coordinatewise image span of a join is the join of the image spans. -/
theorem span_image_piMap_sup {n : ℕ} (φ : R →+* S) (A B : Submodule R (Fin n → R)) :
    Submodule.span S ((fun w (i : Fin n) ↦ φ (w i)) '' ((A ⊔ B : Submodule R (Fin n → R)) : Set (Fin n → R))) =
      Submodule.span S ((fun w (i : Fin n) ↦ φ (w i)) '' (A : Set (Fin n → R))) ⊔
        Submodule.span S ((fun w (i : Fin n) ↦ φ (w i)) '' (B : Set (Fin n → R))) := by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨w, hw, rfl⟩
    obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hw
    have heq : (fun w (i : Fin n) ↦ φ (w i)) (a + b) =
        (fun i ↦ φ (a i)) + (fun i ↦ φ (b i)) := by
      funext i
      simp [map_add]
    exact heq ▸ Submodule.add_mem _
      (Submodule.mem_sup_left (Submodule.subset_span ⟨a, ha, rfl⟩))
      (Submodule.mem_sup_right (Submodule.subset_span ⟨b, hb, rfl⟩))
  · refine sup_le (Submodule.span_mono ?_) (Submodule.span_mono ?_)
    · exact Set.image_mono fun x hx ↦ Submodule.mem_sup_left hx
    · exact Set.image_mono fun x hx ↦ Submodule.mem_sup_right hx

/-- The coordinatewise image span of the coordinate-supported submodule is the
coordinate-supported submodule over the target ring. -/
theorem span_image_piMap_piBot {n : ℕ} (φ : R →+* S) (I : Finset (Fin n)) :
    Submodule.span S ((fun w (i : Fin n) ↦ φ (w i)) ''
        ((Submodule.pi ((Iᶜ : Finset (Fin n)) : Set (Fin n))
          (fun _ ↦ (⊥ : Submodule R R))) : Set (Fin n → R))) =
      Submodule.pi ((Iᶜ : Finset (Fin n)) : Set (Fin n))
        (fun _ ↦ (⊥ : Submodule S S)) := by
  classical
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨w, hw, rfl⟩
    intro j hj
    have h0 : w j = 0 := hw j hj
    simp [h0]
  · intro v hv
    have hval : v = ∑ p ∈ I, v p • (fun i ↦ φ ((Pi.single p 1 : Fin n → R) i)) := by
      funext i
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
      by_cases hi : i ∈ I
      · rw [Finset.sum_eq_single i (fun p _ hpi ↦ by
            simp [Pi.single_apply, Ne.symm hpi]) (fun h ↦ absurd hi h)]
        simp [Pi.single_apply]
      · have h0 : v i = 0 := by
          have := hv i (by simpa using hi)
          simpa using this
        rw [h0]
        symm
        refine Finset.sum_eq_zero fun p hp ↦ ?_
        have hpi : i ≠ p := fun h ↦ hi (h ▸ hp)
        simp [Pi.single_apply, hpi]
    rw [hval]
    refine Submodule.sum_mem _ fun p hp ↦ Submodule.smul_mem _ _
      (Submodule.subset_span ⟨Pi.single p 1, ?_, rfl⟩)
    intro j hj
    have hpj : p ≠ j := by
      rintro rfl
      simp only [Finset.coe_compl, Set.mem_compl_iff, Finset.mem_coe] at hj
      exact hj hp
    simp [Pi.single_apply, Ne.symm hpj]

/-- The heart of Stacks 07ZA (3), presentation-free form: any full-size minor of columns
in `W` multiplies every vector into `W`. The full-matrix case is Cramer's rule
(`Matrix.mul_adjugate`); an arbitrary row selection reduces to it by permutation, or has
determinant zero when two rows repeat. -/
theorem smul_mem_of_forall_mem_of_rows {n : ℕ} {W : Submodule R (Fin n → R)}
    (z : Fin n → (Fin n → R)) (hz : ∀ j, z j ∈ W) (rows : Fin n → Fin n)
    (v : Fin n → R) :
    (Matrix.of fun i j ↦ z j (rows i)).det • v ∈ W := by
  classical
  -- first the identity-rows case, by Cramer
  have base : ∀ (p : Fin n),
      (Matrix.of fun i j ↦ z j i).det • (Pi.single p 1 : Fin n → R) ∈ W := by
    intro p
    set A : Matrix (Fin n) (Fin n) R := (Matrix.of fun i j ↦ z j i : Matrix (Fin n) (Fin n) R) with hA
    have hcram : (∑ j, (Matrix.adjugate A) j p • z j)
        = A.det • (Pi.single p 1 : Fin n → R) := by
      funext i
      simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
      have := Matrix.mul_adjugate A
      have hentry := congrFun (congrFun this i) p
      simp only [Matrix.mul_apply, Matrix.smul_apply, Matrix.one_apply,
        smul_eq_mul] at hentry
      calc ∑ j, (Matrix.adjugate A) j p * z j i
          = ∑ j, A i j * (Matrix.adjugate A) j p := by
            refine Finset.sum_congr rfl fun j _ ↦ ?_
            rw [mul_comm]
            rfl
        _ = A.det * if i = p then 1 else 0 := hentry
        _ = A.det * ((Pi.single p 1 : Fin n → R) i) := by
            rw [show ((Pi.single p 1 : Fin n → R) i) = if i = p then 1 else 0 from
              (Pi.single_apply p 1 i).trans (by simp [eq_comm])]
    rw [← hcram]
    exact Submodule.sum_mem _ fun j _ ↦ Submodule.smul_mem _ _ (hz j)
  have base' : ∀ v : Fin n → R, (Matrix.of fun i j ↦ z j i).det • v ∈ W := by
    intro v
    have hv : v = ∑ p, v p • (Pi.single p 1 : Fin n → R) := by
      funext i
      simp [Pi.single_apply, eq_comm]
    rw [hv, Finset.smul_sum]
    refine Submodule.sum_mem _ fun p _ ↦ ?_
    rw [smul_comm]
    exact Submodule.smul_mem _ _ (base p)
  by_cases hinj : Function.Injective rows
  · -- a permutation of the rows: the determinant changes by a sign
    let σ : Equiv.Perm (Fin n) := Equiv.ofBijective rows
      ((Finite.injective_iff_bijective).mp hinj)
    have hσ : (Matrix.of fun i j ↦ z j (rows i)) =
        (Matrix.of fun i j ↦ z j i).submatrix σ id := by
      ext i j
      rfl
    rw [hσ, Matrix.det_permute]
    rw [show ((Equiv.Perm.sign σ : ℤˣ) : R) * (Matrix.of fun i j ↦ z j i).det =
        ((Equiv.Perm.sign σ : ℤˣ) : R) • (Matrix.of fun i j ↦ z j i).det from rfl,
      smul_assoc]
    exact Submodule.smul_mem _ _ (base' v)
  · -- two repeated rows: the determinant vanishes
    obtain ⟨i, j, hij, hne⟩ : ∃ i j, rows i = rows j ∧ i ≠ j := by
      simp only [Function.Injective, not_forall] at hinj
      obtain ⟨i, j, h1, h2⟩ := hinj
      exact ⟨i, j, h1, h2⟩
    have hdet : (Matrix.of fun i j ↦ z j (rows i)).det = 0 :=
      Matrix.det_zero_of_row_eq hne (by
        funext l
        show z l (rows i) = z l (rows j)
        rw [hij])
    rw [hdet, zero_smul]
    exact Submodule.zero_mem _

/-- **Stacks 07ZA (part)**: the zeroth Fitting ideal of `(Fin n → R) ⧸ W` is the unit
ideal if and only if `W` is everything. No localization is needed: every generator of
`Fit₀` multiplies the ambient module into `W` by Cramer's rule, so `1 ∈ Fit₀` forces
`W = ⊤`; the converse is `fittingIdeal_top`. -/
theorem fittingIdeal_zero_eq_top_iff {n : ℕ} (W : Submodule R (Fin n → R)) :
    W.fittingIdeal 0 = ⊤ ↔ W = ⊤ := by
  constructor
  · intro h
    rw [eq_top_iff]
    rintro v -
    -- the colon-ideal of scalars multiplying everything into `W`
    have hgen : W.fittingIdeal 0 ≤
        { carrier := { d : R | ∀ u : Fin n → R, d • u ∈ W }
          zero_mem' := fun u ↦ by rw [zero_smul]; exact W.zero_mem
          add_mem' := fun {a b} ha hb u ↦ by
            rw [add_smul]; exact W.add_mem (ha u) (hb u)
          smul_mem' := fun c {d} hd u ↦ by
            rw [smul_eq_mul, mul_smul]; exact W.smul_mem c (hd u) } := by
      rw [fittingIdeal, Ideal.span_le]
      rintro d ⟨z, hz, rows, rfl⟩
      intro u
      -- `Fin (n - 0)` is `Fin n` up to the definitional equality `n - 0 = n`
      exact smul_mem_of_forall_mem_of_rows (W := W)
        (fun j ↦ z (Fin.cast (Nat.sub_zero n).symm j))
        (fun j ↦ hz _) (fun i ↦ rows (Fin.cast (Nat.sub_zero n).symm i)) u
    have h1 : (1 : R) ∈ W.fittingIdeal 0 := h ▸ Submodule.mem_top
    have := hgen h1 v
    rwa [one_smul] at this
  · rintro rfl
    exact fittingIdeal_top 0

/-- The submodule of vectors supported in the coordinates `I` is spanned by the
corresponding standard basis vectors. -/
theorem piBot_eq_span_single {n : ℕ} (I : Finset (Fin n)) :
    (Submodule.pi ((Iᶜ : Finset (Fin n)) : Set (Fin n))
        (fun _ ↦ (⊥ : Submodule R R)) : Submodule R (Fin n → R)) =
      Submodule.span R ((fun i ↦ (Pi.single i 1 : Fin n → R)) '' ↑I) := by
  classical
  apply le_antisymm
  · intro w hw
    have hrep : w = ∑ i ∈ I, w i • (Pi.single i 1 : Fin n → R) := by
      funext j
      rw [Finset.sum_apply]
      by_cases hj : j ∈ I
      · rw [Finset.sum_eq_single_of_mem j hj]
        · simp
        · intro i _ hij
          simp [Pi.single_eq_of_ne (Ne.symm hij)]
      · have h0 : w j = 0 := hw j (by simpa using hj)
        rw [h0]
        refine (Finset.sum_eq_zero ?_).symm
        intro i hi
        have hij : j ≠ i := fun h ↦ hj (h ▸ hi)
        simp [Pi.single_eq_of_ne hij]
    rw [hrep]
    exact Submodule.sum_mem _ fun i hi ↦ Submodule.smul_mem _ _
      (Submodule.subset_span ⟨i, hi, rfl⟩)
  · rw [Submodule.span_le]
    rintro _ ⟨i, hi, rfl⟩
    intro j hj
    have hij : j ≠ i := by
      rintro rfl
      have hjI : j ∉ I := by simpa using hj
      exact hjI hi
    simp [Pi.single_eq_of_ne hij]

end Submodule
