module

public import StacksAndModuli.API.FormalBranchComponents
public import Mathlib.RingTheory.Flat.EquationalCriterion
public import Mathlib.RingTheory.Ideal.AssociatedPrime.Localization

/-!
# Minimal primes under flat extension to a reduced ring

Flat base change preserves the annihilator of one element.  In a Noetherian ring,
every minimal prime is the annihilator of one element.  These two facts identify the
extension of a minimal prime whenever a reduced flat algebra has a unique minimal
prime above it.

The uniqueness hypothesis is essential: if several minimal primes lie above the same
minimal prime, the extended ideal can be their intersection.

## Main results

* `Ideal.map_annihilator_span_singleton_of_flat`: flat base change preserves a
  principal cyclic annihilator.
* `Ideal.exists_eq_annihilator_span_singleton_of_mem_minimalPrimes`: a minimal prime
  in a Noetherian ring is a cyclic annihilator.
* `Ideal.map_eq_of_unique_minimalPrime_over_of_flat`: over reduced rings, a minimal
  prime with a unique minimal prime above it extends to that prime.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open scoped BigOperators

universe u v

namespace Ideal

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]

/-- Flat base change preserves the annihilator of the submodule generated by one
element. -/
theorem map_annihilator_span_singleton_of_flat [Module.Flat R S] (a : R) :
    ((Submodule.span R ({a} : Set R)).annihilator : Ideal R).map
        (algebraMap R S) =
      ((Submodule.span S ({algebraMap R S a} : Set S)).annihilator :
        Ideal S) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro r hr
    rw [Ideal.mem_comap, Submodule.mem_annihilator_span_singleton]
    rw [Submodule.mem_annihilator_span_singleton] at hr
    simpa [Algebra.smul_def, mul_comm] using congrArg (algebraMap R S) hr
  · intro b hb
    rw [Submodule.mem_annihilator_span_singleton] at hb
    have hsum : ∑ _ : Fin 1, a • b = 0 := by
      simpa [Algebra.smul_def, mul_comm] using hb
    obtain ⟨n, c, y, hc, hca⟩ :=
      Module.Flat.isTrivialRelation_of_sum_smul_eq_zero hsum
    change (fun _ : Fin 1 => b) 0 ∈ _
    rw [hc 0]
    apply Submodule.sum_mem
    intro j _
    rw [Algebra.smul_def]
    apply Ideal.mul_mem_right
    apply Ideal.mem_map_of_mem
    rw [Submodule.mem_annihilator_span_singleton]
    simpa [mul_comm] using hca j

/-- Every minimal prime in a Noetherian ring is the annihilator of the submodule
generated by one element. -/
theorem exists_eq_annihilator_span_singleton_of_mem_minimalPrimes
    [IsNoetherianRing R] {p : Ideal R} (hp : p ∈ minimalPrimes R) :
    ∃ a : R,
      p = ((Submodule.span R ({a} : Set R)).annihilator : Ideal R) := by
  have hp' : p ∈ associatedPrimes R R :=
    Module.associatedPrimes.minimalPrimes_annihilator_subset_associatedPrimes
      R R (by
        rw [show Module.annihilator R R = (⊥ : Ideal R) by
          rw [← Submodule.annihilator_top]
          ext r
          simp only [Submodule.mem_annihilator, Submodule.mem_top,
            forall_const, Ideal.mem_bot]
          constructor
          · intro h
            simpa using h 1
          · rintro rfl
            simp]
        exact hp)
  rw [AssociatedPrimes.mem_iff, isAssociatedPrime_iff] at hp'
  obtain ⟨_, a, ha⟩ := hp'
  exact ⟨a, ha.trans Submodule.bot_colon'⟩

/-- Let `R → S` be flat, with `R` Noetherian and both rings reduced.  If `q` is
the unique minimal prime of `S` contracting to a minimal prime `p` of `R`, then
the extension of `p` is exactly `q`.

In particular, uniqueness removes the possible nonreduced thickening between an
extended minimal prime and its radical; no excellence hypothesis is needed. -/
theorem map_eq_of_unique_minimalPrime_over_of_flat
    [IsNoetherianRing R] [IsReduced R] [Module.Flat R S] [IsReduced S]
    {p : Ideal R} (hp : p ∈ minimalPrimes R)
    {q : Ideal S} (hq : q ∈ minimalPrimes S)
    (hqover : q.comap (algebraMap R S) = p)
    (hunique : ∀ Q ∈ minimalPrimes S,
      Q.comap (algebraMap R S) = p → Q = q) :
    p.map (algebraMap R S) = q := by
  obtain ⟨a, ha⟩ :=
    exists_eq_annihilator_span_singleton_of_mem_minimalPrimes hp
  have ha_not_mem : a ∉ p := by
    intro hap
    rw [ha, Submodule.mem_annihilator_span_singleton] at hap
    have ha_zero : a = 0 :=
      (show IsNilpotent a from
        ⟨2, by simpa [pow_two] using hap⟩).eq_zero
    subst a
    have hp_top : p = ⊤ := by
      rw [ha]
      ext r
      rw [Submodule.mem_annihilator_span_singleton]
      simp
    exact hp.isPrime.ne_top hp_top
  have hfa_not_mem : algebraMap R S a ∉ q := by
    intro h
    exact ha_not_mem (hqover ▸ h)
  have hother : ∀ Q ∈ minimalPrimes S, Q ≠ q →
      algebraMap R S a ∈ Q := by
    intro Q hQ hQq
    have hQmin : Q.comap (algebraMap R S) ∈ minimalPrimes R :=
      Ideal.mem_minimalPrimes_under_of_flat Q hQ
    have hcomap_ne : Q.comap (algebraMap R S) ≠ p := by
      intro hQp
      exact hQq (hunique Q hQ hQp)
    have hp_not_le : ¬p ≤ Q.comap (algebraMap R S) := by
      intro hpQ
      exact hcomap_ne (le_antisymm (hQmin.2 hp.1 hpQ) hpQ)
    obtain ⟨r, hrp, hrQ⟩ := SetLike.not_le_iff_exists.mp hp_not_le
    have hra : r * a = 0 := by
      rw [ha, Submodule.mem_annihilator_span_singleton] at hrp
      simpa [mul_comm] using hrp
    have hprod : algebraMap R S r * algebraMap R S a ∈ Q := by
      rw [← map_mul, hra, map_zero]
      exact Q.zero_mem
    exact (hQ.isPrime.mem_or_mem hprod).resolve_left hrQ
  rw [ha, map_annihilator_span_singleton_of_flat]
  apply le_antisymm
  · intro b hb
    rw [Submodule.mem_annihilator_span_singleton] at hb
    have hprod : b * algebraMap R S a ∈ q := by
      rw [show b * algebraMap R S a = 0 by
        simpa [smul_eq_mul] using hb]
      exact q.zero_mem
    exact (hq.isPrime.mem_or_mem hprod).resolve_right hfa_not_mem
  · intro b hb
    rw [Submodule.mem_annihilator_span_singleton]
    have hmem : b * algebraMap R S a ∈ sInf (minimalPrimes S) := by
      rw [Ideal.mem_sInf]
      intro Q hQ
      by_cases hQq : Q = q
      · subst Q
        exact q.mul_mem_right _ hb
      · exact Q.mul_mem_left _ (hother Q hQ hQq)
    have hzero : b * algebraMap R S a ∈ (⊥ : Ideal S) := by
      rw [Ideal.sInf_minimalPrimes,
        Ideal.radical_eq_iff.mpr Ideal.isRadical_bot] at hmem
      exact hmem
    exact Ideal.mem_bot.mp hzero

end Ideal

end
