module

public import StacksAndModuli.API.GenusZeroCurveClassificationReduction
public import StacksAndModuli.API.ProjectiveLineIrreducibleComponent
public import StacksAndModuli.API.SmoothCurveRationalPoint
public import Mathlib.AlgebraicGeometry.Morphisms.FlatRank
public import Mathlib.AlgebraicGeometry.Noetherian
public import Mathlib.FieldTheory.Finiteness

/-!
# Degree-one reduction for pointed genus-zero curves

A finite flat morphism has locally constant rank once it is locally of finite
presentation.  Consequently, over a preconnected target it is an isomorphism as soon
as its rank is one at a single point.  For a morphism to the projective line over a
field, finite presentation is automatic: the projective line is locally Noetherian.

This gives a precise next step toward the pointed genus-zero classification.  It is
enough to construct a finite flat map from the curve to the projective line whose rank
is one somewhere.  The remaining construction is the divisor/Riemann--Roch input: a
rational point on a smooth proper genus-zero curve should give a degree-one linear
system.  `SmoothCurveRationalPoint` now proves the point-local input: the point is
closed of residue degree one, and its maximal ideal in the DVR stalk is generated by
a regular uniformizer.  The remaining step is globalizing that local equation to an
invertible ideal sheaf, dualizing it, and applying Riemann--Roch to its complete linear
system.

## Main results

* `AlgebraicGeometry.Scheme.Hom.isIso_of_finrank_eq_one_at` recognizes an
  isomorphism from rank one at one point of a preconnected target.
* `AlgebraicGeometry.Scheme.projectiveLineOverIso_of_finite_flat_finrank_eq_one_at`
  gives the corresponding recognition theorem over a field.
* `AlgebraicGeometry.Scheme.HasFiniteFlatRankOneMapToProjectiveLineOver` packages
  the exact degree-one-map construction still needed for a pointed genus-zero curve.
* `AlgebraicGeometry.Scheme.
  hasPointedSmoothGenusZeroClassification_of_finiteFlatRankOneMaps` reduces the
  pointed classification to that construction.
-/

@[expose] public noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory

universe u

namespace AlgebraicGeometry.Scheme

/-- A finite flat locally finitely presented morphism to a preconnected scheme is an
isomorphism if its rank is one at a single point. -/
theorem Hom.isIso_of_finrank_eq_one_at
    {X Y : Scheme.{u}} (f : X ⟶ Y) [Flat f] [IsFinite f]
    [LocallyOfFinitePresentation f] [PreconnectedSpace Y]
    (y : Y) (hy : f.finrank y = 1) : IsIso f := by
  rw [f.isIso_iff_finrank_eq]
  funext z
  exact (f.isLocallyConstant_finrank.apply_eq_of_preconnectedSpace z y).trans hy

/-- For a finite flat locally finitely presented morphism to a preconnected scheme,
being an isomorphism is equivalent to having rank one at any chosen point. -/
theorem Hom.isIso_iff_finrank_eq_one_at
    {X Y : Scheme.{u}} (f : X ⟶ Y) [Flat f] [IsFinite f]
    [LocallyOfFinitePresentation f] [PreconnectedSpace Y] (y : Y) :
    IsIso f ↔ f.finrank y = 1 := by
  constructor
  · intro hf
    let _ : IsIso f := hf
    exact congrFun f.finrank_eq_one_of_isIso y
  · exact f.isIso_of_finrank_eq_one_at y

/-- A finite flat morphism over `k` from a scheme to the projective line is an
over-isomorphism if its rank is one at a single point of the projective line.

No finite-presentation hypothesis is needed: a field is Noetherian, relative
projective space is locally of finite type over its base, and a finite morphism to a
locally Noetherian scheme is locally of finite presentation. -/
theorem projectiveLineOverIso_of_finite_flat_finrank_eq_one_at
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))]
    (f : C ⟶ projectiveSpaceOver 1 (Spec (CommRingCat.of k)))
    [Flat f] [IsFinite f]
    (hf : f ≫ projectiveSpaceOverπ 1 (Spec (CommRingCat.of k)) =
      C ↘ Spec (CommRingCat.of k))
    (y : projectiveSpaceOver 1 (Spec (CommRingCat.of k)))
    (hy : f.finrank y = 1) :
    Nonempty (projectiveLineAsOver k ≅ C.asOver (Spec (CommRingCat.of k))) := by
  let _ : IsNoetherianRing k := IsNoetherian.iff_fg.mpr inferInstance
  let _ : IsLocallyNoetherian
      (projectiveSpaceOver 1 (Spec (CommRingCat.of k))) :=
    LocallyOfFiniteType.isLocallyNoetherian
      (projectiveSpaceOverπ 1 (Spec (CommRingCat.of k)))
  let _ : IsIso f := f.isIso_of_finrank_eq_one_at y hy
  exact ⟨(Over.isoMk (asIso f) hf).symm⟩

/-- A `k`-scheme admits a finite flat rank-one map to the projective line if it has
a morphism to `ℙ¹_k` over `Spec k` that is finite and flat and whose rank is one at
some point of `ℙ¹_k`.

Because `ℙ¹_k` is preconnected and locally Noetherian, rank one at one point is
equivalent to rank one everywhere.  The one-point formulation is convenient when the
map is constructed from a divisor supported at a rational point. -/
def HasFiniteFlatRankOneMapToProjectiveLineOver
    (k : Type u) [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] : Prop :=
  ∃ f : C.asOver (Spec (CommRingCat.of k)) ⟶ projectiveLineAsOver k,
    Flat f.left ∧ IsFinite f.left ∧ ∃ y, f.left.finrank y = 1

/-- A `k`-scheme admitting a finite flat rank-one map to the projective line is
isomorphic over `k` to the projective line. -/
theorem projectiveLineOverIso_of_hasFiniteFlatRankOneMap
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))]
    (h : HasFiniteFlatRankOneMapToProjectiveLineOver k C) :
    Nonempty (projectiveLineAsOver k ≅ C.asOver (Spec (CommRingCat.of k))) := by
  obtain ⟨f, hflat, hfinite, y, hrank⟩ := h
  let _ : Flat f.left := hflat
  let _ : IsFinite f.left := hfinite
  exact projectiveLineOverIso_of_finite_flat_finrank_eq_one_at
    C f.left f.w y hrank

/-- The pointed smooth genus-zero classification follows once every curve in its
hypotheses is supplied with a finite flat rank-one map to the projective line.

This isolates the remaining Riemann--Roch step without assuming the desired
classification itself. -/
theorem hasPointedSmoothGenusZeroClassification_of_finiteFlatRankOneMaps
    (k : Type u) [Field k]
    (H : ∀ (C : Scheme.{u}) [C.Over (Spec (CommRingCat.of k))]
      [IsCurveOver k C] [IsProper (C ↘ Spec (CommRingCat.of k))]
      [Smooth (C ↘ Spec (CommRingCat.of k))]
      [GeometricallyIntegral (C ↘ Spec (CommRingCat.of k))],
        genusOver k C = 0 →
        (∃ s : Spec (CommRingCat.of k) ⟶ C,
          s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) →
        HasFiniteFlatRankOneMapToProjectiveLineOver k C) :
    HasPointedSmoothGenusZeroClassification k := by
  intro C _ _ _ _ _ hgenus hpoint
  exact projectiveLineOverIso_of_hasFiniteFlatRankOneMap C
    (H C hgenus hpoint)

end AlgebraicGeometry.Scheme

end
