module

public import Mathlib.Algebra.GradedMulAction
public import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal

/-!
# Annihilators of homogeneous elements are homogeneous

For a graded module `ℳ` over a graded ring `𝒜` and a homogeneous `m ∈ ℳ j`, the
annihilator of `m` is a homogeneous ideal: if `a • m = 0` then every homogeneous component
of `a` already kills `m`, because the products `(proj i a) • m` live in pairwise distinct
graded pieces of `ℳ`.

This is the input that lets the projective Nullstellensatz
(`StacksAndModuli/API/ProjectiveSpectrumNullstellensatz.lean`) be applied to `Ann m`, which is the
injectivity half of "a section of `M~` over `D₊(f)` is a single fraction".

## Main results

* `SetLike.proj_smul_eq_zero_of_smul_eq_zero`: components of an annihilator annihilate.
* `SetLike.homogeneousAnnihilator`: the ideal generated by the homogeneous annihilators of `m`,
  with `homogeneousAnnihilator_le_annihilator` and
  `not_homogeneousAnnihilator_le_of_not_annihilator_le`.
-/

@[expose] public section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open DirectSum

namespace SetLike

variable {A σ M τ : Type*} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
variable [AddCommGroup M] [Module A M] [SetLike τ M] [AddSubgroupClass τ M]
variable (𝒜 : ℕ → σ) (ℳ : ℕ → τ) [GradedRing 𝒜] [SetLike.GradedSMul 𝒜 ℳ]
variable [DirectSum.Decomposition ℳ]

/-- **The graded component of a scalar multiple.**  For homogeneous `m ∈ ℳ j`, the degree
`k + j` component of `a • m` is `(proj 𝒜 k a) • m`. -/
theorem coe_decompose_smul {j : ℕ} {m : M} (hm : m ∈ ℳ j) (a : A) (k : ℕ) :
    ((DirectSum.decompose ℳ (a • m) (k + j) : ℳ (k + j)) : M)
      = (GradedRing.proj 𝒜 k a) • m := by
  classical
  set s := (DirectSum.decompose 𝒜 a).support with hs
  have hmeml : ∀ l : ℕ, ((DirectSum.decompose 𝒜 a l : A) • m) ∈ ℳ (l + j) := fun l ↦
    SetLike.GradedSMul.smul_mem (DirectSum.decompose 𝒜 a l).2 hm
  have hsum : a • m = ∑ l ∈ s, ((DirectSum.decompose 𝒜 a l : A) • m) := by
    rw [← Finset.sum_smul, hs, DirectSum.sum_support_decompose 𝒜 a]
  have key : DirectSum.decompose ℳ (a • m) (k + j)
      = ∑ l ∈ s,
        (DirectSum.decompose ℳ ((DirectSum.decompose 𝒜 a l : A) • m)) (k + j) := by
    conv_lhs => rw [hsum]
    simp [DFinsupp.finsetSum_apply]
  have hterm : ∀ l ∈ s,
      (DirectSum.decompose ℳ ((DirectSum.decompose 𝒜 a l : A) • m)) (k + j)
        = if l = k then (⟨(DirectSum.decompose 𝒜 a k : A) • m, hmeml k⟩ : ℳ (k + j))
          else 0 := by
    intro l _
    rw [DirectSum.decompose_of_mem ℳ (hmeml l)]
    by_cases hlk : l = k
    · subst hlk
      rw [if_pos rfl, DirectSum.of_eq_same]
    · rw [if_neg hlk, DirectSum.of_eq_of_ne _ _ _ (by omega)]
  rw [key, Finset.sum_congr rfl hterm, Finset.sum_ite_eq' s k]
  by_cases hk : k ∈ s
  · rw [if_pos hk, GradedRing.proj_apply]
  · rw [if_neg hk, GradedRing.proj_apply, DFinsupp.notMem_support_iff.1 hk]
    simp

/-- If `a` kills a homogeneous element `m` of degree `j`, then so does each homogeneous
component of `a`: the summands `(proj i a) • m` sit in the pairwise distinct pieces
`ℳ (i + j)`, so they vanish separately. -/
theorem proj_smul_eq_zero_of_smul_eq_zero {j : ℕ} {m : M} (hm : m ∈ ℳ j) {a : A}
    (h : a • m = 0) (i : ℕ) : (GradedRing.proj 𝒜 i a) • m = 0 := by
  rw [← coe_decompose_smul 𝒜 ℳ hm a i, h]
  simp

/-- **Homogeneous division.**  If a homogeneous element `z` of degree `D` is a multiple of a
homogeneous `s₀` of degree `i ≤ D`, then the cofactor may be taken homogeneous of degree
`D - i`.  This is the ring case `ℳ = 𝒜` of `coe_decompose_smul`. -/
theorem exists_mem_mul_eq_of_mem_span_singleton {i D : ℕ} {s₀ z : A} (hs₀ : s₀ ∈ 𝒜 i)
    (hz : z ∈ 𝒜 D) (hiD : i ≤ D) (h : z ∈ Ideal.span {s₀}) :
    ∃ c, c ∈ 𝒜 (D - i) ∧ z = c * s₀ := by
  obtain ⟨t, ht⟩ := Ideal.mem_span_singleton'.1 h
  refine ⟨GradedRing.proj 𝒜 (D - i) t, (DirectSum.decompose 𝒜 t (D - i)).2, ?_⟩
  have hcomp := coe_decompose_smul 𝒜 𝒜 hs₀ t (D - i)
  rw [smul_eq_mul, ht] at hcomp
  rw [Nat.sub_add_cancel hiD] at hcomp
  rw [DirectSum.decompose_of_mem 𝒜 hz, DirectSum.of_eq_same] at hcomp
  exact hcomp

variable {ℳ}

/-- The ideal generated by the homogeneous elements killing `m`. -/
def homogeneousAnnihilator (m : M) : Ideal A :=
  Ideal.span {b : A | (∃ i, b ∈ 𝒜 i) ∧ b • m = 0}

theorem isHomogeneous_homogeneousAnnihilator (m : M) :
    (homogeneousAnnihilator 𝒜 m).IsHomogeneous 𝒜 :=
  Ideal.homogeneous_span 𝒜 _ (fun _ hb ↦ hb.1)

theorem homogeneousAnnihilator_le_annihilator (m : M) {a : A}
    (ha : a ∈ homogeneousAnnihilator 𝒜 m) : a • m = 0 := by
  refine Submodule.span_induction (p := fun b _ ↦ b • m = 0) (fun b hb ↦ hb.2) (by simp)
    (fun b c _ _ hb hc ↦ by rw [add_smul, hb, hc, add_zero])
    (fun b c _ hc ↦ by rw [smul_eq_mul, mul_smul, hc, smul_zero]) ha

variable (ℳ)

/-- **A homogeneous annihilator outside a homogeneous ideal.**  If some element outside a
homogeneous ideal kills the homogeneous element `m`, then some homogeneous element outside it
does: pass to homogeneous components, which still kill `m` and cannot all lie in the ideal. -/
theorem exists_homogeneous_smul_eq_zero {j : ℕ} {m : M} (hm : m ∈ ℳ j) {P : Ideal A}
    (hP : P.IsHomogeneous 𝒜) {u : A} (hu : u ∉ P) (h : u • m = 0) :
    ∃ (i : ℕ) (u' : A), u' ∈ 𝒜 i ∧ u' ∉ P ∧ u' • m = 0 := by
  classical
  by_contra hcon
  refine hu ?_
  rw [← DirectSum.sum_support_decompose 𝒜 u]
  refine Ideal.sum_mem _ fun i _ ↦ ?_
  by_contra hmem
  exact hcon ⟨i, (DirectSum.decompose 𝒜 u i : A), (DirectSum.decompose 𝒜 u i).2, hmem,
    by simpa [GradedRing.proj_apply] using proj_smul_eq_zero_of_smul_eq_zero 𝒜 ℳ hm h i⟩

/-- If some element outside a homogeneous prime kills the homogeneous element `m`, then some
*homogeneous* element outside it does; equivalently the homogeneous annihilator is not contained
in the prime either. -/
theorem not_homogeneousAnnihilator_le_of_exists {j : ℕ} {m : M} (hm : m ∈ ℳ j)
    {P : Ideal A} (hP : P.IsHomogeneous 𝒜) (hex : ∃ t : A, t ∉ P ∧ t • m = 0) :
    ¬ homogeneousAnnihilator 𝒜 m ≤ P := by
  classical
  obtain ⟨t, htP, ht⟩ := hex
  intro hle
  refine htP ?_
  rw [← DirectSum.sum_support_decompose 𝒜 t]
  refine Ideal.sum_mem _ fun i _ ↦
    hle (Ideal.subset_span ⟨⟨i, (decompose 𝒜 t i).2⟩, ?_⟩)
  have := proj_smul_eq_zero_of_smul_eq_zero 𝒜 ℳ hm ht i
  rwa [GradedRing.proj_apply] at this

section Ring

variable {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
variable (𝒜 : ℕ → σ) [GradedRing 𝒜]

/-- Projection of a homogeneous element onto its own degree is the identity. -/
theorem proj_of_mem {D : ℕ} {z : A} (hz : z ∈ 𝒜 D) : GradedRing.proj 𝒜 D z = z := by
  rw [GradedRing.proj_apply, DirectSum.decompose_of_mem 𝒜 hz, DirectSum.of_eq_same]

/-- Projecting a product with a homogeneous factor shifts the projection to the other factor. -/
theorem proj_mul_of_mem {n : ℕ} {g : A} (hg : g ∈ 𝒜 n) (t : A) (k : ℕ) :
    GradedRing.proj 𝒜 (k + n) (t * g) = GradedRing.proj 𝒜 k t * g := by
  have := SetLike.coe_decompose_smul 𝒜 𝒜 hg t k
  rw [smul_eq_mul, smul_eq_mul] at this
  rw [GradedRing.proj_apply]
  exact this

/-- **Homogenizing the coefficients of a representation.**  If a homogeneous element of degree
`D` is a combination of homogeneous elements `g i` of degrees `n i ≤ D`, the coefficients may be
replaced by their degree-`D - n i` components. -/
theorem eq_sum_proj_mul {ι : Type*} (s : Finset ι) {n : ι → ℕ} {g : ι → A}
    (hg : ∀ i, g i ∈ 𝒜 (n i)) (lam : ι → A) {D : ℕ} {z : A} (hz : z ∈ 𝒜 D)
    (hzeq : z = ∑ i ∈ s, lam i * g i) (hD : ∀ i ∈ s, n i ≤ D) :
    z = ∑ i ∈ s, (GradedRing.proj 𝒜 (D - n i) (lam i)) * g i := by
  have hproj := congrArg (GradedRing.proj 𝒜 D) hzeq
  rw [proj_of_mem 𝒜 hz, map_sum] at hproj
  refine hproj.trans (Finset.sum_congr rfl fun i hi ↦ ?_)
  have hni : D - n i + n i = D := Nat.sub_add_cancel (hD i hi)
  calc GradedRing.proj 𝒜 D (lam i * g i)
      = GradedRing.proj 𝒜 (D - n i + n i) (lam i * g i) := by rw [hni]
    _ = GradedRing.proj 𝒜 (D - n i) (lam i) * g i := proj_mul_of_mem 𝒜 (hg i) _ _

end Ring

end SetLike
