module

public import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
public import Mathlib.LinearAlgebra.TensorProduct.Pi
public import Mathlib.RingTheory.Finiteness.Basic

/-!
# Zero loci of maps into finite free modules

Let `φ : M →ₗ[R] (Fin r → R)`.  The ideal generated by all coordinates
`φ(m)(i)` cuts out exactly those scalar extensions on which `φ` becomes zero.
This file proves that assertion directly and packages the corresponding affine closed
subscheme of `Spec R` with its universal factorization property.

No finiteness hypothesis on `M` is needed for the universal property.  In applications
over a noetherian ring the coefficient ideal is automatically finitely generated.

Main declarations:

* `LinearMap.coefficientIdeal`;
* `LinearMap.coefficientIdeal_fg`;
* `LinearMap.baseChangeToPi`;
* `LinearMap.coefficientIdeal_baseChangeToPi`;
* `LinearMap.baseChangeToPi_eq_zero_iff`;
* `LinearMap.map_coefficientIdeal_eq_bot_iff`;
* `LinearMap.zeroLocus` and `LinearMap.zeroLocusι`;
* `LinearMap.baseChangeToPi_eq_zero_iff_exists_zeroLocusLift`.
-/

@[expose] public section

set_option linter.style.haveILetI false

open CategoryTheory
open AlgebraicGeometry
open TensorProduct

universe u v w

namespace LinearMap

section Ring

variable {R : Type u} [CommRing R]
variable {M : Type v} [AddCommGroup M] [Module R M]
variable {r : ℕ}

/-- The ideal generated by all coordinates of a linear map into a finite free module. -/
def coefficientIdeal (φ : M →ₗ[R] (Fin r → R)) : Ideal R :=
  Ideal.span (Set.range fun x : M × Fin r ↦ φ x.1 x.2)

/-- Every coordinate of `φ` lies in its coefficient ideal. -/
lemma apply_mem_coefficientIdeal (φ : M →ₗ[R] (Fin r → R)) (m : M) (i : Fin r) :
    φ m i ∈ φ.coefficientIdeal :=
  Ideal.subset_span (Set.mem_range_self (m, i))

/-- To prove that the coefficient ideal is contained in another ideal, it suffices to
check every coordinate of the original linear map. -/
lemma coefficientIdeal_le_iff (φ : M →ₗ[R] (Fin r → R)) (I : Ideal R) :
    φ.coefficientIdeal ≤ I ↔ ∀ (m : M) (i : Fin r), φ m i ∈ I := by
  rw [coefficientIdeal, Ideal.span_le]
  constructor
  · intro h m i
    exact h (Set.mem_range_self (m, i))
  · rintro h _ ⟨⟨m, i⟩, rfl⟩
    exact h m i

/-- A finite generating family for the source gives a finite generating family, obtained
by taking all its coordinates, for the coefficient ideal. -/
lemma coefficientIdeal_eq_span_of_span_eq_top (φ : M →ₗ[R] (Fin r → R))
    {n : ℕ} (s : Fin n → M) (hs : Submodule.span R (Set.range s) = ⊤) :
    φ.coefficientIdeal =
      Ideal.span (Set.range fun x : Fin n × Fin r ↦ φ (s x.1) x.2) := by
  let J := Ideal.span (Set.range fun x : Fin n × Fin r ↦ φ (s x.1) x.2)
  apply le_antisymm
  · rw [coefficientIdeal_le_iff]
    intro m i
    have hm : m ∈ Submodule.span R (Set.range s) := by
      rw [hs]
      trivial
    change φ m i ∈ J
    induction hm using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨j, rfl⟩ := hx
        exact Ideal.subset_span (Set.mem_range_self (j, i))
    | zero =>
        simp
    | add x y _ _ hx hy =>
        simpa using J.add_mem hx hy
    | smul a x _ hx =>
        simpa [smul_eq_mul] using Ideal.mul_mem_left J a hx
  · rw [Ideal.span_le]
    rintro _ ⟨⟨j, i⟩, rfl⟩
    exact φ.apply_mem_coefficientIdeal (s j) i

/-- If the source is a finite module, the coefficient ideal is finitely generated. -/
lemma coefficientIdeal_fg [Module.Finite R M] (φ : M →ₗ[R] (Fin r → R)) :
    φ.coefficientIdeal.FG := by
  obtain ⟨n, s, hs⟩ := Module.Finite.exists_fin (R := R) (M := M)
  rw [φ.coefficientIdeal_eq_span_of_span_eq_top s hs]
  exact Submodule.fg_span (Set.finite_range _)

/-- Scalar extension of a map into `R^r`, followed by the canonical identification
`A ⊗_R R^r ≃ A^r`. -/
noncomputable def baseChangeToPi {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      A ⊗[R] M →ₗ[A] (Fin r → A)) := by
  letI : Algebra R A := f.toAlgebra
  exact (TensorProduct.piScalarRight R A A (Fin r)).toLinearMap.comp (φ.baseChange A)

/-- Formula for scalar extension on pure tensors. -/
@[simp]
lemma baseChangeToPi_tmul_apply {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) (a : A) (m : M) (i : Fin r) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f (a ⊗ₜ[R] m) i = a * f (φ m i)) := by
  letI : Algebra R A := f.toAlgebra
  simp [baseChangeToPi, Algebra.smul_def, RingHom.algebraMap_toAlgebra, mul_comm]

/-- Formation of the coefficient ideal commutes with arbitrary scalar extension. -/
lemma coefficientIdeal_baseChangeToPi {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      (φ.baseChangeToPi f).coefficientIdeal = Ideal.map f φ.coefficientIdeal) := by
  letI : Algebra R A := f.toAlgebra
  apply le_antisymm
  · rw [coefficientIdeal_le_iff]
    intro x i
    induction x using TensorProduct.induction_on with
    | zero =>
        simp
    | tmul a m =>
        rw [baseChangeToPi_tmul_apply]
        exact Ideal.mul_mem_left _ a
          (Ideal.mem_map_of_mem f (φ.apply_mem_coefficientIdeal m i))
    | add x y hx hy =>
        simpa using (Ideal.map f φ.coefficientIdeal).add_mem hx hy
  · refine Ideal.map_le_iff_le_comap.mpr ?_
    rw [coefficientIdeal_le_iff]
    intro m i
    change f (φ m i) ∈ (φ.baseChangeToPi f).coefficientIdeal
    simpa using
      (φ.baseChangeToPi f).apply_mem_coefficientIdeal (1 ⊗ₜ[R] m) i

/-- The scalar extension of `φ` along `f` is zero exactly when `f` kills every
coordinate of `φ`. -/
lemma baseChangeToPi_eq_zero_iff_apply {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f = 0 ↔ ∀ (m : M) (i : Fin r), f (φ m i) = 0) := by
  letI : Algebra R A := f.toAlgebra
  constructor
  · intro h m i
    have h' : φ.baseChangeToPi f (1 ⊗ₜ[R] m) i = 0 := by
      rw [h]
      rfl
    simpa using h'
  · intro h
    apply AlgebraTensorModule.ext
    intro a m
    ext i
    simp [h m i]

/-- The scalar extension of `φ` is zero exactly when its coefficient ideal is
contained in the kernel of the base ring map. -/
lemma baseChangeToPi_eq_zero_iff {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f = 0 ↔ φ.coefficientIdeal ≤ RingHom.ker f) := by
  letI : Algebra R A := f.toAlgebra
  rw [baseChangeToPi_eq_zero_iff_apply, coefficientIdeal_le_iff]
  simp only [RingHom.mem_ker]

/-- Equivalent ideal-map formulation of vanishing after scalar extension. -/
lemma map_coefficientIdeal_eq_bot_iff {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    Ideal.map f φ.coefficientIdeal = ⊥ ↔
      (letI : Algebra R A := f.toAlgebra;
        φ.baseChangeToPi f = 0) := by
  rw [Ideal.map_eq_bot_iff_le_ker]
  exact (φ.baseChangeToPi_eq_zero_iff f).symm

/-- Vanishing after scalar extension, in the orientation useful for rewriting a
zero-map condition into equations defining a closed subscheme. -/
lemma baseChangeToPi_eq_zero_iff_map_coefficientIdeal_eq_bot
    {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f = 0) ↔ Ideal.map f φ.coefficientIdeal = ⊥ :=
  (φ.map_coefficientIdeal_eq_bot_iff f).symm

/-- Ring-level quotient universal property, phrased in terms of vanishing of the
scalar-extended map. -/
lemma baseChangeToPi_eq_zero_iff_exists_quotientLift {A : Type w} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f = 0) ↔
      ∃ q : (R ⧸ φ.coefficientIdeal) →+* A,
        q.comp (Ideal.Quotient.mk φ.coefficientIdeal) = f := by
  rw [φ.baseChangeToPi_eq_zero_iff f]
  constructor
  · intro h
    refine ⟨Ideal.Quotient.lift φ.coefficientIdeal f ?_, ?_⟩
    · intro x hx
      exact RingHom.mem_ker.mp (h hx)
    · rfl
  · rintro ⟨q, hq⟩ x hx
    rw [RingHom.mem_ker]
    rw [← DFunLike.congr_fun hq x]
    simp [Ideal.Quotient.eq_zero_iff_mem.mpr hx]

end Ring

section AffineScheme

variable {R : Type u} [CommRing R]
variable {M : Type u} [AddCommGroup M] [Module R M]
variable {r : ℕ}

/-- The affine zero locus cut out by the coordinates of `φ`. -/
noncomputable abbrev zeroLocus (φ : M →ₗ[R] (Fin r → R)) : Scheme :=
  Spec (.of (R ⧸ φ.coefficientIdeal))

/-- The canonical inclusion of the affine zero locus into `Spec R`. -/
noncomputable def zeroLocusι (φ : M →ₗ[R] (Fin r → R)) :
  φ.zeroLocus ⟶ Spec (.of R) :=
  Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk φ.coefficientIdeal))

instance (φ : M →ₗ[R] (Fin r → R)) : IsClosedImmersion φ.zeroLocusι :=
  by
    change IsClosedImmersion
      (Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk φ.coefficientIdeal)))
    exact AlgebraicGeometry.IsClosedImmersion.spec_of_quotient_mk
      (R := CommRingCat.of R) φ.coefficientIdeal

/-- The canonical lift of `Spec A → Spec R` to the zero locus when the scalar
extension of `φ` is zero. -/
noncomputable def zeroLocusLift {A : Type u} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A)
    (h : letI : Algebra R A := f.toAlgebra; φ.baseChangeToPi f = 0) :
    Spec (.of A) ⟶ φ.zeroLocus :=
  Spec.map (CommRingCat.ofHom (Ideal.Quotient.lift φ.coefficientIdeal f
    (fun _x hx ↦ RingHom.mem_ker.mp ((φ.baseChangeToPi_eq_zero_iff f).mp h hx))))

/-- The canonical zero-locus lift factors the original affine morphism. -/
lemma zeroLocusLift_comp_zeroLocusι {A : Type u} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A)
    (h : letI : Algebra R A := f.toAlgebra; φ.baseChangeToPi f = 0) :
    φ.zeroLocusLift f h ≫ φ.zeroLocusι =
      Spec.map (CommRingCat.ofHom f) := by
  change
    Spec.map (CommRingCat.ofHom (Ideal.Quotient.lift φ.coefficientIdeal f _)) ≫
        Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk φ.coefficientIdeal)) =
      Spec.map (CommRingCat.ofHom f)
  rw [← Spec.map_comp]
  rw [Spec.map_inj]
  apply CommRingCat.hom_ext
  rfl

/-- Universal factorization property of the affine zero locus: a morphism `Spec A →
Spec R` factors through it exactly when the scalar extension of `φ` is zero. -/
lemma baseChangeToPi_eq_zero_iff_exists_zeroLocusLift {A : Type u} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f = 0) ↔
      ∃ g : Spec (.of A) ⟶ φ.zeroLocus,
        g ≫ φ.zeroLocusι = Spec.map (CommRingCat.ofHom f) := by
  constructor
  · intro h
    exact ⟨φ.zeroLocusLift f h, φ.zeroLocusLift_comp_zeroLocusι f h⟩
  · rintro ⟨g, hg⟩
    apply (φ.baseChangeToPi_eq_zero_iff_exists_quotientLift f).mpr
    refine ⟨(Spec.preimage g).hom, ?_⟩
    have hcat :
        CommRingCat.ofHom (Ideal.Quotient.mk φ.coefficientIdeal) ≫
            Spec.preimage g = CommRingCat.ofHom f := by
      apply Spec.map_injective
      rw [Spec.map_comp, Spec.map_preimage]
      exact hg
    exact congrArg CommRingCat.Hom.hom hcat

/-- The zero-locus factorization, when it exists, is unique. -/
lemma baseChangeToPi_eq_zero_iff_unique_zeroLocusLift {A : Type u} [CommRing A]
    (φ : M →ₗ[R] (Fin r → R)) (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      φ.baseChangeToPi f = 0) ↔
      ∃! g : Spec (.of A) ⟶ φ.zeroLocus,
        g ≫ φ.zeroLocusι = Spec.map (CommRingCat.ofHom f) := by
  constructor
  · intro h
    refine ⟨φ.zeroLocusLift f h, φ.zeroLocusLift_comp_zeroLocusι f h, ?_⟩
    intro g hg
    apply (cancel_mono φ.zeroLocusι).mp
    rw [hg, φ.zeroLocusLift_comp_zeroLocusι]
  · rintro ⟨g, hg, -⟩
    exact (φ.baseChangeToPi_eq_zero_iff_exists_zeroLocusLift f).mpr ⟨g, hg⟩

end AffineScheme

end LinearMap
