module

public import Mathlib.RingTheory.LocalRing.Module
public import Mathlib.Algebra.Module.FinitePresentation
public import Mathlib.RingTheory.Finiteness.Cardinality
public import Mathlib.LinearAlgebra.Dimension.StrongRankCondition

/-!
# Selecting a spanning subfamily of basis size over a local ring

Supporting API with no Stacks Project counterpart.

Over a local ring, a finitely presented flat module is free; from any finite spanning
family one can therefore select a subfamily, indexed by a subset of cardinality the
rank, which is a basis — in particular it still spans. This is the Nakayama-type
selection step in the proof that the coordinate charts cover the Grassmannian
(§2.2, `lem:grassmannian-open-subfunctor`): a rank-`q` quotient of `O^n` is locally
generated by some `q` of the `n` standard generators.

Mathlib has the basis-extraction (`Module.exists_basis_of_span_of_flat`) but not this
`Finset`-indexed packaging, which is what the chart covering argument consumes.

Main declarations:
- `IsLocalRing.exists_finset_span_image_eq_top_of_span_eq_top`.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

universe u v

namespace IsLocalRing

/-- Over a local ring, from any finite spanning family of a finitely presented flat
(hence free) module one can select a subfamily indexed by a subset of cardinality
`finrank` which still spans. -/
theorem exists_finset_span_image_eq_top_of_span_eq_top
    {R : Type u} [CommRing R] [IsLocalRing R] {M : Type v} [AddCommGroup M] [Module R M]
    [Module.FinitePresentation R M] [Module.Flat R M]
    {n : ℕ} (v : Fin n → M) (hv : Submodule.span R (Set.range v) = ⊤) :
    ∃ I : Finset (Fin n), Submodule.span R (v '' ↑I) = ⊤ ∧
      I.card = Module.finrank R M := by
  classical
  obtain ⟨κ, a, b, hb⟩ := Module.exists_basis_of_span_of_flat v hv
  have : Finite κ := Module.Finite.finite_basis b
  cases nonempty_fintype κ
  have hainj : Function.Injective a := fun i j hij ↦
    b.injective (by rw [hb, hb, hij])
  refine ⟨Finset.image a Finset.univ, ?_, ?_⟩
  · apply top_unique
    rw [← b.span_eq]
    refine Submodule.span_le.mpr ?_
    rintro _ ⟨i, rfl⟩
    exact Submodule.subset_span ⟨a i, by simp, (hb i).symm⟩
  · rw [Finset.card_image_of_injective _ hainj, Finset.card_univ]
    exact (Module.finrank_eq_card_basis b).symm

end IsLocalRing
