module

public import StacksAndModuli.API.LocalNoetherianCoefficientSystem
public import StacksProject.Algebra.ColimitsAndMapsOfFinitePresentationII.«lemma-flat-finite-presentation-limit-flat»

/-!
# Local Noetherian models of polynomial-module presentations

Let `R` be a local ring and let `M` be a finitely presented module over a polynomial ring
`R[x_i]`.  A finite presentation of `M` involves finitely many coefficients.  Localizing the
finitely generated `ℤ`-subalgebra generated by those coefficients at the inverse image of the
maximal ideal of `R` gives a local Noetherian coefficient ring.  Mapping the presentation
matrix to this localization gives a finitely presented model whose scalar extension back to
`R[x_i]` is `M`.

This is the simultaneous coefficient-and-module descent layer of the approximation in Stacks
Project tag 00QX for polynomial algebras.  It does not assert that the descended module is
flat; making a sufficiently late model flat is the remaining content of tags 00R6 and 02JO.
-/

@[expose] public section

open TensorProduct

universe u v w

namespace Module.FinitePresentation.PolynomialModel

variable {R : Type u} [CommRing R] [IsLocalRing R]
variable {σ : Type v}
variable {M : Type w} [AddCommGroup M] [Module (MvPolynomial σ R) M]

/-- The local-Noetherian-system index containing the coefficients of a polynomial
presentation. -/
noncomputable def localIndex (D : PolynomialModel R σ M) :
    LocalNoetherianApproximation.Index R :=
  ⟨D.coefficientRing (R := ℤ), D.coefficientRing_fg (R := ℤ)⟩

/-- The local Noetherian coefficient ring attached to the presentation. -/
noncomputable abbrev localCoefficient (D : PolynomialModel R σ M) : Type u :=
  LocalNoetherianApproximation.coefficient R D.localIndex

/-- The map from the coefficient subalgebra of the presentation to its local Noetherian
localization. -/
noncomputable def localBaseMap (D : PolynomialModel R σ M) :
    D.coefficientRing (R := ℤ) →+* D.localCoefficient :=
  LocalNoetherianApproximation.ofBase R D.localIndex

/-- The relation matrix after passing to the local Noetherian coefficient ring. -/
noncomputable def localRelation (D : PolynomialModel R σ M) :
    Matrix (Fin D.generators) (Fin D.relations)
      (MvPolynomial σ D.localCoefficient) :=
  (D.modelRelation (R := ℤ)).map
    (MvPolynomial.map D.localBaseMap)

/-- The module presented by the localized relation matrix. -/
noncomputable abbrev localModelModule (D : PolynomialModel R σ M) :=
  polynomialMatrixCokernel D.localRelation

/-- The local Noetherian model remains finitely presented over its polynomial ring. -/
theorem localModelModule_finitePresentation (D : PolynomialModel R σ M) :
    Module.FinitePresentation (MvPolynomial σ D.localCoefficient) D.localModelModule :=
  finitePresentation_polynomialMatrixCokernel D.localRelation

/-- The embedding of the local coefficient stage into the original local ring. -/
@[instance_reducible]
noncomputable def localCoefficientAlgebra (D : PolynomialModel R σ M) :
    Algebra D.localCoefficient R :=
  (LocalNoetherianApproximation.toLimit R D.localIndex).toAlgebra

/-- Mapping the localized relation matrix to `R` recovers the original relation matrix. -/
theorem localRelation_map (D : PolynomialModel R σ M) :
    D.localRelation.map
      (MvPolynomial.map (LocalNoetherianApproximation.toLimit R D.localIndex)) =
        LinearMap.toMatrix' D.relation := by
  ext i j
  have hD := congrFun (congrFun (D.modelRelation_map (R := ℤ)) i) j
  rw [Matrix.map_apply] at hD
  rw [localRelation, Matrix.map_apply, Matrix.map_apply,
    MvPolynomial.map_map]
  rw [← hD]
  have hmaps : (LocalNoetherianApproximation.toLimit R D.localIndex).comp
      D.localBaseMap = algebraMap (D.coefficientRing (R := ℤ)) R := by
    apply RingHom.ext
    intro x
    change LocalNoetherianApproximation.toLimit R D.localIndex
      (LocalNoetherianApproximation.ofBase R D.localIndex x) = (x : R)
    exact LocalNoetherianApproximation.toLimit_ofBase R D.localIndex x
  rw [hmaps]

/-- Extending the local Noetherian polynomial-module model back to `R` recovers the original
finitely presented module. -/
noncomputable def localBaseChangeEquiv (D : PolynomialModel R σ M) :
    letI : Algebra D.localCoefficient R := D.localCoefficientAlgebra
    letI : Algebra (MvPolynomial σ D.localCoefficient) (MvPolynomial σ R) :=
      MvPolynomial.algebraMvPolynomial
    (MvPolynomial σ R) ⊗[MvPolynomial σ D.localCoefficient]
      D.localModelModule ≃ₗ[MvPolynomial σ R] M := by
  letI : Algebra D.localCoefficient R := D.localCoefficientAlgebra
  letI : Algebra (MvPolynomial σ D.localCoefficient) (MvPolynomial σ R) :=
    MvPolynomial.algebraMvPolynomial
  apply polynomialPresentationBaseChangeEquivOfMap
    D.quotient D.relation D.localRelation
  · change D.localRelation.map
      (MvPolynomial.map (LocalNoetherianApproximation.toLimit R D.localIndex)) =
        LinearMap.toMatrix' D.relation
    exact D.localRelation_map
  · exact D.quotient_surjective
  · exact D.exact

end Module.FinitePresentation.PolynomialModel
