module

public import StacksAndModuli.API.LinearMapFiniteFreeZeroLocus
public import Mathlib.RingTheory.FiniteType
public import Mathlib.Algebra.Module.FinitePresentation
public import Mathlib.RingTheory.Flat.LocallyFree
public import Mathlib.LinearAlgebra.TensorProduct.RightExactness
public import Mathlib.RingTheory.TensorProduct.Basic
public import Mathlib.RingTheory.Ideal.Maps

/-!
# When does a base change of a module become free of a fixed rank?

Let `M` be an `R`-module presented by a surjection `p : Rʳ ↠ M`.  This file proves that for
an `R`-algebra `B`, the canonical map `Bʳ → B ⊗ M` is an isomorphism exactly when the
*relation ideal* of `p`, generated by all coordinates of all elements of `ker p`, dies in
`B`; and that this happens exactly when `B ⊗ M` is free of rank `r`.

This is the module-theoretic core of the flattening stratification (Stacks 05P8/05P9): the
locus in `Spec R` where a finite module becomes free of rank `r` is cut out, inside the open
locus where it is generated by `r` elements, by a single explicit ideal, and the cut is
compatible with arbitrary base change.  In the language of Fitting ideals the relation ideal
is `Fit_{r-1}(M)` computed from `p`; nothing here needs Fitting's
independence-of-presentation theorem, because the universal property below characterizes the
ideal's vanishing locus directly.

Main declarations:

* `Module.relationIdeal` — the ideal generated by the coordinates of the relations of `p`,
  i.e. the coefficient ideal of the inclusion of relations `ker p ↪ Rʳ`;
* `Module.relationIdeal_le_ker_iff_bijective_baseChangeMap` — the universal property;
* `Module.free_baseChange_iff_relationIdeal_le_ker` — the free-of-rank-`r` criterion;
* `Module.relationIdeal_eq_of_surjective` — independence of the presentation;
* `Module.relationIdeal_baseChangeMap` — compatibility with base change;
* `Module.relationIdeal_le_ker_iff_flat_and_rankAtStalk` — free of rank `r` is the same as
  flat of constant stalk rank `r`, for a globally `r`-generated module;
* `Module.freeRankLocus` and `Module.free_baseChange_iff_exists_freeRankLocusLift` — the
  closed subscheme of `Spec R` representing the free-of-rank-`r` condition on affine test
  objects;
* `Module.flat_and_rankAtStalk_iff_unique_freeRankLocusLift` — the flattening stratification
  for one rank over an affine base.
-/

@[expose] public section

noncomputable section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

open TensorProduct

universe u v

namespace Module

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M] {r : ℕ}

/-- The **relation ideal** of a presentation `p : Rʳ → M`: the ideal generated by every
coordinate of every relation, i.e. by `x i` for `x ∈ ker p` and `i : Fin r`.

Computed from a presentation matrix this is the ideal of `1 × 1` minors of the relation
matrix, i.e. the Fitting ideal `Fit_{r-1}(M)`. -/
def relationIdeal (p : (Fin r → R) →ₗ[R] M) : Ideal R :=
  ((LinearMap.ker p).subtype).coefficientIdeal

theorem coord_mem_relationIdeal {p : (Fin r → R) →ₗ[R] M} {x : Fin r → R}
    (hx : p x = 0) (i : Fin r) : x i ∈ relationIdeal p :=
  ((LinearMap.ker p).subtype).apply_mem_coefficientIdeal ⟨x, hx⟩ i

theorem relationIdeal_le_iff {p : (Fin r → R) →ₗ[R] M} {I : Ideal R} :
    relationIdeal p ≤ I ↔ ∀ x : Fin r → R, p x = 0 → ∀ i, x i ∈ I := by
  rw [relationIdeal, LinearMap.coefficientIdeal_le_iff]
  exact ⟨fun h x hx i ↦ h ⟨x, hx⟩ i, fun h x i ↦ h (x : Fin r → R) x.2 i⟩

/-- The relation ideal of a presentation of a finitely presented module is finitely
generated: it is the coefficient ideal of the inclusion of the finitely generated
submodule of relations. -/
theorem relationIdeal_fg [Module.FinitePresentation R M]
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    (relationIdeal p).FG := by
  haveI : Module.Finite R (LinearMap.ker p) :=
    Module.Finite.iff_fg.mpr (Module.FinitePresentation.fg_ker p hp)
  exact ((LinearMap.ker p).subtype).coefficientIdeal_fg

/-- Every vector in `Rʳ` is the sum of its coordinate multiples of the standard basis. -/
theorem eq_sum_smul_single (x : Fin r → R) :
    x = ∑ i : Fin r, x i • Pi.single (M := fun _ : Fin r ↦ R) i 1 := by
  classical
  funext j
  simp [Finset.sum_apply, Pi.single_apply]

section BaseChange

variable (B : Type u) [CommRing B] [Algebra R B]

/-- The canonical `B`-linear map `Bʳ → B ⊗ M` attached to a presentation `p : Rʳ → M`:
the base change of `p` read through the standard identification `B ⊗ Rʳ ≅ Bʳ`. -/
def baseChangeMap (p : (Fin r → R) →ₗ[R] M) : (Fin r → B) →ₗ[B] B ⊗[R] M :=
  (LinearMap.baseChange B p).comp
    (TensorProduct.piScalarRight R B B (Fin r)).symm.toLinearMap

@[simp]
theorem baseChangeMap_single (p : (Fin r → R) →ₗ[R] M) (i : Fin r) (b : B) :
    baseChangeMap B p (Pi.single i b) = b ⊗ₜ[R] p (Pi.single i 1) := by
  simp [baseChangeMap]

/-- The canonical map `Bʳ → B ⊗ M` is surjective as soon as `p` is. -/
theorem surjective_baseChangeMap {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    Function.Surjective (baseChangeMap B p) := by
  have h₁ : Function.Surjective (LinearMap.baseChange B p) :=
    LinearMap.baseChange_surjective B hp
  exact h₁.comp (TensorProduct.piScalarRight R B B (Fin r)).symm.surjective

/-- Applying the canonical map to the image in `B` of a vector over `R`. -/
theorem baseChangeMap_algebraMap (p : (Fin r → R) →ₗ[R] M) (x : Fin r → R) :
    baseChangeMap B p (fun i ↦ algebraMap R B (x i)) = 1 ⊗ₜ[R] p x := by
  classical
  have hx : (fun i ↦ algebraMap R B (x i)) =
      ∑ i : Fin r, Pi.single i (algebraMap R B (x i)) := by
    funext j
    simp [Finset.sum_apply, Pi.single_apply]
  rw [hx, map_sum]
  conv_rhs => rw [eq_sum_smul_single x]
  rw [map_sum, tmul_sum]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [baseChangeMap_single, map_smul, tmul_smul, smul_tmul']
  congr 1
  simp [Algebra.smul_def]

/-- A tensor `b ⊗ x` with `x` a relation of `p` vanishes in `B ⊗ Rʳ` as soon as every
coordinate of `x` dies in `B`. -/
theorem tmul_eq_zero_of_coords_eq_zero (b : B) (x : Fin r → R)
    (hx : ∀ i, algebraMap R B (x i) = 0) :
    b ⊗ₜ[R] x = (0 : B ⊗[R] (Fin r → R)) := by
  classical
  conv_lhs => rw [eq_sum_smul_single x]
  rw [tmul_sum]
  refine Finset.sum_eq_zero fun i _ ↦ ?_
  rw [tmul_smul, smul_tmul']
  have : x i • b = 0 := by rw [Algebra.smul_def, hx i, zero_mul]
  rw [this, zero_tmul]

/-- **The universal property of the relation ideal.**  For an `R`-algebra `B` and a
surjective presentation `p : Rʳ ↠ M`, the canonical map `Bʳ → B ⊗ M` is bijective exactly
when every relation of `p` dies in `B`.

The backward direction uses only right exactness of the tensor product; the forward
direction uses that a surjective endomorphism of a finite module over a commutative ring is
injective (`OrzechProperty`). -/
theorem relationIdeal_le_ker_iff_bijective_baseChangeMap
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    relationIdeal p ≤ RingHom.ker (algebraMap R B) ↔
      Function.Bijective (baseChangeMap B p) := by
  constructor
  · intro hI
    refine ⟨?_, surjective_baseChangeMap B hp⟩
    have hexact : Function.Exact (LinearMap.ker p).subtype p :=
      LinearMap.exact_subtype_ker_map p
    have hbc : Function.Exact
        (LinearMap.lTensor B (LinearMap.ker p).subtype) (LinearMap.lTensor B p) :=
      lTensor_exact B hexact hp
    have hzero : ∀ y : B ⊗[R] (LinearMap.ker p),
        LinearMap.lTensor B (LinearMap.ker p).subtype y = 0 := by
      intro y
      induction y using TensorProduct.induction_on with
      | zero => simp
      | tmul b z =>
          rw [LinearMap.lTensor_tmul]
          refine tmul_eq_zero_of_coords_eq_zero B b _ fun i ↦ ?_
          exact hI (coord_mem_relationIdeal z.2 i)
      | add y₁ y₂ h₁ h₂ => rw [map_add, h₁, h₂, add_zero]
    have hinjl : Function.Injective (LinearMap.lTensor B p) := by
      rw [← LinearMap.ker_eq_bot, eq_bot_iff]
      intro y hy
      obtain ⟨w, hw⟩ := (hbc y).mp (LinearMap.mem_ker.mp hy)
      rw [← hw]
      simpa using hzero w
    have happ : ∀ z : B ⊗[R] (Fin r → R),
        LinearMap.baseChange B p z = LinearMap.lTensor B p z :=
      fun z ↦ congrFun (LinearMap.baseChange_eq_ltensor (A := B) p) z
    have hinj : Function.Injective (LinearMap.baseChange B p) := by
      intro u v huv
      exact hinjl (by rw [← happ u, ← happ v, huv])
    exact hinj.comp (TensorProduct.piScalarRight R B B (Fin r)).symm.injective
  · intro hbij
    rw [relationIdeal_le_iff]
    intro x hx i
    have h0 : baseChangeMap B p (fun j ↦ algebraMap R B (x j)) = 0 := by
      rw [baseChangeMap_algebraMap, hx, tmul_zero]
    have h1 : (fun j ↦ algebraMap R B (x j)) = (0 : Fin r → B) :=
      hbij.1 (by rw [h0, map_zero])
    have hi := congrFun h1 i
    simpa [RingHom.mem_ker] using hi

/-- **The free-of-rank-`r` criterion.**  For a surjective presentation `p : Rʳ ↠ M` and an
`R`-algebra `B`, the base change `B ⊗ M` is free of rank `r` over `B` exactly when every
relation of `p` dies in `B`.

The hard direction is that a surjection `Bʳ ↠ B ⊗ M` onto a free module of rank `r` must be
injective, which is `OrzechProperty.injective_of_surjective_endomorphism`. -/
theorem free_baseChange_iff_relationIdeal_le_ker
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    Nonempty ((B ⊗[R] M) ≃ₗ[B] (Fin r → B)) ↔
      relationIdeal p ≤ RingHom.ker (algebraMap R B) := by
  constructor
  · rintro ⟨e⟩
    rw [relationIdeal_le_ker_iff_bijective_baseChangeMap B hp]
    refine ⟨?_, surjective_baseChangeMap B hp⟩
    have hsurj : Function.Surjective
        ((e.toLinearMap).comp (baseChangeMap B p)) :=
      e.surjective.comp (surjective_baseChangeMap B hp)
    have hinj : Function.Injective ((e.toLinearMap).comp (baseChangeMap B p)) :=
      OrzechProperty.injective_of_surjective_endomorphism _ hsurj
    intro x y hxy
    exact hinj (by simpa using congrArg e.toLinearMap hxy)
  · intro hI
    exact ⟨(LinearEquiv.ofBijective (baseChangeMap B p)
      ((relationIdeal_le_ker_iff_bijective_baseChangeMap B hp).mp hI)).symm⟩

/-- The base change of `M` to `R ⧸ relationIdeal p` is free of rank `r`: the relation ideal
is the *universal* ideal making the base change free of rank `r`. -/
theorem free_baseChange_quotient_relationIdeal
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    Nonempty ((R ⧸ relationIdeal p) ⊗[R] M ≃ₗ[R ⧸ relationIdeal p]
      (Fin r → R ⧸ relationIdeal p)) := by
  refine (free_baseChange_iff_relationIdeal_le_ker (R ⧸ relationIdeal p) hp).mpr ?_
  rw [Ideal.Quotient.algebraMap_eq, Ideal.mk_ker]

/-- **Fitting's independence-of-presentation theorem, for the top relation ideal.**  Any two
surjections `Rʳ ↠ M` have the same relation ideal.

The proof does not analyse presentation matrices: both ideals are characterized by the same
universal property, so testing each against the quotient by the other gives the two
inclusions. -/
theorem relationIdeal_eq_of_surjective {p q : (Fin r → R) →ₗ[R] M}
    (hp : Function.Surjective p) (hq : Function.Surjective q) :
    relationIdeal p = relationIdeal q := by
  have key : ∀ {p' q' : (Fin r → R) →ₗ[R] M}, Function.Surjective p' →
      Function.Surjective q' → relationIdeal p' ≤ relationIdeal q' := by
    intro p' q' hp' hq'
    have hfree := free_baseChange_quotient_relationIdeal hq'
    have := (free_baseChange_iff_relationIdeal_le_ker
      (R ⧸ relationIdeal q') hp').mp hfree
    rwa [Ideal.Quotient.algebraMap_eq, Ideal.mk_ker] at this
  exact le_antisymm (key hp hq) (key hq hp)

end BaseChange

section Transitivity

variable (A : Type u) [CommRing A] [Algebra R A]

/-- Base change of the relation ideal.  The relation ideal of the base-changed
presentation `Aʳ ↠ A ⊗ M` is the extension of the relation ideal of `p`.

Like `relationIdeal_eq_of_surjective`, this is read off the universal property rather than
from presentation matrices: an `A`-algebra kills one ideal exactly when it kills the
other, because both conditions say that the further base change of `M` is free of rank
`r`. -/
theorem relationIdeal_baseChangeMap
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    relationIdeal (baseChangeMap A p) = (relationIdeal p).map (algebraMap R A) := by
  have hpA : Function.Surjective (baseChangeMap A p) := surjective_baseChangeMap A hp
  -- Over any `A`-algebra `B`, the two base changes of `M` agree.
  have hiff : ∀ (B : Type u) [CommRing B] [Algebra A B] [Algebra R B],
      IsScalarTower R A B →
      (Nonempty ((B ⊗[A] (A ⊗[R] M)) ≃ₗ[B] (Fin r → B)) ↔
        Nonempty ((B ⊗[R] M) ≃ₗ[B] (Fin r → B))) := by
    intro B _ _ _ _
    exact ⟨fun ⟨e⟩ ↦ ⟨(TensorProduct.AlgebraTensorModule.cancelBaseChange
        R A B B M).symm ≪≫ₗ e⟩,
      fun ⟨e⟩ ↦ ⟨(TensorProduct.AlgebraTensorModule.cancelBaseChange
        R A B B M) ≪≫ₗ e⟩⟩
  refine le_antisymm ?_ ?_
  · -- Test against `A ⧸ (relationIdeal p).map`.
    set J : Ideal A := (relationIdeal p).map (algebraMap R A) with hJ
    have hRle : relationIdeal p ≤ RingHom.ker (algebraMap R (A ⧸ J)) := by
      intro c hc
      have : algebraMap R A c ∈ J := Ideal.mem_map_of_mem _ hc
      have halg : algebraMap R (A ⧸ J) c =
          Ideal.Quotient.mk J (algebraMap R A c) := rfl
      rw [RingHom.mem_ker, halg]
      exact (Ideal.Quotient.eq_zero_iff_mem).mpr this
    have hfree := (free_baseChange_iff_relationIdeal_le_ker (A ⧸ J) hp).mpr hRle
    have hfree' := ((hiff (A ⧸ J) inferInstance).mpr hfree)
    have := (free_baseChange_iff_relationIdeal_le_ker (A ⧸ J) hpA).mp hfree'
    rwa [Ideal.Quotient.algebraMap_eq, Ideal.mk_ker] at this
  · -- Test against `A ⧸ relationIdeal (baseChangeMap A p)`.
    set I : Ideal A := relationIdeal (baseChangeMap A p) with hI
    have hAle : I ≤ RingHom.ker (algebraMap A (A ⧸ I)) := by
      rw [Ideal.Quotient.algebraMap_eq, Ideal.mk_ker]
    have hfree := (free_baseChange_iff_relationIdeal_le_ker (A ⧸ I) hpA).mpr hAle
    have hfree' := ((hiff (A ⧸ I) inferInstance).mp hfree)
    have hRle := (free_baseChange_iff_relationIdeal_le_ker (A ⧸ I) hp).mp hfree'
    rw [Ideal.map_le_iff_le_comap]
    intro c hc
    have := hRle hc
    rw [RingHom.mem_ker] at this
    have halg : algebraMap R (A ⧸ I) c =
        Ideal.Quotient.mk I (algebraMap R A c) := rfl
    rw [halg] at this
    exact Ideal.mem_comap.mpr (Ideal.Quotient.eq_zero_iff_mem.mp this)

end Transitivity

section Flatness

variable (B : Type u) [CommRing B] [Algebra R B]

/-- A module generated by `r` elements which is flat of constant stalk rank `r` is free:
the canonical surjection `Bʳ ↠ B ⊗ M` is then bijective.

This is the input that turns the closed subscheme `freeRankLocus p` into the *flattening*
stratum: over it the base change is not merely free but flat of the right rank, and
conversely. -/
theorem bijective_baseChangeMap_of_flat_of_rankAtStalk
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p)
    [Module.Flat B (B ⊗[R] M)]
    (hrank : ∀ q : PrimeSpectrum B, Module.rankAtStalk (B ⊗[R] M) q = r) :
    Function.Bijective (baseChangeMap B p) := by
  rcases subsingleton_or_nontrivial B with _ | _
  · exact ⟨fun _ _ _ ↦ Subsingleton.elim _ _, surjective_baseChangeMap B hp⟩
  haveI : Module.Finite B (B ⊗[R] M) :=
    Module.Finite.of_surjective (baseChangeMap B p) (surjective_baseChangeMap B hp)
  refine Module.bijective_of_surjective_of_rankAtStalk_eq
    (surjective_baseChangeMap B hp) fun m _ ↦ ?_
  rw [hrank ⟨m, inferInstance⟩, Module.rankAtStalk_eq_finrank_of_free,
    Module.finrank_fin_fun]
  rfl

/-- **The flattening stratum.**  For a surjection `p : Rʳ ↠ M` and an `R`-algebra `B`, the
base change `B ⊗ M` is flat over `B` of constant stalk rank `r` exactly when `B` kills the
relation ideal — equivalently, exactly when `Spec B → Spec R` factors through the closed
subscheme `freeRankLocus p`.

This is Stacks 05P9 for the single rank `r`, in the case of a globally `r`-generated
module, where the stratum is closed rather than merely locally closed. -/
theorem relationIdeal_le_ker_iff_flat_and_rankAtStalk
    {p : (Fin r → R) →ₗ[R] M} (hp : Function.Surjective p) :
    relationIdeal p ≤ RingHom.ker (algebraMap R B) ↔
      (Module.Flat B (B ⊗[R] M) ∧
        ∀ q : PrimeSpectrum B, Module.rankAtStalk (B ⊗[R] M) q = r) := by
  constructor
  · intro hI
    obtain ⟨e⟩ := (free_baseChange_iff_relationIdeal_le_ker B hp).mpr hI
    haveI : Module.Free B (B ⊗[R] M) := Module.Free.of_equiv e.symm
    refine ⟨inferInstance, fun q ↦ ?_⟩
    haveI : Nontrivial B := by
      refine not_subsingleton_iff_nontrivial.mp fun hs ↦ q.isPrime.ne_top ?_
      exact (Ideal.eq_top_iff_one _).mpr
        (by rw [Subsingleton.elim (1 : B) 0]; exact q.asIdeal.zero_mem)
    rw [Module.rankAtStalk_eq_of_equiv e, Module.rankAtStalk_eq_finrank_of_free,
      Module.finrank_fin_fun]
    rfl
  · rintro ⟨hflat, hrank⟩
    exact (relationIdeal_le_ker_iff_bijective_baseChangeMap B hp).mpr
      (bijective_baseChangeMap_of_flat_of_rankAtStalk B hp hrank)

end Flatness

section Scheme

open CategoryTheory AlgebraicGeometry

variable {p : (Fin r → R) →ₗ[R] M}

/-- The **free-rank-`r` locus** of a presentation `p : Rʳ ↠ M`: the closed subscheme of
`Spec R` cut out by the relation ideal.

A morphism from an affine scheme factors through it exactly when the corresponding base
change of `M` is free of rank `r`; see
`Module.free_baseChange_iff_exists_freeRankLocusLift`. -/
noncomputable abbrev freeRankLocus (p : (Fin r → R) →ₗ[R] M) : Scheme :=
  ((LinearMap.ker p).subtype).zeroLocus

/-- The closed immersion of the free-rank-`r` locus into `Spec R`. -/
noncomputable def freeRankLocusι (p : (Fin r → R) →ₗ[R] M) :
    freeRankLocus p ⟶ Spec (.of R) :=
  ((LinearMap.ker p).subtype).zeroLocusι

instance : IsClosedImmersion (freeRankLocusι p) :=
  inferInstanceAs (IsClosedImmersion ((LinearMap.ker p).subtype).zeroLocusι)

/-- The relation ideal is the coefficient ideal of the inclusion of relations, so it is
killed by `f` exactly when the corresponding base-changed coordinate map vanishes. -/
theorem relationIdeal_le_ker_iff_baseChangeToPi_eq_zero
    (A : Type u) [CommRing A] (f : R →+* A) :
    relationIdeal p ≤ RingHom.ker f ↔
      (letI : Algebra R A := f.toAlgebra;
        ((LinearMap.ker p).subtype).baseChangeToPi f = 0) :=
  (((LinearMap.ker p).subtype).baseChangeToPi_eq_zero_iff f).symm

/-- **The affine flattening stratum, universal property.**  For a surjective presentation
`p : Rʳ ↠ M` and a ring map `f : R → A`, the base change `A ⊗ M` is free of rank `r`
exactly when `Spec A → Spec R` factors through the closed subscheme `freeRankLocus p`.

This is the affine, fixed-rank half of the flattening stratification
(Stacks 05P8 (3), 05P9). -/
theorem free_baseChange_iff_exists_freeRankLocusLift
    (hp : Function.Surjective p) (A : Type u) [CommRing A] (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      Nonempty ((A ⊗[R] M) ≃ₗ[A] (Fin r → A))) ↔
      ∃ g : Spec (.of A) ⟶ freeRankLocus p,
        g ≫ freeRankLocusι p = Spec.map (CommRingCat.ofHom f) := by
  letI : Algebra R A := f.toAlgebra
  rw [free_baseChange_iff_relationIdeal_le_ker A hp,
    show RingHom.ker (algebraMap R A) = RingHom.ker f by
      rw [RingHom.algebraMap_toAlgebra],
    relationIdeal_le_ker_iff_baseChangeToPi_eq_zero A f]
  exact ((LinearMap.ker p).subtype).baseChangeToPi_eq_zero_iff_exists_zeroLocusLift f

/-- The factorization through the free-rank-`r` locus is unique when it exists: the locus
is a closed subscheme, so it *represents* the free-of-rank-`r` condition on affine test
objects. -/
theorem free_baseChange_iff_unique_freeRankLocusLift
    (hp : Function.Surjective p) (A : Type u) [CommRing A] (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      Nonempty ((A ⊗[R] M) ≃ₗ[A] (Fin r → A))) ↔
      ∃! g : Spec (.of A) ⟶ freeRankLocus p,
        g ≫ freeRankLocusι p = Spec.map (CommRingCat.ofHom f) := by
  letI : Algebra R A := f.toAlgebra
  rw [free_baseChange_iff_relationIdeal_le_ker A hp,
    show RingHom.ker (algebraMap R A) = RingHom.ker f by
      rw [RingHom.algebraMap_toAlgebra],
    relationIdeal_le_ker_iff_baseChangeToPi_eq_zero A f]
  exact ((LinearMap.ker p).subtype).baseChangeToPi_eq_zero_iff_unique_zeroLocusLift f

/-- **The flattening stratification, for one rank, over an affine base.**  For a surjection
`p : Rʳ ↠ M` and a ring map `f : R → A`, the base change `A ⊗ M` is flat over `A` with every
stalk rank equal to `r` exactly when `Spec A → Spec R` factors through the closed subscheme
`freeRankLocus p`; and the factorization is then unique.

This is Stacks 05P9 for a globally `r`-generated module: the stratum `S_r` is the closed
subscheme cut out by the relation ideal, because the open condition `Fit_r(M) = R` holds
identically. -/
theorem flat_and_rankAtStalk_iff_unique_freeRankLocusLift
    (hp : Function.Surjective p) (A : Type u) [CommRing A] (f : R →+* A) :
    (letI : Algebra R A := f.toAlgebra;
      Module.Flat A (A ⊗[R] M) ∧
        ∀ q : PrimeSpectrum A, Module.rankAtStalk (A ⊗[R] M) q = r) ↔
      ∃! g : Spec (.of A) ⟶ freeRankLocus p,
        g ≫ freeRankLocusι p = Spec.map (CommRingCat.ofHom f) := by
  letI : Algebra R A := f.toAlgebra
  rw [← relationIdeal_le_ker_iff_flat_and_rankAtStalk A hp,
    show RingHom.ker (algebraMap R A) = RingHom.ker f by
      rw [RingHom.algebraMap_toAlgebra],
    relationIdeal_le_ker_iff_baseChangeToPi_eq_zero A f]
  exact ((LinearMap.ker p).subtype).baseChangeToPi_eq_zero_iff_unique_zeroLocusLift f

end Scheme

end Module

end

end
