module

public import StacksAndModuli.API.NodeRingAxisSequence

/-!
# Branch quotients of the standard node ring

Restriction to either coordinate axis gives a surjective algebra map from
`k[[x,y]]/(xy)` to `k[[t]]`. Its kernel is the corresponding minimal prime, so quotienting
the node by either formal branch is canonically equivalent to the one-variable
power-series ring.

This is the local algebra needed to identify the completed stalk of one reduced component
through a split node. The remaining geometric step is to compare that component's
completed stalk with this quotient.

## Main results

* `AlgebraicGeometry.Scheme.nodeAxisRestriction_ker`: the kernel of restriction to one
  axis is the ideal generated by the transverse variable.
* `AlgebraicGeometry.Scheme.nodeRingFormalBranch`: the corresponding intrinsic minimal
  prime of the node ring.
* `AlgebraicGeometry.Scheme.nodeRingBranchQuotientAlgEquiv`: quotienting by that branch
  gives `k[[t]]`.
-/

@[expose] public section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

noncomputable section

open scoped MvPowerSeries PowerSeries

universe u

namespace AlgebraicGeometry.Scheme

/-- Restriction of multivariable power series to either node axis is surjective. -/
lemma nodeAxisRestriction_surjective (k : Type u) [CommRing k] (i : Fin 2) :
    Function.Surjective (nodeAxisRestriction k i) := by
  intro f
  exact ⟨MvPowerSeries.rename (nodeAxisEmbedding i) f,
    nodeAxisRestriction_rename_self k i f⟩

/-- The kernel of restriction to an axis is generated by the transverse variable. -/
lemma nodeAxisRestriction_ker (k : Type u) [Field k] (i : Fin 2) :
    RingHom.ker (nodeAxisRestriction k i) = nodeAxisIdeal k (1 - i) := by
  apply le_antisymm
  · intro f hf
    rw [RingHom.mem_ker] at hf
    rw [nodeAxisIdeal, Ideal.mem_span_singleton, MvPowerSeries.X_dvd_iff]
    intro m hm
    have hi : m = Finsupp.single i (m i) := by
      ext j
      fin_cases i <;> fin_cases j
      · simp
      · simpa using hm
      · simpa using hm
      · simp
    rw [hi]
    exact (nodeAxisRestriction_coeff k i f (m i)).symm.trans
      (congrArg (PowerSeries.coeff (m i)) hf)
  · rw [nodeAxisIdeal, Ideal.span_le]
    rintro _ rfl
    change nodeAxisRestriction k i (MvPowerSeries.X (1 - i)) = 0
    fin_cases i <;> simp [nodeAxisRestriction_X_of_ne]

/-- Restriction from the standard node ring to coordinate axis `i`. -/
def nodeRingAxisRestriction (k : Type u) [Field k] (i : Fin 2) :
    nodeRing k →ₐ[k] PowerSeries k :=
  Ideal.Quotient.liftₐ (nodeIdeal k) (nodeAxisRestriction k i)
    (fun f hf ↦ by
      apply RingHom.mem_ker.mp
      change f ∈ RingHom.ker (nodeAxisRestriction k i)
      rw [nodeAxisRestriction_ker k i]
      exact nodeIdeal_le_nodeAxisIdeal k (1 - i) hf)

/-- Axis restriction on a representative of the standard node quotient. -/
@[simp]
lemma nodeRingAxisRestriction_mk (k : Type u) [Field k] (i : Fin 2)
    (f : MvPowerSeries (Fin 2) k) :
    nodeRingAxisRestriction k i (Ideal.Quotient.mk (nodeIdeal k) f) =
      nodeAxisRestriction k i f := by
  exact Ideal.Quotient.lift_mk _ _ _

/-- Restriction from the node ring to either formal axis is surjective. -/
lemma nodeRingAxisRestriction_surjective (k : Type u) [Field k] (i : Fin 2) :
    Function.Surjective (nodeRingAxisRestriction k i) := by
  intro f
  obtain ⟨g, rfl⟩ := nodeAxisRestriction_surjective k i f
  exact ⟨Ideal.Quotient.mk (nodeIdeal k) g, by simp⟩

/-- The formal branch of the node ring whose quotient is coordinate axis `i`. -/
noncomputable def nodeRingFormalBranch (k : Type u) [Field k] (i : Fin 2) :
    nodeFormalBranches k :=
  (Ideal.minimalPrimesQuotientEquiv (nodeIdeal k)).symm
    ⟨nodeAxisIdeal k (1 - i), nodeAxisIdeal_mem_minimalPrimes k (1 - i)⟩

/-- The formal branch associated to an axis is the kernel of restriction to that axis. -/
lemma nodeRingFormalBranch_eq_ker (k : Type u) [Field k] (i : Fin 2) :
    (nodeRingFormalBranch k i : Ideal (nodeRing k)) =
      RingHom.ker (nodeRingAxisRestriction k i) := by
  apply Ideal.comap_injective_of_surjective
    (Ideal.Quotient.mk (nodeIdeal k)) Ideal.Quotient.mk_surjective
  have hbranch := congrArg Subtype.val
    ((Ideal.minimalPrimesQuotientEquiv (nodeIdeal k)).apply_symm_apply
      ⟨nodeAxisIdeal k (1 - i), nodeAxisIdeal_mem_minimalPrimes k (1 - i)⟩)
  rw [Ideal.minimalPrimesQuotientEquiv] at hbranch
  change (nodeRingFormalBranch k i : Ideal (nodeRing k)).comap
      (Ideal.Quotient.mk (nodeIdeal k)) = _ at hbranch
  rw [hbranch]
  ext f
  change f ∈ nodeAxisIdeal k (1 - i) ↔
    nodeRingAxisRestriction k i (Ideal.Quotient.mk (nodeIdeal k) f) = 0
  rw [nodeRingAxisRestriction_mk, ← RingHom.mem_ker,
    nodeAxisRestriction_ker]

/-- Quotienting the standard node by either formal branch gives `k[[t]]`. -/
noncomputable def nodeRingBranchQuotientAlgEquiv (k : Type u) [Field k]
    (i : Fin 2) :
    (nodeRing k ⧸ (nodeRingFormalBranch k i : Ideal (nodeRing k))) ≃ₐ[k]
      PowerSeries k :=
  (Ideal.quotientEquivAlgOfEq k
      (nodeRingFormalBranch_eq_ker k i)).trans
    (Ideal.quotientKerAlgEquivOfSurjective
      (nodeRingAxisRestriction_surjective k i))

end AlgebraicGeometry.Scheme

end
