module

public import StacksAndModuli.API.NodeRingBranchQuotient
public import StacksAndModuli.API.SplitNodeResidueField

/-!
# Intersection of the two formal branches of a split node

In the standard node ring `k[[x,y]]/(xy)`, the two formal-branch ideals together
generate the maximal ideal.  Equivalently, quotienting simultaneously by both
branches gives the residue field `k`.

This is the local algebra input for proving that two distinct reduced branches of a
nodal curve meet transversely.  Applying it to a scheme-theoretic intersection still
requires a geometric comparison identifying the completed pullback-stalk ideal with
the sum of the two transported branch ideals.

## Main results

* `AlgebraicGeometry.Scheme.nodeAxisIdeal_sup_eq_ker_constantCoeff`: the two
  coordinate-axis ideals generate the zero-constant-term ideal upstairs.
* `AlgebraicGeometry.Scheme.nodeRingFormalBranch_sup_eq_ker_constantCoeff`: the two
  formal branches generate the residue kernel in the node ring.
* `AlgebraicGeometry.Scheme.nodeRingFormalBranch_sup_eq_maximalIdeal`: the same sum is
  the maximal ideal.
* `AlgebraicGeometry.Scheme.nodeFormalBranches_sup_eq_maximalIdeal_of_ne`: any two
  distinct formal branches of the standard node generate its maximal ideal.
* `AlgebraicGeometry.Scheme.
  minimalPrimes_sup_eq_comap_nodeMaximalIdeal_of_ringEquiv`: the coordinate-free
  transport of this identity along a ring equivalence with the standard node.
* `AlgebraicGeometry.Scheme.nodeRingBranchIntersectionAlgEquiv`: the quotient by both
  branches is canonically the ground field.
-/

@[expose] public section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

noncomputable section

open scoped MvPowerSeries PowerSeries

universe u

namespace AlgebraicGeometry.Scheme

/-- The two coordinate-axis ideals in `k[[x,y]]` generate exactly the power series
with zero constant coefficient. -/
lemma nodeAxisIdeal_sup_eq_ker_constantCoeff
    (k : Type u) [Field k] :
    nodeAxisIdeal k 0 ⊔ nodeAxisIdeal k 1 =
      RingHom.ker (MvPowerSeries.constantCoeff (R := k) (σ := Fin 2)) := by
  apply le_antisymm
  · apply sup_le
    · intro f hf
      rw [RingHom.mem_ker]
      have hf' : nodeAxisRestriction k 1 f = 0 := by
        rw [← RingHom.mem_ker, nodeAxisRestriction_ker]
        simpa using hf
      have hc := congrArg PowerSeries.constantCoeff hf'
      simpa using (nodeAxisRestriction_constantCoeff k 1 f).symm.trans hc
    · intro f hf
      rw [RingHom.mem_ker]
      have hf' : nodeAxisRestriction k 0 f = 0 := by
        rw [← RingHom.mem_ker, nodeAxisRestriction_ker]
        simpa using hf
      have hc := congrArg PowerSeries.constantCoeff hf'
      simpa using (nodeAxisRestriction_constantCoeff k 0 f).symm.trans hc
  · intro f hf
    rw [RingHom.mem_ker] at hf
    let p : MvPowerSeries (Fin 2) k :=
      MvPowerSeries.rename (nodeAxisEmbedding 1) (nodeAxisRestriction k 1 f)
    have hp : p ∈ nodeAxisIdeal k 1 := by
      have hker : RingHom.ker (nodeAxisRestriction k 0) =
          nodeAxisIdeal k 1 := by
        simpa using nodeAxisRestriction_ker k (0 : Fin 2)
      rw [← hker, RingHom.mem_ker]
      change nodeAxisRestriction k 0 p = 0
      rw [show p = MvPowerSeries.rename (nodeAxisEmbedding 1)
        (nodeAxisRestriction k 1 f) from rfl,
        nodeAxisRestriction_rename_of_ne k (by decide : (0 : Fin 2) ≠ 1),
        nodeAxisRestriction_constantCoeff, hf, map_zero]
    have hrest : f - p ∈ nodeAxisIdeal k 0 := by
      have hker : RingHom.ker (nodeAxisRestriction k 1) =
          nodeAxisIdeal k 0 := by
        simpa using nodeAxisRestriction_ker k (1 : Fin 2)
      rw [← hker, RingHom.mem_ker]
      change nodeAxisRestriction k 1 (f - p) = 0
      rw [map_sub, show p = MvPowerSeries.rename (nodeAxisEmbedding 1)
        (nodeAxisRestriction k 1 f) from rfl,
        nodeAxisRestriction_rename_self, sub_self]
    exact Submodule.mem_sup.mpr
      ⟨f - p, hrest, p, hp, sub_add_cancel f p⟩

/-- The inverse image of formal branch `i` under the quotient map from
`k[[x,y]]` is the ideal generated by the transverse variable. -/
lemma nodeRingFormalBranch_comap_quotientMk
    (k : Type u) [Field k] (i : Fin 2) :
    (nodeRingFormalBranch k i : Ideal (nodeRing k)).comap
        (Ideal.Quotient.mk (nodeIdeal k)) = nodeAxisIdeal k (1 - i) := by
  rw [nodeRingFormalBranch_eq_ker]
  ext f
  change nodeRingAxisRestriction k i
    (Ideal.Quotient.mk (nodeIdeal k) f) = 0 ↔ _
  rw [nodeRingAxisRestriction_mk, ← RingHom.mem_ker,
    nodeAxisRestriction_ker]

/-- Under the standard enumeration of the node's formal branches, the branch whose
quotient is axis `i` has index `1 - i`. -/
lemma nodeFormalBranchesEquivFinTwo_nodeRingFormalBranch
    (k : Type u) [Field k] (i : Fin 2) :
    nodeFormalBranchesEquivFinTwo k (nodeRingFormalBranch k i) = 1 - i := by
  simp only [nodeFormalBranchesEquivFinTwo, nodeRingFormalBranch,
    Equiv.trans_apply, Equiv.apply_symm_apply]
  symm
  apply (finTwoEquivNodeIdealMinimalPrimes k).injective
  rw [Equiv.apply_symm_apply]
  apply Subtype.ext
  exact finTwoEquivNodeIdealMinimalPrimes_apply k (1 - i)

/-- The two formal branches in the standard node ring generate exactly the kernel
of the constant-coefficient map to the ground field. -/
lemma nodeRingFormalBranch_sup_eq_ker_constantCoeff
    (k : Type u) [Field k] :
    (nodeRingFormalBranch k 0 : Ideal (nodeRing k)) ⊔
        (nodeRingFormalBranch k 1 : Ideal (nodeRing k)) =
      RingHom.ker (nodeRingConstantCoeff k) := by
  let q : MvPowerSeries (Fin 2) k →+* nodeRing k :=
    Ideal.Quotient.mk (nodeIdeal k)
  apply le_antisymm
  · apply sup_le
    · intro z hz
      rw [RingHom.mem_ker]
      have hz' : nodeRingAxisRestriction k 0 z = 0 :=
        RingHom.mem_ker.mp ((nodeRingFormalBranch_eq_ker k 0) ▸ hz)
      have hc := congrArg PowerSeries.constantCoeff hz'
      have hsame : PowerSeries.constantCoeff
          (nodeRingAxisRestriction k 0 z) = nodeRingConstantCoeff k z := by
        obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective z
        simp [nodeRingConstantCoeff]
      simpa [hsame] using hc
    · intro z hz
      rw [RingHom.mem_ker]
      have hz' : nodeRingAxisRestriction k 1 z = 0 :=
        RingHom.mem_ker.mp ((nodeRingFormalBranch_eq_ker k 1) ▸ hz)
      have hc := congrArg PowerSeries.constantCoeff hz'
      have hsame : PowerSeries.constantCoeff
          (nodeRingAxisRestriction k 1 z) = nodeRingConstantCoeff k z := by
        obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective z
        simp [nodeRingConstantCoeff]
      simpa [hsame] using hc
  · intro z hz
    rw [RingHom.mem_ker] at hz
    obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective z
    have hf : MvPowerSeries.constantCoeff f = 0 := by
      simpa [nodeRingConstantCoeff] using hz
    have haxes : f ∈ nodeAxisIdeal k 0 ⊔ nodeAxisIdeal k 1 := by
      rw [nodeAxisIdeal_sup_eq_ker_constantCoeff, RingHom.mem_ker]
      exact hf
    have hcomaps : f ∈
        (nodeRingFormalBranch k 0 : Ideal (nodeRing k)).comap q ⊔
          (nodeRingFormalBranch k 1 : Ideal (nodeRing k)).comap q := by
      rw [nodeRingFormalBranch_comap_quotientMk,
        nodeRingFormalBranch_comap_quotientMk]
      simpa [q, sup_comm] using haxes
    have hmap := Ideal.mem_map_of_mem q hcomaps
    rw [Ideal.map_sup_comap_of_surjective q
      Ideal.Quotient.mk_surjective] at hmap
    exact hmap

/-- The two formal branches of the standard node generate its maximal ideal. -/
theorem nodeRingFormalBranch_sup_eq_maximalIdeal
    (k : Type u) [Field k] :
    (nodeRingFormalBranch k 0 : Ideal (nodeRing k)) ⊔
        (nodeRingFormalBranch k 1 : Ideal (nodeRing k)) =
      IsLocalRing.maximalIdeal (nodeRing k) := by
  rw [nodeRingFormalBranch_sup_eq_ker_constantCoeff]
  exact IsLocalRing.ker_eq_maximalIdeal (nodeRingConstantCoeff k)
    (nodeRingConstantCoeff_surjective k)

/-- Any two distinct formal branches of the standard node generate its maximal
ideal. -/
theorem nodeFormalBranches_sup_eq_maximalIdeal_of_ne
    (k : Type u) [Field k] (P Q : nodeFormalBranches k) (hne : P ≠ Q) :
    (P : Ideal (nodeRing k)) ⊔ Q =
      IsLocalRing.maximalIdeal (nodeRing k) := by
  let e := nodeFormalBranchesEquivFinTwo k
  let i := e P
  let j := e Q
  have hij : i ≠ j := fun h ↦ hne (e.injective h)
  have hinvolutive (a : Fin 2) : 1 - (1 - a) = a := by
    fin_cases a <;> rfl
  have hP : P = nodeRingFormalBranch k (1 - i) := by
    apply e.injective
    rw [nodeFormalBranchesEquivFinTwo_nodeRingFormalBranch]
    change i = 1 - (1 - i)
    exact (hinvolutive i).symm
  have hQ : Q = nodeRingFormalBranch k (1 - j) := by
    apply e.injective
    rw [nodeFormalBranchesEquivFinTwo_nodeRingFormalBranch]
    change j = 1 - (1 - j)
    exact (hinvolutive j).symm
  rw [hP, hQ]
  have hcases : (i = 0 ∧ j = 1) ∨ (i = 1 ∧ j = 0) := by
    omega
  rcases hcases with ⟨hi, hj⟩ | ⟨hi, hj⟩
  · rw [hi, hj]
    simpa [sup_comm] using nodeRingFormalBranch_sup_eq_maximalIdeal k
  · rw [hi, hj]
    simpa using nodeRingFormalBranch_sup_eq_maximalIdeal k

/-- If a ring is identified with the standard node ring, any two distinct minimal
primes generate the inverse image of the standard node's maximal ideal.

This formulation avoids choosing a local-ring instance on the source.  When the
source is already known to be local, the right side is its maximal ideal by
`IsLocalRing.maximalIdeal_comap`. -/
theorem minimalPrimes_sup_eq_comap_nodeMaximalIdeal_of_ringEquiv
    {k R : Type u} [Field k] [CommRing R]
    (e : R ≃+* nodeRing k) (P Q : minimalPrimes R) (hne : P ≠ Q) :
    (P : Ideal R) ⊔ Q =
      (IsLocalRing.maximalIdeal (nodeRing k)).comap e := by
  let P' := Ideal.minimalPrimesEquivOfRingEquiv e P
  let Q' := Ideal.minimalPrimesEquivOfRingEquiv e Q
  have hne' : P' ≠ Q' := fun hPQ ↦
    hne ((Ideal.minimalPrimesEquivOfRingEquiv e).injective hPQ)
  have hsum : (P.1.map e) ⊔ (Q.1.map e) =
      IsLocalRing.maximalIdeal (nodeRing k) := by
    simpa only [P', Q', Ideal.minimalPrimesEquivOfRingEquiv_apply] using
      nodeFormalBranches_sup_eq_maximalIdeal_of_ne k P' Q' hne'
  rw [← Ideal.map_sup] at hsum
  have hcomap := congrArg (Ideal.comap e) hsum
  rw [Ideal.comap_map_of_surjective' e e.surjective] at hcomap
  have hker0 : RingHom.ker e = ⊥ :=
    (RingHom.injective_iff_ker_eq_bot e).mp e.injective
  simpa only [hker0, sup_bot_eq] using hcomap

/-- Quotienting the standard node simultaneously by both formal branches gives the
ground field. -/
noncomputable def nodeRingBranchIntersectionAlgEquiv
    (k : Type u) [Field k] :
    (nodeRing k ⧸ ((nodeRingFormalBranch k 0 : Ideal (nodeRing k)) ⊔
      (nodeRingFormalBranch k 1 : Ideal (nodeRing k)))) ≃ₐ[k] k :=
  (Ideal.quotientEquivAlgOfEq k
      (nodeRingFormalBranch_sup_eq_maximalIdeal k)).trans
    (nodeRingResidueFieldAlgEquiv k)

end AlgebraicGeometry.Scheme

end
