module

public import StacksAndModuli.API.NodeRingAxisSequence
public import Mathlib.Algebra.GCDMonoid.IntegrallyClosed
public import Mathlib.RingTheory.PowerSeries.Inverse

/-!
# Normalization of the standard node ring

For a field `k`, the product of the two branch rings

`k[[x]] × k[[y]]`

is the integral closure of the standard node ring `k[[x,y]]/(xy)` in its total quotient
ring.  The total quotient ring is realized as the product of the fraction fields of the two
power-series rings.

The proof has three independent parts.  First, the axes product is integral over the node
ring: it is generated by the idempotent `(1, 0)`.  Second, the axes product is integrally
closed in the product of the branch fraction fields.  Third, an element of the node ring is
a non-zero-divisor exactly when both of its branch restrictions are nonzero; this identifies
the product of branch fraction fields with the localization at all non-zero-divisors.

## Main definitions

* `AlgebraicGeometry.Scheme.nodeBranchFractionRing`: the product of the two branch
  fraction fields.
* `AlgebraicGeometry.Scheme.nodeAxesToBranchFractions`: the componentwise fraction-ring
  map from the axes.
* `AlgebraicGeometry.Scheme.nodeToBranchFractions`: the total quotient map from the node.

## Main results

* `AlgebraicGeometry.Scheme.nodeToAxes_isIntegral`: the axes extension is integral.
* `AlgebraicGeometry.Scheme.nodeToAxes_mem_nonZeroDivisors_iff`: regular elements are
  exactly those nonzero on both branches.
* `AlgebraicGeometry.Scheme.nodeBranchFractions_isFractionRing`: the product of branch
  fraction fields is the total quotient ring of the node.
* `AlgebraicGeometry.Scheme.nodeAxes_isIntegralClosure`: the axes product is the integral
  closure of the node in that total quotient ring.
-/

@[expose] public section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

noncomputable section

open scoped MvPowerSeries PowerSeries nonZeroDivisors

open Polynomial

universe u

namespace AlgebraicGeometry.Scheme

/-- The product of the fraction fields of the two formal branches of the standard node. -/
abbrev nodeBranchFractionRing (k : Type u) [Field k] :=
  FractionRing (PowerSeries k) × FractionRing (PowerSeries k)

/-- The componentwise map from the two formal axes to their fraction fields. -/
def nodeAxesToBranchFractions (k : Type u) [Field k] :
    PowerSeries k × PowerSeries k →+* nodeBranchFractionRing k :=
  RingHom.prodMap (algebraMap (PowerSeries k) (FractionRing (PowerSeries k)))
    (algebraMap (PowerSeries k) (FractionRing (PowerSeries k)))

/-- The map from the standard node to the product of its branch fraction fields. -/
def nodeToBranchFractions (k : Type u) [Field k] :
    nodeRing k →+* nodeBranchFractionRing k :=
  (nodeAxesToBranchFractions k).comp (nodeToAxes k).toRingHom

/-- The algebra structure on the axes induced by the coordinate-axis embedding. -/
instance nodeRingAlgebraAxes (k : Type u) [Field k] :
    Algebra (nodeRing k) (PowerSeries k × PowerSeries k) :=
  (nodeToAxes k).toRingHom.toAlgebra

/-- The componentwise algebra structure on the branch fraction ring. -/
instance nodeAxesAlgebraBranchFractions (k : Type u) [Field k] :
    Algebra (PowerSeries k × PowerSeries k) (nodeBranchFractionRing k) :=
  (nodeAxesToBranchFractions k).toAlgebra

/-- The algebra structure on the branch fraction ring induced from the node. -/
instance nodeRingAlgebraBranchFractions (k : Type u) [Field k] :
    Algebra (nodeRing k) (nodeBranchFractionRing k) :=
  (nodeToBranchFractions k).toAlgebra

/-- The node, its axes, and the product of branch fraction fields form an algebra tower. -/
instance nodeAxesBranchFractions_isScalarTower (k : Type u) [Field k] :
    IsScalarTower (nodeRing k) (PowerSeries k × PowerSeries k)
      (nodeBranchFractionRing k) :=
  IsScalarTower.of_algebraMap_eq fun _ ↦ rfl

/-- The algebra map from the node to its axes is `nodeToAxes`. -/
@[simp]
lemma algebraMap_nodeRing_axes (k : Type u) [Field k] (a : nodeRing k) :
    algebraMap (nodeRing k) (PowerSeries k × PowerSeries k) a = nodeToAxes k a :=
  rfl

/-- The algebra map from the axes to the branch fraction ring acts componentwise. -/
@[simp]
lemma algebraMap_axes_branchFractions (k : Type u) [Field k]
    (a : PowerSeries k × PowerSeries k) :
    algebraMap (PowerSeries k × PowerSeries k) (nodeBranchFractionRing k) a =
      (algebraMap (PowerSeries k) (FractionRing (PowerSeries k)) a.1,
        algebraMap (PowerSeries k) (FractionRing (PowerSeries k)) a.2) :=
  rfl

/-- The algebra map from the node to its total quotient ring is
`nodeToBranchFractions`. -/
@[simp]
lemma algebraMap_nodeRing_branchFractions (k : Type u) [Field k]
    (a : nodeRing k) :
    algebraMap (nodeRing k) (nodeBranchFractionRing k) a =
      nodeToBranchFractions k a :=
  rfl

/-- The coordinate-axis embedding of the standard node is an integral ring map. -/
theorem nodeToAxes_isIntegral (k : Type u) [Field k] :
    (nodeToAxes k).toRingHom.IsIntegral := by
  let _ : Nontrivial (nodeRing k) := (nodeToAxes k).toRingHom.domain_nontrivial
  intro b
  let e : PowerSeries k × PowerSeries k := (1, 0)
  have he : _root_.IsIntegral (nodeRing k) e := by
    refine ⟨X ^ 2 - X, Polynomial.monic_X_pow_sub (p := X) ?_, ?_⟩
    · rw [Polynomial.degree_X]
      norm_num
    · simp [e]
  let d : k := PowerSeries.constantCoeff b.1 - PowerSeries.constantCoeff b.2
  let aD : nodeRing k :=
    Ideal.Quotient.mk (nodeIdeal k) (MvPowerSeries.C d)
  have haD : algebraMap (nodeRing k) (PowerSeries k × PowerSeries k) aD =
      (PowerSeries.C d, PowerSeries.C d) := by
    change nodeToAxes k aD = _
    simp [aD, nodeAxisRestrictions]
  let z : PowerSeries k × PowerSeries k :=
    b - algebraMap (nodeRing k) (PowerSeries k × PowerSeries k) aD * e
  have hz : nodeConstantDifference k z = 0 := by
    simp [z, haD, e, d, nodeConstantDifference]
  have hzker : z ∈ LinearMap.ker (nodeConstantDifference k) := hz
  rw [← nodeToAxes_range_eq_ker_nodeConstantDifference k] at hzker
  obtain ⟨a, ha⟩ := hzker
  have hza : z = algebraMap (nodeRing k) (PowerSeries k × PowerSeries k) a :=
    ha.symm
  have hzint : _root_.IsIntegral (nodeRing k) z := hza ▸ isIntegral_algebraMap
  have hdeint : _root_.IsIntegral (nodeRing k)
      (algebraMap (nodeRing k) (PowerSeries k × PowerSeries k) aD * e) :=
    isIntegral_algebraMap.mul he
  have hb : b = z + algebraMap (nodeRing k) (PowerSeries k × PowerSeries k) aD * e := by
    simp [z]
  exact hb.symm ▸ hzint.add hdeint

/-- The axes product is integral over the standard node ring. -/
instance nodeAxes_isIntegral (k : Type u) [Field k] :
    Algebra.IsIntegral (nodeRing k) (PowerSeries k × PowerSeries k) :=
  ⟨nodeToAxes_isIntegral k⟩

/-- The product of the two power-series rings is integrally closed in the product of their
fraction fields. -/
instance nodeAxes_isIntegrallyClosedIn_branchFractions (k : Type u) [Field k] :
    IsIntegrallyClosedIn (PowerSeries k × PowerSeries k)
      (nodeBranchFractionRing k) := by
  rw [isIntegrallyClosedIn_iff]
  constructor
  · intro a b hab
    apply Prod.ext
    · exact IsFractionRing.injective (PowerSeries k) _ (congrArg Prod.fst hab)
    · exact IsFractionRing.injective (PowerSeries k) _ (congrArg Prod.snd hab)
  · rintro ⟨x, y⟩ hxy
    have hx : _root_.IsIntegral (PowerSeries k) x := by
      apply hxy.map_of_comp_eq (RingHom.fst (PowerSeries k) (PowerSeries k))
        (RingHom.fst (FractionRing (PowerSeries k)) (FractionRing (PowerSeries k)))
      rfl
    have hy : _root_.IsIntegral (PowerSeries k) y := by
      apply hxy.map_of_comp_eq (RingHom.snd (PowerSeries k) (PowerSeries k))
        (RingHom.snd (FractionRing (PowerSeries k)) (FractionRing (PowerSeries k)))
      rfl
    obtain ⟨a, ha⟩ := IsIntegrallyClosed.algebraMap_eq_of_integral hx
    obtain ⟨b, hb⟩ := IsIntegrallyClosed.algebraMap_eq_of_integral hy
    exact ⟨(a, b), Prod.ext ha hb⟩

/-- An element of the standard node ring is a non-zero-divisor exactly when its restrictions
to both formal branches are nonzero. -/
theorem nodeToAxes_mem_nonZeroDivisors_iff (k : Type u) [Field k]
    (a : nodeRing k) :
    a ∈ nonZeroDivisors (nodeRing k) ↔
      (nodeToAxes k a).1 ≠ 0 ∧ (nodeToAxes k a).2 ≠ 0 := by
  constructor
  · intro ha
    rw [mem_nonZeroDivisors_iff_left] at ha
    constructor
    · intro hzero
      let t : nodeRing k :=
        Ideal.Quotient.mk (nodeIdeal k) (MvPowerSeries.X (0 : Fin 2))
      have ht : nodeToAxes k t = (PowerSeries.X, 0) := by
        simp [t, nodeAxisRestrictions]
      have hat : a * t = 0 := by
        apply nodeToAxes_injective k
        rw [map_mul, ht]
        apply Prod.ext <;> simp [hzero]
      have htzero := ha t hat
      have h := congrArg (nodeToAxes k) htzero
      simpa [ht] using congrArg Prod.fst h
    · intro hzero
      let t : nodeRing k :=
        Ideal.Quotient.mk (nodeIdeal k) (MvPowerSeries.X (1 : Fin 2))
      have ht : nodeToAxes k t = (0, PowerSeries.X) := by
        simp [t, nodeAxisRestrictions]
      have hat : a * t = 0 := by
        apply nodeToAxes_injective k
        rw [map_mul, ht]
        apply Prod.ext <;> simp [hzero]
      have htzero := ha t hat
      have h := congrArg (nodeToAxes k) htzero
      simpa [ht] using congrArg Prod.snd h
  · rintro ⟨hzero, hone⟩
    rw [mem_nonZeroDivisors_iff_left]
    intro b hab
    have h := congrArg (nodeToAxes k) hab
    rw [map_mul, map_zero] at h
    have hbzero : nodeToAxes k b = 0 := by
      apply Prod.ext
      · exact (mul_eq_zero.mp (congrArg Prod.fst h)).resolve_left hzero
      · exact (mul_eq_zero.mp (congrArg Prod.snd h)).resolve_left hone
    apply nodeToAxes_injective k
    exact hbzero.trans (map_zero (nodeToAxes k)).symm

/-- The total quotient map from the standard node is injective. -/
theorem nodeToBranchFractions_injective (k : Type u) [Field k] :
    Function.Injective (nodeToBranchFractions k) := by
  intro a b hab
  apply nodeToAxes_injective k
  apply Prod.ext
  · apply IsFractionRing.injective (PowerSeries k)
      (FractionRing (PowerSeries k))
    exact congrArg Prod.fst hab
  · apply IsFractionRing.injective (PowerSeries k)
      (FractionRing (PowerSeries k))
    exact congrArg Prod.snd hab

/-- The product of the two branch fraction fields is the total quotient ring of the
standard node. -/
instance nodeBranchFractions_isFractionRing (k : Type u) [Field k] :
    IsFractionRing (nodeRing k) (nodeBranchFractionRing k) := by
  change IsLocalization (nonZeroDivisors (nodeRing k)) (nodeBranchFractionRing k)
  rw [isLocalization_iff]
  refine ⟨?_, ?_, ?_⟩
  · intro s
    change IsUnit
      (algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
        (nodeToAxes k s).1,
      algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
        (nodeToAxes k s).2)
    rw [Prod.isUnit_iff]
    have hs := (nodeToAxes_mem_nonZeroDivisors_iff k s).mp s.2
    have hinj : Function.Injective
        (algebraMap (PowerSeries k) (FractionRing (PowerSeries k))) :=
      IsFractionRing.injective (PowerSeries k) (FractionRing (PowerSeries k))
    constructor
    · rw [isUnit_iff_ne_zero]
      change algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
        (nodeToAxes k s).1 ≠ 0
      simpa only [map_zero] using hinj.ne hs.1
    · rw [isUnit_iff_ne_zero]
      change algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
        (nodeToAxes k s).2 ≠ 0
      simpa only [map_zero] using hinj.ne hs.2
  · rintro ⟨x, y⟩
    obtain ⟨⟨px, rx⟩, hx⟩ := IsLocalization.surj
      (nonZeroDivisors (PowerSeries k)) x
    obtain ⟨⟨py, ry⟩, hy⟩ := IsLocalization.surj
      (nonZeroDivisors (PowerSeries k)) y
    let dxy : PowerSeries k × PowerSeries k :=
      (rx.1 * PowerSeries.X, ry.1 * PowerSeries.X)
    have hdxyker : dxy ∈ LinearMap.ker (nodeConstantDifference k) := by
      simp [dxy, nodeConstantDifference]
    rw [← nodeToAxes_range_eq_ker_nodeConstantDifference k] at hdxyker
    obtain ⟨d, hd⟩ := hdxyker
    have hd' : nodeToAxes k d = dxy := hd
    let pxy : PowerSeries k × PowerSeries k :=
      (px * PowerSeries.X, py * PowerSeries.X)
    have hpxyker : pxy ∈ LinearMap.ker (nodeConstantDifference k) := by
      simp [pxy, nodeConstantDifference]
    rw [← nodeToAxes_range_eq_ker_nodeConstantDifference k] at hpxyker
    obtain ⟨p, hp⟩ := hpxyker
    have hp' : nodeToAxes k p = pxy := hp
    have hdnzd : d ∈ nonZeroDivisors (nodeRing k) := by
      rw [nodeToAxes_mem_nonZeroDivisors_iff k, hd']
      exact ⟨mul_ne_zero (nonZeroDivisors.ne_zero rx.2) PowerSeries.X_ne_zero,
        mul_ne_zero (nonZeroDivisors.ne_zero ry.2) PowerSeries.X_ne_zero⟩
    have hdQ : algebraMap (nodeRing k) (nodeBranchFractionRing k) d =
        (algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
            (rx.1 * PowerSeries.X),
          algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
            (ry.1 * PowerSeries.X)) := by
      change nodeToBranchFractions k d = _
      change nodeAxesToBranchFractions k (nodeToAxes k d) = _
      rw [hd']
      rfl
    have hpQ : algebraMap (nodeRing k) (nodeBranchFractionRing k) p =
        (algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
            (px * PowerSeries.X),
          algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
            (py * PowerSeries.X)) := by
      change nodeToBranchFractions k p = _
      change nodeAxesToBranchFractions k (nodeToAxes k p) = _
      rw [hp']
      rfl
    refine ⟨⟨p, ⟨d, hdnzd⟩⟩, ?_⟩
    change (x, y) * algebraMap (nodeRing k) (nodeBranchFractionRing k) d =
      algebraMap (nodeRing k) (nodeBranchFractionRing k) p
    rw [hdQ, hpQ]
    apply Prod.ext
    · change x * algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
          (rx.1 * PowerSeries.X) =
        algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
          (px * PowerSeries.X)
      rw [map_mul, map_mul, ← mul_assoc, hx]
    · change y * algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
          (ry.1 * PowerSeries.X) =
        algebraMap (PowerSeries k) (FractionRing (PowerSeries k))
          (py * PowerSeries.X)
      rw [map_mul, map_mul, ← mul_assoc, hy]
  · intro x y hxy
    exact ⟨⟨1, one_mem _⟩, by simpa using nodeToBranchFractions_injective k hxy⟩

/-- The product of the two formal-axis rings is the integral closure of the standard node
ring in its total quotient ring. -/
instance nodeAxes_isIntegralClosure (k : Type u) [Field k] :
    IsIntegralClosure (PowerSeries k × PowerSeries k) (nodeRing k)
      (nodeBranchFractionRing k) :=
  IsIntegralClosure.of_isIntegrallyClosedIn

end AlgebraicGeometry.Scheme
