module

public import StacksAndModuli.API.IdealTensorIntersection
public import StacksAndModuli.API.TensorProductMixedFinite
public import Mathlib.RingTheory.Filtration
public import Mathlib.RingTheory.LocalRing.RingHom.Basic

/-!
# The Artin--Rees step in the Noetherian local flatness criterion

This file formalizes the Artin--Rees and Krull-intersection part of the local flatness
criterion used in Stacks Project tag 00MK.

For a local homomorphism of Noetherian local rings `R → S` and an `S`-finite module
`M`, injectivity of
`(I + 𝔪_R^n) ⊗[R] M → M` for every `n` implies injectivity of
`I ⊗[R] M → M`.  The remaining step in tag 00MK is the finite-length argument
which obtains the hypotheses for the cofinite ideals `I + 𝔪_R^n` from injectivity
at the maximal ideal.
-/

@[expose] public section

open TensorProduct
open scoped Pointwise

universe uR uS uM

namespace Ideal

variable {R : Type uR} [CommRing R] {S : Type uS} [CommRing S] [Algebra R S]
variable {M : Type uM} [AddCommGroup M] [Module R M] [Module S M]
variable [IsScalarTower R S M]

/-- If `J ⊆ K I`, then after commuting tensor factors, the image of
`J ⊗[R] M → I ⊗[R] M` lies in the submodule generated by the extension of `K`
to `S`.

This is the balancing calculation which connects Artin--Rees over `R` to Krull
intersection over `S`. -/
theorem comm_range_rTensor_mem_map_smul_of_le_smul
    (I J K : Ideal R) (hJI : J ≤ I)
    (hJK : J ≤ K • (I : Submodule R R)) (y : J ⊗[R] M) :
    (TensorProduct.comm R I M) (((Submodule.inclusion hJI).rTensor M) y) ∈
      K.map (algebraMap R S) • (⊤ : Submodule S (M ⊗[R] I)) := by
  induction y using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy => simpa only [map_add] using Submodule.add_mem _ hx hy
  | tmul j m =>
    simp only [LinearMap.rTensor_tmul, TensorProduct.comm_tmul]
    let P : R → Prop := fun z => ∃ hz : z ∈ I,
      m ⊗ₜ[R] (⟨z, hz⟩ : I) ∈
        K.map (algebraMap R S) • (⊤ : Submodule S (M ⊗[R] I))
    have hP : P j := by
      refine Submodule.smul_induction_on (hJK j.property) (p := P) ?_ ?_
      · intro r hr i hi
        have hri : r • i ∈ I := by
          simpa [smul_eq_mul] using I.mul_mem_left r hi
        refine ⟨hri, ?_⟩
        have hrS : algebraMap R S r ∈ K.map (algebraMap R S) :=
          Ideal.mem_map_of_mem (algebraMap R S) hr
        have hmem := Submodule.smul_mem_smul hrS
          (show m ⊗ₜ[R] ⟨i, hi⟩ ∈ (⊤ : Submodule S (M ⊗[R] I)) from
            Submodule.mem_top)
        have heq : m ⊗ₜ[R] (⟨r • i, hri⟩ : I) =
            algebraMap R S r • (m ⊗ₜ[R] (⟨i, hi⟩ : I)) := calc
          m ⊗ₜ[R] (⟨r • i, hri⟩ : I) =
              m ⊗ₜ[R] (r • (⟨i, hi⟩ : I)) := by congr 1
          _ = r • (m ⊗ₜ[R] (⟨i, hi⟩ : I)) := TensorProduct.tmul_smul _ _ _
          _ = algebraMap R S r • (m ⊗ₜ[R] (⟨i, hi⟩ : I)) :=
            (IsScalarTower.algebraMap_smul S r _).symm
        simpa only [smul_eq_mul] using heq.symm ▸ hmem
      · rintro x y ⟨hxI, hx⟩ ⟨hyI, hy⟩
        let hxyI := I.add_mem hxI hyI
        refine ⟨hxyI, ?_⟩
        have heq : (⟨x + y, hxyI⟩ : I) =
            (⟨x, hxI⟩ : I) + (⟨y, hyI⟩ : I) := by
          apply Subtype.ext
          rfl
        rw [heq, tmul_add]
        exact Submodule.add_mem _ hx hy
    obtain ⟨hjI, hj⟩ := hP
    have heq : (⟨j, hjI⟩ : I) = (Submodule.inclusion hJI) j := by
      apply Subtype.ext
      rfl
    rwa [heq] at hj

/-- Artin--Rees and Krull intersection reduce injectivity for `I ⊗[R] M → M` to
injectivity for the cofinite approximations
`(I + 𝔪_R^n) ⊗[R] M → M`.

This is the Noetherian-completion step in the proof of the local flatness criterion.
It avoids constructing completions explicitly: Artin--Rees places the tensor kernel
in every power of the extended maximal ideal, and Krull intersection kills it. -/
theorem injective_rTensor_of_injective_sup_maximalIdeal_pow
    [IsNoetherianRing R] [IsLocalRing R] [IsNoetherianRing S] [IsLocalRing S]
    [IsLocalHom (algebraMap R S)] [Module.Finite S M]
    (I : Ideal R)
    (hSup : ∀ n : ℕ, Function.Injective
      ((I ⊔ (IsLocalRing.maximalIdeal R) ^ n : Ideal R).subtype.rTensor M)) :
    Function.Injective (I.subtype.rTensor M) := by
  let m := IsLocalRing.maximalIdeal R
  let mS := m.map (algebraMap R S)
  let _ : Module.Finite R I := Module.Finite.of_fg (IsNoetherian.noetherian I)
  let _ : Module.Finite S (M ⊗[R] I) :=
    Module.Finite.tensorProduct_of_scalarTower
  obtain ⟨c, hc⟩ := Ideal.exists_pow_inf_eq_pow_smul m (I : Submodule R R)
  rw [injective_iff_map_eq_zero]
  intro z hz
  have hzker : z ∈ LinearMap.ker (I.subtype.rTensor M) := LinearMap.mem_ker.mpr hz
  have hpow : ∀ t : ℕ,
      (TensorProduct.comm R I M) z ∈ mS ^ t • (⊤ : Submodule S (M ⊗[R] I)) := by
    intro t
    let n := t + c
    have hrange := Ideal.ker_rTensor_subtype_le_range_inf_inclusion I (m ^ n) (hSup n)
      hzker
    obtain ⟨y, hy⟩ := hrange
    have hle : (I ⊓ m ^ n : Ideal R) ≤ m ^ t • (I : Submodule R R) := by
      have har := hc n (show c ≤ n by simp [n])
      rw [show n - c = t by simp [n]] at har
      have har' : (m ^ n ⊓ I : Ideal R) = m ^ t • (m ^ c ⊓ I : Ideal R) := by
        simpa [Ideal.smul_eq_mul] using har
      rw [← inf_comm, har']
      exact Submodule.smul_mono le_rfl inf_le_right
    have hmem := comm_range_rTensor_mem_map_smul_of_le_smul (S := S)
      I (I ⊓ m ^ n) (m ^ t) inf_le_left hle y
    rw [hy] at hmem
    simpa only [Ideal.map_pow] using hmem
  have hInf : (TensorProduct.comm R I M) z ∈
      (⨅ t : ℕ, mS ^ t • (⊤ : Submodule S (M ⊗[R] I))) :=
    (Submodule.mem_iInf _).mpr hpow
  have hmS : mS ≠ ⊤ := (IsLocalRing.map_maximalIdeal_lt_top (algebraMap R S)).ne
  rw [Ideal.iInf_pow_smul_eq_bot_of_isLocalRing mS hmS] at hInf
  exact (TensorProduct.comm R I M).injective (by simpa using hInf)

end Ideal
