module

public import Mathlib.CategoryTheory.Sites.Over
public import Mathlib.CategoryTheory.Sites.IsSheafFor
public import Mathlib.CategoryTheory.Sites.SubcanonicalOver

/-!
# Total presheaves over a slice category

For a presheaf `G` on `Over S`, this file constructs the total presheaf on the
base category whose sections over `T` are pairs consisting of a morphism
`a : T ⟶ S` and a section of `G` over `a`.  This is the presheaf-level
Grothendieck construction used to compare sheaf conditions on a slice site with
ordinary sheaf conditions on the base site.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory Opposite

universe w v u

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] {S : C}

namespace PresheafOver

private lemma eqToHom_apply_heq {A B : Type w} (h : A = B) (x : A) :
    (eqToHom h : A ⟶ B) x ≍ x := by
  subst h
  rfl

private lemma map_homMk_heq (G : (Over S)ᵒᵖ ⥤ Type w)
    {A Z : Over S} (g : Z ⟶ A) (x : G.obj (op A)) :
    G.map g.op x ≍
      G.map ((Over.homMk g.left : Over.mk (g.left ≫ A.hom) ⟶ A)).op x := by
  obtain ⟨Z, z, rfl⟩ := Z.mk_surjective
  let m : Over.mk (g.left ≫ A.hom) ⟶ A := Over.homMk g.left
  have e : Over.mk (g.left ≫ A.hom) = Over.mk z :=
    congrArg Over.mk (Over.w g)
  have hm : m = eqToHom e ≫ g := by
    ext
    simp [m]
  change G.map g.op x ≍ G.map m.op x
  rw [hm]
  simp only [op_comp, Functor.map_comp, types_comp_apply]
  rw [eqToHom_op, eqToHom_map]
  exact (eqToHom_apply_heq _ _).symm

private lemma map_comp_eqToHom_homMk_heq (G : (Over S)ᵒᵖ ⥤ Type w)
    {A B Z : Over S} (e : B = A) (g : Z ⟶ B) (x : G.obj (op A)) :
    G.map g.op (G.map (eqToHom e).op x) ≍
      G.map ((Over.homMk (g ≫ eqToHom e).left :
        Over.mk ((g ≫ eqToHom e).left ≫ A.hom) ⟶ A)).op x := by
  rw [← types_comp_apply, ← G.map_comp, ← op_comp]
  exact map_homMk_heq G (g ≫ eqToHom e) x

/-- The total presheaf associated to a presheaf on `Over S`.  Its sections over
`T` are pairs `(a : T ⟶ S, x ∈ G(a))`. -/
def total (G : (Over S)ᵒᵖ ⥤ Type w) : Cᵒᵖ ⥤ Type max v w where
  obj T := Σ a : T.unop ⟶ S, G.obj (op (Over.mk a))
  map {T U} f := ↾fun x ↦
    ⟨f.unop ≫ x.1, G.map (Over.homMk f.unop).op x.2⟩
  map_id T := by
    ext x
    · simp
    · obtain ⟨a, x⟩ := x
      dsimp
      have h : (Over.homMk (𝟙 (unop T)) :
          Over.mk ((𝟙 (unop T)) ≫ a) ⟶ Over.mk a) =
          eqToHom (by simp) := by
        ext
        simp
      rw [h]
      rw [eqToHom_op, eqToHom_map]
      exact eqToHom_apply_heq _ _
  map_comp {T U V} f g := by
    ext x
    · simp
    · obtain ⟨a, x⟩ := x
      dsimp
      let m₁ : Over.mk (f.unop ≫ a) ⟶ Over.mk a := Over.homMk f.unop
      let m₂ : Over.mk (g.unop ≫ (f.unop ≫ a)) ⟶
          Over.mk (f.unop ≫ a) := Over.homMk g.unop
      have e : Over.mk ((g.unop ≫ f.unop) ≫ a) =
          Over.mk (g.unop ≫ (f.unop ≫ a)) :=
        congrArg Over.mk (Category.assoc _ _ _)
      have hm : (Over.homMk (g.unop ≫ f.unop) :
          Over.mk ((g.unop ≫ f.unop) ≫ a) ⟶ Over.mk a) =
          eqToHom e ≫ m₂ ≫ m₁ := by
        ext
        simp [m₁, m₂]
      rw [hm]
      simp only [op_comp, Functor.map_comp, types_comp_apply]
      rw [eqToHom_op, eqToHom_map]
      exact eqToHom_apply_heq _ _

@[simp]
lemma total_obj (G : (Over S)ᵒᵖ ⥤ Type w) (T : Cᵒᵖ) :
    (total G).obj T = (Σ a : T.unop ⟶ S, G.obj (op (Over.mk a))) :=
  rfl

@[simp]
lemma total_map_fst (G : (Over S)ᵒᵖ ⥤ Type w) {T U : Cᵒᵖ} (f : T ⟶ U)
    (x : (total G).obj T) :
    ((total G).map f x).1 = f.unop ≫ x.1 :=
  rfl

/-- The canonical object over `S` obtained by composing one member of a family
with a fixed morphism to `S`. -/
def liftObj {B : C} {I : Type*} {X : I → C} (f : ∀ i, X i ⟶ B)
    (a : B ⟶ S) (i : I) : Over S :=
  Over.mk (f i ≫ a)

/-- A family on `B` lifted to the slice over `S`. -/
def liftHom {B : C} {I : Type*} {X : I → C} (f : ∀ i, X i ⟶ B)
    (a : B ⟶ S) (i : I) : liftObj f a i ⟶ Over.mk a :=
  Over.homMk (f i)

@[simp]
lemma liftHom_left {B : C} {I : Type*} {X : I → C} (f : ∀ i, X i ⟶ B)
    (a : B ⟶ S) (i : I) : (liftHom f a i).left = f i :=
  rfl

set_option backward.isDefEq.respectTransparency false in
/-- The sieve generated by the canonical lift of a family is the pullback, under
the slice equivalence on sieves, of the sieve generated by the original family. -/
lemma generate_lift_eq_overEquiv_symm {B : C} {I : Type*} {X : I → C}
    (f : ∀ i, X i ⟶ B) (a : B ⟶ S) :
    Sieve.generate (Presieve.ofArrows (liftObj f a) (liftHom f a)) =
      (Sieve.overEquiv (Over.mk a)).symm (Sieve.ofArrows X f) := by
  apply (Sieve.overEquiv (Over.mk a)).injective
  rw [Sieve.overEquiv_generate, OrderIso.apply_symm_apply,
    ← Sieve.arrows_generate_map_eq_functorPushforward,
    Sieve.generate_sieve, Presieve.map_ofArrows]
  simp [liftObj, liftHom]

set_option backward.isDefEq.respectTransparency false in
/-- If the total presheaf is a sheaf for a family and the representable
presheaf of `S` is separated for that family, then the original presheaf is a
sheaf for the canonically lifted family in the slice over `S`. -/
lemma isSheafFor_lift_of_total
    (G : (Over S)ᵒᵖ ⥤ Type w) {B : C} {I : Type*} {X : I → C}
    (f : ∀ i, X i ⟶ B) (a : B ⟶ S)
    (hTotal : Presieve.IsSheafFor (total G) (Presieve.ofArrows X f))
    (hRepresentable : Presieve.IsSeparatedFor (yoneda.obj S)
      (Presieve.ofArrows X f)) :
    Presieve.IsSheafFor G
      (Presieve.ofArrows (liftObj f a) (liftHom f a)) := by
  rw [Presieve.isSheafFor_arrows_iff] at hTotal ⊢
  intro x hx
  let xTotal : ∀ i, (total G).obj (op (X i)) := fun i ↦ ⟨f i ≫ a, x i⟩
  have hxTotal : Presieve.Arrows.Compatible (total G) f xTotal := by
    intro i j Z gᵢ gⱼ h
    apply Sigma.ext
    · change gᵢ ≫ (f i ≫ a) = gⱼ ≫ (f j ≫ a)
      simpa only [Category.assoc] using congrArg (fun k ↦ k ≫ a) h
    · change G.map ((Over.homMk gᵢ :
          Over.mk (gᵢ ≫ (f i ≫ a)) ⟶ liftObj f a i)).op (x i) ≍
        G.map ((Over.homMk gⱼ :
          Over.mk (gⱼ ≫ (f j ≫ a)) ⟶ liftObj f a j)).op (x j)
      let p : gⱼ ≫ (liftObj f a j).hom = gᵢ ≫ (f i ≫ a) := by
        simpa [liftObj, Category.assoc] using congrArg (fun k ↦ k ≫ a) h.symm
      let m : Over.mk (gᵢ ≫ (f i ≫ a)) ⟶ liftObj f a j :=
        Over.homMk gⱼ p
      have H := hx i j
        (Over.mk (gᵢ ≫ (f i ≫ a))) (Over.homMk gᵢ)
        m
        (by ext; exact h)
      apply (heq_of_eq H).trans
      change G.map m.op (x j) ≍
        G.map ((Over.homMk gⱼ :
          Over.mk (gⱼ ≫ (f j ≫ a)) ⟶ liftObj f a j)).op (x j)
      have e : Over.mk (gᵢ ≫ (f i ≫ a)) =
          Over.mk (gⱼ ≫ (f j ≫ a)) := by
        apply congrArg Over.mk
        simpa only [Category.assoc] using congrArg (fun k ↦ k ≫ a) h
      let m' : Over.mk (gⱼ ≫ (f j ≫ a)) ⟶ liftObj f a j :=
        Over.homMk gⱼ
      have hm : m = eqToHom e ≫ m' := by
        ext
        simp [m, m']
      rw [hm]
      simp only [op_comp, Functor.map_comp, types_comp_apply]
      rw [eqToHom_op, eqToHom_map]
      exact eqToHom_apply_heq _ _
  obtain ⟨t, ht, htUnique⟩ := hTotal xTotal hxTotal
  obtain ⟨b, t⟩ := t
  have hba : b = a := hRepresentable.ext (t₁ := b) (t₂ := a) (by
    intro Y g hg
    obtain ⟨i⟩ := hg
    change f i ≫ b = f i ≫ a
    exact congrArg Sigma.fst (ht i))
  subst b
  refine ⟨t, fun i ↦ ?_, fun y hy ↦ ?_⟩
  · exact eq_of_heq (Sigma.ext_iff.mp (ht i)).2
  · have hpair : (⟨a, y⟩ : (total G).obj (op B)) = ⟨a, t⟩ := by
      apply htUnique
      intro i
      change (⟨f i ≫ a, G.map (Over.homMk (f i)).op y⟩ :
        (total G).obj (op (X i))) = ⟨f i ≫ a, x i⟩
      exact Sigma.ext rfl (heq_of_eq (hy i))
    exact eq_of_heq (Sigma.ext_iff.mp hpair).2

set_option backward.isDefEq.respectTransparency false in
/-- Conversely, if the representable presheaf of `S` is a sheaf for a family
and `G` is a sheaf for every lift of that family to `Over S`, then the total
presheaf is a sheaf for the original family. -/
lemma isSheafFor_total_of_lift
    (G : (Over S)ᵒᵖ ⥤ Type w) {B : C} {I : Type*} {X : I → C}
    (f : ∀ i, X i ⟶ B)
    (hRepresentable : Presieve.IsSheafFor (yoneda.obj S)
      (Presieve.ofArrows X f))
    (hLift : ∀ (a : B ⟶ S), Presieve.IsSheafFor G
      (Presieve.ofArrows (liftObj f a) (liftHom f a))) :
    Presieve.IsSheafFor (total G) (Presieve.ofArrows X f) := by
  rw [Presieve.isSheafFor_arrows_iff] at hRepresentable ⊢
  intro x hx
  let xBase : ∀ i, (yoneda.obj S).obj (op (X i)) := fun i ↦ (x i).1
  have hxBase : Presieve.Arrows.Compatible (yoneda.obj S) f xBase := by
    intro i j Z gᵢ gⱼ h
    change gᵢ ≫ (x i).1 = gⱼ ≫ (x j).1
    exact congrArg Sigma.fst (hx i j Z gᵢ gⱼ h)
  obtain ⟨a, ha, haUnique⟩ := hRepresentable xBase hxBase
  let e (i : I) : liftObj f a i = Over.mk (x i).1 :=
    congrArg Over.mk (ha i)
  let xLift : ∀ i, G.obj (op (liftObj f a i)) := fun i ↦
    G.map (eqToHom (e i)).op (x i).2
  have hxLift : Presieve.Arrows.Compatible G (liftHom f a) xLift := by
    intro i j Z gᵢ gⱼ h
    let qᵢ : Z ⟶ Over.mk (x i).1 := gᵢ ≫ eqToHom (e i)
    let qⱼ : Z ⟶ Over.mk (x j).1 := gⱼ ≫ eqToHom (e j)
    have hq : qᵢ.left ≫ f i = qⱼ.left ≫ f j := by
      have h' := congrArg (fun k ↦ k.left) h
      simpa [qᵢ, qⱼ, liftHom, e] using h'
    have hTotal := hx i j Z.left qᵢ.left qⱼ.left hq
    have hSecond := (Sigma.ext_iff.mp hTotal).2
    have hLeft := map_comp_eqToHom_homMk_heq G (e i) gᵢ (x i).2
    have hRight := map_comp_eqToHom_homMk_heq G (e j) gⱼ (x j).2
    exact eq_of_heq (hLeft.trans (hSecond.trans hRight.symm))
  have hLiftA := hLift a
  rw [Presieve.isSheafFor_arrows_iff] at hLiftA
  obtain ⟨t, ht, htUnique⟩ := hLiftA xLift hxLift
  refine ⟨⟨a, t⟩, fun i ↦ ?_, ?_⟩
  · apply Sigma.ext (ha i)
    apply (heq_of_eq (ht i)).trans
    dsimp [xLift]
    rw [eqToHom_op, eqToHom_map]
    exact eqToHom_apply_heq _ _
  · rintro ⟨b, s⟩ hs
    have hba : b = a := haUnique b (by
      intro i
      change f i ≫ b = xBase i
      exact congrArg Sigma.fst (hs i))
    subst b
    have hst : s = t := by
      apply htUnique s
      intro i
      have hs' := (Sigma.ext_iff.mp (hs i)).2
      have hx' : xLift i ≍ (x i).2 := by
        dsimp [xLift]
        rw [eqToHom_op, eqToHom_map]
        exact eqToHom_apply_heq _ _
      exact eq_of_heq (hs'.trans hx'.symm)
    exact Sigma.ext rfl (heq_of_eq hst)

set_option backward.isDefEq.respectTransparency false in
/-- If `J` is subcanonical, the total presheaf of a sheaf on the slice site
`Over S` is a sheaf on the base site. -/
lemma isSheaf_total (J : GrothendieckTopology C) [J.Subcanonical]
    (G : Functor (Over S)ᵒᵖ (Type w)) (hG : Presieve.IsSheaf (J.over S) G) :
    Presieve.IsSheaf J (total G) := by
  intro B R hR
  obtain ⟨I, X, f, rfl⟩ := R.exists_eq_ofArrows
  rw [← Presieve.isSheafFor_iff_generate]
  apply isSheafFor_total_of_lift G f
  · exact (GrothendieckTopology.Subcanonical.isSheaf_of_isRepresentable
      (yoneda.obj S)).isSheafFor _ hR
  · intro a
    apply hG.isSheafFor
    rw [J.mem_over_iff, Sieve.overEquiv_generate,
      ← Sieve.arrows_generate_map_eq_functorPushforward,
      Sieve.generate_sieve, Presieve.map_ofArrows]
    simpa [liftObj, liftHom] using hR

end PresheafOver

end CategoryTheory
