module

public import Mathlib.RingTheory.MvPolynomial.Homogeneous
public import Mathlib.RingTheory.GradedAlgebra.Basic
public import Mathlib.Algebra.MvPolynomial.CommRing
public import Mathlib.Data.Fin.Tuple.Basic
public import Mathlib.Algebra.BigOperators.Fin
public import Mathlib.RingTheory.Ideal.Quotient.Operations
public import Mathlib.Tactic.FieldSimp

/-!
# A hyperplane in `ℙⁿ⁺¹` is a `ℙⁿ`

Supporting API with no Stacks Project counterpart, developed for §2.3 (Castelnuovo–Mumford
regularity) of *Stacks and Moduli*.

Let `k` be a field and `L = ∑ᵢ cᵢ xᵢ ∈ k[x₀, …, x_{n+1}]` a linear form with `c_j` a unit.
Substituting `x_j ↦ -c_j⁻¹ ∑_{i ≠ j} cᵢ xᵢ` and `x_{j.succAbove i} ↦ y_i` defines a graded
`k`-algebra map `k[x₀, …, x_{n+1}] → k[y₀, …, y_n]` whose kernel is exactly `(L)`; this is the
algebraic form of the statement that the hyperplane `V(L) ⊆ ℙⁿ⁺¹` is a copy of `ℙⁿ`. It is what
turns the inductive step of Mumford's Boundedness of Regularity (Theorem 2.3.8) into an
application of the inductive hypothesis on `ℙⁿ`.

Mathlib has no API for quotients of a polynomial ring by a linear form.

Main declarations:
- `MvPolynomial.linearForm`, `MvPolynomial.hyperplaneAlgHom`, `MvPolynomial.liftAlgHom`.
- `MvPolynomial.hyperplaneAlgHom_linearForm`: the linear form is killed.
- `MvPolynomial.mem_span_linearForm_of_hyperplaneAlgHom_eq_zero`: the kernel is contained in
  `(L)`, hence equal to it.
- `MvPolynomial.isHomogeneous_hyperplaneAlgHom`: the substitution preserves degrees.
- `MvPolynomial.exists_isHomogeneous_of_mem_span_of_isHomogeneous`: a homogeneous element of
  the ideal generated by a linear form is that form times a homogeneous element of one degree
  less.
-/

@[expose] public section

-- These files were written when Lean's backward-compat defeq options were on by default.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

universe u

namespace MvPolynomial

variable {k : Type u} [CommRing k] {n : ℕ}

/-- The linear form `L = ∑ᵢ cᵢ xᵢ`. -/
noncomputable def linearForm (c : Fin (n + 1) → k) : MvPolynomial (Fin (n + 1)) k :=
  ∑ i, C (c i) * X i

lemma linearForm_def (c : Fin (n + 1) → k) : linearForm c = ∑ i, C (c i) * X i := rfl

lemma isHomogeneous_linearForm (c : Fin (n + 1) → k) : (linearForm c).IsHomogeneous 1 :=
  IsHomogeneous.sum _ _ _ fun i _ => (isHomogeneous_X k i).C_mul (c i)

section Field

variable {k : Type u} [Field k] {n : ℕ}

/-- The substitution `x_j ↦ -c_j⁻¹ ∑_{i ≠ j} cᵢ xᵢ`, `x_{j.succAbove i} ↦ yᵢ`, on variables. -/
noncomputable def hyperplaneSubst (c : Fin (n + 2) → k) (j : Fin (n + 2)) :
    Fin (n + 2) → MvPolynomial (Fin (n + 1)) k :=
  j.insertNth (-(c j)⁻¹ • ∑ i : Fin (n + 1), C (c (j.succAbove i)) * X i) fun i => X i

@[simp] lemma hyperplaneSubst_succAbove (c : Fin (n + 2) → k) (j : Fin (n + 2))
    (i : Fin (n + 1)) : hyperplaneSubst c j (j.succAbove i) = X i := by
  simp [hyperplaneSubst]

@[simp] lemma hyperplaneSubst_self (c : Fin (n + 2) → k) (j : Fin (n + 2)) :
    hyperplaneSubst c j j
      = -(c j)⁻¹ • ∑ i : Fin (n + 1), C (c (j.succAbove i)) * X i := by
  simp [hyperplaneSubst]

/-- The graded `k`-algebra map `k[x₀, …, x_{n+1}] → k[y₀, …, y_n]` cutting out the hyperplane
`V(L)`, `L = ∑ᵢ cᵢ xᵢ`. -/
noncomputable def hyperplaneAlgHom (c : Fin (n + 2) → k) (j : Fin (n + 2)) :
    MvPolynomial (Fin (n + 2)) k →ₐ[k] MvPolynomial (Fin (n + 1)) k :=
  aeval (hyperplaneSubst c j)

/-- The `k`-algebra map `k[y₀, …, y_n] → k[x₀, …, x_{n+1}]`, `yᵢ ↦ x_{j.succAbove i}`, a section
of `hyperplaneAlgHom`. -/
noncomputable def liftAlgHom (j : Fin (n + 2)) :
    MvPolynomial (Fin (n + 1)) k →ₐ[k] MvPolynomial (Fin (n + 2)) k :=
  aeval fun i : Fin (n + 1) => (X (j.succAbove i) : MvPolynomial (Fin (n + 2)) k)

@[simp] lemma hyperplaneAlgHom_X_succAbove (c : Fin (n + 2) → k) (j : Fin (n + 2))
    (i : Fin (n + 1)) : hyperplaneAlgHom c j (X (j.succAbove i)) = X i := by
  simp [hyperplaneAlgHom]

@[simp] lemma hyperplaneAlgHom_X_self (c : Fin (n + 2) → k) (j : Fin (n + 2)) :
    hyperplaneAlgHom c j (X j)
      = -(c j)⁻¹ • ∑ i : Fin (n + 1), C (c (j.succAbove i)) * X i := by
  simp [hyperplaneAlgHom]

@[simp] lemma liftAlgHom_X (j : Fin (n + 2)) (i : Fin (n + 1)) :
    liftAlgHom (k := k) j (X i) = X (j.succAbove i) := by
  simp [liftAlgHom]

lemma hyperplaneAlgHom_comp_liftAlgHom (c : Fin (n + 2) → k) (j : Fin (n + 2)) :
    (hyperplaneAlgHom c j).comp (liftAlgHom j) = AlgHom.id k _ := by
  refine algHom_ext fun i => ?_
  simp

/-- The substitution kills the linear form. -/
lemma hyperplaneAlgHom_linearForm (c : Fin (n + 2) → k) (j : Fin (n + 2)) (hj : c j ≠ 0) :
    hyperplaneAlgHom c j (linearForm c) = 0 := by
  rw [linearForm, map_sum, Fin.sum_univ_succAbove _ j]
  simp only [map_mul, hyperplaneAlgHom, aeval_C, algebraMap_eq, aeval_X,
    hyperplaneSubst_self, hyperplaneSubst_succAbove]
  rw [smul_eq_C_mul, ← mul_assoc, ← C_mul]
  have hcj : c j * -(c j)⁻¹ = -1 := by field_simp
  rw [hcj]
  simp

/-- Every polynomial agrees, modulo the ideal generated by the linear form `L`, with the image
of its substitution: `p - ψ(φ(p)) ∈ (L)`. -/
lemma sub_liftAlgHom_hyperplaneAlgHom_mem_span (c : Fin (n + 2) → k) (j : Fin (n + 2))
    (hj : c j ≠ 0) (p : MvPolynomial (Fin (n + 2)) k) :
    p - liftAlgHom j (hyperplaneAlgHom c j p) ∈ Ideal.span {linearForm c} := by
  set I : Ideal (MvPolynomial (Fin (n + 2)) k) := Ideal.span {linearForm c} with hI
  set Q : MvPolynomial (Fin (n + 2)) k →ₐ[k] (MvPolynomial (Fin (n + 2)) k ⧸ I) :=
    Ideal.Quotient.mkₐ k I with hQ
  have hL : Q (linearForm c) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span rfl)
  have hCmul : ∀ (a : k) (x : MvPolynomial (Fin (n + 2)) k), Q (C a * x) = a • Q x := by
    intro a x
    rw [map_mul]
    have : Q (C a) = algebraMap k _ a := by
      rw [← algebraMap_eq]; exact Q.commutes a
    rw [this, ← Algebra.smul_def]
  have hkey : Q.comp ((liftAlgHom j).comp (hyperplaneAlgHom c j)) = Q := by
    refine algHom_ext ?_
    rw [Fin.forall_iff_succAbove j]
    refine ⟨?_, fun i => by simp⟩
    have hsplit : linearForm c = C (c j) * X j
        + ∑ i : Fin (n + 1), C (c (j.succAbove i)) * X (j.succAbove i) := by
      rw [linearForm, Fin.sum_univ_succAbove _ j]
    have h1 : (c j) • Q (X j)
        + Q (∑ i : Fin (n + 1), C (c (j.succAbove i)) * X (j.succAbove i)) = 0 := by
      rw [← hCmul, ← map_add, ← hsplit, hL]
    have hlift : liftAlgHom (k := k) j (∑ i : Fin (n + 1), C (c (j.succAbove i)) * X i)
        = ∑ i : Fin (n + 1), C (c (j.succAbove i)) * X (j.succAbove i) := by
      rw [map_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [map_mul, liftAlgHom_X]
      congr 1
      rw [← algebraMap_eq]
      exact (liftAlgHom j).commutes _
    simp only [AlgHom.comp_apply, hyperplaneAlgHom_X_self, map_smul, hlift]
    have h2 : Q (∑ i : Fin (n + 1), C (c (j.succAbove i)) * X (j.succAbove i))
        = -((c j) • Q (X j)) := eq_neg_of_add_eq_zero_right h1
    rw [h2, smul_neg, neg_smul, neg_neg, smul_smul, inv_mul_cancel₀ hj, one_smul]
  have hp := congrArg (fun f : MvPolynomial (Fin (n + 2)) k →ₐ[k] _ => f p) hkey
  simp only [AlgHom.comp_apply] at hp
  exact (Submodule.Quotient.eq I).mp hp.symm

/-- The kernel of the substitution is the ideal generated by the linear form. -/
lemma mem_span_linearForm_of_hyperplaneAlgHom_eq_zero (c : Fin (n + 2) → k) (j : Fin (n + 2))
    (hj : c j ≠ 0) {p : MvPolynomial (Fin (n + 2)) k} (hp : hyperplaneAlgHom c j p = 0) :
    p ∈ Ideal.span {linearForm c} := by
  have h := sub_liftAlgHom_hyperplaneAlgHom_mem_span c j hj p
  rwa [hp, map_zero, sub_zero] at h

lemma isHomogeneous_hyperplaneSubst (c : Fin (n + 2) → k) (j : Fin (n + 2))
    (i : Fin (n + 2)) : (hyperplaneSubst c j i).IsHomogeneous 1 := by
  rcases eq_or_ne i j with rfl | hne
  · rw [hyperplaneSubst_self, smul_eq_C_mul]
    exact (IsHomogeneous.sum _ _ _ fun i' _ =>
      (isHomogeneous_X k i').C_mul (c (i.succAbove i'))).C_mul _
  · obtain ⟨i', rfl⟩ := Fin.exists_succAbove_eq hne
    rw [hyperplaneSubst_succAbove]
    exact isHomogeneous_X k i'

/-- The substitution preserves degrees. -/
lemma isHomogeneous_hyperplaneAlgHom (c : Fin (n + 2) → k) (j : Fin (n + 2)) {d : ℕ}
    {p : MvPolynomial (Fin (n + 2)) k} (hp : p.IsHomogeneous d) :
    (hyperplaneAlgHom c j p).IsHomogeneous d := by
  have := hp.aeval (hyperplaneSubst c j) (isHomogeneous_hyperplaneSubst c j)
  rwa [one_mul] at this

/-- The section preserves degrees. -/
lemma isHomogeneous_liftAlgHom (j : Fin (n + 2)) {d : ℕ}
    {p : MvPolynomial (Fin (n + 1)) k} (hp : p.IsHomogeneous d) :
    (liftAlgHom (k := k) j p).IsHomogeneous d := by
  have := hp.aeval (fun i : Fin (n + 1) => (X (j.succAbove i) : MvPolynomial (Fin (n + 2)) k))
    (fun i => isHomogeneous_X k _)
  rwa [one_mul] at this

lemma hyperplaneAlgHom_liftAlgHom (c : Fin (n + 2) → k) (j : Fin (n + 2))
    (p : MvPolynomial (Fin (n + 1)) k) : hyperplaneAlgHom c j (liftAlgHom j p) = p :=
  congrArg (fun f : MvPolynomial (Fin (n + 1)) k →ₐ[k] _ => f p)
    (hyperplaneAlgHom_comp_liftAlgHom c j)

end Field

/- The total-degree grading is deliberately not a global instance in Mathlib. -/
attribute [local instance] MvPolynomial.gradedAlgebra

/-- A homogeneous element of degree `d` in the ideal generated by a linear form `L` is `L`
times a homogeneous element of degree `d - 1`. -/
lemma exists_isHomogeneous_of_mem_span_of_isHomogeneous {m : ℕ}
    {L p : MvPolynomial (Fin (m + 1)) k} (hL : L.IsHomogeneous 1) {d : ℕ}
    (hp : p.IsHomogeneous d) (hmem : p ∈ Ideal.span {L}) :
    ∃ h : MvPolynomial (Fin (m + 1)) k,
      h.IsHomogeneous (d - 1) ∧ p = L * h ∧ (d = 0 → p = 0) := by
  classical
  obtain ⟨h, hh⟩ := Ideal.mem_span_singleton.mp hmem
  have hpd : ((DirectSum.decompose (homogeneousSubmodule (Fin (m + 1)) k) p d :
      homogeneousSubmodule (Fin (m + 1)) k d) : MvPolynomial (Fin (m + 1)) k) = p :=
    DirectSum.decompose_of_mem_same _ hp
  have hLmem : L ∈ homogeneousSubmodule (Fin (m + 1)) k 1 := hL
  rcases Nat.eq_zero_or_pos d with rfl | hd1
  · have hzero : ((DirectSum.decompose (homogeneousSubmodule (Fin (m + 1)) k) (L * h) 0 :
        homogeneousSubmodule (Fin (m + 1)) k 0) : MvPolynomial (Fin (m + 1)) k) = 0 :=
      DirectSum.coe_decompose_mul_of_left_mem_of_not_le
        (homogeneousSubmodule (Fin (m + 1)) k) hLmem (by omega)
    have hp0 : p = 0 := by rw [← hpd, hh, hzero]
    exact ⟨0, isHomogeneous_zero _ _ _, by rw [mul_zero, hp0], fun _ => hp0⟩
  · have hkey : ((DirectSum.decompose (homogeneousSubmodule (Fin (m + 1)) k) (L * h) d :
        homogeneousSubmodule (Fin (m + 1)) k d) : MvPolynomial (Fin (m + 1)) k)
        = L * ((DirectSum.decompose (homogeneousSubmodule (Fin (m + 1)) k) h (d - 1) :
          homogeneousSubmodule (Fin (m + 1)) k (d - 1)) : MvPolynomial (Fin (m + 1)) k) :=
      DirectSum.coe_decompose_mul_of_left_mem_of_le
        (homogeneousSubmodule (Fin (m + 1)) k) hLmem (by omega)
    refine ⟨_, (DirectSum.decompose (homogeneousSubmodule (Fin (m + 1)) k) h (d - 1)).2, ?_,
      fun hd0 => absurd hd0 (by omega)⟩
    rw [← hpd, hh, hkey]

end MvPolynomial


