module

public import StacksAndModuli.«Section4.4-Equivalence-Relations».«part4.4.3-quotient-stacks-of-groupoids»
public import StacksAndModuli.API.PresheafSheafificationHom

/-!
# The pointwise quotient of a presheaf groupoid is a coequalizer

For a presheaf groupoid `R ⇉ U`, its quotient presheaf was defined pointwise as the
quotient of `U(T)` by the equivalence relation generated by `R(T)`.  This file records
the corresponding categorical universal property: the projection
`U ⟶ quotientPresheaf` is a coequalizer of the source and target maps.

This comparison is useful when a quotient presheaf was originally introduced with
Mathlib's chosen `coequalizer` object.
-/

@[expose] public section

-- These files were written when Lean's backward-compat defeq options were on by default.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory CategoryTheory.Limits

universe u

namespace AlgebraicGeometry.PresheafGroupoid

variable (G : PresheafGroupoid.{u})

/-- The canonical cofork from the source and target of a presheaf groupoid to its
pointwise quotient presheaf. -/
abbrev quotientPresheafCofork : Cofork G.s G.t :=
  Cofork.ofπ G.toQuotientPresheaf (by
    ext T r
    exact G.toQuotientPresheaf_app_eq ⟨r, rfl, rfl⟩)

/-- The pointwise quotient presheaf of a presheaf groupoid is the coequalizer of its
source and target natural transformations. -/
def quotientPresheafCoforkIsColimit : IsColimit G.quotientPresheafCofork :=
  Cofork.IsColimit.mk _
    (fun s ↦
      { app := fun T ↦ ↾(Quot.lift (s.π.app T)
          (fun (a b : G.U.obj T) (h : G.quotientRel T a b) ↦ by
          obtain ⟨r, hs, ht⟩ := h
          rw [← hs, ← ht]
          exact ConcreteCategory.congr_hom (NatTrans.congr_app s.condition T) r))
        naturality := fun {T T'} f ↦ by
          ext x
          induction x using Quot.ind with
          | mk x => exact s.π.naturality_apply f x })
    (fun _ ↦ by ext T x; rfl)
    (fun _ m hm ↦ by
      ext T x
      induction x using Quot.ind with
      | mk x =>
          exact ConcreteCategory.congr_hom (NatTrans.congr_app hm T) x)

/-- The canonical isomorphism from the pointwise quotient presheaf of a groupoid to
Mathlib's chosen coequalizer of its source and target. -/
noncomputable def quotientPresheafIsoCoequalizer :
    G.quotientPresheaf ≅ coequalizer G.s G.t :=
  IsColimit.coconePointUniqueUpToIso G.quotientPresheafCoforkIsColimit
    (colimit.isColimit (parallelPair G.s G.t))

@[reassoc]
lemma toQuotientPresheaf_comp_quotientPresheafIsoCoequalizer_hom :
    G.toQuotientPresheaf ≫ G.quotientPresheafIsoCoequalizer.hom = coequalizer.π G.s G.t :=
  IsColimit.comp_coconePointUniqueUpToIso_hom G.quotientPresheafCoforkIsColimit
    (colimit.isColimit (parallelPair G.s G.t)) WalkingParallelPair.one

/-- A sheafification of the chosen categorical coequalizer of a presheaf groupoid is a
quotient sheaf of the groupoid's pointwise quotient presheaf. -/
theorem isQuotientSheaf_of_isSheafificationHom_coequalizer
    {X : AlgebraicGeometry.Scheme.{u}ᵒᵖ ⥤ Type u}
    (η : coequalizer G.s G.t ⟶ X)
    (hη : Presheaf.IsSheafificationHom AlgebraicGeometry.Scheme.etaleTopology η) :
    G.IsQuotientSheaf X (G.quotientPresheafIsoCoequalizer.hom ≫ η) := by
  have h := hη.iso_hom_comp AlgebraicGeometry.Scheme.etaleTopology
    G.quotientPresheafIsoCoequalizer
  exact ⟨h.1, h.2.1, h.2.2⟩

end AlgebraicGeometry.PresheafGroupoid
