module

public import StacksAndModuli.API.GlobalPrincipalBundleAffine
public import StacksAndModuli.API.GlobalPrincipalBundleFpqcProperties
public import StacksAndModuli.API.GlobalPrincipalBundleUnderlyingArrowGluing
public import StacksAndModuli.API.ClassifyingPrestackFpqcMorphisms
public import StacksAndModuli.API.MorphismsGlueCocone
public import StacksAndModuli.API.RepresentableActionQuotient
public import Mathlib.CategoryTheory.Sites.EffectiveEpimorphic

/-!
# Induction of principal bundles

This file develops the descent datum for extension of structure group.  Given a
homomorphism `H ⟶ G` and a principal `H`-bundle `P ⟶ T`, the bundle becomes
trivial over the fpqc cover `P ⟶ T`.  The induced `G`-bundle is therefore locally
the trivial bundle, with transition functions obtained by applying `H ⟶ G` to
the torsor-coordinate differences between local sections.

The raw transition functor constructed here is independent of effective affine
descent.  A later section packages the descended affine arrow as the contracted
product `G ×ᴴ P`.
-/

@[expose] public section

set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory CategoryTheory.Functor CategoryTheory.Limits
  CategoryTheory.MonoidalCategory CategoryTheory.CartesianMonoidalCategory
  CategoryTheory.MonObj
open scoped CategoryTheory.Obj CategoryTheory.ModObj

universe u

namespace AlgebraicGeometry.Scheme

namespace GlobalPrincipalBundle

variable {S : Scheme.{u}} {H T : Over S} [GrpObj H]

/-- Torsor-coordinate differences are compatible with precomposition. -/
lemma torsorDifference_precomp (B : GlobalPrincipalBundle H T)
    {Z W : Over S} (a : W ⟶ Z) (f g : Z ⟶ B.P)
    (h : f ≫ B.p = g ≫ B.p) :
    B.torsorDifference (a ≫ f) (a ≫ g)
      (by simpa only [Category.assoc] using congrArg (fun q ↦ a ≫ q) h) =
      a ≫ B.torsorDifference f g h := by
  apply B.torsorDifference_eq
  rw [← ModObj.comp_smul, B.torsorDifference_smul]

/-- The torsor-coordinate difference from a point to itself is the identity. -/
lemma torsorDifference_self (B : GlobalPrincipalBundle H T)
    {Z : Over S} (f : Z ⟶ B.P) :
    B.torsorDifference f f rfl = 1 := by
  apply B.torsorDifference_eq
  simp

/-- Torsor-coordinate differences satisfy the usual cocycle identity. -/
lemma torsorDifference_mul (B : GlobalPrincipalBundle H T)
    {Z : Over S} (f g k : Z ⟶ B.P)
    (hfg : f ≫ B.p = g ≫ B.p) (hgk : g ≫ B.p = k ≫ B.p) :
    B.torsorDifference f g hfg * B.torsorDifference g k hgk =
      B.torsorDifference f k (hfg.trans hgk) := by
  symm
  apply B.torsorDifference_eq
  rw [mul_smul, B.torsorDifference_smul, B.torsorDifference_smul]

/-- Reversing two torsor points inverts their coordinate difference. -/
lemma torsorDifference_symm (B : GlobalPrincipalBundle H T)
    {Z : Over S} (f g : Z ⟶ B.P)
    (h : f ≫ B.p = g ≫ B.p) :
    B.torsorDifference f g h =
      (B.torsorDifference g f h.symm)⁻¹ := by
  rw [eq_inv_iff_mul_eq_one]
  rw [B.torsorDifference_mul f g f h h.symm]
  exact B.torsorDifference_self f

/-- An equivariant map between torsors preserves torsor-coordinate
differences. -/
lemma torsorDifference_map {T' : Over S} (B : GlobalPrincipalBundle H T)
    (B' : GlobalPrincipalBundle H T') {Z : Over S} (f g : Z ⟶ B.P)
    (h : f ≫ B.p = g ≫ B.p) (q : B.P ⟶ B'.P) [IsModHom H q]
    (h' : (f ≫ q) ≫ B'.p = (g ≫ q) ≫ B'.p) :
    B'.torsorDifference (f ≫ q) (g ≫ q) h' =
      B.torsorDifference f g h := by
  apply B'.torsorDifference_eq
  rw [← IsModHom.map_smul, B.torsorDifference_smul]

variable {G : Over S} [GrpObj G]

/-- The point of a trivial principal bundle with prescribed group coordinate
and identity base coordinate. -/
noncomputable def trivialPoint [Smooth G.hom] [IsAffineHom G.hom]
    {Z : Over S} (m : Z ⟶ G) : Z ⟶ (trivial G Z).P :=
  Limits.pullback.lift m (𝟙 Z) (by apply toUnit_unique)

@[reassoc (attr := simp)]
lemma trivialPoint_fst [Smooth G.hom] [IsAffineHom G.hom]
    {Z : Over S} (m : Z ⟶ G) :
    trivialPoint (G := G) m ≫ trivialFst G Z = m :=
  Limits.pullback.lift_fst _ _ _

@[reassoc (attr := simp)]
lemma trivialPoint_snd [Smooth G.hom] [IsAffineHom G.hom]
    {Z : Over S} (m : Z ⟶ G) :
    trivialPoint (G := G) m ≫ trivialSnd G Z = 𝟙 Z :=
  Limits.pullback.lift_snd _ _ _

end GlobalPrincipalBundle

namespace PrincipalBundleInduction

variable {S : Scheme.{u}} {H G T : Over S} [GrpObj H] [GrpObj G]
  (phi : H ⟶ G) [IsMonHom phi]
  (B : GlobalPrincipalBundle H T)

/-- The sieve of morphisms into `T` which factor through the bundle projection
`P ⟶ T`. -/
def coverSieve : Sieve T := Sieve.generateSingleton B.p

/-- The sieve generated by a principal-bundle projection is fpqc-covering. -/
lemma coverSieve_mem :
    coverSieve B ∈ Scheme.fpqcTopology.over S T := by
  have hshape : coverSieve B =
      Sieve.ofArrows (fun _ : PUnit.{1} ↦ B.P) (fun _ ↦ B.p) := by
    rw [coverSieve, ← Sieve.generateSingleton_eq]
    congr 1
    exact (Presieve.ofArrows_pUnit (f := B.p)).symm
  rw [hshape, Scheme.fpqcTopology.mem_over_iff,
    Sieve.overEquiv_ofArrows]
  change Sieve.generate
    (Presieve.ofArrows (fun _ : PUnit.{1} ↦ B.P.left)
      (fun _ ↦ B.p.left)) ∈ Scheme.fpqcTopology T.left
  rw [Presieve.ofArrows_pUnit]
  exact Precoverage.generate_mem_toGrothendieck
    (Scheme.fppfPrecoverage_le_fpqcPrecoverage _
      B.p.left.singleton_mem_fppfPrecoverage)

/-- A chosen lift to `P` of an arrow in the sieve generated by `P ⟶ T`. -/
noncomputable def localSection (q : (coverSieve B).arrows.category) :
    q.obj.left ⟶ B.P :=
  q.property.choose

@[reassoc (attr := simp)]
lemma localSection_fac (q : (coverSieve B).arrows.category) :
    localSection B q ≫ B.p = q.obj.hom :=
  q.property.choose_spec

/-- The two local sections compared by a morphism in the covering sieve lie
over the same map to `T`. -/
lemma localSection_transition_eq
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    localSection B q ≫ B.p =
      (k.hom.left ≫ localSection B r) ≫ B.p := by
  rw [localSection_fac, Category.assoc, localSection_fac]
  exact k.hom.w.symm

/-- The `G`-valued transition function obtained from the torsor-coordinate
difference between two chosen local sections. -/
noncomputable def transitionGauge
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    q.obj.left ⟶ G :=
  B.torsorDifference (localSection B q)
    (k.hom.left ≫ localSection B r) (localSection_transition_eq B k) ≫ phi

/-- The transition function of an identity arrow is the identity. -/
lemma transitionGauge_id (q : (coverSieve B).arrows.category) :
    transitionGauge phi B (𝟙 q) = 1 := by
  dsimp [transitionGauge]
  let idq : q ⟶ q := 𝟙 q
  have hd : B.torsorDifference (localSection B q)
      (idq.hom.left ≫ localSection B q)
      (localSection_transition_eq B idq) = 1 := by
    apply B.torsorDifference_eq
    simp [idq]
  change B.torsorDifference (localSection B q)
      (idq.hom.left ≫ localSection B q)
      (localSection_transition_eq B idq) ≫ phi = 1
  rw [hd]
  exact MonObj.one_comp phi

/-- The transition functions obey the cocycle identity. -/
lemma transitionGauge_comp
    {q r t : (coverSieve B).arrows.category} (k : q ⟶ r) (l : r ⟶ t) :
    transitionGauge phi B k * (k.hom.left ≫ transitionGauge phi B l) =
      transitionGauge phi B (k ≫ l) := by
  dsimp [transitionGauge]
  let d₁ := B.torsorDifference (localSection B q)
    (k.hom.left ≫ localSection B r) (localSection_transition_eq B k)
  let d₂ := B.torsorDifference (localSection B r)
    (l.hom.left ≫ localSection B t) (localSection_transition_eq B l)
  let d₁₂ := B.torsorDifference (localSection B q)
    ((k ≫ l).hom.left ≫ localSection B t)
      (localSection_transition_eq B (k ≫ l))
  have hd : d₁ * (k.hom.left ≫ d₂) = d₁₂ := by
    symm
    apply B.torsorDifference_eq
    have hinner : (k.hom.left ≫ d₂) •
        ((k.hom.left ≫ l.hom.left) ≫ localSection B t) =
        k.hom.left ≫ localSection B r := by
      calc
        (k.hom.left ≫ d₂) •
            ((k.hom.left ≫ l.hom.left) ≫ localSection B t) =
            (k.hom.left ≫ d₂) •
              (k.hom.left ≫ (l.hom.left ≫ localSection B t)) := by
                rw [Category.assoc]
        _ = k.hom.left ≫
            (d₂ • (l.hom.left ≫ localSection B t)) :=
          (ModObj.comp_smul k.hom.left d₂
            (l.hom.left ≫ localSection B t)).symm
        _ = k.hom.left ≫ localSection B r := by
          rw [GlobalPrincipalBundle.torsorDifference_smul]
    calc
      (d₁ * (k.hom.left ≫ d₂)) •
          ((k.hom.left ≫ l.hom.left) ≫ localSection B t) =
          d₁ • ((k.hom.left ≫ d₂) •
            ((k.hom.left ≫ l.hom.left) ≫ localSection B t)) :=
        mul_smul d₁ (k.hom.left ≫ d₂) _
      _ = d₁ • (k.hom.left ≫ localSection B r) :=
        congrArg (fun z ↦ d₁ • z) hinner
      _ = localSection B q :=
        GlobalPrincipalBundle.torsorDifference_smul _ _ _ _
  calc
    (d₁ ≫ phi) * ((k.hom.left ≫ d₂) ≫ phi) =
        (d₁ * (k.hom.left ≫ d₂)) ≫ phi :=
      (MonObj.mul_comp d₁ (k.hom.left ≫ d₂) phi).symm
    _ = d₁₂ ≫ phi := congrArg (fun d ↦ d ≫ phi) hd

/-- The local object of the induced bundle is the trivial `G`-bundle. -/
noncomputable abbrev localObj [Smooth G.hom] [IsAffineHom G.hom]
    (q : (coverSieve B).arrows.category) : ClassifyingObj G :=
  { base := q.obj.left
    bundle := GlobalPrincipalBundle.trivial G q.obj.left }

/-- The transition morphism between the local trivial `G`-bundles. -/
noncomputable def localHom [Smooth G.hom] [IsAffineHom G.hom]
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    localObj (G := G) B q ⟶ localObj (G := G) B r where
  base := k.hom.left
  total :=
    GlobalPrincipalBundle.trivialRightTranslate (G := G)
        (transitionGauge phi B k) ≫
      GlobalPrincipalBundle.trivialBaseMap (G := G) k.hom.left
  isPullback := by
    have htranslate : IsPullback
        (GlobalPrincipalBundle.trivialRightTranslate (G := G)
          (transitionGauge phi B k))
        (GlobalPrincipalBundle.trivialSnd G q.obj.left)
        (GlobalPrincipalBundle.trivialSnd G q.obj.left) (𝟙 q.obj.left) := by
      apply IsPullback.of_horiz_isIso
      exact ⟨by simp⟩
    exact htranslate.paste_horiz
      (GlobalPrincipalBundle.trivialBaseMap_isPullback (G := G) k.hom.left)
  equivariant := by
    letI := GlobalPrincipalBundle.trivialRightTranslate_equivariant
      (G := G) (transitionGauge phi B k)
    letI := GlobalPrincipalBundle.trivialBaseMap_equivariant
      (G := G) k.hom.left
    infer_instance

@[simp]
lemma localHom_base [Smooth G.hom] [IsAffineHom G.hom]
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    (localHom phi B k).base = k.hom.left := rfl

@[simp]
lemma localHom_total [Smooth G.hom] [IsAffineHom G.hom]
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    (localHom phi B k).total =
      GlobalPrincipalBundle.trivialRightTranslate (G := G)
          (transitionGauge phi B k) ≫
        GlobalPrincipalBundle.trivialBaseMap (G := G) k.hom.left := rfl

/-- The local trivial bundles and their transition functions form a functor on
the covering sieve. -/
noncomputable def localFunctor [Smooth G.hom] [IsAffineHom G.hom] :
    (coverSieve B).arrows.category ⥤ ClassifyingObj G where
  obj := localObj (G := G) B
  map := localHom phi B
  map_id q := by
    apply ClassifyingHom.ext
    · rfl
    · change
        GlobalPrincipalBundle.trivialRightTranslate (G := G)
            (transitionGauge phi B (𝟙 q)) ≫
          GlobalPrincipalBundle.trivialBaseMap (G := G) (𝟙 q.obj.left) = 𝟙 _
      rw [transitionGauge_id, GlobalPrincipalBundle.trivialRightTranslate_one,
        GlobalPrincipalBundle.trivialBaseMap_id, Category.id_comp]
  map_comp k l := by
    apply ClassifyingHom.ext
    · rfl
    · change
        GlobalPrincipalBundle.trivialRightTranslate (G := G)
            (transitionGauge phi B (k ≫ l)) ≫
          GlobalPrincipalBundle.trivialBaseMap (G := G)
            (k.hom.left ≫ l.hom.left) =
        (GlobalPrincipalBundle.trivialRightTranslate (G := G)
            (transitionGauge phi B k) ≫
          GlobalPrincipalBundle.trivialBaseMap (G := G) k.hom.left) ≫
        (GlobalPrincipalBundle.trivialRightTranslate (G := G)
            (transitionGauge phi B l) ≫
          GlobalPrincipalBundle.trivialBaseMap (G := G) l.hom.left)
      symm
      slice_lhs 2 3 =>
        rw [GlobalPrincipalBundle.trivialBaseMap_comp_rightTranslate]
      slice_lhs 1 2 =>
        rw [GlobalPrincipalBundle.trivialRightTranslate_comp]
      slice_lhs 2 3 =>
        rw [GlobalPrincipalBundle.trivialBaseMap_comp]
      rw [transitionGauge_comp]

@[simp]
lemma localFunctor_obj_base [Smooth G.hom] [IsAffineHom G.hom]
    (q : (coverSieve B).arrows.category) :
    ((localFunctor phi B).obj q).base = q.obj.left := rfl

/-- Every transition morphism of the local functor is cartesian over its map
of bases. -/
lemma localFunctor_map_isHomLift [Smooth G.hom] [IsAffineHom G.hom]
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    IsHomLift (classifyingPrestack G).p k.hom.left
      ((localFunctor phi B).map k) := by
  exact Functor.IsHomLift.map (p := (classifyingPrestack G).p)
    ((localFunctor phi B).map k)

/-- The cartesian-arrow diagram underlying the local trivial `G`-bundles. -/
noncomputable abbrev underlyingArrowFunctor [Smooth G.hom]
    [IsAffineHom G.hom] :
    (coverSieve B).arrows.category ⥤
      CategoryTheory.ArrowCartesian Scheme.{u} :=
  ClassifyingObj.underlyingArrowFunctor (localFunctor phi B)

@[simp]
lemma underlyingArrowFunctor_obj_hom [Smooth G.hom] [IsAffineHom G.hom]
    (q : (coverSieve B).arrows.category) :
    ((underlyingArrowFunctor phi B).obj q : Arrow Scheme.{u}).hom =
      ((localFunctor phi B).obj q).bundle.p.left := rfl

/-- Every object in the underlying descent diagram is affine over its local
base. -/
lemma underlyingArrowFunctor_obj_isAffine [Smooth G.hom]
    [IsAffineHom G.hom] (q : (coverSieve B).arrows.category) :
    IsAffineHom ((underlyingArrowFunctor phi B).obj q : Arrow Scheme.{u}).hom := by
  change IsAffineHom
    (((GlobalPrincipalBundle.universal G).pullback
      (toUnit q.obj.left)).p.left)
  apply MorphismProperty.IsStableUnderBaseChange.of_isPullback
    ((IsPullback.of_hasPullback (GlobalPrincipalBundle.universal G).p
      (toUnit q.obj.left)).map (Over.forget S))
  change IsAffineHom G.hom
  infer_instance

/-! ### Descending the local datum from an affine-arrow gluing -/

/-- A gluing of the cartesian scheme-arrow diagram underlying the local
extension-of-structure-group datum.  This is the precise unstructured input
needed by principal-bundle descent. -/
structure ArrowGluing [Smooth G.hom] [IsAffineHom G.hom] where
  /-- The descended arrow of schemes. -/
  obj : Arrow Scheme.{u}
  /-- Its target is the base of the original principal bundle. -/
  obj_base : (CategoryTheory.arrowCartesian Scheme.{u}).p.obj obj = T.left
  /-- The cartesian local comparison maps. -/
  comparison : ∀ q : (coverSieve B).arrows.category,
    (underlyingArrowFunctor phi B).obj q ⟶ obj
  /-- Each comparison lies over the corresponding covering arrow. -/
  comparison_isHomLift : ∀ q : (coverSieve B).arrows.category,
    IsHomLift (CategoryTheory.arrowCartesian Scheme.{u}).p q.obj.hom.left
      (comparison q)
  /-- The comparisons form a cocone. -/
  comparison_naturality : ∀ {q r : (coverSieve B).arrows.category}
    (k : q ⟶ r),
    (underlyingArrowFunctor phi B).map k ≫ comparison r = comparison q

/-- A descended principal `G`-bundle together with the cartesian comparisons
from the local trivial bundles used to construct it. -/
structure Cocone [Smooth G.hom] [IsAffineHom G.hom] where
  /-- The induced principal `G`-bundle over the original base. -/
  bundle : GlobalPrincipalBundle G T
  /-- Local comparison from the trivial `G`-bundle. -/
  comparison : ∀ q : (coverSieve B).arrows.category,
    (localFunctor phi B).obj q ⟶ (⟨T, bundle⟩ : ClassifyingObj G)
  /-- Each local comparison is cartesian over the covering arrow. -/
  comparison_isHomLift : ∀ q : (coverSieve B).arrows.category,
    IsHomLift (classifyingPrestack G).p q.obj.hom (comparison q)
  /-- The local comparisons form a cocone. -/
  comparison_naturality : ∀ {q r : (coverSieve B).arrows.category}
    (k : q ⟶ r), (localFunctor phi B).map k ≫ comparison r = comparison q

/-- The induced bundle viewed as an object of the classifying prestack. -/
def Cocone.obj [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) : ClassifyingObj G := ⟨T, C.bundle⟩

@[simp]
lemma Cocone.obj_base [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) : C.obj.base = T := rfl

/-- Effective affine-arrow descent of the local trivial bundles produces the
principal `G`-bundle induced from `B` along `phi`. -/
theorem exists_cocone_of_arrowGluing [Smooth G.hom] [IsAffineHom G.hom]
    (A : ArrowGluing phi B) : Nonempty (Cocone phi B) := by
  let U : ClassifyingObj.UnderlyingGluing
      (localFunctor phi B) (localFunctor_obj_base phi B)
      (fun {_ _} k ↦ localFunctor_map_isHomLift phi B k) :=
    ClassifyingObj.underlyingGluingOfArrowGluing
      (localFunctor phi B) (localFunctor_obj_base phi B)
      (fun {_ _} k ↦ localFunctor_map_isHomLift phi B k)
      A.obj A.obj_base A.comparison A.comparison_isHomLift
      A.comparison_naturality
  let hR := coverSieve_mem B
  let hflat := U.descended_flat hR
  let hsurjective := U.descended_surjective hR
  let hlfp := U.descended_locallyOfFinitePresentation hR
  let hsmooth := U.descended_smooth hR
  let htorsor := U.descended_torsor_isIso hR
  exact ⟨
    { bundle := (U.descendedObj hR hflat hsurjective hlfp hsmooth htorsor).bundle
      comparison := U.comparison hR hflat hsurjective hlfp hsmooth htorsor
      comparison_isHomLift :=
        U.comparison_isHomLift hR hflat hsurjective hlfp hsmooth htorsor
      comparison_naturality :=
        U.comparison_naturality hR hflat hsurjective hlfp hsmooth htorsor }⟩

/-! ### Functoriality of the local induction datum -/

variable {T' : Over S} (B' : GlobalPrincipalBundle H T')

/-- A morphism of principal `H`-bundles sends each arrow trivializing the
source bundle to an arrow trivializing the target bundle. -/
noncomputable abbrev mapCoverObj
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    (coverSieve B').arrows.category :=
  (coverSieve B').arrows.categoryMk (q.obj.hom ≫ f.base) ⟨
    localSection B q ≫ f.total, by
      rw [Category.assoc, f.isPullback.w, ← Category.assoc,
        localSection_fac]⟩

/-- The functor on covering-arrow categories induced by a morphism of
principal `H`-bundles. -/
noncomputable abbrev mapCoverFunctor
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩) :
    (coverSieve B).arrows.category ⥤ (coverSieve B').arrows.category where
  obj := mapCoverObj B B' f
  map {q r} k := ObjectProperty.homMk (Over.homMk k.hom.left (by
    change k.hom.left ≫ (r.obj.hom ≫ f.base) =
      q.obj.hom ≫ f.base
    rw [← Category.assoc, k.hom.w]))
  map_id q := by
    apply ObjectProperty.hom_ext
    apply Over.OverMorphism.ext
    rfl
  map_comp k l := by
    apply ObjectProperty.hom_ext
    apply Over.OverMorphism.ext
    rfl

@[simp]
lemma mapCoverFunctor_obj_left
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    ((mapCoverFunctor B B' f).obj q).obj.left = q.obj.left := rfl

@[simp]
lemma mapCoverFunctor_obj_hom
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    ((mapCoverFunctor B B' f).obj q).obj.hom = q.obj.hom ≫ f.base := rfl

@[simp]
lemma mapCoverFunctor_map_left
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    ((mapCoverFunctor B B' f).map k).hom.left = k.hom.left := rfl

/-- The chosen target section differs from the image of the chosen source
section by a unique `H`-valued gauge. -/
noncomputable def mappedLocalSection
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) : q.obj.left ⟶ B'.P :=
  eqToHom (mapCoverFunctor_obj_left B B' f q).symm ≫
    localSection B' ((mapCoverFunctor B B' f).obj q)

@[reassoc (attr := simp)]
lemma mappedLocalSection_fac
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    mappedLocalSection B B' f q ≫ B'.p = q.obj.hom ≫ f.base := by
  dsimp only [mappedLocalSection]
  rw [Category.assoc, localSection_fac]
  simp

noncomputable def mapSectionGauge
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) : q.obj.left ⟶ H :=
  B'.torsorDifference
    (mappedLocalSection B B' f q)
    (localSection B q ≫ f.total) (by
      rw [mappedLocalSection_fac, Category.assoc, f.isPullback.w,
        ← Category.assoc, localSection_fac])

/-- Coordinate-change identity for a morphism of torsors. -/
lemma mapSectionGauge_cocycle
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    mapSectionGauge B B' f q *
        B.torsorDifference (localSection B q)
          (k.hom.left ≫ localSection B r)
          (localSection_transition_eq B k) =
      B'.torsorDifference
          (mappedLocalSection B B' f q)
          (k.hom.left ≫
            mappedLocalSection B B' f r)
          (by
            rw [mappedLocalSection_fac, Category.assoc,
              mappedLocalSection_fac]
            simpa only [Category.assoc] using
              congrArg (fun z ↦ z ≫ f.base) k.hom.w.symm) *
        (k.hom.left ≫ mapSectionGauge B B' f r) := by
  let sq := localSection B q
  let sr := localSection B r
  let tq := mappedLocalSection B B' f q
  let tr := mappedLocalSection B B' f r
  let a := B.torsorDifference sq (k.hom.left ≫ sr)
    (localSection_transition_eq B k)
  let c := B'.torsorDifference tq (sq ≫ f.total) (by
    rw [mappedLocalSection_fac, Category.assoc, f.isPullback.w,
      ← Category.assoc, localSection_fac])
  let d := B'.torsorDifference tq (k.hom.left ≫ tr)
    (by
      rw [mappedLocalSection_fac, Category.assoc, mappedLocalSection_fac]
      simpa only [Category.assoc] using
        congrArg (fun z ↦ z ≫ f.base) k.hom.w.symm)
  let b := B'.torsorDifference tr (sr ≫ f.total) (by
    rw [mappedLocalSection_fac, Category.assoc, f.isPullback.w,
      ← Category.assoc, localSection_fac])
  letI : IsModHom H f.total := f.equivariant
  have hmap : (sq ≫ f.total) ≫ B'.p =
      ((k.hom.left ≫ sr) ≫ f.total) ≫ B'.p := by
    calc
      (sq ≫ f.total) ≫ B'.p = (sq ≫ B.p) ≫ f.base := by
        simp only [Category.assoc, f.isPullback.w]
      _ = ((k.hom.left ≫ sr) ≫ B.p) ≫ f.base := by
        rw [localSection_transition_eq B k]
      _ = ((k.hom.left ≫ sr) ≫ f.total) ≫ B'.p := by
        simp only [Category.assoc, f.isPullback.w]
  have ha : B'.torsorDifference (sq ≫ f.total)
      (k.hom.left ≫ (sr ≫ f.total)) (by
        calc
          (sq ≫ f.total) ≫ B'.p =
              (sq ≫ B.p) ≫ f.base := by
                simp only [Category.assoc, f.isPullback.w]
          _ = ((k.hom.left ≫ sr) ≫ B.p) ≫ f.base := by
                rw [localSection_transition_eq B k]
          _ = (k.hom.left ≫ (sr ≫ f.total)) ≫ B'.p := by
                simp only [Category.assoc, f.isPullback.w]) = a := by
    simpa only [Category.assoc] using
      B.torsorDifference_map B' sq (k.hom.left ≫ sr)
        (localSection_transition_eq B k) f.total hmap
  have hbr : tr ≫ B'.p = (sr ≫ f.total) ≫ B'.p := by
    rw [mappedLocalSection_fac, Category.assoc, f.isPullback.w,
      ← Category.assoc, localSection_fac]
  have hb : k.hom.left ≫ b =
      B'.torsorDifference (k.hom.left ≫ tr)
        (k.hom.left ≫ (sr ≫ f.total)) (by
          simpa only [Category.assoc] using
            congrArg (fun z ↦ k.hom.left ≫ z) hbr) := by
    symm
    exact B'.torsorDifference_precomp k.hom.left tr (sr ≫ f.total) hbr
  change c * a = d * (k.hom.left ≫ b)
  rw [← ha, hb]
  rw [B'.torsorDifference_mul, B'.torsorDifference_mul]

/-- The local map between the two trivial induced `G`-bundles attached to a
morphism of `H`-bundles. -/
noncomputable def mapLocalHom [Smooth G.hom] [IsAffineHom G.hom]
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    (localFunctor phi B).obj q ⟶
      (localFunctor phi B').obj ((mapCoverFunctor B B' f).obj q) where
  base := 𝟙 q.obj.left
  total := GlobalPrincipalBundle.trivialRightTranslate (G := G)
    ((mapSectionGauge B B' f q ≫ phi)⁻¹)
  isPullback := by
    change IsPullback
      (GlobalPrincipalBundle.trivialRightTranslate (G := G)
        ((mapSectionGauge B B' f q ≫ phi)⁻¹))
      (GlobalPrincipalBundle.trivialSnd G q.obj.left)
      (GlobalPrincipalBundle.trivialSnd G q.obj.left) (𝟙 q.obj.left)
    exact IsPullback.of_horiz_isIso ⟨by simp⟩
  equivariant :=
    GlobalPrincipalBundle.trivialRightTranslate_equivariant
      ((mapSectionGauge B B' f q ≫ phi)⁻¹)

@[simp]
lemma mapLocalHom_base [Smooth G.hom] [IsAffineHom G.hom]
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    (mapLocalHom phi B B' f q).base = 𝟙 q.obj.left := rfl

/-- After reindexing along `mapCoverFunctor`, the target transition gauge is
the coordinate difference between the normalized chosen sections. -/
lemma transitionGauge_mapCover
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    transitionGauge phi B' ((mapCoverFunctor B B' f).map k) =
      B'.torsorDifference (mappedLocalSection B B' f q)
        (k.hom.left ≫ mappedLocalSection B B' f r) (by
          rw [mappedLocalSection_fac, Category.assoc,
            mappedLocalSection_fac]
          simpa only [Category.assoc] using
            congrArg (fun z ↦ z ≫ f.base) k.hom.w.symm) ≫ phi := by
  rfl

/-- The local maps are natural with respect to the transition functors. -/
lemma mapLocalHom_naturality [Smooth G.hom] [IsAffineHom G.hom]
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    (localFunctor phi B).map k ≫
      mapLocalHom phi B B' f r =
      mapLocalHom phi B B' f q ≫
        (localFunctor phi B').map ((mapCoverFunctor B B' f).map k) := by
  apply ClassifyingHom.ext
  · change k.hom.left ≫ 𝟙 _ = 𝟙 _ ≫ k.hom.left
    simp
  · change
      (GlobalPrincipalBundle.trivialRightTranslate (G := G)
          (transitionGauge phi B k) ≫
        GlobalPrincipalBundle.trivialBaseMap (G := G) k.hom.left) ≫
          GlobalPrincipalBundle.trivialRightTranslate (G := G)
            ((mapSectionGauge B B' f r ≫ phi)⁻¹) =
      GlobalPrincipalBundle.trivialRightTranslate (G := G)
          ((mapSectionGauge B B' f q ≫ phi)⁻¹) ≫
        (GlobalPrincipalBundle.trivialRightTranslate (G := G)
            (transitionGauge phi B'
              ((mapCoverFunctor B B' f).map k)) ≫
          GlobalPrincipalBundle.trivialBaseMap (G := G) k.hom.left)
    rw [transitionGauge_mapCover phi B B' f k]
    slice_lhs 2 3 =>
      rw [GlobalPrincipalBundle.trivialBaseMap_comp_rightTranslate]
    slice_lhs 1 2 =>
      rw [GlobalPrincipalBundle.trivialRightTranslate_comp]
    slice_rhs 1 2 =>
      rw [GlobalPrincipalBundle.trivialRightTranslate_comp]
    have hgauge :
        transitionGauge phi B k *
            (k.hom.left ≫ (mapSectionGauge B B' f r ≫ phi)⁻¹) =
          (mapSectionGauge B B' f q ≫ phi)⁻¹ *
            (B'.torsorDifference (mappedLocalSection B B' f q)
              (k.hom.left ≫ mappedLocalSection B B' f r) (by
                rw [mappedLocalSection_fac, Category.assoc,
                  mappedLocalSection_fac]
                simpa only [Category.assoc] using
                  congrArg (fun z ↦ z ≫ f.base) k.hom.w.symm) ≫ phi) := by
      dsimp only [transitionGauge]
      have hkb : k.hom.left ≫ (mapSectionGauge B B' f r ≫ phi)⁻¹ =
          (k.hom.left ≫ mapSectionGauge B B' f r)⁻¹ ≫ phi := by
        rw [GrpObj.comp_inv, GrpObj.inv_comp]
        simp only [Category.assoc]
      have hcphi : (mapSectionGauge B B' f q ≫ phi)⁻¹ =
          (mapSectionGauge B B' f q)⁻¹ ≫ phi :=
        (GrpObj.inv_comp _ _).symm
      rw [hkb, hcphi]
      rw [← MonObj.mul_comp, ← MonObj.mul_comp]
      congr 1
      have hc := mapSectionGauge_cocycle B B' f k
      rw [mul_inv_eq_iff_eq_mul, _root_.mul_assoc,
        eq_inv_mul_iff_mul_eq]
      exact hc
    rw [hgauge]

/-! ### Local cocones defining the induced morphism -/

/-- Given descended induced bundles for the source and target, the local map
attached to a morphism of `H`-bundles followed by the target comparison is the
local datum for its induced morphism. -/
noncomputable def mapCoconeLeg [Smooth G.hom] [IsAffineHom G.hom]
    (C' : Cocone phi B')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    (localFunctor phi B).obj q ⟶ C'.obj :=
  mapLocalHom phi B B' f q ≫
    C'.comparison ((mapCoverFunctor B B' f).obj q)

/-- Each local leg defining the induced morphism lies over the composite of
the covering arrow and the original map of bases. -/
lemma mapCoconeLeg_isHomLift [Smooth G.hom] [IsAffineHom G.hom]
    (C' : Cocone phi B')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    IsHomLift (classifyingPrestack G).p (q.obj.hom ≫ f.base)
      (mapCoconeLeg phi B B' C' f q) := by
  letI h₁ : IsHomLift (classifyingPrestack G).p (𝟙 q.obj.left)
      (mapLocalHom phi B B' f q) :=
    Functor.IsHomLift.map (p := (classifyingPrestack G).p)
      (mapLocalHom phi B B' f q)
  letI h₂ : IsHomLift (classifyingPrestack G).p
      (q.obj.hom ≫ f.base)
      (C'.comparison ((mapCoverFunctor B B' f).obj q)) :=
    by
      rw [← mapCoverFunctor_obj_hom B B' f q]
      exact C'.comparison_isHomLift
        ((mapCoverFunctor B B' f).obj q)
  change IsHomLift (classifyingPrestack G).p (q.obj.hom ≫ f.base)
    (mapLocalHom phi B B' f q ≫
      C'.comparison ((mapCoverFunctor B B' f).obj q))
  simpa using (inferInstance : IsHomLift (classifyingPrestack G).p
    ((𝟙 q.obj.left) ≫ (q.obj.hom ≫ f.base))
    (mapLocalHom phi B B' f q ≫
      C'.comparison ((mapCoverFunctor B B' f).obj q)))

/-- The local legs defining an induced morphism form a cocone over the source
transition functor. -/
lemma mapCoconeLeg_naturality [Smooth G.hom] [IsAffineHom G.hom]
    (C' : Cocone phi B')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    {q r : (coverSieve B).arrows.category} (k : q ⟶ r) :
    (localFunctor phi B).map k ≫ mapCoconeLeg phi B B' C' f r =
      mapCoconeLeg phi B B' C' f q := by
  change (localFunctor phi B).map k ≫
      (mapLocalHom phi B B' f r ≫
        C'.comparison ((mapCoverFunctor B B' f).obj r)) =
    mapLocalHom phi B B' f q ≫
      C'.comparison ((mapCoverFunctor B B' f).obj q)
  rw [← Category.assoc, mapLocalHom_naturality]
  rw [Category.assoc, C'.comparison_naturality]

/-! ### Identity coherence of the local induced maps -/

/-- The canonical comparison from a cover chart to its image under the
cover functor of the identity bundle morphism. -/
noncomputable def mapCoverIdHom
    (q : (coverSieve B).arrows.category) :
    q ⟶ (mapCoverFunctor B B (𝟙 (⟨T, B⟩ : ClassifyingObj H))).obj q :=
  ObjectProperty.homMk (Over.homMk (𝟙 q.obj.left) (by
    change q.obj.hom ≫ 𝟙 T = q.obj.hom
    simp))

@[simp]
lemma mapCoverIdHom_left
    (q : (coverSieve B).arrows.category) :
    (mapCoverIdHom B q).hom.left = 𝟙 q.obj.left := rfl

/-- The local map attached to the identity is the transition map to the
canonically reindexed chart. -/
lemma mapLocalHom_id_eq_localHom [Smooth G.hom] [IsAffineHom G.hom]
    (q : (coverSieve B).arrows.category) :
    mapLocalHom phi B B (𝟙 (⟨T, B⟩ : ClassifyingObj H)) q =
      localHom phi B (mapCoverIdHom B q) := by
  apply ClassifyingHom.ext
  · rfl
  · change GlobalPrincipalBundle.trivialRightTranslate (G := G)
        ((mapSectionGauge B B (𝟙 (⟨T, B⟩ : ClassifyingObj H)) q ≫ phi)⁻¹) =
      GlobalPrincipalBundle.trivialRightTranslate (G := G)
        (transitionGauge phi B (mapCoverIdHom B q)) ≫
          GlobalPrincipalBundle.trivialBaseMap (G := G) (𝟙 q.obj.left)
    rw [GlobalPrincipalBundle.trivialBaseMap_id, Category.comp_id]
    congr 1
    rw [← GrpObj.inv_comp]
    congr 1
    have hdiff := congrArg (fun d ↦ d⁻¹)
      (B.torsorDifference_symm
        (mappedLocalSection B B
          (𝟙 (⟨T, B⟩ : ClassifyingObj H)) q)
        (localSection B q ≫
          (show ClassifyingHom H _ _ from
            𝟙 (⟨T, B⟩ : ClassifyingObj H)).total)
        (by
          rw [mappedLocalSection_fac, Category.assoc]
          change q.obj.hom ≫ 𝟙 T =
            (localSection B q ≫ 𝟙 B.P) ≫ B.p
          simp [localSection_fac]))
    simp only [inv_inv] at hdiff
    change (mapSectionGauge B B
      (𝟙 (⟨T, B⟩ : ClassifyingObj H)) q)⁻¹ = _ at hdiff
    convert hdiff using 1
    congr 2

/-- The local map attached to the identity induces the identity after
comparison with the descended cocone. -/
lemma mapCoconeLeg_id [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) (q : (coverSieve B).arrows.category) :
    mapCoconeLeg phi B B C (𝟙 (⟨T, B⟩ : ClassifyingObj H)) q =
      C.comparison q := by
  rw [mapCoconeLeg, mapLocalHom_id_eq_localHom]
  exact C.comparison_naturality (mapCoverIdHom B q)

variable {T' T'' : Over S} (B' : GlobalPrincipalBundle H T')
  (B'' : GlobalPrincipalBundle H T'')

/-- The canonical associativity comparison between direct and iterated
reindexing of a cover chart. -/
noncomputable def mapCoverCompHom
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (q : (coverSieve B).arrows.category) :
    (mapCoverFunctor B B'' (f ≫ g)).obj q ⟶
      (mapCoverFunctor B' B'' g).obj
        ((mapCoverFunctor B B' f).obj q) :=
  ObjectProperty.homMk (Over.homMk (𝟙 q.obj.left) (by
    change 𝟙 q.obj.left ≫ ((q.obj.hom ≫ f.base) ≫ g.base) =
      q.obj.hom ≫ (f.base ≫ g.base)
    simp [Category.assoc]))

@[simp]
lemma mapCoverCompHom_left
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (q : (coverSieve B).arrows.category) :
    (mapCoverCompHom B B' B'' f g q).hom.left = 𝟙 q.obj.left := rfl

/-- The gauges comparing mapped local sections satisfy the composition
cocycle. -/
lemma mapSectionGauge_comp
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (q : (coverSieve B).arrows.category) :
    (eqToHom (mapCoverFunctor_obj_left B B'' (f ≫ g) q).symm ≫
      transitionGauge (H := H) (𝟙 H) B''
        (mapCoverCompHom B B' B'' f g q)) *
      (eqToHom (mapCoverFunctor_obj_left B B' f q).symm ≫
        mapSectionGauge B' B'' g ((mapCoverFunctor B B' f).obj q)) *
      mapSectionGauge B B' f q =
        mapSectionGauge B B'' (f ≫ g) q := by
  let q' := (mapCoverFunctor B B' f).obj q
  let s : q.obj.left ⟶ B.P := localSection B q
  let t : q.obj.left ⟶ B'.P := mappedLocalSection B B' f q
  let u : q.obj.left ⟶ B''.P :=
    eqToHom (mapCoverFunctor_obj_left B B' f q).symm ≫
      mappedLocalSection B' B'' g q'
  let v : q.obj.left ⟶ B''.P := mappedLocalSection B B'' (f ≫ g) q
  have hvu : v ≫ B''.p = u ≫ B''.p := by
    dsimp only [v, u]
    rw [Category.assoc, mappedLocalSection_fac, mappedLocalSection_fac]
    change q.obj.hom ≫ (f.base ≫ g.base) =
      eqToHom _ ≫ ((q.obj.hom ≫ f.base) ≫ g.base)
    simp [Category.assoc]
  have hut : u ≫ B''.p = (t ≫ g.total) ≫ B''.p := by
    dsimp only [u, t]
    rw [Category.assoc, mappedLocalSection_fac]
    rw [Category.assoc, g.isPullback.w]
    simp only [← Category.assoc]
    apply congrArg (fun z ↦ z ≫ g.base)
    change eqToHom _ ≫ (q.obj.hom ≫ f.base) =
      mappedLocalSection B B' f q ≫ B'.p
    rw [mappedLocalSection_fac]
    simp
  have hts : (t ≫ g.total) ≫ B''.p =
      ((s ≫ f.total) ≫ g.total) ≫ B''.p := by
    rw [Category.assoc, Category.assoc, g.isPullback.w]
    rw [← Category.assoc, ← Category.assoc]
    congr 1
    dsimp only [t, s]
    rw [mappedLocalSection_fac, Category.assoc, f.isPullback.w,
      ← Category.assoc, localSection_fac]
  have htf : t ≫ B'.p = (s ≫ f.total) ≫ B'.p := by
    dsimp only [t, s]
    rw [mappedLocalSection_fac, Category.assoc, f.isPullback.w,
      ← Category.assoc, localSection_fac]
  let d := B''.torsorDifference v u hvu
  let b := B''.torsorDifference u (t ≫ g.total) hut
  let a := B'.torsorDifference t (s ≫ f.total) htf
  let c := B''.torsorDifference v
    ((s ≫ f.total) ≫ g.total) (hvu.trans (hut.trans hts))
  have hdb := B''.torsorDifference_mul v u (t ≫ g.total) hvu hut
  letI : IsModHom H g.total := g.equivariant
  have hmap := B'.torsorDifference_map B'' t (s ≫ f.total) htf
    g.total hts
  have hlast := B''.torsorDifference_mul v (t ≫ g.total)
    ((s ≫ f.total) ≫ g.total) (hvu.trans hut) hts
  have hcalc : d * b * a = c := by
    dsimp only [d, b, a, c]
    rw [hdb, ← hmap]
    exact hlast
  let dg : q.obj.left ⟶ H :=
    eqToHom (mapCoverFunctor_obj_left B B'' (f ≫ g) q).symm ≫
      transitionGauge (𝟙 H) B'' (mapCoverCompHom B B' B'' f g q)
  let bg : q.obj.left ⟶ H :=
    eqToHom (mapCoverFunctor_obj_left B B' f q).symm ≫
      mapSectionGauge B' B'' g ((mapCoverFunctor B B' f).obj q)
  let ag : q.obj.left ⟶ H := mapSectionGauge B B' f q
  let cg : q.obj.left ⟶ H := mapSectionGauge B B'' (f ≫ g) q
  change dg * bg * ag = cg
  have hd : dg = d := by
    dsimp only [dg, d, v, u, transitionGauge, mappedLocalSection]
    simp only [Category.id_comp, Category.comp_id, eqToHom_refl,
      mapCoverCompHom_left]
    congr 2
  have hb : bg = b := by
    dsimp only [bg, b, u, t, mapSectionGauge, mappedLocalSection]
    simp only [Category.id_comp, eqToHom_refl]
    congr 2
  have ha : ag = a := by
    dsimp only [ag, a, t, s, mapSectionGauge]
  have hc : cg = c := by
    dsimp only [cg, c, v, s, mapSectionGauge]
    rfl
  rw [hd, hb, ha, hc]
  exact hcalc

@[simp]
lemma mapLocalHom_total [Smooth G.hom] [IsAffineHom G.hom]
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (q : (coverSieve B).arrows.category) :
    (mapLocalHom phi B B' f q).total =
      GlobalPrincipalBundle.trivialRightTranslate (G := G)
        ((mapSectionGauge B B' f q ≫ phi)⁻¹) := rfl

/-- The local morphism for the canonical composition comparison is the
corresponding right translation. -/
lemma localHom_mapCoverComp_total [Smooth G.hom] [IsAffineHom G.hom]
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (q : (coverSieve B).arrows.category) :
    (localHom phi B'' (mapCoverCompHom B B' B'' f g q)).total =
      GlobalPrincipalBundle.trivialRightTranslate (G := G)
        (transitionGauge phi B'' (mapCoverCompHom B B' B'' f g q)) := by
  rw [localHom_total, mapCoverCompHom_left]
  apply GlobalPrincipalBundle.trivial_hom_ext
  · simp
  · simp

/-- Local induction maps preserve composition, up to the canonical chart
comparison. -/
lemma mapLocalHom_comp [Smooth G.hom] [IsAffineHom G.hom]
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (q : (coverSieve B).arrows.category) :
    mapLocalHom phi B B' f q ≫
        mapLocalHom phi B' B'' g ((mapCoverFunctor B B' f).obj q) =
      mapLocalHom phi B B'' (f ≫ g) q ≫
        localHom phi B'' (mapCoverCompHom B B' B'' f g q) := by
  have hbase :
      (mapLocalHom phi B B' f q).base ≫
          (mapLocalHom phi B' B'' g
            ((mapCoverFunctor B B' f).obj q)).base =
        (mapLocalHom phi B B'' (f ≫ g) q).base ≫
          (localHom phi B''
            (mapCoverCompHom B B' B'' f g q)).base := by
    simp
  have htotal :
      (mapLocalHom phi B B' f q).total ≫
          (mapLocalHom phi B' B'' g
            ((mapCoverFunctor B B' f).obj q)).total =
        (mapLocalHom phi B B'' (f ≫ g) q).total ≫
          (localHom phi B''
            (mapCoverCompHom B B' B'' f g q)).total := by
    rw [mapLocalHom_total, mapLocalHom_total, mapLocalHom_total,
      localHom_mapCoverComp_total]
    rw [GlobalPrincipalBundle.trivialRightTranslate_comp,
      GlobalPrincipalBundle.trivialRightTranslate_comp]
    congr 1
    let a : q.obj.left ⟶ H := mapSectionGauge B B' f q
    let b : q.obj.left ⟶ H :=
      eqToHom (mapCoverFunctor_obj_left B B' f q).symm ≫
        mapSectionGauge B' B'' g ((mapCoverFunctor B B' f).obj q)
    let c : q.obj.left ⟶ H := mapSectionGauge B B'' (f ≫ g) q
    let d : q.obj.left ⟶ H :=
      eqToHom (mapCoverFunctor_obj_left B B'' (f ≫ g) q).symm ≫
        transitionGauge (𝟙 H) B''
          (mapCoverCompHom B B' B'' f g q)
    have hsec : d * b * a = c :=
      mapSectionGauge_comp B B' B'' f g q
    have hab : a⁻¹ * b⁻¹ = c⁻¹ * d := by
      rw [eq_inv_mul_iff_mul_eq]
      rw [← hsec]
      simp
    have hphi := congrArg (fun z ↦ z ≫ phi) hab
    have htrans :
        transitionGauge (𝟙 H) B''
              (mapCoverCompHom B B' B'' f g q) ≫ phi =
          transitionGauge phi B''
              (mapCoverCompHom B B' B'' f g q) := by
      dsimp only [transitionGauge]
      simp
    simp only [a, b, c, d, MonObj.mul_comp, GrpObj.inv_comp,
      eqToHom_refl, Category.id_comp] at hphi
    rw [htrans] at hphi
    exact hphi
  apply ClassifyingHom.ext
  · exact hbase
  · exact htotal

/-- Composing a descended comparison leg with a descended map gives the local
map for the composite bundle morphism. -/
lemma mapCoconeLeg_comp_of_fac [Smooth G.hom] [IsAffineHom G.hom]
    (C' : Cocone phi B') (C'' : Cocone phi B'')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (F : C'.obj ⟶ C''.obj)
    (hF : ∀ r : (coverSieve B').arrows.category,
      C'.comparison r ≫ F = mapCoconeLeg phi B' B'' C'' g r)
    (q : (coverSieve B).arrows.category) :
    mapCoconeLeg phi B B' C' f q ≫ F =
      mapCoconeLeg phi B B'' C'' (f ≫ g) q := by
  rw [mapCoconeLeg, Category.assoc,
    hF ((mapCoverFunctor B B' f).obj q)]
  rw [mapCoconeLeg, ← Category.assoc, mapLocalHom_comp]
  rw [mapCoconeLeg, Category.assoc]
  congr 1
  exact C''.comparison_naturality (mapCoverCompHom B B' B'' f g q)

/-! ### The canonical chart over the original bundle -/

/-- The object of the trivializing sieve given by the bundle projection
itself. -/
noncomputable abbrev selfCoverObj : (coverSieve B).arrows.category :=
  (coverSieve B).arrows.categoryMk B.p ⟨𝟙 B.P, Category.id_comp _⟩

/-! ### The descended morphism interface -/

/-- A morphism between two descended induced bundles which realizes the local
maps attached to a morphism of principal `H`-bundles.  Effective descent of
affine arrows supplies this structure; keeping the interface explicit lets the
transition-function construction remain independent of a particular descent
implementation. -/
structure DescendedHom [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) (C' : Cocone phi B')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩) where
  /-- The descended morphism of principal `G`-bundles. -/
  hom : C.obj ⟶ C'.obj
  /-- Its base map is the base map of the original morphism. -/
  hom_isHomLift :
    IsHomLift (classifyingPrestack G).p f.base hom
  /-- Pulling the descended morphism back to every chart gives the prescribed
  local map. -/
  comparison_fac : ∀ q : (coverSieve B).arrows.category,
    C.comparison q ≫ hom = mapCoconeLeg phi B B' C' f q

/-- Morphism descent produces a descended map realizing the prescribed local
maps between two induced bundles. -/
theorem DescendedHom.nonempty [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) (C' : Cocone phi B')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩) :
    Nonempty (DescendedHom phi B B' C C' f) := by
  let p := (classifyingPrestack G).p
  let target := ClassifyingObj.pullback C'.obj f.base
  let targetTo : target ⟶ C'.obj := ClassifyingObj.pullbackHom C'.obj f.base
  letI htargetTo : IsHomLift p f.base targetTo :=
    ClassifyingObj.pullbackHom_isHomLift C'.obj f.base
  letI htargetToCart : IsStronglyCartesian p f.base targetTo :=
    Functor.IsFiberedInGroupoids.isStronglyCartesian_of_isHomLift p f.base targetTo
  let localFactor : ∀ q : (coverSieve B).arrows.category,
      (localFunctor phi B).obj q ⟶ target := fun q ↦ by
    letI := mapCoconeLeg_isHomLift phi B B' C' f q
    exact IsStronglyCartesian.map p f.base targetTo
      (g := q.obj.hom) (f' := q.obj.hom ≫ f.base) rfl
      (mapCoconeLeg phi B B' C' f q)
  have localFactor_isHomLift : ∀ q : (coverSieve B).arrows.category,
      IsHomLift p q.obj.hom (localFactor q) := fun q ↦ by
    letI := mapCoconeLeg_isHomLift phi B B' C' f q
    dsimp only [localFactor]
    exact IsStronglyCartesian.map_isHomLift p f.base targetTo rfl
      (mapCoconeLeg phi B B' C' f q)
  have localFactor_fac : ∀ q : (coverSieve B).arrows.category,
      localFactor q ≫ targetTo = mapCoconeLeg phi B B' C' f q := fun q ↦ by
    letI := mapCoconeLeg_isHomLift phi B B' C' f q
    dsimp only [localFactor]
    exact IsStronglyCartesian.fac p f.base targetTo rfl
      (mapCoconeLeg phi B B' C' f q)
  have localFactor_naturality : ∀ {q r : (coverSieve B).arrows.category}
      (k : q ⟶ r), (localFunctor phi B).map k ≫ localFactor r = localFactor q := by
    intro q r k
    letI hk := localFunctor_map_isHomLift phi B k
    letI hr := localFactor_isHomLift r
    letI hq := localFactor_isHomLift q
    have hcomp : IsHomLift p q.obj.hom
        ((localFunctor phi B).map k ≫ localFactor r) := by
      have h := IsHomLift.comp p k.hom.left r.obj.hom
        ((localFunctor phi B).map k) (localFactor r)
      simpa [k.hom.w] using h
    letI := hcomp
    apply IsStronglyCartesian.ext p f.base targetTo q.obj.hom
    rw [Category.assoc, localFactor_fac, localFactor_fac,
      mapCoconeLeg_naturality]
  let hglue : p.MorphismsGlue (Scheme.fpqcTopology.over S) :=
    ClassifyingPrestackMorphisms.morphismsGlue_fpqc
  obtain ⟨F, hF, -⟩ :=
    MorphismsGlue.existsUnique_gluing_hom_of_cocone hglue
      (coverSieve_mem B) (localFunctor phi B) rfl rfl C.comparison
      C.comparison_isHomLift (fun {_ _} k ↦ localFunctor_map_isHomLift phi B k)
      C.comparison_naturality localFactor localFactor_isHomLift
      localFactor_naturality
  let hom : C.obj ⟶ C'.obj := F ≫ targetTo
  have hom_isHomLift : IsHomLift p f.base hom := by
    letI := hF.1
    exact IsHomLift.comp_lift_id_left' p T F f.base targetTo
  exact ⟨
    { hom := hom
      hom_isHomLift := hom_isHomLift
      comparison_fac := fun q ↦ by
        let q' := (coverSieve B).arrows.categoryMk q.obj.hom q.property
        let k : q ⟶ q' := ObjectProperty.homMk
          (Over.homMk (𝟙 q.obj.left) (by simp [q']))
        have hlocal : localFactor q = C.comparison q ≫ F := by
          calc
            localFactor q = (localFunctor phi B).map k ≫ localFactor q' :=
              (localFactor_naturality k).symm
            _ = (localFunctor phi B).map k ≫ (C.comparison q' ≫ F) := by
              rw [hF.2 q.property]
            _ = ((localFunctor phi B).map k ≫ C.comparison q') ≫ F :=
              (Category.assoc _ _ _).symm
            _ = C.comparison q ≫ F := by rw [C.comparison_naturality k]
        change C.comparison q ≫ (F ≫ targetTo) = _
        rw [← Category.assoc, ← hlocal, localFactor_fac] }⟩

/-- The comparison over the bundle projection itself is an effective
epimorphism on total spaces. -/
lemma comparison_self_total_effectiveEpi [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) :
    EffectiveEpi (C.comparison (selfCoverObj B)).total.left := by
  let q := selfCoverObj B
  let c := C.comparison q
  letI hc : IsHomLift (classifyingPrestack G).p q.obj.hom c :=
    C.comparison_isHomLift q
  have hbase : q.obj.hom = c.base :=
    IsHomLift.eq_of_isHomLift (classifyingPrestack G).p q.obj.hom c
  have hpull : IsPullback c.total.left
      ((localFunctor phi B).obj q).bundle.p.left
      C.bundle.p.left c.base.left :=
    c.isPullback.map (Over.forget S)
  letI : Flat c.base.left := by
    rw [← hbase]
    change Flat B.p.left
    infer_instance
  letI : Surjective c.base.left := by
    rw [← hbase]
    change Surjective B.p.left
    infer_instance
  letI : LocallyOfFinitePresentation c.base.left := by
    rw [← hbase]
    change LocallyOfFinitePresentation B.p.left
    infer_instance
  letI : Flat c.total.left :=
    MorphismProperty.IsStableUnderBaseChange.of_isPullback hpull.flip
      (inferInstance : Flat c.base.left)
  letI : Surjective c.total.left :=
    MorphismProperty.IsStableUnderBaseChange.of_isPullback hpull.flip
      (inferInstance : Surjective c.base.left)
  letI : LocallyOfFinitePresentation c.total.left :=
    MorphismProperty.IsStableUnderBaseChange.of_isPullback hpull.flip
      (inferInstance : LocallyOfFinitePresentation c.base.left)
  infer_instance

/-- A descended morphism is uniquely determined by its local comparison maps. -/
@[ext]
lemma DescendedHom.ext [Smooth G.hom] [IsAffineHom G.hom]
    {C : Cocone phi B} {C' : Cocone phi B'}
    {f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩}
    (F₁ F₂ : DescendedHom phi B B' C C' f) : F₁ = F₂ := by
  cases F₁ with
  | mk hom₁ hlift₁ hfac₁ =>
    cases F₂ with
    | mk hom₂ hlift₂ hfac₂ =>
      have hhom : hom₁ = hom₂ := by
        apply ClassifyingHom.ext
        · exact
            (IsHomLift.eq_of_isHomLift
                (classifyingPrestack G).p f.base hom₁).symm.trans
              (IsHomLift.eq_of_isHomLift
                (classifyingPrestack G).p f.base hom₂)
        · apply Over.OverMorphism.ext
          let q := selfCoverObj B
          let c := C.comparison q
          letI : EffectiveEpi c.total.left :=
            comparison_self_total_effectiveEpi phi B C
          apply (cancel_epi c.total.left).mp
          have h := (hfac₁ q).trans (hfac₂ q).symm
          exact congrArg (fun k ↦ k.total.left) h
      subst hom₂
      rfl

namespace DescendedHom

/-- The identity morphism realizes the local datum attached to the identity
bundle morphism. -/
noncomputable def identity [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) :
    DescendedHom phi B B C C (𝟙 (⟨T, B⟩ : ClassifyingObj H)) where
  hom := 𝟙 C.obj
  hom_isHomLift := by
    change IsHomLift (classifyingPrestack G).p (𝟙 T) (𝟙 C.obj)
    exact IsHomLift.id rfl
  comparison_fac q := by
    calc
      C.comparison q ≫ 𝟙 C.obj = C.comparison q := Category.comp_id _
      _ = mapCoconeLeg phi B B C
          (𝟙 (⟨T, B⟩ : ClassifyingObj H)) q :=
        (mapCoconeLeg_id phi B C q).symm

/-- Composition of descended morphisms realizes the composite local datum. -/
noncomputable def comp [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) (C' : Cocone phi B') (C'' : Cocone phi B'')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (g : (⟨T', B'⟩ : ClassifyingObj H) ⟶ ⟨T'', B''⟩)
    (F : DescendedHom phi B B' C C' f)
    (F' : DescendedHom phi B' B'' C' C'' g) :
    DescendedHom phi B B'' C C'' (f ≫ g) where
  hom := F.hom ≫ F'.hom
  hom_isHomLift := by
    letI hF := F.hom_isHomLift
    letI hF' := F'.hom_isHomLift
    change IsHomLift (classifyingPrestack G).p
      (f.base ≫ g.base) (F.hom ≫ F'.hom)
    infer_instance
  comparison_fac q := by
    calc
      C.comparison q ≫ (F.hom ≫ F'.hom) =
          (C.comparison q ≫ F.hom) ≫ F'.hom :=
        (Category.assoc _ _ _).symm
      _ = mapCoconeLeg phi B B' C' f q ≫ F'.hom := by
        rw [F.comparison_fac]
      _ = mapCoconeLeg phi B B'' C'' (f ≫ g) q :=
        mapCoconeLeg_comp_of_fac phi B B' B'' C' C'' f g F'.hom
          F'.comparison_fac q

end DescendedHom

/-- Normalize a descended morphism so that its base component is definitionally
the base component of the original bundle morphism. -/
noncomputable def DescendedHom.normalizedHom [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) (C' : Cocone phi B')
    (f : (⟨T, B⟩ : ClassifyingObj H) ⟶ ⟨T', B'⟩)
    (F : DescendedHom phi B B' C C' f) : C.obj ⟶ C'.obj where
  base := f.base
  total := F.hom.total
  isPullback := by
    letI := F.hom_isHomLift
    have hbase := IsHomLift.eq_of_isHomLift
      (classifyingPrestack G).p f.base F.hom
    change f.base = F.hom.base at hbase
    rw [hbase]
    exact F.hom.isPullback
  equivariant := F.hom.equivariant

/-- Effective extension-of-structure-group data: a descended object for every
principal bundle and a descended map for every bundle morphism.  The local
uniqueness theorem forces the functor laws. -/
structure EffectiveInduction [Smooth G.hom] [IsAffineHom G.hom] where
  /-- The descended contracted product of each principal bundle. -/
  cocone : ∀ x : ClassifyingObj H, Cocone phi x.bundle
  /-- The descended map associated to each morphism of principal bundles. -/
  map : ∀ {x y : ClassifyingObj H} (f : x ⟶ y),
    DescendedHom phi x.bundle y.bundle (cocone x) (cocone y) f

/-- Choosing an effective local gluing for every principal bundle supplies all
object and morphism data for extension of structure group. -/
noncomputable def effectiveInductionOfCocones [Smooth G.hom] [IsAffineHom G.hom]
    (hC : ∀ x : ClassifyingObj H, Nonempty (Cocone phi x.bundle)) :
    EffectiveInduction phi where
  cocone x := Classical.choice (hC x)
  map {_ _} f := Classical.choice
    (DescendedHom.nonempty phi _ _ _ _ f)

/-- If every local contracted-product datum is effective, extension of
structure group exists functorially. -/
theorem nonempty_effectiveInduction_of_cocones [Smooth G.hom]
    [IsAffineHom G.hom]
    (hC : ∀ x : ClassifyingObj H, Nonempty (Cocone phi x.bundle)) :
    Nonempty (EffectiveInduction phi) :=
  ⟨effectiveInductionOfCocones phi hC⟩

namespace EffectiveInduction

/-- Effective descent of the contracted products and their maps defines the
extension-of-structure-group morphism `BH ⟶ BG`. -/
noncomputable def toBasedFunctor [Smooth G.hom] [IsAffineHom G.hom]
    (I : EffectiveInduction phi) :
    BasedFunctor (classifyingPrestack H) (classifyingPrestack G) where
  obj x := (I.cocone x).obj
  map f := DescendedHom.normalizedHom phi _ _ _ _ _ (I.map f)
  map_id x := by
    apply ClassifyingHom.ext
    · rfl
    · exact congrArg (fun F ↦ F.hom.total)
        (DescendedHom.ext phi x.bundle x.bundle (I.map (𝟙 x))
          (DescendedHom.identity phi x.bundle (I.cocone x)))
  map_comp f g := by
    apply ClassifyingHom.ext
    · rfl
    · exact congrArg (fun F ↦ F.hom.total)
        (DescendedHom.ext phi _ _ (I.map (f ≫ g))
          (DescendedHom.comp phi _ _ _ (I.cocone _) (I.cocone _)
            (I.cocone _) f g (I.map f) (I.map g)))
  w := rfl

end EffectiveInduction

/-! ### The canonical map into the induced bundle -/

/-- In the chart chosen over `P`, this is the group coordinate of the
canonical point `[1,p]` of the contracted product. -/
noncomputable def unitGauge : B.P ⟶ G :=
  (B.torsorDifference (localSection B (selfCoverObj B)) (𝟙 B.P) (by
    rw [localSection_fac, Category.id_comp]
    rfl) ≫ phi)⁻¹

/-- The canonical local point of the trivial `G`-bundle over `P`. -/
noncomputable def unitLocal [Smooth G.hom] [IsAffineHom G.hom] :
    B.P ⟶ ((localFunctor phi B).obj (selfCoverObj B)).bundle.P :=
  GlobalPrincipalBundle.trivialPoint (unitGauge phi B)

/-- The canonical map `P → G ×ᴴ P`, obtained by composing the local point
representing `[1,p]` with the descended comparison. -/
noncomputable def unit [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) : B.P ⟶ C.bundle.P :=
  unitLocal phi B ≫ (C.comparison (selfCoverObj B)).total

/-- The canonical map to the induced bundle lies over the identity of the
original base. -/
@[reassoc (attr := simp)]
lemma unit_comp_projection [Smooth G.hom] [IsAffineHom G.hom]
    (C : Cocone phi B) : unit phi B C ≫ C.bundle.p = B.p := by
  change (unitLocal phi B ≫ (C.comparison (selfCoverObj B)).total) ≫
      C.bundle.p = B.p
  rw [Category.assoc, (C.comparison (selfCoverObj B)).isPullback.w,
    ← Category.assoc]
  have hlocal : unitLocal phi B ≫
      ((localFunctor phi B).obj (selfCoverObj B)).bundle.p = 𝟙 B.P := by
    change GlobalPrincipalBundle.trivialPoint (unitGauge phi B) ≫
      GlobalPrincipalBundle.trivialSnd G B.P = 𝟙 B.P
    exact GlobalPrincipalBundle.trivialPoint_snd (unitGauge phi B)
  rw [hlocal, Category.id_comp]
  letI := C.comparison_isHomLift (selfCoverObj B)
  have hbase := IsHomLift.eq_of_isHomLift (classifyingPrestack G).p
    (selfCoverObj B).obj.hom (C.comparison (selfCoverObj B))
  exact hbase.symm.trans rfl

end PrincipalBundleInduction

end AlgebraicGeometry.Scheme
