module

public import StacksAndModuli.API.AffineSheafMorphismZeroLocus
public import StacksAndModuli.API.ClosedImmersionQuotient
public import StacksAndModuli.API.GlobalSectionsOverBase
public import StacksAndModuli.API.ModuleSheafGlobalSectionMul
public import StacksAndModuli.API.OpenImmersionModuleBaseChange
public import StacksAndModuli.API.PullbackGeneration
public import StacksAndModuli.API.SchemeModulesOpenCover
public import Mathlib.RingTheory.QuotSMulTop
public import Mathlib.RingTheory.TensorProduct.Quotient

/-!
# Cokernels on a principal closed fibre

For a ring element `r : R`, let `i : Spec (R/(r)) ⟶ Spec R` be the principal
closed fibre.  This file identifies the cokernel of multiplication by `r` on a
quasicoherent module sheaf with `i_* i^*` of that sheaf.

The proof first identifies the module cokernel with extension of scalars to
`R/(r)`, then transports that calculation through the affine tilde equivalence.

Main declaration:

* `Scheme.Modules.cokernelMulByGlobalSectionIsoPushforwardPullbackSpec`.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory CategoryTheory.Limits
open AlgebraicGeometry
open scoped Pointwise

universe u

noncomputable section

namespace AlgebraicGeometry

/-- The quotient of a ring by the principal ideal generated by `r`. -/
abbrev principalClosedFiberRing {R : CommRingCat.{u}} (r : R) :
    CommRingCat.{u} :=
  CommRingCat.of (R ⧸ Ideal.span {r})

/-- The quotient map defining the principal closed fibre. -/
def principalClosedFiberRingHom {R : CommRingCat.{u}} (r : R) :
    R ⟶ principalClosedFiberRing r :=
  CommRingCat.ofHom (Ideal.Quotient.mk (Ideal.span {r}))

end AlgebraicGeometry

namespace ModuleCat

variable {R : CommRingCat.{u}} (r : R)
variable {M : Type u} [AddCommGroup M] [Module R M]

/-- The cokernel of multiplication by `r` is extension of scalars to `R/(r)`,
regarded again as an `R`-module. -/
noncomputable def cokernelLSMulIsoRestrictScalarsExtendScalars :
    cokernel (ofHom (LinearMap.lsmul R M r)) ≅
      (restrictScalars (principalClosedFiberRingHom r).hom).obj
        ((extendScalars (principalClosedFiberRingHom r).hom).obj
          (of R M)) :=
  let h : LinearMap.range (LinearMap.lsmul R M r) =
      r • (⊤ : Submodule R M) := by
    ext x
    simp only [LinearMap.mem_range, LinearMap.lsmul_apply,
      Submodule.mem_smul_pointwise_iff_exists, Submodule.mem_top, true_and]
  cokernelIsoRangeQuotient _ ≪≫
    ((Submodule.quotEquivOfEq _ _ h) ≪≫ₗ
      QuotSMulTop.equivQuotTensor r M).toModuleIso

end ModuleCat

namespace AlgebraicGeometry.Scheme.Modules

variable {R : CommRingCat.{u}} (r : R)
variable {M : Type u} [AddCommGroup M] [Module R M]

/-- On affine spectra, the tilde of a module restricted from `R/(r)` is the
pushforward of its tilde over `R/(r)`. -/
noncomputable def tildeRestrictScalarsIsoPushforwardTilde :
    (AlgebraicGeometry.tilde.functor R).obj
        ((ModuleCat.restrictScalars (principalClosedFiberRingHom r).hom).obj
          ((ModuleCat.extendScalars (principalClosedFiberRingHom r).hom).obj
            (ModuleCat.of R M))) ≅
      (pushforward (Spec.map (principalClosedFiberRingHom r))).obj
        ((AlgebraicGeometry.tilde.functor (principalClosedFiberRing r)).obj
          ((ModuleCat.extendScalars (principalClosedFiberRingHom r).hom).obj
            (ModuleCat.of R M))) := by
  let q := principalClosedFiberRingHom r
  let N := (ModuleCat.extendScalars q.hom).obj (ModuleCat.of R M)
  let F := (pushforward (Spec.map q)).obj
    ((AlgebraicGeometry.tilde.functor (principalClosedFiberRing r)).obj N)
  let e₁ : (ModuleCat.restrictScalars q.hom).obj N ≅
      (ModuleCat.restrictScalars q.hom).obj
        (AlgebraicGeometry.moduleSpecΓFunctor.obj
          ((AlgebraicGeometry.tilde.functor (principalClosedFiberRing r)).obj N)) :=
    (ModuleCat.restrictScalars q.hom).mapIso
      (AlgebraicGeometry.tilde.isoTop N)
  let e₂ : (ModuleCat.restrictScalars q.hom).obj
        (AlgebraicGeometry.moduleSpecΓFunctor.obj
          ((AlgebraicGeometry.tilde.functor (principalClosedFiberRing r)).obj N)) ≅
      AlgebraicGeometry.moduleSpecΓFunctor.obj F :=
    ((affinePushforwardGlobalSectionsIso q).app
      ((AlgebraicGeometry.tilde.functor (principalClosedFiberRing r)).obj N)).symm
  letI : ((AlgebraicGeometry.tilde.functor
      (principalClosedFiberRing r)).obj N).IsQuasicoherent :=
    inferInstanceAs (AlgebraicGeometry.tilde N).IsQuasicoherent
  letI : IsIso (fromTildeΓ
      ((AlgebraicGeometry.tilde.functor
        (principalClosedFiberRing r)).obj N)) :=
    isIso_fromTildeΓ_of_isQuasicoherent _
  letI : IsIso (fromTildeΓ F) :=
    AlgebraicGeometry.isIso_fromTildeΓ_pushforward q _
  let e₃ : (AlgebraicGeometry.tilde.functor R).obj
        (AlgebraicGeometry.moduleSpecΓFunctor.obj F) ≅ F :=
    asIso (fromTildeΓ F)
  exact (AlgebraicGeometry.tilde.functor R).mapIso (e₁ ≪≫ e₂) ≪≫ e₃

/-- For a tilde sheaf on `Spec R`, the cokernel of multiplication by `r` is the
pushforward of its pullback to `Spec (R/(r))`. -/
noncomputable def tildeCokernelLSMulIsoPushforwardPullback :
    cokernel ((AlgebraicGeometry.tilde.functor R).map
      (ModuleCat.ofHom (LinearMap.lsmul R M r))) ≅
      (pushforward (Spec.map (principalClosedFiberRingHom r))).obj
        ((pullback (Spec.map (principalClosedFiberRingHom r))).obj
          ((AlgebraicGeometry.tilde.functor R).obj (ModuleCat.of R M))) :=
  (PreservesCokernel.iso (AlgebraicGeometry.tilde.functor R)
      (ModuleCat.ofHom (LinearMap.lsmul R M r))).symm ≪≫
    (AlgebraicGeometry.tilde.functor R).mapIso
      (ModuleCat.cokernelLSMulIsoRestrictScalarsExtendScalars r) ≪≫
    tildeRestrictScalarsIsoPushforwardTilde r ≪≫
    (pushforward (Spec.map (principalClosedFiberRingHom r))).mapIso
      ((affineTildePullbackIso
        (principalClosedFiberRingHom r)).app (ModuleCat.of R M)).symm

variable (F : (Spec R).Modules)

/-- Taking affine global sections sends multiplication by the global function
corresponding to `r` to scalar multiplication by `r`. -/
lemma moduleSpecΓFunctor_map_mulByGlobalSection :
    AlgebraicGeometry.moduleSpecΓFunctor.map
        (F.mulByGlobalSection ((Scheme.ΓSpecIso R).inv r)) =
      ModuleCat.ofHom (LinearMap.lsmul R
        (AlgebraicGeometry.moduleSpecΓFunctor.obj F) r) := by
  apply ModuleCat.hom_ext
  ext x
  rfl

/-- On `Spec R`, the cokernel of multiplication by `r` on a quasicoherent module
sheaf is the pushforward of its pullback to the principal closed fibre
`Spec (R/(r))`. -/
noncomputable def cokernelMulByGlobalSectionIsoPushforwardPullbackSpec
    [F.IsQuasicoherent] :
    cokernel (F.mulByGlobalSection ((Scheme.ΓSpecIso R).inv r)) ≅
      (pushforward (Spec.map (principalClosedFiberRingHom r))).obj
        ((pullback (Spec.map (principalClosedFiberRingHom r))).obj F) := by
  let N := AlgebraicGeometry.moduleSpecΓFunctor.obj F
  let a := (AlgebraicGeometry.tilde.functor R).map
    (ModuleCat.ofHom (LinearMap.lsmul R N r))
  let b := F.mulByGlobalSection ((Scheme.ΓSpecIso R).inv r)
  letI : IsIso (fromTildeΓ F) :=
    isIso_fromTildeΓ_of_isQuasicoherent F
  let e : (AlgebraicGeometry.tilde.functor R).obj N ≅ F :=
    @asIso _ _ _ _ (fromTildeΓ F)
      (isIso_fromTildeΓ_of_isQuasicoherent F)
  have hab : a ≫ e.hom = e.hom ≫ b := by
    dsimp [a, b, e, N]
    have hnat := fromTildeΓNatTrans.naturality b
    change (AlgebraicGeometry.tilde.functor R).map
          (AlgebraicGeometry.moduleSpecΓFunctor.map b) ≫
        fromTildeΓ F = fromTildeΓ F ≫ b at hnat
    rw [moduleSpecΓFunctor_map_mulByGlobalSection] at hnat
    exact hnat
  exact (cokernel.mapIso a b e e hab).symm ≪≫
    tildeCokernelLSMulIsoPushforwardPullback r ≪≫
    (pushforward (Spec.map (principalClosedFiberRingHom r))).mapIso
      ((pullback (Spec.map (principalClosedFiberRingHom r))).mapIso e)

@[reassoc]
lemma cokernel_π_cokernelLSMulIsoRestrictScalarsExtendScalars :
    cokernel.π (ModuleCat.ofHom (LinearMap.lsmul R M r)) ≫
        (ModuleCat.cokernelLSMulIsoRestrictScalarsExtendScalars r).hom =
      (ModuleCat.extendRestrictScalarsAdj
        (principalClosedFiberRingHom r).hom).unit.app (ModuleCat.of R M) := by
  let h : LinearMap.range (LinearMap.lsmul R M r) =
      r • (⊤ : Submodule R M) := by
    ext x
    simp only [LinearMap.mem_range, LinearMap.lsmul_apply,
      Submodule.mem_smul_pointwise_iff_exists, Submodule.mem_top, true_and]
  let e := (Submodule.quotEquivOfEq _ _ h) ≪≫ₗ
    QuotSMulTop.equivQuotTensor r M
  change (cokernel.π (ModuleCat.ofHom (LinearMap.lsmul R M r)) ≫
      (ModuleCat.cokernelIsoRangeQuotient _).hom) ≫
        e.toModuleIso.hom = _
  rw [ModuleCat.cokernel_π_cokernelIsoRangeQuotient_hom]
  apply ModuleCat.hom_ext
  ext x
  rfl

lemma tilde_moduleUnit_comp_restrictScalarsIso_pushforward_pullbackIso :
    (AlgebraicGeometry.tilde.functor R).map
          ((ModuleCat.extendRestrictScalarsAdj
            (principalClosedFiberRingHom r).hom).unit.app (ModuleCat.of R M)) ≫
        (tildeRestrictScalarsIsoPushforwardTilde r).hom ≫
        (Scheme.Modules.pushforward
          (Spec.map (principalClosedFiberRingHom r))).map
            ((Scheme.Modules.affineTildePullbackIso
              (principalClosedFiberRingHom r)).inv.app (ModuleCat.of R M)) =
      (Scheme.Modules.pullbackPushforwardAdjunction
        (Spec.map (principalClosedFiberRingHom r))).unit.app
          ((AlgebraicGeometry.tilde.functor R).obj (ModuleCat.of R M)) := by
  apply (AlgebraicGeometry.tilde.adjunction.homEquiv _ _).injective
  simp only [CategoryTheory.Adjunction.homEquiv_unit,
    Functor.map_comp, Category.assoc]
  simp [tildeRestrictScalarsIsoPushforwardTilde]
  let q := principalClosedFiberRingHom r
  let N := (ModuleCat.extendScalars q.hom).obj (ModuleCat.of R M)
  let T := (AlgebraicGeometry.tilde.functor (principalClosedFiberRing r)).obj N
  let F := (Scheme.Modules.pushforward (Spec.map q)).obj T
  let a := (ModuleCat.extendRestrictScalarsAdj q.hom).unit.app
    (ModuleCat.of R M)
  let b := (ModuleCat.restrictScalars q.hom).map
    (AlgebraicGeometry.tilde.adjunction.unit.app N)
  let c := (Scheme.Modules.affinePushforwardGlobalSectionsIso q).inv.app T
  let α := (Scheme.Modules.affineTildePullbackIso q).inv.app
    (ModuleCat.of R M)
  let adjComp := AlgebraicGeometry.tilde.adjunction.comp
    (Scheme.Modules.pullbackPushforwardAdjunction (Spec.map q))
  let adjExt := (ModuleCat.extendRestrictScalarsAdj q.hom).comp
    AlgebraicGeometry.tilde.adjunction
  change AlgebraicGeometry.tilde.adjunction.unit.app (ModuleCat.of R M) ≫
      AlgebraicGeometry.moduleSpecΓFunctor.map
          ((AlgebraicGeometry.tilde.functor R).map a) ≫
      AlgebraicGeometry.moduleSpecΓFunctor.map
          ((AlgebraicGeometry.tilde.functor R).map b) ≫
      AlgebraicGeometry.moduleSpecΓFunctor.map
          ((AlgebraicGeometry.tilde.functor R).map c) ≫
      AlgebraicGeometry.moduleSpecΓFunctor.map
          (AlgebraicGeometry.tilde.adjunction.counit.app F) ≫
      AlgebraicGeometry.moduleSpecΓFunctor.map
          ((Scheme.Modules.pushforward (Spec.map q)).map α) =
    AlgebraicGeometry.tilde.adjunction.unit.app (ModuleCat.of R M) ≫
      AlgebraicGeometry.moduleSpecΓFunctor.map
        ((Scheme.Modules.pullbackPushforwardAdjunction
          (Spec.map q)).unit.app
            ((AlgebraicGeometry.tilde.functor R).obj (ModuleCat.of R M)))
  have hmate := CategoryTheory.unit_conjugateEquiv adjComp adjExt
    (Scheme.Modules.affineTildePullbackIso q).inv (ModuleCat.of R M)
  dsimp only [Scheme.Modules.affineTildePullbackIso] at hmate
  rw [CategoryTheory.Adjunction.conjugateEquiv_leftAdjointCompIso_inv]
    at hmate
  have hmate' : adjComp.unit.app (ModuleCat.of R M) =
      adjExt.unit.app (ModuleCat.of R M) ≫ c ≫
        AlgebraicGeometry.moduleSpecΓFunctor.map
          ((Scheme.Modules.pushforward (Spec.map q)).map α) := by
    rw [← cancel_mono
      ((Scheme.Modules.affinePushforwardGlobalSectionsIso q).hom.app
        ((Scheme.Modules.pullback (Spec.map q)).obj
          ((AlgebraicGeometry.tilde.functor R).obj (ModuleCat.of R M))))]
    slice_rhs 3 4 =>
      erw [(Scheme.Modules.affinePushforwardGlobalSectionsIso q).hom.naturality α]
    simpa [c, α, T, N, adjComp, adjExt, q,
      Scheme.Modules.affineTildePullbackIso, Category.assoc] using hmate
  have hcollapse :
      AlgebraicGeometry.tilde.adjunction.unit.app (ModuleCat.of R M) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              ((AlgebraicGeometry.tilde.functor R).map a) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              ((AlgebraicGeometry.tilde.functor R).map b) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              ((AlgebraicGeometry.tilde.functor R).map c) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              (AlgebraicGeometry.tilde.adjunction.counit.app F) =
        a ≫ b ≫ c := by
    calc
      _ = AlgebraicGeometry.tilde.adjunction.unit.app (ModuleCat.of R M) ≫
          (AlgebraicGeometry.tilde.functor R ⋙
            AlgebraicGeometry.moduleSpecΓFunctor).map (a ≫ b ≫ c) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
            (AlgebraicGeometry.tilde.adjunction.counit.app F) := by
              simp only [Functor.comp_map, Functor.map_comp, Category.assoc]
      _ = (a ≫ b ≫ c) ≫
          AlgebraicGeometry.tilde.adjunction.unit.app
            (AlgebraicGeometry.moduleSpecΓFunctor.obj F) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
            (AlgebraicGeometry.tilde.adjunction.counit.app F) := by
              rw [← Category.assoc,
                ← AlgebraicGeometry.tilde.adjunction.unit.naturality,
                Category.assoc]
              simp [F]
      _ = a ≫ b ≫ c := by
              rw [Category.assoc,
                AlgebraicGeometry.tilde.adjunction.right_triangle_components]
              dsimp only [F]
              simpa only [Functor.id_obj, Functor.comp_obj, Category.assoc] using
                (Category.comp_id (a ≫ b ≫ c))
  calc
    _ = (AlgebraicGeometry.tilde.adjunction.unit.app (ModuleCat.of R M) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              ((AlgebraicGeometry.tilde.functor R).map a) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              ((AlgebraicGeometry.tilde.functor R).map b) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              ((AlgebraicGeometry.tilde.functor R).map c) ≫
          AlgebraicGeometry.moduleSpecΓFunctor.map
              (AlgebraicGeometry.tilde.adjunction.counit.app F)) ≫
        AlgebraicGeometry.moduleSpecΓFunctor.map
          ((Scheme.Modules.pushforward (Spec.map q)).map α) := by
            simp only [Category.assoc]
    _ = (a ≫ b ≫ c) ≫
        AlgebraicGeometry.moduleSpecΓFunctor.map
          ((Scheme.Modules.pushforward (Spec.map q)).map α) := by rw [hcollapse]
    _ = adjExt.unit.app (ModuleCat.of R M) ≫ c ≫
        AlgebraicGeometry.moduleSpecΓFunctor.map
          ((Scheme.Modules.pushforward (Spec.map q)).map α) := by
            simp [adjExt, a, b, N, Adjunction.comp, Category.assoc]
    _ = adjComp.unit.app (ModuleCat.of R M) := hmate'.symm
    _ = _ := by simp [adjComp, Adjunction.comp]

@[reassoc]
lemma cokernel_π_tildeCokernelLSMulIsoPushforwardPullback :
    cokernel.π ((AlgebraicGeometry.tilde.functor R).map
        (ModuleCat.ofHom (LinearMap.lsmul R M r))) ≫
        (tildeCokernelLSMulIsoPushforwardPullback r).hom =
      (Scheme.Modules.pullbackPushforwardAdjunction
        (Spec.map (principalClosedFiberRingHom r))).unit.app
          ((AlgebraicGeometry.tilde.functor R).obj (ModuleCat.of R M)) := by
  simp only [tildeCokernelLSMulIsoPushforwardPullback, Iso.trans_hom,
    Category.assoc]
  rw [← Category.assoc]
  change (cokernel.π ((AlgebraicGeometry.tilde.functor R).map
          (ModuleCat.ofHom (LinearMap.lsmul R M r))) ≫
        (PreservesCokernel.iso (AlgebraicGeometry.tilde.functor R)
          (ModuleCat.ofHom (LinearMap.lsmul R M r))).inv) ≫ _ = _
  rw [show cokernel.π ((AlgebraicGeometry.tilde.functor R).map
          (ModuleCat.ofHom (LinearMap.lsmul R M r))) ≫
        (PreservesCokernel.iso (AlgebraicGeometry.tilde.functor R)
          (ModuleCat.ofHom (LinearMap.lsmul R M r))).inv =
      (AlgebraicGeometry.tilde.functor R).map
        (cokernel.π (ModuleCat.ofHom (LinearMap.lsmul R M r))) by
    rw [← cancel_mono (PreservesCokernel.iso
      (AlgebraicGeometry.tilde.functor R)
      (ModuleCat.ofHom (LinearMap.lsmul R M r))).hom]
    simp]
  change (AlgebraicGeometry.tilde.functor R).map
        (cokernel.π (ModuleCat.ofHom (LinearMap.lsmul R M r))) ≫
      (AlgebraicGeometry.tilde.functor R).map
        (ModuleCat.cokernelLSMulIsoRestrictScalarsExtendScalars r).hom ≫ _ = _
  rw [← Functor.map_comp_assoc,
    cokernel_π_cokernelLSMulIsoRestrictScalarsExtendScalars]
  exact tilde_moduleUnit_comp_restrictScalarsIso_pushforward_pullbackIso r

@[reassoc]
lemma cokernel_π_cokernelMulByGlobalSectionIsoPushforwardPullbackSpec [F.IsQuasicoherent] :
    cokernel.π (F.mulByGlobalSection ((Scheme.ΓSpecIso R).inv r)) ≫
        (cokernelMulByGlobalSectionIsoPushforwardPullbackSpec r F).hom =
      (pullbackPushforwardAdjunction
        (Spec.map (principalClosedFiberRingHom r))).unit.app F := by
  simp [cokernelMulByGlobalSectionIsoPushforwardPullbackSpec,
    cokernel_π_tildeCokernelLSMulIsoPushforwardPullback]
  rw [cokernel_π_tildeCokernelLSMulIsoPushforwardPullback_assoc]
  exact ((pullbackPushforwardAdjunction
    (Spec.map (principalClosedFiberRingHom r))).unit.naturality
      (Scheme.Modules.fromTildeΓ F)).symm

variable {X : Scheme.{u}} (p : X ⟶ Spec R)

abbrev principalClosedFiber : Scheme.{u} :=
  Limits.pullback p (Spec.map (principalClosedFiberRingHom r))

noncomputable def principalClosedFiberι : principalClosedFiber (r := r) p ⟶ X :=
  Limits.pullback.fst p (Spec.map (principalClosedFiberRingHom r))

noncomputable def principalClosedFiberToQuotientSpec :
    principalClosedFiber (r := r) p ⟶ Spec (principalClosedFiberRing r) :=
  Limits.pullback.snd p (Spec.map (principalClosedFiberRingHom r))

lemma principalClosedFiberι_appTop_baseRingHom_eq_zero :
    ((principalClosedFiberι (r := r) p).appTop).hom ((baseRingHom p).hom r) = 0 := by
  let q := principalClosedFiberRingHom r
  let i := principalClosedFiberι (r := r) p
  let g := principalClosedFiberToQuotientSpec (r := r) p
  have hsquare : i ≫ p = g ≫ Spec.map q := Limits.pullback.condition
  have happ := congrArg Scheme.Hom.appTop hsquare
  change p.appTop ≫ i.appTop = (Spec.map q).appTop ≫ g.appTop at happ
  have hq : q.hom r = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (Set.mem_singleton r))
  change (i.appTop).hom (((Scheme.ΓSpecIso R).inv ≫ p.appTop).hom r) = 0
  rw [← CommRingCat.comp_apply, Category.assoc, happ,
    ← Category.assoc, ← Scheme.ΓSpecIso_inv_naturality q]
  change g.appTop.hom ((Scheme.ΓSpecIso (principalClosedFiberRing r)).inv.hom
    (q.hom r)) = 0
  rw [hq, map_zero, map_zero]

lemma principalClosedFiberι_app_restrict_baseRingHom_eq_zero (U : X.Opens) :
    ((principalClosedFiberι (r := r) p).app U).hom
        ((X.presheaf.map (homOfLE (show U ≤ ⊤ from le_top)).op).hom
          ((baseRingHom p).hom r)) = 0 := by
  let i := principalClosedFiberι (r := r) p
  have hnat := i.naturality (homOfLE (show U ≤ ⊤ from le_top)).op
  have happ := CategoryTheory.congr_fun hnat ((baseRingHom p).hom r)
  have hi : i.appTop.hom ((baseRingHom p).hom r) = 0 := by
    simpa [i] using principalClosedFiberι_appTop_baseRingHom_eq_zero (r := r) p
  have hi' : (i.app (⊤ : X.Opens)).hom ((baseRingHom p).hom r) = 0 := hi
  rw [CategoryTheory.comp_apply, CategoryTheory.comp_apply,
    hi', map_zero] at happ
  exact happ

lemma principalClosedFiber_pullback_map_mulByGlobalSection_eq_zero (M : X.Modules) :
    (pullback (principalClosedFiberι (r := r) p)).map
        (M.mulByGlobalSection ((baseRingHom p).hom r)) = 0 := by
  let i := principalClosedFiberι (r := r) p
  let mul := M.mulByGlobalSection ((baseRingHom p).hom r)
  apply AlgebraicGeometry.eq_zero_of_unit_sections_zero i M
  intro U s
  have hunit := congrArg
    (fun (k : M ⟶ (pushforward i).obj ((pullback i).obj M)) ↦
      (k.app U).hom s)
    ((pullbackPushforwardAdjunction i).unit.naturality mul)
  rw [Hom.comp_app, Hom.comp_app,
    CategoryTheory.comp_apply, CategoryTheory.comp_apply] at hunit
  change (((pullbackPushforwardAdjunction i).unit.app M).app U).hom
      ((mul.app U).hom s) =
    (((pullback i).map mul).app (i ⁻¹ᵁ U)).hom
      ((((pullbackPushforwardAdjunction i).unit.app M).app U).hom s) at hunit
  change (((pullback i).map mul).app (i ⁻¹ᵁ U)).hom
      ((((pullbackPushforwardAdjunction i).unit.app M).app U).hom s) = 0
  slice_lhs 1 3 => rw [← hunit]
  rw [show (mul.app U).hom s =
      (X.presheaf.map (homOfLE (show U ≤ ⊤ from le_top)).op).hom
        ((baseRingHom p).hom r) • s from rfl,
    Hom.app_smul]
  have hz := principalClosedFiberι_app_restrict_baseRingHom_eq_zero (r := r) p U
  change (i.app U).hom
      ((X.presheaf.map (homOfLE (show U ≤ ⊤ from le_top)).op).hom
        ((baseRingHom p).hom r)) •
      (show Γ((pullback i).obj M, i ⁻¹ᵁ U) from
        (((pullbackPushforwardAdjunction i).unit.app M).app U).hom s) = 0
  rw [hz, zero_smul]

noncomputable def principalClosedFiberCokernelToPushforwardPullback (M : X.Modules) :
    cokernel (M.mulByGlobalSection ((baseRingHom p).hom r)) ⟶
      (pushforward (principalClosedFiberι (r := r) p)).obj
        ((pullback (principalClosedFiberι (r := r) p)).obj M) := by
  let i := principalClosedFiberι (r := r) p
  let mul := M.mulByGlobalSection ((baseRingHom p).hom r)
  apply cokernel.desc mul ((pullbackPushforwardAdjunction i).unit.app M)
  have hnat := (pullbackPushforwardAdjunction i).unit.naturality mul
  change mul ≫ (pullbackPushforwardAdjunction i).unit.app M =
    (pullbackPushforwardAdjunction i).unit.app M ≫
      (pushforward i).map ((pullback i).map mul) at hnat
  rw [principalClosedFiber_pullback_map_mulByGlobalSection_eq_zero,
    Functor.map_zero, comp_zero] at hnat
  exact hnat

@[reassoc (attr := simp)]
lemma cokernel_π_principalClosedFiberCokernelToPushforwardPullback (M : X.Modules) :
    cokernel.π (M.mulByGlobalSection ((baseRingHom p).hom r)) ≫
        principalClosedFiberCokernelToPushforwardPullback (r := r) p M =
      (pullbackPushforwardAdjunction (principalClosedFiberι (r := r) p)).unit.app M := by
  apply cokernel.π_desc

variable {A : CommRingCat.{u}}

/-- The affine base change of the principal quotient is the spectrum of the
corresponding principal quotient of the affine source ring. -/
noncomputable def affinePrincipalFiberIso (f : R ⟶ A) :
    Limits.pullback (Spec.map f) (Spec.map (principalClosedFiberRingHom r)) ≅
      Spec (principalClosedFiberRing (f.hom r)) := by
  letI : Algebra R A := f.hom.toAlgebra
  letI : Algebra R (R ⧸ Ideal.span {r}) :=
    (principalClosedFiberRingHom r).hom.toAlgebra
  let eIdeal : (Ideal.span {r}).map (algebraMap R A) =
      Ideal.span {(algebraMap R A) r} := by
    rw [Ideal.map_span]
    congr
    exact Set.image_singleton
  let e : (A ⧸ Ideal.span {(algebraMap R A) r}) ≃ₐ[A]
      TensorProduct R A (R ⧸ Ideal.span {r}) :=
    (Ideal.quotientEquivAlgOfEq A eIdeal.symm).trans
      (Algebra.TensorProduct.quotIdealMapEquivTensorQuot A (Ideal.span {r}))
  exact pullbackSpecIso R A (R ⧸ Ideal.span {r}) ≪≫
    Scheme.Spec.mapIso e.toRingEquiv.toCommRingCatIso.op

@[reassoc]
lemma affinePrincipalFiberIso_inv_fst (f : R ⟶ A) :
    (affinePrincipalFiberIso (r := r) f).inv ≫
        Limits.pullback.fst (Spec.map f)
          (Spec.map (principalClosedFiberRingHom r)) =
      Spec.map (principalClosedFiberRingHom (f.hom r)) := by
  letI : Algebra R A := f.hom.toAlgebra
  letI : Algebra R (R ⧸ Ideal.span {r}) :=
    (principalClosedFiberRingHom r).hom.toAlgebra
  change (affinePrincipalFiberIso (r := r) f).inv ≫
      Limits.pullback.fst
        (Spec.map (CommRingCat.ofHom (algebraMap R A)))
        (Spec.map (CommRingCat.ofHom
          (algebraMap R (R ⧸ Ideal.span {r})))) =
    Spec.map (CommRingCat.ofHom
      (algebraMap A (A ⧸ Ideal.span {(algebraMap R A) r})))
  simp only [affinePrincipalFiberIso, Iso.trans_inv,
    Functor.mapIso_inv, Iso.op_inv, Iso.unop_hom]
  erw [Category.assoc, pullbackSpecIso_inv_fst]
  rw [Scheme.Spec_map]
  rw [← Spec.map_comp]
  rw [Spec.map_inj]
  ext a
  exact ((Ideal.quotientEquivAlgOfEq A (by
    symm
    rw [Ideal.map_span]
    congr
    exact Set.image_singleton)).trans
      (Algebra.TensorProduct.quotIdealMapEquivTensorQuot A
      (Ideal.span {r}))).symm.commutes a

@[reassoc]
lemma affinePrincipalFiberIso_hom_quotientMap (f : R ⟶ A) :
    (affinePrincipalFiberIso (r := r) f).hom ≫
        Spec.map (principalClosedFiberRingHom (f.hom r)) =
      Limits.pullback.fst (Spec.map f)
        (Spec.map (principalClosedFiberRingHom r)) := by
  rw [← affinePrincipalFiberIso_inv_fst (r := r) f,
    ← Category.assoc, Iso.hom_inv_id, Category.id_comp]

/-- Pullback along a scheme isomorphism, regarded as an equivalence of module-sheaf
categories. -/
noncomputable def pullbackEquivalenceOfIso {Y Z : Scheme.{u}} (e : Y ≅ Z) :
    Z.Modules ≌ Y.Modules :=
  CategoryTheory.Equivalence.mk (pullback e.hom) (pullback e.inv)
    (((pullbackComp e.inv e.hom) ≪≫
      (pullbackCongr e.inv_hom_id) ≪≫ pullbackId Z).symm)
    ((pullbackComp e.hom e.inv) ≪≫
      (pullbackCongr e.hom_inv_id) ≪≫ pullbackId Y)

lemma isIso_pullbackPushforwardAdjunction_unit_of_iso
    {Y Z : Scheme.{u}} (e : Y ≅ Z) (N : Z.Modules) :
    IsIso ((pullbackPushforwardAdjunction e.hom).unit.app N) := by
  let E := pullbackEquivalenceOfIso e
  letI : (pullback e.hom).Full := E.fullyFaithfulFunctor.full
  letI : (pullback e.hom).Faithful := E.fullyFaithfulFunctor.faithful
  haveI : IsIso (pullbackPushforwardAdjunction e.hom).unit :=
    (pullbackPushforwardAdjunction e.hom).unit_isIso_of_L_fully_faithful
  infer_instance

/-- Replacing the source of a morphism by an isomorphic scheme does not change
pushforward-after-pullback. -/
noncomputable def pushPullIsoOfSourceIso {Y Z W : Scheme.{u}}
    (e : Y ≅ Z) (g : Z ⟶ W) (f : Y ⟶ W) (h : e.hom ≫ g = f)
    (N : W.Modules) :
    (pushforward f).obj ((pullback f).obj N) ≅
      (pushforward g).obj ((pullback g).obj N) := by
  subst f
  let P := (pullback g).obj N
  let epb : (pullback e.hom).obj P ≅
      (pullback (e.hom ≫ g)).obj N :=
    (pullbackComp e.hom g).app N
  letI : IsIso ((pullbackPushforwardAdjunction e.hom).unit.app P) :=
    isIso_pullbackPushforwardAdjunction_unit_of_iso e P
  exact (pushforward (e.hom ≫ g)).mapIso epb.symm ≪≫
    (pushforwardComp e.hom g).symm.app ((pullback e.hom).obj P) ≪≫
    (pushforward g).mapIso
      (asIso ((pullbackPushforwardAdjunction e.hom).unit.app P)).symm

@[reassoc]
lemma unit_pushPullIsoOfSourceIso_hom {Y Z W : Scheme.{u}}
    (e : Y ≅ Z) (g : Z ⟶ W) (f : Y ⟶ W) (h : e.hom ≫ g = f)
    (N : W.Modules) :
    (pullbackPushforwardAdjunction f).unit.app N ≫
        (pushPullIsoOfSourceIso e g f h N).hom =
      (pullbackPushforwardAdjunction g).unit.app N := by
  subst f
  let P := (pullback g).obj N
  letI : IsIso ((pullbackPushforwardAdjunction e.hom).unit.app P) :=
    isIso_pullbackPushforwardAdjunction_unit_of_iso e P
  simp only [pushPullIsoOfSourceIso, Iso.trans_hom, Functor.mapIso_hom,
    Iso.symm_hom, asIso_inv, Category.assoc]
  let adjComp := (pullbackPushforwardAdjunction g).comp
    (pullbackPushforwardAdjunction e.hom)
  let adjComposite := pullbackPushforwardAdjunction (e.hom ≫ g)
  have hconj := CategoryTheory.unit_conjugateEquiv adjComp adjComposite
    (pullbackComp e.hom g).inv N
  rw [conjugateEquiv_pullbackComp_inv] at hconj
  have hunit : adjComp.unit.app N =
      adjComposite.unit.app N ≫
        (pushforward (e.hom ≫ g)).map
          ((pullbackComp e.hom g).inv.app N) ≫
        (pushforwardComp e.hom g).inv.app
          ((pullback g ⋙ pullback e.hom).obj N) := by
    rw [← Category.assoc, ← hconj, Category.assoc,
      Iso.hom_inv_id_app]
    exact (Category.comp_id _).symm
  change adjComposite.unit.app N ≫
      (pushforward (e.hom ≫ g)).map
        ((pullbackComp e.hom g).inv.app N) ≫
      (pushforwardComp e.hom g).inv.app
        ((pullback g ⋙ pullback e.hom).obj N) ≫
      (pushforward g).map
        (inv ((pullbackPushforwardAdjunction e.hom).unit.app P)) = _
  calc
    adjComposite.unit.app N ≫
          (pushforward (e.hom ≫ g)).map
            ((pullbackComp e.hom g).inv.app N) ≫
          (pushforwardComp e.hom g).inv.app
            ((pullback g ⋙ pullback e.hom).obj N) ≫
          (pushforward g).map
            (inv ((pullbackPushforwardAdjunction e.hom).unit.app P)) =
        (adjComposite.unit.app N ≫
          (pushforward (e.hom ≫ g)).map
            ((pullbackComp e.hom g).inv.app N) ≫
          (pushforwardComp e.hom g).inv.app
            ((pullback g ⋙ pullback e.hom).obj N)) ≫
          (pushforward g).map
            (inv ((pullbackPushforwardAdjunction e.hom).unit.app P)) := by
          simp only [Category.assoc]
    _ = adjComp.unit.app N ≫
          (pushforward g).map
            (inv ((pullbackPushforwardAdjunction e.hom).unit.app P)) := by
          rw [← hunit]
    _ = ((pullbackPushforwardAdjunction g).unit.app N ≫
          (pushforward g).map
            ((pullbackPushforwardAdjunction e.hom).unit.app P)) ≫
          (pushforward g).map
            (inv ((pullbackPushforwardAdjunction e.hom).unit.app P)) := by
          rw [show adjComp.unit.app N =
              (pullbackPushforwardAdjunction g).unit.app N ≫
                (pushforward g).map
                  ((pullbackPushforwardAdjunction e.hom).unit.app P) from by
            simp [adjComp, P, Adjunction.comp]]
    _ = (pullbackPushforwardAdjunction g).unit.app N := by simp

/-- On an affine base, the pullback-defined principal fibre gives the same
pushforward-after-pullback object as the explicit principal quotient spectrum. -/
noncomputable def affinePrincipalFiberPushPullIso (f : R ⟶ A)
    (N : (Spec A).Modules) :
    (pushforward (Limits.pullback.fst (Spec.map f)
      (Spec.map (principalClosedFiberRingHom r)))).obj
        ((pullback (Limits.pullback.fst (Spec.map f)
          (Spec.map (principalClosedFiberRingHom r)))).obj N) ≅
      (pushforward (Spec.map (principalClosedFiberRingHom (f.hom r)))).obj
        ((pullback (Spec.map (principalClosedFiberRingHom (f.hom r)))).obj N) :=
  pushPullIsoOfSourceIso (affinePrincipalFiberIso (r := r) f)
    (Spec.map (principalClosedFiberRingHom (f.hom r)))
    (Limits.pullback.fst (Spec.map f)
      (Spec.map (principalClosedFiberRingHom r)))
    (affinePrincipalFiberIso_hom_quotientMap (r := r) f) N

lemma baseRingHom_specMap_apply (f : R ⟶ A) :
    (baseRingHom (Spec.map f)).hom r =
      (Scheme.ΓSpecIso A).inv.hom (f.hom r) := by
  change (((Scheme.ΓSpecIso R).inv ≫ (Spec.map f).appTop).hom r) = _
  rw [← Scheme.ΓSpecIso_inv_naturality f]
  rfl

/-- The affine principal-fibre cokernel theorem with the fibre presented as the
categorical pullback over the base spectrum. -/
noncomputable def affinePullbackFiberCokernelIso (f : R ⟶ A)
    (N : (Spec A).Modules) [N.IsQuasicoherent] :
    cokernel (N.mulByGlobalSection ((baseRingHom (Spec.map f)).hom r)) ≅
      (pushforward (Limits.pullback.fst (Spec.map f)
        (Spec.map (principalClosedFiberRingHom r)))).obj
          ((pullback (Limits.pullback.fst (Spec.map f)
            (Spec.map (principalClosedFiberRingHom r)))).obj N) := by
  let a := N.mulByGlobalSection ((baseRingHom (Spec.map f)).hom r)
  let b := N.mulByGlobalSection ((Scheme.ΓSpecIso A).inv (f.hom r))
  let e : N ≅ N := Iso.refl N
  have hab : a ≫ e.hom = e.hom ≫ b := by
    dsimp only [a, b, e, Iso.refl_hom]
    rw [Category.comp_id, Category.id_comp, baseRingHom_specMap_apply]
  exact cokernel.mapIso a b e e hab ≪≫
    cokernelMulByGlobalSectionIsoPushforwardPullbackSpec (f.hom r) N ≪≫
    (affinePrincipalFiberPushPullIso (r := r) f N).symm

@[reassoc]
lemma cokernel_π_affinePullbackFiberCokernelIso (f : R ⟶ A)
    (N : (Spec A).Modules) [N.IsQuasicoherent] :
    cokernel.π
          (N.mulByGlobalSection ((baseRingHom (Spec.map f)).hom r)) ≫
        (affinePullbackFiberCokernelIso (r := r) f N).hom =
      (pullbackPushforwardAdjunction
        (Limits.pullback.fst (Spec.map f)
          (Spec.map (principalClosedFiberRingHom r)))).unit.app N := by
  let a := N.mulByGlobalSection ((baseRingHom (Spec.map f)).hom r)
  let b := N.mulByGlobalSection ((Scheme.ΓSpecIso A).inv (f.hom r))
  let e : N ≅ N := Iso.refl N
  have hab : a ≫ e.hom = e.hom ≫ b := by
    dsimp only [a, b, e, Iso.refl_hom]
    rw [Category.comp_id, Category.id_comp, baseRingHom_specMap_apply]
  change cokernel.π a ≫
      ((cokernel.mapIso a b e e hab ≪≫
        cokernelMulByGlobalSectionIsoPushforwardPullbackSpec (f.hom r) N ≪≫
        (affinePrincipalFiberPushPullIso (r := r) f N).symm).hom) = _
  simp only [Iso.trans_hom, Category.assoc]
  have hπmap : cokernel.π a ≫
      (cokernel.mapIso a b e e hab).hom = cokernel.π b := by
    simp [cokernel.mapIso_hom, e]
  rw [← cancel_mono (affinePrincipalFiberPushPullIso (r := r) f N).hom]
  simp only [Category.assoc, Iso.inv_hom_id_assoc]
  rw [← Category.assoc, hπmap]
  dsimp only [b]
  rw [cokernel_π_cokernelMulByGlobalSectionIsoPushforwardPullbackSpec_assoc]
  simpa [affinePrincipalFiberPushPullIso] using
    (unit_pushPullIsoOfSourceIso_hom
    (affinePrincipalFiberIso (r := r) f)
    (Spec.map (principalClosedFiberRingHom (f.hom r)))
    (Limits.pullback.fst (Spec.map f)
      (Spec.map (principalClosedFiberRingHom r)))
    (affinePrincipalFiberIso_hom_quotientMap (r := r) f) N).symm

lemma principalClosedFiberCokernelToPushforwardPullback_eq_affineIso_hom
    (f : R ⟶ A) (N : (Spec A).Modules) [N.IsQuasicoherent] :
    principalClosedFiberCokernelToPushforwardPullback (r := r) (Spec.map f) N =
      (affinePullbackFiberCokernelIso (r := r) f N).hom := by
  rw [← cancel_epi
    (cokernel.π
      (N.mulByGlobalSection ((baseRingHom (Spec.map f)).hom r)))]
  rw [cokernel_π_principalClosedFiberCokernelToPushforwardPullback,
    cokernel_π_affinePullbackFiberCokernelIso]
  rfl

instance isIso_principalClosedFiberCokernelToPushforwardPullback_specMap
    (f : R ⟶ A) (N : (Spec A).Modules) [N.IsQuasicoherent] :
    IsIso (principalClosedFiberCokernelToPushforwardPullback
      (r := r) (Spec.map f) N) := by
  rw [principalClosedFiberCokernelToPushforwardPullback_eq_affineIso_hom]
  infer_instance

instance isIso_principalClosedFiberCokernelToPushforwardPullback_specSource
    (p' : Spec A ⟶ Spec R) (N : (Spec A).Modules) [N.IsQuasicoherent] :
    IsIso (principalClosedFiberCokernelToPushforwardPullback (r := r) p' N) := by
  rw [← Spec.map_preimage p']
  infer_instance

/-- Restriction along an open immersion carries multiplication by a global function
to multiplication by its restriction. -/
lemma restrictFunctor_map_mulByGlobalSection {Y Z : Scheme.{u}}
    (j : Y ⟶ Z) [IsOpenImmersion j] (N : Z.Modules) (t : Γ(Z, ⊤)) :
    (restrictFunctor j).map (N.mulByGlobalSection t) =
      ((restrictFunctor j).obj N).mulByGlobalSection (j.appTop.hom t) := by
  apply Modules.hom_ext _ _ fun U ↦ ?_
  ext x
  change
    ((Z.presheaf.map (homOfLE (show j ''ᵁ U ≤ ⊤ from le_top)).op).hom t) •
        (show Γ(N, j ''ᵁ U) from x) =
      (j.appIso U).inv.hom
        ((Y.presheaf.map (homOfLE (show U ≤ ⊤ from le_top)).op).hom
          (j.appTop.hom t)) • (show Γ(N, j ''ᵁ U) from x)
  congr 1
  have h := j.appLE_appIso_inv
    (U := (⊤ : Z.Opens)) (V := U)
    (show U ≤ j ⁻¹ᵁ (⊤ : Z.Opens) from le_top)
  exact (CategoryTheory.congr_fun h t).symm

lemma appTop_baseRingHom_apply {Y : Scheme.{u}} (j : Y ⟶ X) :
    j.appTop.hom ((baseRingHom p).hom r) =
      (baseRingHom (j ≫ p)).hom r := by
  rfl

/-- Restriction along an open immersion commutes with the cokernel of multiplication
by a global function. -/
noncomputable def restrictCokernelMulIso {Y Z : Scheme.{u}}
    (j : Y ⟶ Z) [IsOpenImmersion j] (N : Z.Modules) (t : Γ(Z, ⊤)) :
    (restrictFunctor j).obj (cokernel (N.mulByGlobalSection t)) ≅
      cokernel (((restrictFunctor j).obj N).mulByGlobalSection (j.appTop.hom t)) :=
  PreservesCokernel.iso (restrictFunctor j) (N.mulByGlobalSection t) ≪≫
    cokernelIsoOfEq (restrictFunctor_map_mulByGlobalSection j N t)

@[reassoc]
lemma map_cokernelπ_restrictCokernelMulIso_hom {Y Z : Scheme.{u}}
    (j : Y ⟶ Z) [IsOpenImmersion j] (N : Z.Modules) (t : Γ(Z, ⊤)) :
    (restrictFunctor j).map (cokernel.π (N.mulByGlobalSection t)) ≫
        (restrictCokernelMulIso j N t).hom =
      cokernel.π (((restrictFunctor j).obj N).mulByGlobalSection
        (j.appTop.hom t)) := by
  simp [restrictCokernelMulIso]

@[reassoc]
lemma unit_restrictPullbackIsoOfOpenSquare_hom
    {Y Z W P : Scheme.{u}} (i : W ⟶ Z) (g : P ⟶ Y)
    (k : P ⟶ W) (j : Y ⟶ Z) [IsOpenImmersion k] [IsOpenImmersion j]
    (hsq : g ≫ j = k ≫ i) (N : Z.Modules) :
    (pullbackPushforwardAdjunction i).unit.app N ≫
        (pushforward i).map
          ((restrictAdjunction k).unit.app ((pullback i).obj N)) ≫
        (pushforwardCompIsoOfSquare i g k j hsq).hom.app
          ((pullback i ⋙ restrictFunctor k).obj N) ≫
        (pushforward g ⋙ pushforward j).map
          ((restrictPullbackIsoOfOpenSquare i g k j hsq).hom.app N) =
      (restrictAdjunction j).unit.app N ≫
        (pushforward j).map
          ((pullbackPushforwardAdjunction g).unit.app
            ((restrictFunctor j).obj N)) := by
  let adjA := ((pullbackPushforwardAdjunction i).comp (restrictAdjunction k)).ofNatIsoRight
    (pushforwardCompIsoOfSquare i g k j hsq)
  let adjB := (restrictAdjunction j).comp (pullbackPushforwardAdjunction g)
  simpa [adjA, adjB, restrictPullbackIsoOfOpenSquare, Adjunction.comp]
    using Adjunction.unit_leftAdjointUniq_hom_app adjA adjB N

@[reassoc]
lemma map_unit_restrictPushPullIsoPullbackRestrict_hom
    {Y Z W : Scheme.{u}} (j : Y ⟶ Z) [IsOpenImmersion j]
    (i : W ⟶ Z) (N : Z.Modules) :
    (restrictFunctor j).map
        ((pullbackPushforwardAdjunction i).unit.app N) ≫
      (restrictPushPullIsoPullbackRestrict j i N).hom =
    (pullbackPushforwardAdjunction
      (Limits.pullback.fst j i)).unit.app ((restrictFunctor j).obj N) := by
  let g := Limits.pullback.fst j i
  let k := Limits.pullback.snd j i
  let hsq : g ≫ j = k ≫ i := Limits.pullback.condition
  let hopen : ∀ U : Y.Opens, k ''ᵁ (g ⁻¹ᵁ U) = i ⁻¹ᵁ (j ''ᵁ U) :=
    image_preimage_eq_pullback_openSquare j i
  let L := (pullback i).obj N
  let bc := restrictPushforwardIsoOfOpenSquare i g k j hsq hopen L
  let α := restrictPullbackIsoOfOpenSquare i g k j hsq
  change (restrictFunctor j).map
      ((pullbackPushforwardAdjunction i).unit.app N) ≫
        (bc ≪≫ (pushforward g).mapIso (α.app N)).hom =
      (pullbackPushforwardAdjunction g).unit.app ((restrictFunctor j).obj N)
  refine ((restrictAdjunction j).homEquiv N _).injective ?_
  rw [Adjunction.homEquiv_apply, Adjunction.homEquiv_apply]
  simp only [Iso.trans_hom, Functor.mapIso_hom, Functor.map_comp,
    Category.assoc]
  rw [← cancel_mono ((pushforwardComp g j).hom.app
    ((restrictFunctor j ⋙ pullback g).obj N))]
  have hadj := unit_restrictPullbackIsoOfOpenSquare_hom
    i g k j hsq N
  have hadj' := congrArg (fun q ↦ q ≫
    (pushforwardComp g j).hom.app
      ((restrictFunctor j ⋙ pullback g).obj N)) hadj
  simp only [pushforwardCompIsoOfSquare, Iso.trans_hom,
    Iso.symm_hom, NatTrans.comp_app, Category.assoc] at hadj'
  rw [← (pushforwardComp g j).inv.naturality_assoc (α.hom.app N)] at hadj'
  simp only [Category.assoc, Iso.inv_hom_id_app, Category.comp_id] at hadj'
  have hadjCommon :
      (pullbackPushforwardAdjunction i).unit.app N ≫
          (pushforward i).map
            ((restrictAdjunction k).unit.app L) ≫
          (pushforwardComp k i).hom.app
            ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforwardCongr hsq.symm).hom.app
            ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforward (g ≫ j)).map (α.hom.app N) =
        (restrictAdjunction j).unit.app N ≫
          (pushforward j).map
            ((pullbackPushforwardAdjunction g).unit.app
              ((restrictFunctor j).obj N)) ≫
          (pushforwardComp g j).hom.app
            ((restrictFunctor j ⋙ pullback g).obj N) := by
    exact hadj'
  have hunit :
      (restrictAdjunction j).unit.app N ≫
          (pushforward j).map ((restrictFunctor j).map
            ((pullbackPushforwardAdjunction i).unit.app N)) =
        (pullbackPushforwardAdjunction i).unit.app N ≫
          (restrictAdjunction j).unit.app ((pushforward i).obj L) := by
    simpa only [Functor.id_obj, Functor.id_map, Functor.comp_obj,
      Functor.comp_map] using
        ((restrictAdjunction j).unit.naturality
          ((pullbackPushforwardAdjunction i).unit.app N)).symm
  have hcomp :
      (pushforward j).map ((pushforward g).map ((α.app N).hom)) ≫
          (pushforwardComp g j).hom.app
            ((restrictFunctor j ⋙ pullback g).obj N) =
        (pushforwardComp g j).hom.app
            ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforward (g ≫ j)).map ((α.app N).hom) := by
    simpa only [Functor.comp_obj, Functor.comp_map] using
      (pushforwardComp g j).hom.naturality ((α.app N).hom)
  have hbc :
      (restrictAdjunction j).unit.app ((pushforward i).obj L) ≫
          (pushforward j).map bc.hom ≫
          (pushforwardComp g j).hom.app
            ((pullback i ⋙ restrictFunctor k).obj N) =
        (pushforward i).map ((restrictAdjunction k).unit.app L) ≫
          (pushforwardComp k i).hom.app
            ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforwardCongr hsq.symm).hom.app
            ((pullback i ⋙ restrictFunctor k).obj N) := by
    simpa only [bc, L, Functor.comp_obj] using
      unit_restrictPushforwardIsoOfOpenSquare_hom
        i g k j hsq hopen L
  have hbcPost :
      (restrictAdjunction j).unit.app ((pushforward i).obj L) ≫
          (pushforward j).map bc.hom ≫
          (pushforwardComp g j).hom.app
              ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforward (g ≫ j)).map ((α.app N).hom) =
        (pushforward i).map ((restrictAdjunction k).unit.app L) ≫
          (pushforwardComp k i).hom.app
              ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforwardCongr hsq.symm).hom.app
              ((pullback i ⋙ restrictFunctor k).obj N) ≫
          (pushforward (g ≫ j)).map ((α.app N).hom) := by
    simpa only [Category.assoc] using congrArg
      (fun q ↦ q ≫ (pushforward (g ≫ j)).map ((α.app N).hom)) hbc
  simp only [Category.assoc]
  rw [← Category.assoc, hunit]
  simp only [Category.assoc]
  rw [hcomp]
  rw [hbcPost]
  exact hadjCommon

/-- On an affine open of the source, the restriction of the canonical
principal-fibre cokernel comparison is an isomorphism. -/
instance isIso_restrict_principalClosedFiberCokernelToPushforwardPullback_spec
    {A : CommRingCat.{u}} (j : Spec A ⟶ X) [IsOpenImmersion j]
    (M : X.Modules) [M.IsQuasicoherent] :
    IsIso ((restrictFunctor j).map
      (principalClosedFiberCokernelToPushforwardPullback (r := r) p M)) := by
  let q := Spec.map (principalClosedFiberRingHom r)
  let i := principalClosedFiberι (r := r) p
  let g := Limits.pullback.fst j i
  let i' := principalClosedFiberι (r := r) (j ≫ p)
  let e := Limits.pullbackRightPullbackFstIso p q j
  let N := (restrictFunctor j).obj M
  let sourceIso₀ := restrictCokernelMulIso j M ((baseRingHom p).hom r)
  have hmul :
      N.mulByGlobalSection (j.appTop.hom ((baseRingHom p).hom r)) =
        N.mulByGlobalSection ((baseRingHom (j ≫ p)).hom r) := by
    rw [appTop_baseRingHom_apply]
  let sourceIso := sourceIso₀ ≪≫ cokernelIsoOfEq hmul
  have he : e.hom ≫ i' = g := by
    exact Limits.pullbackRightPullbackFstIso_hom_fst p q j
  let fibreIso := pushPullIsoOfSourceIso e i' g he N
  let targetIso := restrictPushPullIsoPullbackRestrict j i M
  let localIso := sourceIso ≪≫
    asIso (principalClosedFiberCokernelToPushforwardPullback
      (r := r) (j ≫ p) N) ≪≫ fibreIso.symm
  have hcomparison :
      (restrictFunctor j).map
          (principalClosedFiberCokernelToPushforwardPullback (r := r) p M) ≫
        targetIso.hom = localIso.hom := by
    rw [← cancel_epi ((restrictFunctor j).map
      (cokernel.π
        (M.mulByGlobalSection ((baseRingHom p).hom r))))]
    have hleft :
        (restrictFunctor j).map
              (cokernel.π
                (M.mulByGlobalSection ((baseRingHom p).hom r))) ≫
            (restrictFunctor j).map
              (principalClosedFiberCokernelToPushforwardPullback (r := r) p M) ≫
            targetIso.hom =
          (pullbackPushforwardAdjunction g).unit.app N := by
      rw [← (restrictFunctor j).map_comp_assoc]
      rw [cokernel_π_principalClosedFiberCokernelToPushforwardPullback]
      simpa only [i, g, N, targetIso] using
        map_unit_restrictPushPullIsoPullbackRestrict_hom j i M
    have hright :
        (restrictFunctor j).map
              (cokernel.π
                (M.mulByGlobalSection ((baseRingHom p).hom r))) ≫
            localIso.hom =
          (pullbackPushforwardAdjunction g).unit.app N := by
      simp only [localIso, sourceIso, Iso.trans_hom, Category.assoc]
      have hsource :
          (restrictFunctor j).map
                (cokernel.π
                  (M.mulByGlobalSection ((baseRingHom p).hom r))) ≫
              sourceIso₀.hom =
            cokernel.π
              (N.mulByGlobalSection
                (j.appTop.hom ((baseRingHom p).hom r))) := by
        simpa only [sourceIso₀, N] using
          map_cokernelπ_restrictCokernelMulIso_hom
            j M ((baseRingHom p).hom r)
      rw [← Category.assoc, hsource]
      rw [π_comp_cokernelIsoOfEq_hom_assoc hmul]
      simp only [asIso_hom]
      rw [cokernel_π_principalClosedFiberCokernelToPushforwardPullback_assoc]
      rw [← cancel_mono fibreIso.hom]
      simp only [Category.assoc, Iso.symm_hom, Iso.inv_hom_id,
        Category.comp_id]
      simpa only [fibreIso] using
        (unit_pushPullIsoOfSourceIso_hom e i' g he N).symm
    rw [hleft, hright]
  haveI : IsIso localIso.hom := inferInstance
  haveI : IsIso
      ((restrictFunctor j).map
          (principalClosedFiberCokernelToPushforwardPullback (r := r) p M) ≫
        targetIso.hom) := hcomparison ▸ inferInstance
  exact IsIso.of_isIso_comp_right _ targetIso.hom

/-- The canonical cokernel comparison with pullback to a principal fibre and
pushforward back to the source is an isomorphism for every quasicoherent module. -/
instance isIso_principalClosedFiberCokernelToPushforwardPullback
    (M : X.Modules) [M.IsQuasicoherent] :
    IsIso (principalClosedFiberCokernelToPushforwardPullback (r := r) p M) := by
  apply isIso_of_restrict_openCover _ X.affineOpenCover.openCover
  intro a
  change IsIso ((restrictFunctor (X.affineOpenCover.f a)).map
    (principalClosedFiberCokernelToPushforwardPullback (r := r) p M))
  infer_instance


end AlgebraicGeometry.Scheme.Modules

end
