module

public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Topology
public import Mathlib.RingTheory.GradedAlgebra.Radical

/-!
# A Nullstellensatz for relevant homogeneous primes

The points of `ProjectiveSpectrum 𝒜` are the homogeneous primes that do **not** contain the
irrelevant ideal, so the naive Nullstellensatz can fail there: `zeroLocus 𝒜 (irrelevant 𝒜)` is
empty without the irrelevant ideal being the unit ideal.  The statement is repaired as soon as
the element being tested has positive degree, because a homogeneous prime avoiding such an
element is automatically relevant.

This is the algebraic core of both halves of "every section of `M~` over `D₊(f)` is a single
fraction `m / f^N`" (Hartshorne II.5.11): the injectivity half applies it to the annihilator of a
homogeneous element, and the surjectivity half to the ideal generated by a finite cover.

## Main results

* `ProjectiveSpectrum.exists_pow_mem_of_forall_not_le`: if every point at which a positive-degree
  homogeneous `g` is nonzero fails to contain `I`, then `g ^ N ∈ I` for some `N`.
* `ProjectiveSpectrum.exists_pow_mem_span_of_basicOpen_le_iSup`: if `D₊(f)` is covered by the
  `D₊(g i)` for `i` in a finite index type, then `f ^ N` lies in the ideal generated by the
  `g i`.
-/

@[expose] public section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open TopologicalSpace

namespace ProjectiveSpectrum

variable {A σ : Type*} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
variable (𝒜 : ℕ → σ) [GradedRing 𝒜]

/-- A homogeneous element of positive degree lies in the irrelevant ideal. -/
theorem mem_irrelevant_of_mem_of_pos {e : ℕ} (he : 0 < e) {g : A} (hg : g ∈ 𝒜 e) :
    g ∈ HomogeneousIdeal.irrelevant 𝒜 := by
  rw [HomogeneousIdeal.mem_irrelevant_iff]
  rw [GradedRing.proj_apply, DirectSum.decompose_of_mem 𝒜 hg,
    DirectSum.of_eq_of_ne _ _ _ (by omega)]
  simp

variable {𝒜}

/-- **A Nullstellensatz for relevant homogeneous primes.**  If a homogeneous ideal `I` is
contained in no point of `D₊(g)`, for `g` homogeneous of positive degree, then some power of
`g` lies in `I`.

The degree hypothesis is what rules out the irrelevant ideal: a homogeneous prime avoiding a
positive-degree element cannot contain the irrelevant ideal, hence *is* a point of the
projective spectrum. -/
theorem exists_pow_mem_of_forall_not_le {I : Ideal A} (hI : I.IsHomogeneous 𝒜)
    {e : ℕ} (he : 0 < e) {g : A} (hg : g ∈ 𝒜 e)
    (h : ∀ x : ProjectiveSpectrum 𝒜,
      x ∈ basicOpen 𝒜 g → ¬ I ≤ x.asHomogeneousIdeal.toIdeal) :
    ∃ N : ℕ, g ^ N ∈ I := by
  have hrad : g ∈ I.radical := by
    rw [hI.radical_eq]
    refine Ideal.mem_sInf.2 ?_
    rintro J ⟨hJhom, hIJ, hJprime⟩
    by_contra hgJ
    refine h ⟨⟨J, hJhom⟩, hJprime, fun hle ↦ hgJ ?_⟩ hgJ hIJ
    exact hle (mem_irrelevant_of_mem_of_pos 𝒜 he hg)
  exact hrad

/-- If the basic open of a positive-degree homogeneous `f` is covered by the basic opens of a
family `g`, then a power of `f` lies in the ideal generated by the `g i`.

No finiteness is needed: the conclusion is membership in the span of the whole family. -/
theorem exists_pow_mem_span_of_basicOpen_le_iSup {ι : Type*} {g : ι → A} {n : ι → ℕ}
    (hg : ∀ i, g i ∈ 𝒜 (n i)) {e : ℕ} (he : 0 < e) {f : A} (hf : f ∈ 𝒜 e)
    (hcover : basicOpen 𝒜 f ≤ ⨆ i, basicOpen 𝒜 (g i)) :
    ∃ N : ℕ, f ^ N ∈ Ideal.span (Set.range g) := by
  refine exists_pow_mem_of_forall_not_le ?_ he hf ?_
  · exact Ideal.homogeneous_span 𝒜 _ (by rintro _ ⟨i, rfl⟩; exact ⟨n i, hg i⟩)
  · intro x hx hle
    obtain ⟨i, hxi⟩ := Opens.mem_iSup.1 (hcover hx)
    exact hxi (hle (Ideal.subset_span ⟨i, rfl⟩))

end ProjectiveSpectrum
