module

public import StacksAndModuli.API.ProjectiveGradedCoherent
public import StacksAndModuli.API.MvPolynomialDegreeZero
public import Mathlib.Algebra.Category.ModuleCat.Monoidal.Basic

/-!
# A graded free module generated by an arbitrary coefficient module

The finite-generator construction `GradedModule.freeGenHom` starts from a finite free
module in one degree.  Grassmannian reconstruction instead starts from the kernel of a
finite locally free quotient.  That kernel is projective but need not be free on an affine
base, so it needs the coordinate-free analogue

`S(-d₀) ⊗ K`.

This file constructs that graded module and its universal map to a graded module `M` from
a coefficient-linear map `K → M_d₀`.  Its cokernel is the honest graded quotient by
the relations generated by `K` in degree `d₀`; its first two pieces are the algebraic
degree-`d₀` and degree-`d₀+1` quotients used in the Hilbert--Grassmannian
construction.

Main declarations:

* `GradedModule.tensorRight`;
* `GradedModule.freeOnModule`;
* `GradedModule.freeOnModuleHom`;
* `GradedModule.freeOnModuleSelfLinearEquiv` and
  `GradedModule.freeOnModuleHom_app_self`.
-/

@[expose] public section

noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.MonoidalCategory TensorProduct

namespace AlgebraicGeometry.ProjectiveSpace.GradedModule

variable {R : Type u} [CommRing R] {n : ℕ}

/-- Tensor every piece and every variable-action map of a graded module on the right by a
fixed coefficient module. -/
noncomputable def tensorRight (M : GradedModule R n) (K : ModuleCat.{u} R) :
    GradedModule R n where
  obj d := M.obj d ⊗ K
  mulX i d := M.mulX i d ▷ K
  mulX_comm i j d := by
    rw [← MonoidalCategory.comp_whiskerRight,
      ← MonoidalCategory.comp_whiskerRight, M.mulX_comm]

/-- The graded `R[x₀,…,xₙ]`-module freely generated by an arbitrary `R`-module
`K` in degree `d₀`. -/
noncomputable def freeOnModule (K : ModuleCat.{u} R) (d₀ : ℤ) :
    GradedModule R n :=
  tensorRight ((structureModule R n).twist (-d₀)) K

/-- The degree-zero homogeneous piece, in the integer-indexed polynomial-piece model, is
the coefficient ring. -/
noncomputable def polySubmoduleZeroLinearEquiv :
    polySubmodule R n 0 ≃ₗ[R] R :=
  LinearEquiv.ofEq (polySubmodule R n 0)
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R 0)
      (polySubmodule_of_nonneg R n (by omega)) ≪≫ₗ
    { (MvPolynomial.degreeZeroRingEquiv (Fin (n + 1)) R).symm.toAddEquiv with
      map_smul' := by
        intro a p
        change MvPolynomial.coeff 0 (a • p.1) = a * MvPolynomial.coeff 0 p.1
        simp }

/-- The generating-degree piece of `S(-d₀) ⊗ K` is canonically `K`. -/
noncomputable def freeOnModuleSelfLinearEquiv (K : ModuleCat.{u} R) (d₀ : ℤ) :
    (freeOnModule (n := n) K d₀).obj d₀ ≃ₗ[R] K := by
  change (polySubmodule R n (d₀ + -d₀) ⊗[R] K) ≃ₗ[R] K
  exact
    (LinearEquiv.ofEq (polySubmodule R n (d₀ + -d₀))
      (polySubmodule R n 0) (by congr 1; omega)).rTensor K ≪≫ₗ
    (polySubmoduleZeroLinearEquiv (R := R) (n := n)).rTensor K ≪≫ₗ
    TensorProduct.lid R K

@[simp]
lemma polySubmoduleZeroLinearEquiv_apply (p : polySubmodule R n 0) :
    polySubmoduleZeroLinearEquiv (R := R) (n := n) p =
      MvPolynomial.coeff 0 p.1 := rfl

@[simp]
lemma freeOnModuleSelfLinearEquiv_tmul (K : ModuleCat.{u} R) (d₀ : ℤ)
    (p : polySubmodule R n (d₀ + -d₀)) (x : K) :
    freeOnModuleSelfLinearEquiv (n := n) K d₀ (p ⊗ₜ x) =
      MvPolynomial.coeff 0 p.1 • x := rfl

/-- A linear map `K → M_d₀` extends uniquely in the expected way to a graded map
`S(-d₀) ⊗ K → M`: a homogeneous form acts on the image of its coefficient.

The universal uniqueness statement is not needed here; the explicit formula is exposed by
`freeOnModuleHom_app_tmul`. -/
noncomputable def freeOnModuleHom (M : GradedModule R n) (d₀ : ℤ)
    (K : ModuleCat.{u} R) (f : K ⟶ M.obj d₀) :
    freeOnModule (n := n) K d₀ ⟶ M where
  app d := ModuleCat.MonoidalCategory.tensorLift
    (fun p x ↦ mulFormZ M (d + -d₀) d₀ d (by ring) p (f.hom x))
    (by intro p q x; simp)
    (by intro a p x; simp)
    (by intro p x y; simp)
    (by intro a p x; simp)
  comm i d := by
    apply ModuleCat.MonoidalCategory.tensor_ext
    intro p x
    simp only [ModuleCat.hom_comp, LinearMap.comp_apply,
      ModuleCat.MonoidalCategory.tensorLift_tmul]
    change (M.mulX i d).hom
        (mulFormZ M (d + -d₀) d₀ d (by ring) p (f.hom x)) =
      mulFormZ M (d + 1 + -d₀) d₀ (d + 1) (by ring)
        (((((structureModule R n).twist (-d₀)).mulX i d).hom p)) (f.hom x)
    let q : polySubmodule R n ((d + -d₀) + 1) :=
      ⟨MvPolynomial.X i * p.1,
        X_mul_mem_polySubmodule R n i (d + -d₀) p.2⟩
    have hq : q.1 = MvPolynomial.X i * p.1 := rfl
    have h := mulFormZ_mulX' M (d + -d₀) d₀ d (d + 1)
      (by ring) rfl (by ring) i p q hq (f.hom x)
    rw [show M.mulX i d = M.mulX' i d (d + 1) rfl from
      (mulX'_rfl M i d).symm, h]
    apply mulFormZ_congr_degree M ((d + -d₀) + 1)
      (d + 1 + -d₀) (by ring) d₀ (d + 1) (by ring) (by ring) q
    show q.1 =
      (((((structureModule R n).twist (-d₀)).mulX i d).hom p)).1
    change q.1 = (((structureModule R n).mulX' i (d + -d₀)
      (d + 1 + -d₀) (by ring)).hom p).1
    rw [structureModule_mulX'_val]

/-- On a pure tensor, the extension map is multiplication of the coefficient image by the
homogeneous form. -/
@[simp]
lemma freeOnModuleHom_app_tmul (M : GradedModule R n) (d₀ : ℤ)
    (K : ModuleCat.{u} R) (f : K ⟶ M.obj d₀) (d : ℤ)
    (p : ((structureModule R n).twist (-d₀)).obj d) (x : K) :
    ((freeOnModuleHom M d₀ K f).app d).hom (p ⊗ₜ x) =
      mulFormZ M (d + -d₀) d₀ d (by ring) p (f.hom x) := rfl

/-- A degree-zero homogeneous form acts on a graded module through its constant
coefficient. -/
lemma mulFormZ_zero (M : GradedModule R n) (d : ℤ)
    (p : polySubmodule R n 0) (x : M.obj d) :
    mulFormZ M 0 d d (by omega) p x =
      MvPolynomial.coeff 0 p.1 • x := by
  let c : R := MvPolynomial.coeff 0 p.1
  have hp : p.1 = MvPolynomial.monomial 0 c := by
    change p.1 = MvPolynomial.C c
    exact congrArg Subtype.val
      ((MvPolynomial.degreeZeroRingEquiv (Fin (n + 1)) R).apply_symm_apply
        (⟨p.1, (polySubmodule_of_nonneg R n (e := 0) (by omega)) ▸ p.2⟩)) |>.symm
  let q : polySubmodule R n 0 := ⟨MvPolynomial.monomial 0 c, hp ▸ p.2⟩
  have hpq : p = q := Subtype.ext hp
  rw [hpq]
  have h := mulFormZ_monomial M 0 d d (by omega) 0 (by simp) c q.2 x
  rw [h]
  have hact : (M.mulMono 0 d d (by simp)).hom x = x := by
    have hperm : (monoList (0 : Fin (n + 1) →₀ ℕ)).Perm [] := by
      rw [show monoList (0 : Fin (n + 1) →₀ ℕ) = [] by simp [monoList]]
    rw [mulMono, M.mulList_perm hperm d d (by simp [monoList]) (by simp)]
    rfl
  rw [hact]
  simp [q, c]

/-- In its generating degree, the universal graded extension is the original coefficient
map under the canonical identification `S₀ ⊗ K ≅ K`. -/
lemma freeOnModuleHom_app_self (M : GradedModule R n) (d₀ : ℤ)
    (K : ModuleCat.{u} R) (f : K ⟶ M.obj d₀) :
    (freeOnModuleHom M d₀ K f).app d₀ =
      ModuleCat.ofHom (f.hom.comp
        (freeOnModuleSelfLinearEquiv (n := n) K d₀).toLinearMap) := by
  apply ModuleCat.MonoidalCategory.tensor_ext
  intro (p : polySubmodule R n (d₀ + -d₀)) x
  change mulFormZ M (d₀ + -d₀) d₀ d₀ (by ring) p (f.hom x) =
    f.hom (freeOnModuleSelfLinearEquiv (n := n) K d₀ (p ⊗ₜ x))
  rw [mulFormZ_congr_degree M (d₀ + -d₀) 0 (by ring) d₀ d₀ (by ring)
    (by ring) p
    ⟨p.1, (LinearEquiv.ofEq (polySubmodule R n (d₀ + -d₀))
      (polySubmodule R n 0) (by congr 1; omega)) p |>.2⟩ rfl]
  rw [mulFormZ_zero, freeOnModuleSelfLinearEquiv_tmul, map_smul]

end AlgebraicGeometry.ProjectiveSpace.GradedModule

end

end
