module

public import StacksAndModuli.API.ProjGammaStarChartBaseChange
public import StacksAndModuli.API.ProjectiveGradedLocalizationPair
public import StacksAndModuli.API.ProjectiveGradedCechLocalIso

/-!
# `Γ_*` commutes with a change of coefficients after taking Čech `H⁰`

For a finitely presented sheaf `F` on `Proj R[x₀,…,xₙ]` and a ring map `φ : R → S`, the
comparison `gammaStarBaseChangeHom : Γ_*(F) ⊗_R S ⟶ Γ_*(φ^*F)` is *not* an isomorphism of
graded modules — `Γ_*` is a global-sections functor and does not commute with base change.
It does, however, become an isomorphism after applying `Hᵍʳ 0`, because the graded Čech complex
sees only the localizations at the coordinates, and those are computed by the charts `D₊(xᵢ)`,
where base change is unconditional.

The two inputs are:

* on a single coordinate, `bijective_locMap_gammaStarBaseChangeHom_app` — the chart square,
  whose every leg is bijective;
* on a pair of coordinates, `GradedModule.injective_locMap_pair_app` — the overlap needs only
  *injectivity*, and injectivity on `D₊(xᵢxⱼ)` follows formally from bijectivity on `D₊(xᵢ)`
  by localizing once more, with no second chart argument.

Both are available only in **non-negative** degrees: the twist-pullback comparison
`ProjectiveSpectrum.Twist.twistModulePolynomialPullbackHom` is known to be an isomorphism only
for `d : ℕ` (the proof uses that `𝒪(d)` is generated by the sections `xᵢ^d`).  This is why
`AlgebraicGeometry.ProjectiveSpace.HasGammaStarBaseChangeCechHgrZero` is stated in
non-negative degrees, which is all its consumer
`AlgebraicGeometry.ProjectiveSpace.schemeGlobalSectionsComparison` uses.

Main declarations:

* `AlgebraicGeometry.ProjectiveSpace.isIso_cechHgrMap_gammaStarBaseChangeHom_app`;
* `AlgebraicGeometry.ProjectiveSpace.cechHgrZeroGammaStarBaseChangeLinearEquiv`.
-/

@[expose] public section

noncomputable section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 10
set_option linter.style.haveILetI false

open CategoryTheory Opposite TensorProduct
open AlgebraicGeometry ProjectiveSpectrum.Twist

universe u

namespace AlgebraicGeometry.ProjectiveSpace

attribute [local instance] MvPolynomial.gradedAlgebra

variable (n : ℕ) {R S : Type u} [CommRing R] [CommRing S] (φ : R →+* S)
variable (F : (Proj (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)).Modules)

/-- **The base-change comparison is an isomorphism on graded Čech `H⁰`, in every non-negative
degree.**  The `0`-simplices of the Čech cover are the charts `D₊(xᵢ)`, where the comparison is
bijective (`bijective_locMap_gammaStarBaseChangeHom_app`); the `1`-simplices are the overlaps
`D₊(xᵢxⱼ)`, where only injectivity is needed, and that follows from the chart statement by
`GradedModule.injective_locMap_pair_app`. -/
theorem isIso_cechHgrMap_gammaStarBaseChangeHom_app [F.IsFinitePresentation] (dN : ℕ) :
    letI : Algebra R S := φ.toAlgebra
    IsIso ((GradedModule.cechHgrMap (gammaStarBaseChangeHom n φ F) 0).app (dN : ℤ)) := by
  letI : Algebra R S := φ.toAlgebra
  refine GradedModule.isIso_cechHgrMap_app_zero_of_injective _ _ (fun τ => ?_) (fun τ => ?_)
  · obtain ⟨i, hi⟩ := List.length_eq_one_iff.mp (by simpa using τ.length_eq)
    exact GradedModule.bijective_locMap_app_of_list_eq _ hi _
      (bijective_locMap_gammaStarBaseChangeHom_app n φ F i dN)
  · obtain ⟨i, k, hik⟩ := List.length_eq_two.mp (by simpa using τ.length_eq)
    refine GradedModule.injective_locMap_app_of_list_eq _ hik _ ?_
    refine GradedModule.injective_locMap_pair_app _ i k _ fun t => ?_
    refine GradedModule.bijective_locMap_app_of_eq _ [i] ?_
      (bijective_locMap_gammaStarBaseChangeHom_app n φ F i (dN + t))
    push_cast
    ring

/-- The linear-equivalence form of `isIso_cechHgrMap_gammaStarBaseChangeHom_app`: base changing
`Γ_*(F)` to `S` computes the same degree-`d` graded Čech `H⁰` as `Γ_*` of the base-changed
sheaf, for every `d ≥ 0`. -/
def cechHgrZeroGammaStarBaseChangeLinearEquiv [F.IsFinitePresentation] (dN : ℕ) :
    letI : Algebra R S := φ.toAlgebra
    ((((Proj.gammaStar (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
            (Proj.polynomialToSpec (Fin (n + 1)) R) F (stdVars n R)).baseChange S).cechHgr
          0).obj (dN : ℤ)) ≃ₗ[S]
      (((Proj.gammaStar (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) S)
            (Proj.polynomialToSpec (Fin (n + 1)) S)
            ((Scheme.Modules.pullback (coeffMap n φ)).obj F) (stdVars n S)).cechHgr 0).obj
        (dN : ℤ)) := by
  letI : Algebra R S := φ.toAlgebra
  haveI := isIso_cechHgrMap_gammaStarBaseChangeHom_app n φ F dN
  exact (asIso ((GradedModule.cechHgrMap (gammaStarBaseChangeHom n φ F) 0).app
    (dN : ℤ))).toLinearEquiv

end AlgebraicGeometry.ProjectiveSpace

end

end
