module

public import StacksAndModuli.API.ProjectiveLineBinaryQuotientPersistence
public import StacksAndModuli.API.TwistedFreeQuotAffineGeneratedGraded

/-!
# Generated relations and binary persistence on the projective line

For a graded map `F : A ⟶ M`, if the degree-`t + 1` piece of `A` is generated from
degree `t` by the projective variables, then the range of `F` in degree `t + 1` is the
sum of the variable multiples of its range in degree `t`.  The free graded module
`S(-d) ⊗ K` has this property in every degree at least `d`.

Specializing the target to a finite power of a twist of the binary polynomial module and
transporting through the homogeneous-form equivalences identifies all later generated
relation spaces with `MvPolynomial.binaryNextSpanIterate`.  A final coordinate wrapper
starts with the monomial-coordinate presentation used by the affine reconstructed Quot
model.

The resulting persistence theorem concerns the algebraic graded quotient generated in
one degree.  To obtain the geometric seed ranks used by Quot reconstruction, one still
needs either an eventual comparison with the sheafification of this generated quotient,
or the stronger next-degree reconstruction-saturation comparison.

Main declarations:

* `GradedModule.range_app_succ_eq_iSup_map_of_mulSpan_eq_top`;
* `GradedModule.freeOnModule_mulSpan_succ_eq_top`;
* `GradedModule.freeObjHomogeneousEquiv_mulX_binary`;
* `GradedModule.binaryGeneratedRelationHomogeneousRange_eq_iterate`;
* `GradedModule.finrank_generatedQuotient_obj_eq_of_binary_seed`;
* `binaryTwistedFreeGeneratedRelationHomogeneousRange_eq_iterate`.
-/

@[expose] public section

noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits TensorProduct

namespace AlgebraicGeometry.ProjectiveSpace.GradedModule

variable {R : Type u} [CommRing R] {n : ℕ}

/-- If consecutive pieces of the source of a graded map are generated by the variables,
then the next range is the supremum of the variable multiples of the current range. -/
theorem range_app_succ_eq_iSup_map_of_mulSpan_eq_top
    {A M : GradedModule R n} (F : A ⟶ M) (t : ℤ)
    (hgen : A.mulSpan t (t + 1) = ⊤) :
    LinearMap.range (F.app (t + 1)).hom =
      ⨆ i : Fin (n + 1),
        (LinearMap.range (F.app t).hom).map (M.mulX i t).hom := by
  have hcomm (i : Fin (n + 1)) (x : A.obj t) :
      (F.app (t + 1)).hom ((A.mulX i t).hom x) =
        (M.mulX i t).hom ((F.app t).hom x) := by
    have h := congrArg (fun q : A.obj t ⟶ M.obj (t + 1) ↦ q.hom x)
      (F.comm i t)
    simpa only [ModuleCat.hom_comp, LinearMap.comp_apply] using h.symm
  apply le_antisymm
  · rintro y ⟨x, rfl⟩
    have hx : x ∈ A.mulSpan t (t + 1) := by
      rw [hgen]
      exact Submodule.mem_top
    rw [mulSpan_succ_eq_iSup] at hx
    simp only [mulX'_rfl] at hx
    refine Submodule.iSup_induction _
      (motive := fun z ↦ (F.app (t + 1)).hom z ∈
        ⨆ i : Fin (n + 1),
          (LinearMap.range (F.app t).hom).map (M.mulX i t).hom)
      hx ?_ ?_ ?_
    · intro i z hz
      obtain ⟨x, rfl⟩ := hz
      rw [hcomm]
      exact le_iSup
        (fun i : Fin (n + 1) ↦
          (LinearMap.range (F.app t).hom).map (M.mulX i t).hom) i
        ⟨(F.app t).hom x, ⟨x, rfl⟩, rfl⟩
    · simp
    · intro x y hx hy
      simpa only [map_add] using Submodule.add_mem _ hx hy
  · refine iSup_le fun i ↦ ?_
    rintro y ⟨z, hz, rfl⟩
    obtain ⟨x, rfl⟩ := hz
    exact ⟨(A.mulX i t).hom x, hcomm i x⟩

/-- Tensoring every graded piece on the right preserves generation between two
consecutive degrees. -/
theorem tensorRight_mulSpan_succ_eq_top
    (M : GradedModule R n) (K : ModuleCat.{u} R) (t : ℤ)
    (hgen : M.mulSpan t (t + 1) = ⊤) :
    (tensorRight M K).mulSpan t (t + 1) = ⊤ := by
  rw [eq_top_iff]
  intro z hz
  clear hz
  induction z using TensorProduct.induction_on with
  | zero => exact Submodule.zero_mem _
  | add x y hx hy => exact Submodule.add_mem _ hx hy
  | tmul p x =>
      have hp : p ∈ M.mulSpan t (t + 1) := by
        rw [hgen]
        exact Submodule.mem_top
      rw [mulSpan_succ_eq_iSup] at hp
      refine Submodule.iSup_induction _
        (motive := fun q ↦ q ⊗ₜ[R] x ∈ (tensorRight M K).mulSpan t (t + 1))
        hp ?_ ?_ ?_
      · intro i q hq
        obtain ⟨w, rfl⟩ := hq
        refine range_mulX'_le_mulSpan (tensorRight M K) i t (t + 1) rfl ?_
        refine ⟨w ⊗ₜ[R] x, ?_⟩
        rfl
      · simp
      · intro p q hp hq
        simpa only [add_tmul] using Submodule.add_mem _ hp hq

/-- The graded module freely generated by a coefficient module in degree `d₀` is
generated by the projective variables between every pair of consecutive degrees at or
above `d₀`. -/
theorem freeOnModule_mulSpan_succ_eq_top
    (K : ModuleCat.{u} R) (d₀ t : ℤ) (ht : d₀ ≤ t) :
    (freeOnModule (n := n) K d₀).mulSpan t (t + 1) = ⊤ := by
  apply tensorRight_mulSpan_succ_eq_top
  rw [twist_mulSpan]
  have hs := structureModule_mulSpan_succ (k := R) (n := n)
    (t + -d₀) (by omega)
  have key : ∀ a b : ℤ, a = b →
      (structureModule R n).mulSpan (t + -d₀) a = ⊤ →
      (structureModule R n).mulSpan (t + -d₀) b = ⊤ := by
    intro a b hab h
    subst hab
    exact h
  exact key _ _ (by ring) hs

variable (K : Type u) [Field K]

/-- The homogeneous-form coordinates for a binary twisted-free module intertwine its
graded action by `X_j` with coordinatewise multiplication by that binary variable. -/
theorem freeObjHomogeneousEquiv_mulX_binary
    (l : ℤ) (r : ℕ) (t : ℤ) (e : ℕ)
    (he : (e : ℤ) = t - l) (j : Fin 2) :
    (freeObjHomogeneousEquiv K 1 l r (t + 1) (e + 1) (by omega)).toLinearMap.comp
        (((((structureModule K 1).twist (-l)).pow r).mulX j t).hom) =
      (MvPolynomial.binaryMulVector K (Fin r) e j).comp
        (freeObjHomogeneousEquiv K 1 l r t e he).toLinearMap := by
  apply LinearMap.ext
  intro x
  simp only [LinearMap.comp_apply]
  funext a
  apply Subtype.ext
  change (((((((structureModule K 1).twist (-l)).pow r).mulX j t).hom x) a).1 :
      MvPolynomial (Fin 2) K) =
    (((MvPolynomial.binaryMulVector K (Fin r) e j
      (freeObjHomogeneousEquiv K 1 l r t e he x)) a).1 :
        MvPolynomial (Fin 2) K)
  rw [pow_mulX_apply]
  let p := x a
  have htwist :
      (((((structureModule K 1).twist (-l)).mulX j t).hom p).1 :
          MvPolynomial (Fin 2) K) = MvPolynomial.X j * p.1 := by
    exact structureModule_mulX'_val
      j (t + -l) (t + 1 + -l) (by ring) p
  change (((((structureModule K 1).twist (-l)).mulX j t).hom p).1 :
      MvPolynomial (Fin 2) K) = _
  rw [htwist, MvPolynomial.binaryMulVector_apply]
  change MvPolynomial.X j * p.1 = MvPolynomial.X j *
    (((freeObjHomogeneousEquiv K 1 l r t e he x a :
      MvPolynomial.homogeneousSubmodule (Fin 2) K e) :
        MvPolynomial (Fin 2) K))
  rw [AlgebraicGeometry.freeObjHomogeneousEquiv_apply_val]

private theorem iSup_fin_two_eq_sup
    {X : Type*} [AddCommGroup X] [Module K X]
    (U : Fin 2 → Submodule K X) :
    (⨆ i, U i) = U 0 ⊔ U 1 := by
  apply le_antisymm
  · refine iSup_le fun i ↦ ?_
    fin_cases i
    · exact le_sup_left
    · exact le_sup_right
  · exact sup_le (le_iSup U 0) (le_iSup U 1)

/-- The homogeneous relation space in the `k`-th degree after a chosen generating
degree.  It is the range of the universal generated-relation map in that degree,
transported to vectors of binary homogeneous forms. -/
noncomputable def binaryGeneratedRelationHomogeneousRange
    (l : ℤ) (r : ℕ) (d : ℤ) (e : ℕ)
    (he : (e : ℤ) = d - l) (A : ModuleCat.{u} K)
    (f : A ⟶ ((((structureModule K 1).twist (-l)).pow r).obj d))
    (k : ℕ) :
    Submodule K
      (Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) :=
  (LinearMap.range
      ((freeOnModuleHom
        (((structureModule K 1).twist (-l)).pow r) d A f).app
          (d + (k : ℤ))).hom).map
    (freeObjHomogeneousEquiv K 1 l r (d + (k : ℤ)) (e + k)
      (by omega)).toLinearMap

/-- A degree of the generated graded quotient, expressed as the quotient of binary
homogeneous vectors by the corresponding generated relation space. -/
noncomputable def generatedQuotientHomogeneousEquiv
    (l : ℤ) (r : ℕ) (d : ℤ) (e : ℕ)
    (he : (e : ℤ) = d - l) (A : ModuleCat.{u} K)
    (f : A ⟶ ((((structureModule K 1).twist (-l)).pow r).obj d))
    (k : ℕ) :
    (generatedQuotient
        (((structureModule K 1).twist (-l)).pow r) d A f).obj
          (d + (k : ℤ)) ≃ₗ[K]
      ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) ⧸
        binaryGeneratedRelationHomogeneousRange K l r d e he A f k) := by
  change
    ((((((structureModule K 1).twist (-l)).pow r).obj
        (d + (k : ℤ))) ⧸
      LinearMap.range
        ((freeOnModuleHom
          (((structureModule K 1).twist (-l)).pow r) d A f).app
            (d + (k : ℤ))).hom)) ≃ₗ[K]
      ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) ⧸
        binaryGeneratedRelationHomogeneousRange K l r d e he A f k)
  exact Submodule.Quotient.equiv _ _
    (freeObjHomogeneousEquiv K 1 l r (d + (k : ℤ)) (e + k)
      (by omega)) rfl

/-- Advancing one degree in the universal generated-relation map is exactly the binary
successor-span operation after passing to homogeneous-form coordinates. -/
theorem binaryGeneratedRelationHomogeneousRange_succ
    (l : ℤ) (r : ℕ) (d : ℤ) (e : ℕ)
    (he : (e : ℤ) = d - l) (A : ModuleCat.{u} K)
    (f : A ⟶ ((((structureModule K 1).twist (-l)).pow r).obj d))
    (k : ℕ) :
    binaryGeneratedRelationHomogeneousRange K l r d e he A f (k + 1) =
      MvPolynomial.binaryNextSpan K
        (binaryGeneratedRelationHomogeneousRange K l r d e he A f k) := by
  classical
  let M := (((structureModule K 1).twist (-l)).pow r)
  let F := freeOnModuleHom M d A f
  let t : ℤ := d + (k : ℤ)
  let W : Submodule K (M.obj t) := LinearMap.range (F.app t).hom
  let E₀ := freeObjHomogeneousEquiv K 1 l r t (e + k) (by
    dsimp only [t]
    omega)
  let E₁ := freeObjHomogeneousEquiv K 1 l r (t + 1) (e + k + 1) (by
    dsimp only [t]
    omega)
  have hrange : LinearMap.range (F.app (t + 1)).hom =
      ⨆ j : Fin 2,
        W.map (M.mulX j t).hom := by
    exact range_app_succ_eq_iSup_map_of_mulSpan_eq_top F t
      (freeOnModule_mulSpan_succ_eq_top A d t (by
        dsimp only [t]
        omega))
  have hcompat (j : Fin 2) :
      E₁.toLinearMap.comp (M.mulX j t).hom =
        (MvPolynomial.binaryMulVector K (Fin r) (e + k) j).comp
          E₀.toLinearMap := by
    exact freeObjHomogeneousEquiv_mulX_binary K l r t (e + k) (by
      dsimp only [t]
      omega) j
  have hmap (j : Fin 2) :
      (W.map (M.mulX j t).hom).map E₁.toLinearMap =
        (W.map E₀.toLinearMap).map
          (MvPolynomial.binaryMulVector K (Fin r) (e + k) j) := by
    rw [← Submodule.map_comp, hcompat, Submodule.map_comp]
  have hlocal : (LinearMap.range (F.app (t + 1)).hom).map E₁.toLinearMap =
      (W.map E₀.toLinearMap).map
          (MvPolynomial.binaryMulVector K (Fin r) (e + k) 0) ⊔
        (W.map E₀.toLinearMap).map
          (MvPolynomial.binaryMulVector K (Fin r) (e + k) 1) := by
    rw [hrange, Submodule.map_iSup]
    simp_rw [hmap]
    exact iSup_fin_two_eq_sup K _
  have htransport : ∀ (t' : ℤ) (ht' : t' = t + 1),
      (LinearMap.range (F.app t').hom).map
          (freeObjHomogeneousEquiv K 1 l r t' (e + (k + 1)) (by
            dsimp only [t] at ht'
            omega)).toLinearMap =
        (W.map E₀.toLinearMap).map
            (MvPolynomial.binaryMulVector K (Fin r) (e + k) 0) ⊔
          (W.map E₀.toLinearMap).map
            (MvPolynomial.binaryMulVector K (Fin r) (e + k) 1) := by
    intro t' ht'
    subst t'
    exact hlocal
  simpa only [binaryGeneratedRelationHomogeneousRange, M, F, t, W, E₀,
    MvPolynomial.binaryNextSpan] using
      htransport (d + ((k + 1 : ℕ) : ℤ)) (by
        dsimp only [t]
        omega)

/-- Every later homogeneous relation space generated from one degree is the corresponding
iterate of the binary successor span. -/
theorem binaryGeneratedRelationHomogeneousRange_eq_iterate
    (l : ℤ) (r : ℕ) (d : ℤ) (e : ℕ)
    (he : (e : ℤ) = d - l) (A : ModuleCat.{u} K)
    (f : A ⟶ ((((structureModule K 1).twist (-l)).pow r).obj d)) :
    ∀ k : ℕ,
      binaryGeneratedRelationHomogeneousRange K l r d e he A f k =
        MvPolynomial.binaryNextSpanIterate K e
          (binaryGeneratedRelationHomogeneousRange K l r d e he A f 0) k := by
  intro k
  induction k with
  | zero => rfl
  | succ k hk =>
      rw [binaryGeneratedRelationHomogeneousRange_succ,
        MvPolynomial.binaryNextSpanIterate_succ, hk]

/-- Field-valued persistence for the graded quotient generated by relations in one
degree.  The hypotheses are exactly the two adjacent quotient dimensions and the
subtraction-free binary Gotzmann numerical conditions. -/
theorem finrank_generatedQuotient_obj_eq_of_binary_seed
    (l : ℤ) (r : ℕ) (d : ℤ) (e : ℕ)
    (he : (e : ℤ) = d - l) (A : ModuleCat.{u} K)
    (f : A ⟶ ((((structureModule K 1).twist (-l)).pow r).obj d))
    (q₀ q₁ a s : ℕ)
    (hself : Module.finrank K
      ((generatedQuotient
        (((structureModule K 1).twist (-l)).pow r) d A f).obj d) = q₀)
    (hnext : Module.finrank K
      ((generatedQuotient
        (((structureModule K 1).twist (-l)).pow r) d A f).obj (d + 1)) = q₁)
    (hquotientGrowth : q₁ = q₀ + a)
    (hambientSplit : r = a + s)
    (hcase : s = 0 ∨ q₁ < (a + 1) * (e + 2)) :
    ∀ k : ℕ,
      Module.finrank K
        ((generatedQuotient
          (((structureModule K 1).twist (-l)).pow r) d A f).obj
            (d + (k : ℤ))) = q₀ + k * a := by
  let V := binaryGeneratedRelationHomogeneousRange K l r d e he A f 0
  letI : FiniteDimensional K V := by
    dsimp only [V]
    infer_instance
  have hselfZero : Module.finrank K
      ((generatedQuotient
        (((structureModule K 1).twist (-l)).pow r) d A f).obj
          (d + ((0 : ℕ) : ℤ))) = q₀ := by
    have htransport : ∀ t : ℤ, t = d →
        Module.finrank K
          ((generatedQuotient
            (((structureModule K 1).twist (-l)).pow r) d A f).obj t) = q₀ := by
      intro t ht
      subst t
      exact hself
    exact htransport _ (by omega)
  have hV : Module.finrank K
      ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K e) ⧸ V) = q₀ := by
    exact (generatedQuotientHomogeneousEquiv
      K l r d e he A f 0).finrank_eq.symm.trans hselfZero
  have hrangeOne :
      binaryGeneratedRelationHomogeneousRange K l r d e he A f 1 =
        MvPolynomial.binaryNextSpan K V := by
    simpa only [V, Nat.zero_add] using
      binaryGeneratedRelationHomogeneousRange_succ K l r d e he A f 0
  have hnextV : Module.finrank K
      ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
        MvPolynomial.binaryNextSpan K V) = q₁ := by
    calc
      Module.finrank K
          ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
            MvPolynomial.binaryNextSpan K V) =
          Module.finrank K
            ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
              binaryGeneratedRelationHomogeneousRange K l r d e he A f 1) := by
        rw [hrangeOne]
      _ = Module.finrank K
            ((generatedQuotient
              (((structureModule K 1).twist (-l)).pow r) d A f).obj
                (d + 1)) := by
        simpa using
          (generatedQuotientHomogeneousEquiv K l r d e he A f 1).finrank_eq.symm
      _ = q₁ := hnext
  have hpersist := MvPolynomial.finrank_quotient_binaryNextSpanIterate_eq
    K (Fin r) e V q₀ q₁ a s hV hnextV hquotientGrowth
      (by simpa only [Fintype.card_fin] using hambientSplit) hcase
  intro k
  calc
    Module.finrank K
        ((generatedQuotient
          (((structureModule K 1).twist (-l)).pow r) d A f).obj
            (d + (k : ℤ))) =
        Module.finrank K
          ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) ⧸
            binaryGeneratedRelationHomogeneousRange K l r d e he A f k) :=
      (generatedQuotientHomogeneousEquiv K l r d e he A f k).finrank_eq
    _ = Module.finrank K
          ((Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) ⧸
            MvPolynomial.binaryNextSpanIterate K e V k) := by
      rw [binaryGeneratedRelationHomogeneousRange_eq_iterate]
    _ = q₀ + k * a := hpersist k

end AlgebraicGeometry.ProjectiveSpace.GradedModule

namespace AlgebraicGeometry

open ProjectiveSpace ProjectiveSpace.GradedModule

variable (K : Type u) [Field K]

/-- A relation map supplied in the monomial coordinates of a binary twisted-free piece,
transported back to that piece of the graded polynomial module. -/
noncomputable def binaryTwistedFreeGeneratedRelation
    (l : ℤ) (r d e : ℕ) (he : (d : ℤ) - l = (e : ℤ))
    (A : ModuleCat.{u} K)
    (g : A ⟶ ModuleCat.of K
      ((ULift.{u} (Fin r) × Fin ((1 + e).choose 1)) → K)) :
    A ⟶ ((((GradedModule.structureModule K 1).twist (-l)).pow r).obj (d : ℤ)) :=
  g ≫ (twistedFreeGradedMonomialEquiv 1 K l r d e he).toModuleIso.inv

/-- The later homogeneous relation spaces generated by a relation map originally given in
the affine monomial coordinates used by twisted-free Quot reconstruction. -/
noncomputable def binaryTwistedFreeGeneratedRelationHomogeneousRange
    (l : ℤ) (r d e : ℕ) (he : (d : ℤ) - l = (e : ℤ))
    (A : ModuleCat.{u} K)
    (g : A ⟶ ModuleCat.of K
      ((ULift.{u} (Fin r) × Fin ((1 + e).choose 1)) → K))
    (k : ℕ) :
    Submodule K
      (Fin r → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) :=
  GradedModule.binaryGeneratedRelationHomogeneousRange
    K l r (d : ℤ) e he.symm A
      (binaryTwistedFreeGeneratedRelation K l r d e he A g) k

/-- In every later degree, the relations generated from an affine monomial-coordinate
relation map are the iterated binary successor span of its initial homogeneous image. -/
theorem binaryTwistedFreeGeneratedRelationHomogeneousRange_eq_iterate
    (l : ℤ) (r d e : ℕ) (he : (d : ℤ) - l = (e : ℤ))
    (A : ModuleCat.{u} K)
    (g : A ⟶ ModuleCat.of K
      ((ULift.{u} (Fin r) × Fin ((1 + e).choose 1)) → K)) :
    ∀ k : ℕ,
      binaryTwistedFreeGeneratedRelationHomogeneousRange
          K l r d e he A g k =
        MvPolynomial.binaryNextSpanIterate K e
          (binaryTwistedFreeGeneratedRelationHomogeneousRange
            K l r d e he A g 0) k := by
  exact GradedModule.binaryGeneratedRelationHomogeneousRange_eq_iterate
    K l r (d : ℤ) e he.symm A
      (binaryTwistedFreeGeneratedRelation K l r d e he A g)

/-- Field-valued persistence for the affine generated graded quotient attached to a
twisted-free truncated quotient.  This is the direct affine-reconstruction
specialization of `GradedModule.finrank_generatedQuotient_obj_eq_of_binary_seed`;
it still concerns the algebraic graded quotient, not the twisted pushforwards of the
reconstructed sheaf. -/
theorem finrank_affineReconstructedGeneratedGradedQuotient_obj_eq_of_binary_seed
    (l : ℤ) (r d e : ℕ) (he : (d : ℤ) - l = (e : ℤ))
    {E : (Spec (.of K)).Modules}
    (u : SheafOfModules.free (R := (Spec (.of K)).ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((1 + e).choose 1)) ⟶ E)
    (q₀ q₁ a s : ℕ)
    (hself : Module.finrank K
      ((affineReconstructedGeneratedGradedQuotient
        1 (.of K) l r d e he u).obj (d : ℤ)) = q₀)
    (hnext : Module.finrank K
      ((affineReconstructedGeneratedGradedQuotient
        1 (.of K) l r d e he u).obj ((d : ℤ) + 1)) = q₁)
    (hquotientGrowth : q₁ = q₀ + a)
    (hambientSplit : r = a + s)
    (hcase : s = 0 ∨ q₁ < (a + 1) * (e + 2)) :
    ∀ k : ℕ,
      Module.finrank K
        ((affineReconstructedGeneratedGradedQuotient
          1 (.of K) l r d e he u).obj ((d : ℤ) + (k : ℤ))) =
        q₀ + k * a := by
  simpa only [affineReconstructedGeneratedGradedQuotient] using
    GradedModule.finrank_generatedQuotient_obj_eq_of_binary_seed
      K l r (d : ℤ) e he.symm
        ((Scheme.Modules.specEvaluation (.of K) ⊤).obj (kernel u))
        (affineReconstructedKernelRelation 1 (.of K) l r d e he u)
        q₀ q₁ a s hself hnext hquotientGrowth hambientSplit hcase

end AlgebraicGeometry

end

end
