module

public import StacksAndModuli.API.ProjectiveTwistBaseChange
public import StacksAndModuli.API.SchemeModulesPullbackPolynomialTwist
public import StacksAndModuli.API.ProjectiveTwistBaseChangeMul
public import StacksAndModuli.API.SchemeModulesPullbackTensor

/-!
# Coefficient change and the twist of a sheaf on polynomial `Proj`

`ProjectiveSpectrum.Twist.polynomialPullbackIso` says that changing the coefficient ring
along `g : R → S` pulls the twisting sheaf `𝒪(d)` on `Proj R[x]` back to `𝒪(d)` on
`Proj S[x]`.  This file records the consequence for the twist `F(d) = F ⊗ 𝒪(d)` of an
arbitrary sheaf: there is a canonical comparison

`g^*(F(d)) ⟶ (g^*F)(d)`.

The comparison is constructed for every integer twist. For a nonnegative twist it is an
isomorphism: the twisting sheaf is generated by the standard monomial sections, and the
tensor comparison can be checked on the standard charts `D₊(xᵢ)`, where
`ProjectiveSpectrum.Twist.restrictTwistIsoUnit` trivializes it. The comparison is also shown
to be natural in the sheaf and compatible with multiplication by homogeneous elements.

Main declarations:

* `ProjectiveSpectrum.Twist.twistModulePolynomialPullbackHom`;
* `ProjectiveSpectrum.Twist.pullback_map_twistModuleMulHom_comp_twistModulePolynomialPullbackHom`;
* `ProjectiveSpectrum.Twist.pullback_map_twistModuleMap_comp_twistModulePolynomialPullbackHom`;
* `ProjectiveSpectrum.Twist.twistModulePolynomialPullbackHom_isIso`.
-/

@[expose] public section

noncomputable section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

open CategoryTheory
open AlgebraicGeometry

universe u

namespace ProjectiveSpectrum.Twist

variable {R S : Type u} [CommRing R] [CommRing S] (i : Type) [DecidableEq i]
variable (g : R →+* S)

attribute [local instance] MvPolynomial.gradedAlgebra

/-- **Coefficient change and twisting.**  The canonical comparison
`g^*(F(d)) ⟶ (g^*F)(d)` on polynomial projective spectra: the pullback--tensor comparison
followed by the identification of the pulled-back twisting sheaf. -/
noncomputable def twistModulePolynomialPullbackHom
    (F : (Proj (MvPolynomial.homogeneousSubmodule i R)).Modules) (d : ℤ) :
    (Scheme.Modules.pullback (Proj.polynomialMap i g)).obj
        (twistModule (MvPolynomial.homogeneousSubmodule i R) F d) ⟶
      twistModule (MvPolynomial.homogeneousSubmodule i S)
        ((Scheme.Modules.pullback (Proj.polynomialMap i g)).obj F) d :=
  Scheme.Modules.pullbackTensorComparison (Proj.polynomialMap i g) F _ ≫
    Scheme.Modules.tensorMapRight _ (polynomialPullbackIso i g d).hom

omit [DecidableEq i] in
/-- **The twist comparison intertwines multiplication by a homogeneous element.**  For a
coefficient change `g : R → S` and a homogeneous `p` of the polynomial ring over `R`,
multiplication by `p` on `F(d)` corresponds to multiplication by the image of `p` on
`(g^*F)(d)`.

This is the `comm` field of the comparison of graded modules `Γ_*(F) ⊗ S ⟶ Γ_*(g^*F)`: the
degree-raising maps of `Γ_*` are exactly these multiplications. -/
theorem pullback_map_twistModuleMulHom_comp_twistModulePolynomialPullbackHom
    (F : (Proj (MvPolynomial.homogeneousSubmodule i R)).Modules) {m : ℕ}
    (p : MvPolynomial.homogeneousSubmodule i R m) (d dc : ℤ) (hdc : dc = d + (m : ℤ)) :
    (Scheme.Modules.pullback (Proj.polynomialMap i g)).map
          (twistModuleMulHom (MvPolynomial.homogeneousSubmodule i R) F p d dc hdc) ≫
        twistModulePolynomialPullbackHom i g F dc
      = twistModulePolynomialPullbackHom i g F d ≫
        twistModuleMulHom (MvPolynomial.homogeneousSubmodule i S)
          ((Scheme.Modules.pullback (Proj.polynomialMap i g)).obj F)
          (gradedImage (MvPolynomial.mapGradedRingHom (ι := i) g) p) d dc hdc := by
  unfold twistModulePolynomialPullbackHom twistModuleMulHom
  rw [← Category.assoc, Scheme.Modules.pullbackTensorComparison_naturality_right,
    Category.assoc, Category.assoc, ← Scheme.Modules.tensorMapRight_comp,
    ← Scheme.Modules.tensorMapRight_comp]
  exact congrArg
    (fun ψ : (Scheme.Modules.pullback (Proj.polynomialMap i g)).obj
        (twist (MvPolynomial.homogeneousSubmodule i R) d) ⟶
        twist (MvPolynomial.homogeneousSubmodule i S) dc ↦
      Scheme.Modules.pullbackTensorComparison (Proj.polynomialMap i g) F
          (twist (MvPolynomial.homogeneousSubmodule i R) d) ≫
        Scheme.Modules.tensorMapRight
          ((Scheme.Modules.pullback (Proj.polynomialMap i g)).obj F) ψ)
    (pullback_map_mulHom_comp_pullbackComparison
      (MvPolynomial.mapGradedRingHom (ι := i) g)
      (MvPolynomial.irrelevant_le_map_mapGradedRingHom g) p d dc hdc)

omit [DecidableEq i] in
/-- **The twist comparison is natural in the sheaf.**  For a coefficient change `g : R → S`
and a morphism `v : F ⟶ F'` of sheaves on `Proj R[x]`, the comparison `g^*(F(d)) ⟶ (g^*F)(d)`
intertwines the twist of the pulled-back morphism with the pullback of the twisted one. -/
theorem pullback_map_twistModuleMap_comp_twistModulePolynomialPullbackHom
    {F F' : (Proj (MvPolynomial.homogeneousSubmodule i R)).Modules} (v : F ⟶ F') (d : ℤ) :
    (Scheme.Modules.pullback (Proj.polynomialMap i g)).map
          (twistModuleMap (MvPolynomial.homogeneousSubmodule i R) v d) ≫
        twistModulePolynomialPullbackHom i g F' d
      = twistModulePolynomialPullbackHom i g F d ≫
        twistModuleMap (MvPolynomial.homogeneousSubmodule i S)
          ((Scheme.Modules.pullback (Proj.polynomialMap i g)).map v) d := by
  unfold twistModulePolynomialPullbackHom twistModuleMap
  rw [← Category.assoc, Scheme.Modules.pullbackTensorComparison_naturality_left,
    Category.assoc, Category.assoc]
  congr 1
  exact (Scheme.Modules.tensorMap_exchange _ _).symm

/-- **The twist-pullback comparison is an isomorphism in nonnegative degrees.**  For a natural
twist `d`, `g^*(F(d)) ≅ (g^*F)(d)`: the tensor comparison is an isomorphism because `𝒪(d)` is
generated by the sections `xᵢ^d` on the standard cover
(`Scheme.Modules.pullbackTensorComparison_polynomialTwist_nat_isIso`), and the twist itself
pulls back to the twist (`polynomialPullbackIso`). -/
instance twistModulePolynomialPullbackHom_isIso
    (F : (Proj (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)).Modules) (d : ℕ) :
    IsIso (twistModulePolynomialPullbackHom (Fin (n + 1)) g F (d : ℤ)) := by
  haveI : IsIso (Scheme.Modules.pullbackTensorComparison
      (Proj.polynomialMap (Fin (n + 1)) g) F
      (twist (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R) (d : ℤ))) :=
    MvPolynomial.pullbackTensorComparison_polynomialTwist_nat_isIso n R
      (Proj.polynomialMap (Fin (n + 1)) g) F d
  haveI : IsIso (Scheme.Modules.tensorMapRight
      ((Scheme.Modules.pullback (Proj.polynomialMap (Fin (n + 1)) g)).obj F)
      (polynomialPullbackIso (Fin (n + 1)) g (d : ℤ)).hom) :=
    (Scheme.Modules.tensorRightIso _ (polynomialPullbackIso (Fin (n + 1)) g (d : ℤ))).isIso_hom
  exact IsIso.comp_isIso

end ProjectiveSpectrum.Twist

end

end
