module

public import StacksAndModuli.API.ProjectiveGradedCech
public import StacksAndModuli.API.ProjectiveGradedLocalizationPair

/-!
# Čech cohomology only sees the localizations

A morphism of graded modules that becomes an isomorphism after localizing at every list of
variables induces an isomorphism on Čech cohomology.  This is what lets a quasicoherent sheaf be
computed by *any* graded module presenting it, rather than by `Γ_*` — which matters because
`Γ_*(F)` of a coherent sheaf is finitely generated only by Serre's theorem, whereas a presenting
module can be finitely generated by construction.

It is enough to assume bijectivity after localizing at each single variable in the degrees
visited by the localization towers: `ProjectiveGradedLocalizationPair.lean` propagates that
hypothesis to every nonempty list of variables.

Main declarations:
- `GradedModule.isIso_cechCochainMap`;
- `GradedModule.isIso_cechComplexMap`;
- `GradedModule.isIso_cechHgrMap_app`;
- `GradedModule.isIso_cechHgrMap_app_zero` and
  `GradedModule.cechHgrZeroLinearEquivOfIsIsoLoc`, the variants for `Hᵍʳ 0` which inspect only
  the localizations at a single variable and at a pair of variables;
- `GradedModule.isIso_cechHgrMap_app_zero_of_injective` and
  `GradedModule.cechHgrZeroLinearEquivOfIsIsoLocOfInjective`, the same needing only
  *injectivity* on pairs — which is what the chart comparison on the overlaps `D₊(xᵢxⱼ)`
  supplies (`AlgebraicGeometry.Proj.injective_pairColimitMap`);
- `GradedModule.isIso_cechHgrMap_app_of_singleton_bijective`, the all-degree criterion using
  only single-variable localizations.
-/

@[expose] public section

noncomputable section

-- These options are load-bearing throughout the library.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

universe u

namespace AlgebraicGeometry.ProjectiveSpace.GradedModule

open CategoryTheory

variable {k : Type u} [CommRing k] {n : ℕ} {M N : GradedModule k n}

/-- If localization at every index of the cover turns `φ` into a bijection in degree `d`, the
induced map on Čech `p`-cochains is an isomorphism. -/
theorem isIso_cechCochainMap (φ : M ⟶ N) (p : ℕ) (d : ℤ)
    (h : ∀ τ : CechIdx n p, Function.Bijective ((locMap τ.toList φ).app d).hom) :
    IsIso (cechCochainMap φ p d) := by
  classical
  rw [ConcreteCategory.isIso_iff_bijective]
  constructor
  · intro c c' hcc
    funext τ
    exact (h τ).1 (congrFun hcc τ)
  · intro c
    refine ⟨fun τ ↦ Classical.choose ((h τ).2 (c τ)), ?_⟩
    funext τ
    exact Classical.choose_spec ((h τ).2 (c τ))

/-- If localization at every list of variables turns `φ` into a bijection in degree `d`, the
induced map of Čech complexes in degree `d` is an isomorphism. -/
theorem isIso_cechComplexMap (φ : M ⟶ N) (d : ℤ)
    (h : ∀ l : List (Fin (n + 1)), Function.Bijective ((locMap l φ).app d).hom) :
    IsIso (cechComplexMap φ d) := by
  haveI : ∀ p : ℕ, IsIso ((cechComplexMap φ d).f p) := by
    intro p
    have hf : (cechComplexMap φ d).f p = cechCochainMap φ p d := rfl
    rw [hf]
    exact isIso_cechCochainMap φ p d fun τ ↦ h τ.toList
  exact HomologicalComplex.Hom.isIso_of_components _

/-- **Čech cohomology only sees the localizations.**  A morphism of graded modules that is an
isomorphism after localizing at every list of variables induces an isomorphism on `Hᵍʳ`. -/
theorem isIso_cechHgrMap_app (φ : M ⟶ N) (q : ℕ) (d : ℤ)
    (h : ∀ l : List (Fin (n + 1)), Function.Bijective ((locMap l φ).app d).hom) :
    IsIso ((cechHgrMap φ q).app d) := by
  haveI := isIso_cechComplexMap φ d h
  have hEq : (cechHgrMap φ q).app d
      = (HomologicalComplex.homologyFunctor (ModuleCat.{u} k) (ComplexShape.up ℕ) q).map
        (cechComplexMap φ d) := rfl
  rw [hEq]
  infer_instance

/-- **Only the first two Čech cochain groups matter for `Hᵍʳ 0`.**  A morphism of graded
modules that becomes bijective after localizing at every single variable and at every pair of
variables induces an isomorphism on `Hᵍʳ 0`.

This is the form the base-change comparison needs: the standard opens `D₊(xᵢ)` and their
pairwise intersections are affine and their coefficient-change squares are cartesian
(`API/ProjectiveStandardCoverBaseChange.lean`), while longer intersections are not covered
there. -/
theorem isIso_cechHgrMap_app_zero (φ : M ⟶ N) (d : ℤ)
    (h0 : ∀ τ : CechIdx n 0, Function.Bijective ((locMap τ.toList φ).app d).hom)
    (h1 : ∀ τ : CechIdx n 1, Function.Bijective ((locMap τ.toList φ).app d).hom) :
    IsIso ((cechHgrMap φ 0).app d) := by
  haveI i0 : IsIso ((cechComplexMap φ d).f 0) := by
    have hf : (cechComplexMap φ d).f 0 = cechCochainMap φ 0 d := rfl
    rw [hf]
    exact isIso_cechCochainMap φ 0 d h0
  haveI i1 : IsIso ((cechComplexMap φ d).f 1) := by
    have hf : (cechComplexMap φ d).f 1 = cechCochainMap φ 1 d := rfl
    rw [hf]
    exact isIso_cechCochainMap φ 1 d h1
  have hEq : (cechHgrMap φ 0).app d
      = (HomologicalComplex.homologyFunctor (ModuleCat.{u} k) (ComplexShape.up ℕ) 0).map
        (cechComplexMap φ d) := rfl
  rw [hEq]
  haveI iprev : IsIso ((cechComplexMap φ d).f ((ComplexShape.up ℕ).prev 0)) := by
    rw [CochainComplex.prev_nat_zero]
    exact i0
  haveI inext : IsIso ((cechComplexMap φ d).f ((ComplexShape.up ℕ).next 0)) := by
    rw [ComplexShape.next_eq' (ComplexShape.up ℕ) (show (0 : ℕ) + 1 = 1 from rfl)]
    exact i1
  haveI t1 : IsIso ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
    (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)).τ₁ := iprev
  haveI t2 : IsIso ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
    (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)).τ₂ := i0
  haveI t3 : IsIso ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
    (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)).τ₃ := inext
  haveI hsc : IsIso ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
      (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)) :=
    ShortComplex.isIso_of_isIso _
  have hh : (HomologicalComplex.homologyFunctor (ModuleCat.{u} k) (ComplexShape.up ℕ) 0).map
      (cechComplexMap φ d)
      = ShortComplex.homologyMap ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
        (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)) := rfl
  rw [hh]
  infer_instance

/-- The `k`-linear equivalence on `Hᵍʳ 0` induced by a morphism that is bijective after
localizing at every variable and every pair of variables. -/
noncomputable def cechHgrZeroLinearEquivOfIsIsoLoc (φ : M ⟶ N) (d : ℤ)
    (h0 : ∀ τ : CechIdx n 0, Function.Bijective ((locMap τ.toList φ).app d).hom)
    (h1 : ∀ τ : CechIdx n 1, Function.Bijective ((locMap τ.toList φ).app d).hom) :
    (M.cechHgr 0).obj d ≃ₗ[k] (N.cechHgr 0).obj d := by
  haveI := isIso_cechHgrMap_app_zero φ d h0 h1
  exact (asIso ((cechHgrMap φ 0).app d)).toLinearEquiv

/-- The `R`-linear equivalence induced on Čech cohomology by a morphism that is an isomorphism on
every localization. -/
noncomputable def cechHgrLinearEquivOfIsIsoLoc (φ : M ⟶ N) (q : ℕ) (d : ℤ)
    (h : ∀ l : List (Fin (n + 1)), Function.Bijective ((locMap l φ).app d).hom) :
    (M.cechHgr q).obj d ≃ₗ[k] (N.cechHgr q).obj d := by
  haveI := isIso_cechHgrMap_app φ q d h
  exact (asIso ((cechHgrMap φ q).app d)).toLinearEquiv

/-- Degreewise injectivity after localization makes the map on Čech cochains a
monomorphism. -/
theorem mono_cechCochainMap (φ : M ⟶ N) (p : ℕ) (d : ℤ)
    (h : ∀ τ : CechIdx n p, Function.Injective ((locMap τ.toList φ).app d).hom) :
    Mono (cechCochainMap φ p d) := by
  rw [ModuleCat.mono_iff_injective]
  intro c c' hcc
  funext τ
  exact h τ (congrFun hcc τ)

/-- **`Hᵍʳ 0` needs only injectivity on pairs.**  A morphism of graded modules that becomes
bijective after localizing at every single variable and merely *injective* after localizing at
every pair induces an isomorphism on `Hᵍʳ 0`.

This is the form the base-change comparison needs: on the overlaps `D₊(xᵢxⱼ)` the chart
comparison `Proj.pairColimitMap` is known to be injective, not bijective. -/
theorem isIso_cechHgrMap_app_zero_of_injective (φ : M ⟶ N) (d : ℤ)
    (h0 : ∀ τ : CechIdx n 0, Function.Bijective ((locMap τ.toList φ).app d).hom)
    (h1 : ∀ τ : CechIdx n 1, Function.Injective ((locMap τ.toList φ).app d).hom) :
    IsIso ((cechHgrMap φ 0).app d) := by
  haveI i0 : IsIso ((cechComplexMap φ d).f 0) := by
    have hf : (cechComplexMap φ d).f 0 = cechCochainMap φ 0 d := rfl
    rw [hf]
    exact isIso_cechCochainMap φ 0 d h0
  haveI m1 : Mono ((cechComplexMap φ d).f 1) := by
    have hf : (cechComplexMap φ d).f 1 = cechCochainMap φ 1 d := rfl
    rw [hf]
    exact mono_cechCochainMap φ 1 d h1
  have hEq : (cechHgrMap φ 0).app d
      = (HomologicalComplex.homologyFunctor (ModuleCat.{u} k) (ComplexShape.up ℕ) 0).map
        (cechComplexMap φ d) := rfl
  rw [hEq]
  haveI iprev : IsIso ((cechComplexMap φ d).f ((ComplexShape.up ℕ).prev 0)) := by
    rw [CochainComplex.prev_nat_zero]
    exact i0
  haveI mnext : Mono ((cechComplexMap φ d).f ((ComplexShape.up ℕ).next 0)) := by
    rw [ComplexShape.next_eq' (ComplexShape.up ℕ) (show (0 : ℕ) + 1 = 1 from rfl)]
    exact m1
  have hh : (HomologicalComplex.homologyFunctor (ModuleCat.{u} k) (ComplexShape.up ℕ) 0).map
      (cechComplexMap φ d)
      = ShortComplex.homologyMap ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
        (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)) := rfl
  rw [hh]
  haveI t1 : Epi ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
    (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)).τ₁ := by
    haveI := iprev
    exact (inferInstance : Epi ((cechComplexMap φ d).f ((ComplexShape.up ℕ).prev 0)))
  haveI t2 : IsIso ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
    (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)).τ₂ := i0
  haveI t3 : Mono ((HomologicalComplex.shortComplexFunctor (ModuleCat.{u} k)
    (ComplexShape.up ℕ) 0).map (cechComplexMap φ d)).τ₃ := mnext
  exact ShortComplex.isIso_homologyMap_of_epi_of_isIso_of_mono' _ t1 t2 t3

/-- The `k`-linear equivalence on `Hᵍʳ 0` induced by a morphism that is bijective after
localizing at every variable and injective after localizing at every pair. -/
noncomputable def cechHgrZeroLinearEquivOfIsIsoLocOfInjective (φ : M ⟶ N) (d : ℤ)
    (h0 : ∀ τ : CechIdx n 0, Function.Bijective ((locMap τ.toList φ).app d).hom)
    (h1 : ∀ τ : CechIdx n 1, Function.Injective ((locMap τ.toList φ).app d).hom) :
    (M.cechHgr 0).obj d ≃ₗ[k] (N.cechHgr 0).obj d := by
  haveI := isIso_cechHgrMap_app_zero_of_injective φ d h0 h1
  exact (asIso ((cechHgrMap φ 0).app d)).toLinearEquiv

/-- **Čech cohomology in every cohomological degree only sees the single-variable
localizations.**  A morphism of graded modules that is bijective after localizing at each
single variable, in every degree `d + t` with `t : ℕ`, induces an isomorphism on `Hᵍʳ q` in
degree `d` for every `q`.  Combines `bijective_locMap_app_of_singleton_bijective` with
`isIso_cechCochainMap`. -/
theorem isIso_cechHgrMap_app_of_singleton_bijective {M N : GradedModule k n} (φ : M ⟶ N)
    (q : ℕ) (d : ℤ)
    (h : ∀ (a : Fin (n + 1)) (t : ℕ),
      Function.Bijective (((locMap [a] φ).app (d + (t : ℤ))).hom)) :
    IsIso ((cechHgrMap φ q).app d) := by
  haveI : IsIso (cechComplexMap φ d) := by
    haveI : ∀ p : ℕ, IsIso ((cechComplexMap φ d).f p) := by
      intro p
      have hf : (cechComplexMap φ d).f p = cechCochainMap φ p d := rfl
      rw [hf]
      refine isIso_cechCochainMap φ p d fun τ ↦ ?_
      refine bijective_locMap_app_of_singleton_bijective φ τ.toList ?_ d h
      intro hnil
      have := τ.length_eq
      rw [hnil] at this
      simp at this
    exact HomologicalComplex.Hom.isIso_of_components _
  have hEq : (cechHgrMap φ q).app d
      = (HomologicalComplex.homologyFunctor (ModuleCat.{u} k) (ComplexShape.up ℕ) q).map
        (cechComplexMap φ d) := rfl
  rw [hEq]
  infer_instance

end AlgebraicGeometry.ProjectiveSpace.GradedModule

end

end
