module

public import StacksAndModuli.API.ProjectiveGradedCoherent
public import StacksAndModuli.API.ProjectiveGradedStructureCohomology
public import Mathlib.Data.Int.Interval

/-!
# Serre's finiteness and vanishing theorems on `ℙⁿ_k`

Supporting API with no Stacks Project counterpart.

Hartshorne III.5.2 for the graded Čech model: for a finitely generated graded module `M`,
`Hⁱ(ℙⁿ, M~(d))` is finite dimensional, and vanishes for `i ≥ 1` once `d` is large.  Both go
by dévissage from the free presentation `S(-d₀)^{⊕r} ↠ M` of
`StacksAndModuli/API/ProjectiveGradedCoherent.lean`, with the kernel finitely generated by
`IsFG.of_injective` — which is why that field had to come first.

Main declarations:
- `GradedModule.bijective_cechHgrMap_of_shortExact_of_subsingleton`;
- `GradedModule.imgMod`, the image of the free presentation, and its comparison with `M`.
-/

@[expose] public section

noncomputable section

-- These files were written when Lean's backward-compat defeq options were on by default.
set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

universe u

namespace AlgebraicGeometry.ProjectiveSpace.GradedModule

open CategoryTheory MvPolynomial

variable {k : Type u} [CommRing k] [IsNoetherianRing k] {n : ℕ}

/-! ## The long exact sequence with a vanishing outer term -/

omit [IsNoetherianRing k] in
/-- If the third term of a short exact sequence has no Čech cohomology, the first map is an
isomorphism on cohomology in every degree. -/
lemma bijective_cechHgrMap_of_shortExact_of_subsingleton {M N P : GradedModule k n}
    {u : M ⟶ N} {v : N ⟶ P} (hSE : ShortExact u v)
    (hP : ∀ (i : ℕ) (d : ℤ), Subsingleton ((P.cechHgr i).obj d)) (i : ℕ) (d : ℤ) :
    Function.Bijective ((cechHgrMap u i).app d).hom := by
  refine ⟨?_, ?_⟩
  · cases i with
    | zero => exact cech_injective_map_zero hSE.injective d
    | succ i =>
        intro x z hxz
        have h0 : ((cechHgrMap u (i + 1)).app d).hom (x - z) = 0 := by
          rw [map_sub, hxz, sub_self]
        obtain ⟨w, hw⟩ := (cech_exact_δ_map hSE i d _).mp h0
        haveI := hP i d
        rw [Subsingleton.elim w 0, map_zero] at hw
        exact sub_eq_zero.mp hw.symm
  · intro z
    haveI := hP i d
    exact (cech_exact_map_map hSE i d _).mp (Subsingleton.elim _ _)

/-! ## The image of the free presentation -/

variable (M : GradedModule k n) (d₀ : ℤ) {r : ℕ} (y : Fin r → M.obj d₀)

/-- The image of the free presentation, as a graded submodule of `M`. -/
noncomputable def imgMod : GradedModule k n := ker (toCoker (freeGenHom M d₀ y))

/-- The inclusion of the image into `M`. -/
noncomputable def imgIota : imgMod M d₀ y ⟶ M := kerι (toCoker (freeGenHom M d₀ y))

omit [IsNoetherianRing k] in
lemma injective_imgIota (d : ℤ) : Function.Injective (((imgIota M d₀ y).app d).hom) :=
  fun _ _ h => Subtype.val_injective h

omit [IsNoetherianRing k] in
/-- The quotient of `M` by the image vanishes in every degree from `d₀` on. -/
lemma subsingleton_coker_imgIota (hy : Submodule.span k (Set.range y) = ⊤)
    (hgen : ∀ d : ℤ, d₀ ≤ d → M.mulSpan d (d + 1) = ⊤) (d : ℤ) (hd : d₀ ≤ d) :
    Subsingleton ((coker (imgIota M d₀ y)).obj d) := by
  have hsurj : Function.Surjective (((imgIota M d₀ y).app d).hom) := by
    intro z
    have hz : z ∈ LinearMap.ker (((toCoker (freeGenHom M d₀ y)).app d).hom) := by
      obtain ⟨p, hp⟩ := surjective_freeGenHom_app M d₀ y hy hgen d hd z
      rw [toCoker_app]
      show (LinearMap.range (((freeGenHom M d₀ y).app d).hom)).mkQ z = 0
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact ⟨p, hp⟩
    exact ⟨⟨z, hz⟩, rfl⟩
  constructor
  intro a b
  obtain ⟨a', rfl⟩ := Submodule.Quotient.mk_surjective _ a
  obtain ⟨b', rfl⟩ := Submodule.Quotient.mk_surjective _ b
  obtain ⟨a'', rfl⟩ := hsurj a'
  obtain ⟨b'', rfl⟩ := hsurj b'
  exact (Submodule.Quotient.eq _).mpr (by
    rw [← map_sub]
    exact LinearMap.mem_range_self _ _)

/-- The free presentation, corestricted to its image. -/
noncomputable def freeGenToImg :
    ((structureModule k n).twist (-d₀)).pow r ⟶ imgMod M d₀ y :=
  kerLift (toCoker (freeGenHom M d₀ y)) (freeGenHom M d₀ y) (fun d x => by
    rw [toCoker_app]
    show (LinearMap.range (((freeGenHom M d₀ y).app d).hom)).mkQ
      (((freeGenHom M d₀ y).app d).hom x) = 0
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
    exact ⟨x, rfl⟩)

omit [IsNoetherianRing k] in
lemma surjective_freeGenToImg (d : ℤ) :
    Function.Surjective (((freeGenToImg M d₀ y).app d).hom) := by
  rintro ⟨z, hz⟩
  rw [toCoker_app] at hz
  have hz' : z ∈ LinearMap.range (((freeGenHom M d₀ y).app d).hom) := by
    have h1 : z ∈ LinearMap.ker
        ((LinearMap.range (((freeGenHom M d₀ y).app d).hom)).mkQ) := hz
    rwa [Submodule.ker_mkQ] at h1
  obtain ⟨p, hp⟩ := hz'
  exact ⟨p, Subtype.ext hp⟩

omit [IsNoetherianRing k] in
/-- The free presentation is short exact onto its image. -/
lemma shortExact_freeGenToImg :
    ShortExact (kerι (freeGenHom M d₀ y)) (freeGenToImg M d₀ y) where
  injective _ _ _ h := Subtype.val_injective h
  exact d := by
    refine le_antisymm (fun x hx => ?_) (fun x hx => ?_)
    · obtain ⟨w, rfl⟩ := hx
      rw [LinearMap.mem_ker]
      refine Subtype.ext ?_
      exact LinearMap.mem_ker.mp w.2
    · rw [LinearMap.mem_ker] at hx
      refine ⟨⟨x, LinearMap.mem_ker.mpr (congrArg Subtype.val hx)⟩, rfl⟩
  surjective := surjective_freeGenToImg M d₀ y

omit [IsNoetherianRing k] in
/-- The image has the same cohomology as `M`, because the quotient vanishes in large
degrees. -/
lemma bijective_cechHgrMap_imgIota (hy : Submodule.span k (Set.range y) = ⊤)
    (hgen : ∀ d : ℤ, d₀ ≤ d → M.mulSpan d (d + 1) = ⊤) (i : ℕ) (d : ℤ) :
    Function.Bijective ((cechHgrMap (imgIota M d₀ y) i).app d).hom := by
  refine bijective_cechHgrMap_of_shortExact_of_subsingleton
    (shortExact_toCoker (imgIota M d₀ y) (injective_imgIota M d₀ y)) ?_ i d
  intro i' d'
  exact subsingleton_cechHgr_of_eventually_zero _
    ⟨d₀, fun e he => subsingleton_coker_imgIota M d₀ y hy hgen e he⟩ i' d'

/-! ## `H⁰(ℙⁿ, 𝒪(d))` in negative degrees -/

/-- The Čech index of a single variable. -/
def singIdx (i : Fin (n + 1)) : CechIdx n 0 :=
  ⟨[i], List.pairwise_singleton _ _, rfl⟩

@[simp] lemma singIdx_toList (i : Fin (n + 1)) : (singIdx i).toList = [i] := rfl

@[simp] lemma singIdx_toFinset (i : Fin (n + 1)) :
    (singIdx (n := n) i).toFinset = {i} := by
  simp [CechIdx.toFinset]

omit [IsNoetherianRing k] in
/-- On `ℙⁿ` with `n ≥ 1`, a `0`-cocycle in a negative degree vanishes: its components agree
as Laurent elements, so no exponent is negative, so the degree is `≥ 0`. -/
lemma cocycle_eq_zero_of_neg (hn : 1 ≤ n) {d : ℤ} (hd : d < 0)
    (c : (structureModule k n).cechCochain 0 d)
    (hc : ((structureModule k n).cechD 0 d).hom c = 0) : c = 0 := by
  classical
  have hpair : ∀ i j : Fin (n + 1), i ≠ j → ∀ a : Fin (n + 1) → ℤ,
      cechLaurent k d c {i} a ≠ 0 → cechLaurent k d c {j} a ≠ 0 := by
    intro i j hij a hai
    have hzero := simplicialD_cechLaurent_eq_zero d c hc {i, j}
    rw [Finset.simplicialD, Finset.sum_pair hij] at hzero
    have he₁ : ({i, j} : Finset (Fin (n + 1))).erase i = {j} := by
      rw [Finset.erase_insert (by simpa using hij)]
    have he₂ : ({i, j} : Finset (Fin (n + 1))).erase j = {i} := by
      rw [Finset.pair_comm, Finset.erase_insert (by simpa using hij.symm)]
    rw [he₁, he₂] at hzero
    have hval := congrArg (fun w : LaurentSpace k n => w a) hzero
    simp only [Finsupp.add_apply, Finsupp.smul_apply, Finsupp.coe_zero,
      Pi.zero_apply] at hval
    intro hzj
    rw [hzj, smul_zero, zero_add, zsmul_eq_mul] at hval
    have hunit : IsUnit ((((Finset.koszulSign j ({i, j} : Finset (Fin (n + 1)))) : ℤ) : k)) := by
      rw [Finset.koszulSign]
      push_cast
      exact IsUnit.pow _ (isUnit_one.neg)
    obtain ⟨w, hw⟩ := hunit.exists_left_inv
    refine hai ?_
    have h2 := congrArg (fun z : k => w * z) hval
    simpa only [mul_zero, ← mul_assoc, hw, one_mul] using h2
  have hcomp : ∀ i : Fin (n + 1), cechLaurent k d c {i} = 0 := by
    intro i
    refine Finsupp.ext fun a => ?_
    by_contra hai
    obtain ⟨j, hij⟩ : ∃ j : Fin (n + 1), j ≠ i := by
      rcases eq_or_ne i ⟨0, by omega⟩ with hi0 | hi0
      · exact ⟨⟨1, by omega⟩, by rw [hi0]; exact fun hc => by simpa using congrArg Fin.val hc⟩
      · exact ⟨⟨0, by omega⟩, fun hc => hi0 hc.symm⟩
    have hmemi := cechLaurent_mem d c (singIdx (n := n) i)
    have hmemj := cechLaurent_mem d c (singIdx (n := n) j)
    rw [singIdx_toFinset, laurentPiece, Finsupp.mem_supported] at hmemi hmemj
    have hai' : a ∈ lexpAdm (singIdx (n := n) i).toList d :=
      hmemi (Finset.mem_coe.mpr (Finsupp.mem_support_iff.mpr hai))
    have haj' : a ∈ lexpAdm (singIdx (n := n) j).toList d :=
      hmemj (Finset.mem_coe.mpr (Finsupp.mem_support_iff.mpr
        (hpair i j (Ne.symm hij) a hai)))
    have hall : ∀ l : Fin (n + 1), 0 ≤ a l := by
      intro l
      rcases eq_or_ne l i with rfl | hl
      · refine haj'.2 l ?_
        simp only [singIdx_toList, List.mem_singleton]
        exact fun h => hij h.symm
      · refine hai'.2 l ?_
        simp only [singIdx_toList, List.mem_singleton]
        exact hl
    have hsum : (0 : ℤ) ≤ lexpDeg a := Finset.sum_nonneg fun l _ => hall l
    rw [hai'.1] at hsum
    omega
  funext τ
  obtain ⟨i, hi⟩ : ∃ i : Fin (n + 1), τ.toList = [i] :=
    List.length_eq_one_iff.mp τ.length_eq
  have hτ : τ = singIdx i := CechIdx.ext (by rw [hi]; rfl)
  subst hτ
  refine laurent_injective (singIdx i).toList d ?_
  show (laurent (singIdx i).toList d).hom (c (singIdx i))
    = (laurent (singIdx i).toList d).hom 0
  rw [map_zero, ← cechLaurent_toFinset d c (singIdx i), singIdx_toFinset]
  exact hcomp i

omit [IsNoetherianRing k] in
lemma finiteDimensional_of_subsingleton {V : Type*} [AddCommGroup V] [Module k V]
    [Subsingleton V] : Module.Finite k V := by
  have htop : (⊤ : Submodule k V) = ⊥ :=
    (Submodule.eq_bot_iff _).mpr fun x _ => Subsingleton.elim x 0
  exact ⟨htop ▸ Submodule.fg_bot⟩

omit [IsNoetherianRing k] in
/-- `H⁰(ℙⁿ, 𝒪(d)) = 0` for `d < 0` when `n ≥ 1`. -/
theorem subsingleton_cechHgr_zero_of_neg (hn : 1 ≤ n) {d : ℤ} (hd : d < 0) :
    Subsingleton ((((structureModule k n).cechHgr 0)).obj d) := by
  haveI hsub : Subsingleton ((structureModule k n).obj d) :=
    subsingleton_polySubmodule_lt_zero (k := k) (n := n) hd
  have hsurj : Function.Surjective (((structureModule k n).cechAug d).hom) :=
    surjective_cechAug_of_cocycles _ d (fun c hc =>
      ⟨0, by rw [map_zero, cocycle_eq_zero_of_neg hn hd c hc]⟩)
  refine ⟨fun a b => ?_⟩
  obtain ⟨x, rfl⟩ := hsurj a
  obtain ⟨y, rfl⟩ := hsurj b
  rw [Subsingleton.elim x y]

omit [IsNoetherianRing k] in
/-- The cohomology of the twisting sheaves is finite dimensional away from the top degree. -/
theorem finiteDimensional_cechHgr_structureModule_of_ne (i : ℕ) (d : ℤ) (hi : i ≠ n) :
    Module.Finite k ((((structureModule k n).cechHgr i)).obj d) := by
  rcases Nat.eq_zero_or_pos i with rfl | hipos
  · -- `H⁰`
    have hn1 : 1 ≤ n := by omega
    rcases lt_or_ge d 0 with hd | hd
    · haveI := subsingleton_cechHgr_zero_of_neg (k := k) hn1 hd
      exact finiteDimensional_of_subsingleton
    · haveI : Mono ((structureModule k n).cechAug d) :=
        (ModuleCat.mono_iff_injective _).mpr
          (injective_cechAug _ (injective_structureModule_mulX n) d)
      haveI : Epi ((structureModule k n).cechAug d) :=
        (ModuleCat.epi_iff_surjective _).mpr
          (surjective_cechAug_of_cocycles _ d
            (fun cc hcc => cocycle_structureModule d hd cc hcc))
      haveI : IsIso ((structureModule k n).cechAug d) := isIso_of_mono_of_epi _
      exact Module.Finite.equiv
        ((asIso ((structureModule k n).cechAug d)).toLinearEquiv)
  · -- `Hⁱ` for `1 ≤ i ≠ n`
    haveI := subsingleton_cechHgr_structureModule (k := k) (n := n) i d hipos (Or.inl hi)
    exact finiteDimensional_of_subsingleton

/-! ## The top degree -/

/-- Homology is a subquotient, so a finite-dimensional term gives finite-dimensional
homology. -/
lemma finiteDimensional_homology_of_X (K : CochainComplex (ModuleCat.{u} k) ℕ) (i : ℕ)
    [Module.Finite k (K.X i)] : Module.Finite k (K.homology i) := by
  haveI hcyc : Module.Finite k (K.cycles i) :=
    Module.Finite.of_injective ((K.iCycles i)).hom
      ((ModuleCat.mono_iff_injective _).mp inferInstance)
  exact Module.Finite.of_surjective ((K.homologyπ i)).hom
    ((ModuleCat.epi_iff_surjective _).mp inferInstance)

omit [IsNoetherianRing k] in
/-- On `ℙ⁰` the Čech cochains are finite dimensional: there is one chart and one Laurent
monomial in each degree. -/
lemma finiteDimensional_supported_of_finite {s : Set (Fin (n + 1) → ℤ)} (hs : s.Finite) :
    Module.Finite k (Finsupp.supported k k s) := by
  rw [Finsupp.supported_eq_span_single]
  exact Module.Finite.span_of_finite k (hs.image _)

omit [IsNoetherianRing k] in
lemma finiteDimensional_laurentPiece_of_finite {l : List (Fin (n + 1))} {d : ℤ}
    (hfin : (lexpAdm l d).Finite) : Module.Finite k (laurentPiece k l d) :=
  finiteDimensional_supported_of_finite hfin

/-- Every localization of the structure sheaf on `ℙ⁰` is one dimensional in each degree:
there is exactly one Laurent monomial of a given degree in one variable. -/
lemma finite_lexpAdm_zero (l : List (Fin (0 + 1))) (d : ℤ) : (lexpAdm l d).Finite := by
  refine Set.Finite.subset (Set.finite_singleton (fun _ : Fin (0 + 1) => d)) ?_
  rintro a ⟨ha, -⟩
  have h0 : a 0 = d := by
    rw [lexpDeg, Fin.sum_univ_one] at ha
    exact ha
  refine Set.mem_singleton_iff.mpr ?_
  funext i
  haveI : Subsingleton (Fin (0 + 1)) := inferInstanceAs (Subsingleton (Fin 1))
  rw [Subsingleton.elim i 0]
  exact h0

omit [IsNoetherianRing k] in
lemma finiteDimensional_loc_zero (l : List (Fin (0 + 1))) (d : ℤ) :
    Module.Finite k (((structureModule k 0).loc l).obj d) := by
  haveI : Module.Finite k (laurentPiece k l d) :=
    finiteDimensional_laurentPiece_of_finite (finite_lexpAdm_zero l d)
  have he : (((structureModule k 0).loc l).obj d)
      ≃ₗ[k] (LinearMap.range ((laurent (k := k) l d).hom)) :=
    LinearEquiv.ofInjective _ (laurent_injective l d)
  have he' : (LinearMap.range ((laurent (k := k) l d).hom)) = laurentPiece k l d :=
    range_laurent l d
  exact Module.Finite.of_surjective (he.symm.toLinearMap.comp
    (LinearEquiv.ofEq _ _ he'.symm).toLinearMap)
    (fun z => by
      obtain ⟨w, hw⟩ := he.symm.surjective z
      exact ⟨(LinearEquiv.ofEq _ _ he'.symm).symm w, by
        simp only [LinearMap.comp_apply, LinearEquiv.coe_coe]
        rw [LinearEquiv.apply_symm_apply, hw]⟩)

omit [IsNoetherianRing k] in
/-- On `ℙ⁰` all Čech cohomology is finite dimensional. -/
theorem finiteDimensional_cechHgr_structureModule_zero (i : ℕ) (d : ℤ) :
    Module.Finite k ((((structureModule k 0).cechHgr i)).obj d) := by
  cases i with
  | succ i =>
      haveI := subsingleton_cechHgr (structureModule k 0) (i + 1) (by omega) d
      exact finiteDimensional_of_subsingleton
  | zero =>
      have hfinite_nonneg : ∀ e : ℤ, 0 ≤ e →
          Module.Finite k ((((structureModule k 0).cechHgr 0)).obj e) := by
        intro e he
        haveI : Mono ((structureModule k 0).cechAug e) :=
          (ModuleCat.mono_iff_injective _).mpr
            (injective_cechAug _ (injective_structureModule_mulX 0) e)
        haveI : Epi ((structureModule k 0).cechAug e) :=
          (ModuleCat.epi_iff_surjective _).mpr
            (surjective_cechAug_of_cocycles _ e
              (fun cc hcc => cocycle_structureModule e he cc hcc))
        haveI : IsIso ((structureModule k 0).cechAug e) := isIso_of_mono_of_epi _
        exact Module.Finite.equiv
          ((asIso ((structureModule k 0).cechAug e)).toLinearEquiv)
      by_cases hd : 0 ≤ d
      · exact hfinite_nonneg d hd
      · let L : List (Fin 1) := List.replicate ((0 - d).toNat) 0
        have hlen : d + (L.length : ℤ) = 0 := by
          simp only [L, List.length_replicate]
          omega
        haveI := zero_cechHgr_mulList_isIso (structureModule k 0) 0 L d 0 hlen
        haveI : Module.Finite k ((((structureModule k 0).cechHgr 0)).obj 0) :=
          hfinite_nonneg 0 le_rfl
        exact Module.Finite.equiv
          ((asIso (((structureModule k 0).cechHgr 0).mulList L d 0 hlen)).symm.toLinearEquiv)

/-! ## The top degree for `n ≥ 1` -/

lemma CechIdx.toFinset_top (τ : CechIdx n n) : τ.toFinset = Finset.univ :=
  Finset.eq_univ_of_card _ (by rw [τ.card_toFinset]; simp)

omit [IsNoetherianRing k] in
/-- A Laurent monomial with a non-negative exponent is a Čech coboundary in the top degree:
cone off the variable at which it is regular. -/
lemma single_mem_span_range_cechD {m : ℕ} (d : ℤ) (a : Fin (m + 1 + 1) → ℤ)
    (had : lexpDeg a = d) (v : Fin (m + 1 + 1)) (hav : 0 ≤ a v)
    (υ : CechIdx (m + 1) (m + 1)) :
    ∃ u : (structureModule k (m + 1)).cechCochain m d,
      (laurent υ.toList d).hom ((((structureModule k (m + 1)).cechD m d).hom u) υ)
        = (Finset.koszulSign v (Finset.univ : Finset (Fin (m + 1 + 1)))) •
            (Finsupp.single a (1 : k)) := by
  classical
  have hpre : ∀ τ : CechIdx (m + 1) m, τ.toFinset = Finset.univ.erase v →
      Finsupp.single a (1 : k) ∈ LinearMap.range ((laurent (k := k) τ.toList d).hom) := by
    intro τ hτ
    rw [range_laurent]
    refine Finsupp.single_mem_supported _ _ ⟨had, fun i hi => ?_⟩
    have hiv : i = v := by
      by_contra hc
      refine hi ?_
      rw [← CechIdx.mem_toFinset, hτ]
      exact Finset.mem_erase.mpr ⟨hc, Finset.mem_univ i⟩
    rw [hiv]
    exact hav
  -- an opaque cochain supported on the single index missing `v`
  have hex : ∀ τ : CechIdx (m + 1) m,
      ∃ z : (((structureModule k (m + 1)).loc τ.toList).obj d),
        (τ.toFinset = Finset.univ.erase v →
          (laurent τ.toList d).hom z = Finsupp.single a (1 : k)) ∧
        (τ.toFinset ≠ Finset.univ.erase v → z = 0) := by
    intro τ
    by_cases h : τ.toFinset = Finset.univ.erase v
    · obtain ⟨z, hz⟩ := LinearMap.mem_range.mp (hpre τ h)
      exact ⟨z, fun _ => hz, fun hc => absurd h hc⟩
    · exact ⟨0, fun hc => absurd hc h, fun _ => rfl⟩
  choose u hu1 hu0 using hex
  refine ⟨u, ?_⟩
  rw [← simplicialD_cechLaurent d u υ, Finset.simplicialD, CechIdx.toFinset_top]
  have hterm : ∀ x ∈ (Finset.univ : Finset (Fin (m + 1 + 1))),
      Finset.koszulSign x Finset.univ • cechLaurent k d u (Finset.univ.erase x)
        = if x = v then
            (Finset.koszulSign v (Finset.univ : Finset (Fin (m + 1 + 1)))) •
              (Finsupp.single a (1 : k))
          else 0 := by
    intro x _
    have hcard : (Finset.univ.erase x).card = m + 1 := by
      rw [Finset.card_erase_of_mem (Finset.mem_univ x)]
      simp
    obtain ⟨τ, hτ⟩ := CechIdx.exists_toFinset_eq (p := m) (Finset.univ.erase x) hcard
    have hval : cechLaurent k d u (Finset.univ.erase x)
        = (laurent τ.toList d).hom (u τ) := by
      rw [← hτ]
      exact cechLaurent_toFinset d u τ
    by_cases hxv : x = v
    · subst hxv
      rw [hval, hu1 τ hτ]
      simp only [↓reduceIte]
    · rw [if_neg hxv, hval, hu0 τ (by
        rw [hτ]
        intro hc
        refine hxv ?_
        have hx : x ∉ Finset.univ.erase x := Finset.notMem_erase x _
        rw [hc] at hx
        by_contra hne'
        exact hx (Finset.mem_erase.mpr ⟨hne', Finset.mem_univ x⟩)), map_zero, smul_zero]
  rw [Finset.sum_congr rfl hterm, Finset.sum_ite_eq' Finset.univ v]
  simp only [Finset.mem_univ, ↓reduceIte]

instance subsingleton_cechIdx_top : Subsingleton (CechIdx n n) :=
  ⟨fun σ τ => CechIdx.toFinset_injective
    (by rw [CechIdx.toFinset_top, CechIdx.toFinset_top])⟩

/-- In the top Čech degree every variable is inverted, so there is no positivity
constraint. -/
lemma lexpAdm_top (τ : CechIdx n n) (d : ℤ) :
    lexpAdm τ.toList d = {a : Fin (n + 1) → ℤ | lexpDeg a = d} := by
  ext a
  refine ⟨fun h => h.1, fun h => ⟨h, fun i hi => absurd ?_ hi⟩⟩
  rw [← CechIdx.mem_toFinset, CechIdx.toFinset_top]
  exact Finset.mem_univ i

/-- For a fixed degree there are only finitely many Laurent monomials with every exponent
negative: each exponent is squeezed between `d + n` and `-1`. -/
lemma finite_allNeg (d : ℤ) :
    {a : Fin (n + 1) → ℤ | lexpDeg a = d ∧ ∀ i, a i < 0}.Finite := by
  classical
  refine Set.Finite.subset
    (Set.Finite.pi (fun _ : Fin (n + 1) => Set.finite_Icc (d + (n : ℤ)) (-1))) ?_
  rintro a ⟨hdeg, hneg⟩ i -
  have hai := hneg i
  refine ⟨?_, by omega⟩
  -- the other `n` exponents sum to at most `-n`
  have hsplit : a i + ∑ j ∈ Finset.univ.erase i, a j = lexpDeg a := by
    rw [lexpDeg]
    exact Finset.add_sum_erase _ _ (Finset.mem_univ i)
  have hbound : ∑ j ∈ Finset.univ.erase i, a j ≤ -(n : ℤ) := by
    have hcard : (Finset.univ.erase i).card = n := by
      rw [Finset.card_erase_of_mem (Finset.mem_univ i)]
      simp
    have hle : ∑ j ∈ Finset.univ.erase i, a j
        ≤ ∑ _j ∈ Finset.univ.erase i, (-1 : ℤ) :=
      Finset.sum_le_sum fun j _ => by have := hneg j; omega
    rw [Finset.sum_const, hcard] at hle
    simpa using hle
  omega

instance nonempty_cechIdx_top : Nonempty (CechIdx n n) :=
  ⟨(CechIdx.exists_toFinset_eq (p := n) (Finset.univ : Finset (Fin (n + 1))) (by simp)).choose⟩

noncomputable instance unique_cechIdx_top : Unique (CechIdx n n) :=
  haveI : Inhabited (CechIdx n n) := Classical.inhabited_of_nonempty inferInstance
  Unique.mk' _

omit [IsNoetherianRing k] in
/-- Every Laurent monomial of the right degree occurs in the top Čech group. -/
lemma single_mem_laurentPiece_top (τ : CechIdx n n) (d : ℤ) {a : Fin (n + 1) → ℤ}
    (ha : lexpDeg a = d) : Finsupp.single a (1 : k) ∈ laurentPiece k τ.toList d := by
  refine Finsupp.single_mem_supported _ _ ?_
  rw [lexpAdm_top τ d]
  exact ha

omit [IsNoetherianRing k] in
/-- The top Čech group is spanned by the Laurent monomials of the right degree. -/
lemma top_cechCochain_eq_span (τ : CechIdx n n) (d : ℤ) :
    Submodule.span k {w : LaurentSpace k n |
        ∃ a : Fin (n + 1) → ℤ, lexpDeg a = d ∧ w = Finsupp.single a (1 : k)}
      = laurentPiece k τ.toList d := by
  rw [laurentPiece, lexpAdm_top τ d, Finsupp.supported_eq_span_single]
  congr 1
  ext w
  constructor
  · rintro ⟨a, ha, rfl⟩
    exact ⟨a, ha, rfl⟩
  · rintro ⟨a, ha, rfl⟩
    exact ⟨a, ha, rfl⟩

/-! ## Splitting the top Čech group -/

variable (k) in
/-- Laurent elements supported on monomials with every exponent negative — a finite
dimensional space. -/
noncomputable def topNeg {m : ℕ} (d : ℤ) : Submodule k (LaurentSpace k (m + 1)) :=
  Finsupp.supported k k {a : Fin (m + 1 + 1) → ℤ | lexpDeg a = d ∧ ∀ i, a i < 0}

omit [IsNoetherianRing k] in
lemma finiteDimensional_topNeg {m : ℕ} (d : ℤ) : Module.Finite k (topNeg k (m := m) d) :=
  finiteDimensional_supported_of_finite (k := k) (n := m + 1) (finite_allNeg (n := m + 1) d)

/-- Coboundaries in the top Čech group. -/
noncomputable def topBdryMap {m : ℕ} (d : ℤ) (υ : CechIdx (m + 1) (m + 1)) :
    (structureModule k (m + 1)).cechCochain m d →ₗ[k]
      (((structureModule k (m + 1)).loc υ.toList).obj d) :=
  (LinearMap.proj υ).comp (((structureModule k (m + 1)).cechD m d).hom)

omit [IsNoetherianRing k] in
/-- A monomial with a non-negative exponent lies in the image of the coboundaries. -/
lemma single_mem_map_topBdry {m : ℕ} (d : ℤ) (υ : CechIdx (m + 1) (m + 1))
    {a : Fin (m + 1 + 1) → ℤ} (ha : lexpDeg a = d) {v : Fin (m + 1 + 1)} (hav : 0 ≤ a v) :
    Finsupp.single a (1 : k) ∈ Submodule.map ((laurent υ.toList d).hom)
      (LinearMap.range (topBdryMap d υ)) := by
  obtain ⟨u, hu⟩ := single_mem_span_range_cechD (k := k) d a ha v hav υ
  have hsq := Finset.koszulSign_smul_koszulSign_smul v
    (Finset.univ : Finset (Fin (m + 1 + 1))) (Finsupp.single a (1 : k))
  rw [← hsq, ← hu]
  have hmem : (laurent υ.toList d).hom ((((structureModule k (m + 1)).cechD m d).hom u) υ)
      ∈ Submodule.map ((laurent υ.toList d).hom) (LinearMap.range (topBdryMap d υ)) :=
    ⟨(((structureModule k (m + 1)).cechD m d).hom u) υ, ⟨u, rfl⟩, rfl⟩
  exact zsmul_mem hmem _

omit [IsNoetherianRing k] in
/-- The top Čech group splits: all-negative monomials, plus coboundaries. -/
lemma laurentPiece_top_le {m : ℕ} (d : ℤ) (υ : CechIdx (m + 1) (m + 1)) :
    laurentPiece k υ.toList d ≤ topNeg k d ⊔ Submodule.map ((laurent υ.toList d).hom)
      (LinearMap.range (topBdryMap d υ)) := by
  classical
  rw [← top_cechCochain_eq_span υ d, Submodule.span_le]
  rintro _ ⟨a, ha, rfl⟩
  by_cases hall : ∀ i, a i < 0
  · exact Submodule.mem_sup_left (Finsupp.single_mem_supported _ _ ⟨ha, hall⟩)
  · obtain ⟨v, hv⟩ : ∃ v, 0 ≤ a v := by
      by_contra hc
      exact hall (by
        intro i
        by_contra hi
        exact hc ⟨i, by omega⟩)
    exact Submodule.mem_sup_right (single_mem_map_topBdry d υ ha hv)

/-! ## From the splitting to finite dimensionality -/

omit [IsNoetherianRing k] in
/-- In the top Čech degree the outgoing differential is zero. -/
lemma cechComplex_d_top_eq_zero {m : ℕ} (d : ℤ) :
    ((structureModule k (m + 1)).cechComplex d).d (m + 1) (m + 2) = 0 :=
  (isZero_cechCochain (structureModule k (m + 1)) (p := m + 2) (by omega) d).eq_zero_of_tgt _

/-- Every top-degree cochain is a cycle, giving a surjection onto the cohomology. -/
noncomputable def topClass {m : ℕ} (d : ℤ) :
    ((structureModule k (m + 1)).cechCochain (m + 1) d)
      ⟶ (((structureModule k (m + 1)).cechHgr (m + 1)).obj d) :=
  ((structureModule k (m + 1)).cechComplex d).liftCycles (𝟙 (((structureModule k (m + 1)).cechComplex d).X (m + 1))) (m + 2) (by simp)
      (by rw [cechComplex_d_top_eq_zero, Limits.comp_zero]) ≫
    ((structureModule k (m + 1)).cechComplex d).homologyπ (m + 1)

omit [IsNoetherianRing k] in
lemma topClass_apply {m : ℕ} (d : ℤ)
    (x : (structureModule k (m + 1)).cechCochain (m + 1) d) :
    (topClass (k := k) (m := m) d).hom x
      = (((structureModule k (m + 1)).cechComplex d).homologyπ (m + 1)).hom
          ((((structureModule k (m + 1)).cechComplex d).liftCycles (𝟙 (((structureModule k (m + 1)).cechComplex d).X (m + 1))) (m + 2) (by simp)
            (by rw [cechComplex_d_top_eq_zero, Limits.comp_zero])).hom x) := rfl

omit [IsNoetherianRing k] in
lemma surjective_topClass {m : ℕ} (d : ℤ) :
    Function.Surjective ((topClass (k := k) (m := m) d).hom) := by
  intro q
  obtain ⟨c, hc⟩ := (ModuleCat.epi_iff_surjective
    (((structureModule k (m + 1)).cechComplex d).homologyπ (m + 1))).mp inferInstance q
  refine ⟨(((structureModule k (m + 1)).cechComplex d).iCycles (m + 1)).hom c, ?_⟩
  rw [topClass_apply]
  have hmono : Function.Injective
      ((((structureModule k (m + 1)).cechComplex d).iCycles (m + 1)).hom) :=
    (ModuleCat.mono_iff_injective _).mp inferInstance
  have hfac := congrArg ModuleCat.Hom.hom
    (((structureModule k (m + 1)).cechComplex d).liftCycles_i (i := m + 1)
      (𝟙 (((structureModule k (m + 1)).cechComplex d).X (m + 1))) (m + 2) (by simp)
      (by rw [cechComplex_d_top_eq_zero, Limits.comp_zero]))
  rw [ModuleCat.hom_comp] at hfac
  have hlc : (((structureModule k (m + 1)).cechComplex d).liftCycles (𝟙 (((structureModule k (m + 1)).cechComplex d).X (m + 1))) (m + 2) (by simp)
      (by rw [cechComplex_d_top_eq_zero, Limits.comp_zero])).hom
      ((((structureModule k (m + 1)).cechComplex d).iCycles (m + 1)).hom c) = c := by
    refine hmono ?_
    have h1 := LinearMap.congr_fun hfac
      ((((structureModule k (m + 1)).cechComplex d).iCycles (m + 1)).hom c)
    simp only [LinearMap.comp_apply, ModuleCat.hom_id, LinearMap.id_apply] at h1
    exact h1
  rw [hlc, hc]

omit [IsNoetherianRing k] in
/-- Coboundaries have zero class. -/
lemma topClass_cechD {m : ℕ} (d : ℤ)
    (u : (structureModule k (m + 1)).cechCochain m d) :
    (topClass (k := k) (m := m) d).hom ((((structureModule k (m + 1)).cechD m d).hom u))
      = 0 := by
  have hdm : ((structureModule k (m + 1)).cechComplex d).d m (m + 1)
      = (structureModule k (m + 1)).cechD m d :=
    CochainComplex.of_d (fun p => (structureModule k (m + 1)).cechCochain p d)
      (fun p => (structureModule k (m + 1)).cechD p d) m
  have hlift : ((structureModule k (m + 1)).cechComplex d).d m (m + 1) ≫
      ((structureModule k (m + 1)).cechComplex d).liftCycles
        (𝟙 (((structureModule k (m + 1)).cechComplex d).X (m + 1))) (m + 2) (by simp)
        (by rw [cechComplex_d_top_eq_zero, Limits.comp_zero])
      = ((structureModule k (m + 1)).cechComplex d).toCycles m (m + 1) := by
    refine (cancel_mono (((structureModule k (m + 1)).cechComplex d).iCycles (m + 1))).mp ?_
    rw [Category.assoc, HomologicalComplex.liftCycles_i, HomologicalComplex.toCycles_i]
    simp
  have hcomp : ((structureModule k (m + 1)).cechComplex d).d m (m + 1) ≫ topClass d = 0 := by
    rw [topClass, ← Category.assoc, hlift,
      HomologicalComplex.toCycles_comp_homologyπ]
  have := congrArg ModuleCat.Hom.hom hcomp
  rw [ModuleCat.hom_comp, hdm] at this
  exact LinearMap.congr_fun this u

/-- The top Čech group, read in the Laurent model. -/
noncomputable def topLaurent {m : ℕ} (d : ℤ) :
    (structureModule k (m + 1)).cechCochain (m + 1) d →ₗ[k] LaurentSpace k (m + 1) :=
  ((laurent (default : CechIdx (m + 1) (m + 1)).toList d).hom).comp (LinearMap.proj default)

omit [IsNoetherianRing k] in
lemma injective_topLaurent {m : ℕ} (d : ℤ) :
    Function.Injective (topLaurent (k := k) (m := m) d) := by
  intro z w hzw
  funext τ
  rw [Subsingleton.elim τ default]
  exact laurent_injective _ d hzw

omit [IsNoetherianRing k] in
lemma range_topLaurent {m : ℕ} (d : ℤ) :
    LinearMap.range (topLaurent (k := k) (m := m) d)
      = laurentPiece k (default : CechIdx (m + 1) (m + 1)).toList d := by
  rw [← range_laurent]
  refine le_antisymm ?_ ?_
  · rintro _ ⟨z, rfl⟩
    exact ⟨z default, rfl⟩
  · rintro _ ⟨x, rfl⟩
    refine ⟨(Equiv.piUnique (fun τ : CechIdx (m + 1) (m + 1) =>
      (((structureModule k (m + 1)).loc τ.toList).obj d))).symm x, ?_⟩
    show (laurent (default : CechIdx (m + 1) (m + 1)).toList d).hom _ = _
    congr 1

omit [IsNoetherianRing k] in
lemma topNeg_le_range {m : ℕ} (d : ℤ) :
    topNeg k (m := m) d ≤ LinearMap.range (topLaurent (k := k) (m := m) d) := by
  rw [range_topLaurent, laurentPiece, lexpAdm_top default d]
  refine Finsupp.supported_mono ?_
  rintro a ⟨ha, -⟩
  exact ha

omit [IsNoetherianRing k] in
/-- Every top cochain is an all-negative one plus a coboundary. -/
lemma exists_topNeg_add_cechD {m : ℕ} (d : ℤ)
    (z : (structureModule k (m + 1)).cechCochain (m + 1) d) :
    ∃ c : (structureModule k (m + 1)).cechCochain (m + 1) d,
      topLaurent d c ∈ topNeg k (m := m) d ∧
      ∃ u : (structureModule k (m + 1)).cechCochain m d,
        z = c + (((structureModule k (m + 1)).cechD m d).hom u) := by
  have hmem : topLaurent d z ∈ laurentPiece k (default : CechIdx (m + 1) (m + 1)).toList d := by
    rw [← range_topLaurent]
    exact ⟨z, rfl⟩
  obtain ⟨w₁, hw₁, w₂, hw₂, hsum⟩ :=
    Submodule.mem_sup.mp (laurentPiece_top_le d default hmem)
  obtain ⟨b, ⟨u, hu⟩, hb⟩ := hw₂
  refine ⟨z - (((structureModule k (m + 1)).cechD m d).hom u), ?_, u, by abel⟩
  have hcd : topLaurent d ((((structureModule k (m + 1)).cechD m d).hom u)) = w₂ := by
    rw [← hb, ← hu]
    rfl
  rw [map_sub, hcd, ← hsum]
  simpa using hw₁

omit [IsNoetherianRing k] in
/-- **Serre finiteness for the twisting sheaves in the top degree.** -/
theorem finiteDimensional_cechHgr_structureModule_top {m : ℕ} (d : ℤ) :
    Module.Finite k ((((structureModule k (m + 1)).cechHgr (m + 1))).obj d) := by
  haveI := finiteDimensional_topNeg (k := k) (m := m) d
  refine Module.Finite.of_surjective
    (((topClass (k := k) (m := m) d).hom).comp
      (((LinearEquiv.ofInjective (topLaurent (k := k) (m := m) d)
        (injective_topLaurent d)).symm.toLinearMap).comp
        (Submodule.inclusion (topNeg_le_range (k := k) (m := m) d)))) ?_
  intro q
  obtain ⟨z, hz⟩ := surjective_topClass (k := k) (m := m) d q
  obtain ⟨c, hc, u, hzc⟩ := exists_topNeg_add_cechD d z
  refine ⟨⟨topLaurent d c, hc⟩, ?_⟩
  show (topClass (k := k) (m := m) d).hom
    ((LinearEquiv.ofInjective (topLaurent (k := k) (m := m) d)
      (injective_topLaurent d)).symm ⟨topLaurent d c, ⟨c, rfl⟩⟩) = q
  rw [show ((LinearEquiv.ofInjective (topLaurent (k := k) (m := m) d)
      (injective_topLaurent d)).symm ⟨topLaurent d c, ⟨c, rfl⟩⟩) = c from
    (LinearEquiv.symm_apply_eq _).mpr rfl]
  rw [← hz, hzc, map_add, topClass_cechD, add_zero]

/-! ## Serre finiteness by dévissage -/

/-- Finite dimensionality passes to the middle term of an exact sequence. -/
lemma finiteDimensional_of_exact {A B C : Type*} [AddCommGroup A] [Module k A]
    [AddCommGroup B] [Module k B] [AddCommGroup C] [Module k C]
    (f : A →ₗ[k] B) (g : B →ₗ[k] C) (hfg : Function.Exact f g)
    [Module.Finite k A] [Module.Finite k C] : Module.Finite k B := by
  have h1 : Module.Finite k (LinearMap.ker g) := by
    rw [hfg.linearMap_ker_eq]
    infer_instance
  have h2 : Module.Finite k (B ⧸ LinearMap.ker g) :=
    Module.Finite.equiv (g.quotKerEquivRange).symm
  exact Module.Finite.of_submodule_quotient (LinearMap.ker g)

omit [IsNoetherianRing k] in
/-- Finite dimensionality transports along an isomorphism of `ModuleCat`. -/
lemma finiteDimensional_of_iso {A B : ModuleCat.{u} k} (e : A ≅ B)
    [Module.Finite k A] : Module.Finite k B :=
  Module.Finite.of_surjective e.hom.hom fun y =>
    ⟨e.inv.hom y, by
      simpa using congrArg (fun f : B ⟶ B => f.hom y) e.inv_hom_id⟩

omit [IsNoetherianRing k] in
/-- **Serre finiteness for the twisting sheaves**, all `i` and all `d`. -/
theorem finiteDimensional_cechHgr_structureModule (i : ℕ) (d : ℤ) :
    Module.Finite k (((structureModule k n).cechHgr i).obj d) := by
  rcases eq_or_ne i n with rfl | hi
  · cases i with
    | zero => exact finiteDimensional_cechHgr_structureModule_zero 0 d
    | succ m => exact finiteDimensional_cechHgr_structureModule_top d
  · exact finiteDimensional_cechHgr_structureModule_of_ne i d hi

omit [IsNoetherianRing k] in
/-- Serre finiteness for a twist of the twisting sheaves. -/
theorem finiteDimensional_cechHgr_twist_structureModule (a : ℤ) (i : ℕ) (d : ℤ) :
    Module.Finite k ((((structureModule k n).twist a).cechHgr i).obj d) := by
  haveI := finiteDimensional_cechHgr_structureModule (k := k) (n := n) i (d + a)
  exact finiteDimensional_of_iso (cechHgrTwistIso (structureModule k n) a i d).symm

omit [IsNoetherianRing k] in
/-- Serre finiteness for a finite direct sum of twists — the free modules of the
presentation. -/
theorem finiteDimensional_cechHgr_free (a : ℤ) (r i : ℕ) (d : ℤ) :
    Module.Finite k (((((structureModule k n).twist a).pow r).cechHgr i).obj d) := by
  haveI := finiteDimensional_cechHgr_twist_structureModule (k := k) (n := n) a i d
  haveI : Module.Finite k
      (((((structureModule k n).twist a).cechHgr i).pow r).obj d) :=
    inferInstanceAs (Module.Finite k
      (Fin r → ((((structureModule k n).twist a).cechHgr i)).obj d))
  exact finiteDimensional_of_iso
    (cechHgrPowIso ((structureModule k n).twist a) r i d).symm

omit [IsNoetherianRing k] in
/-- The free module of the presentation is finitely generated. -/
lemma isFG_free (a : ℤ) (r : ℕ) : IsFG (((structureModule k n).twist a).pow r) :=
  ((isFG_structureModule (k := k) (n := n)).twist a).pow r

/-- The descending induction behind Serre finiteness: cohomology above the induction
threshold vanishes, and each step down uses the free presentation. -/
theorem finiteDimensional_cechHgr_of_isFG_aux (j : ℕ) :
    ∀ (M : GradedModule k n), IsFG M → ∀ i : ℕ, n + 1 ≤ i + j → ∀ d : ℤ,
      Module.Finite k ((M.cechHgr i).obj d) := by
  classical
  induction j with
  | zero =>
      intro M _ i hij d
      haveI := subsingleton_cechHgr M i (by omega) d
      exact finiteDimensional_of_subsingleton
  | succ j ih =>
      intro M hM i hij d
      rcases lt_or_ge n i with hni | hni
      · haveI := subsingleton_cechHgr M i hni d
        exact finiteDimensional_of_subsingleton
      obtain ⟨hfd, hlow, d₀, hgen⟩ := hM
      haveI : Module.Finite k (M.obj d₀) := hfd d₀
      obtain ⟨r, y, hyspan⟩ := Module.Finite.exists_fin (R := k) (M := (M.obj d₀ : Type u))
      -- the kernel of the free presentation is finitely generated
      have hK : IsFG (ker (freeGenHom M d₀ y)) :=
        IsFG.of_injective (kerι (freeGenHom M d₀ y))
          (fun _ _ _ h => Subtype.val_injective h) (isFG_free (-d₀) r)
      haveI : Module.Finite k
          (((ker (freeGenHom M d₀ y)).cechHgr (i + 1)).obj d) :=
        ih _ hK (i + 1) (by omega) d
      haveI : Module.Finite k
          ((((((structureModule k n).twist (-d₀)).pow r)).cechHgr i).obj d) :=
        finiteDimensional_cechHgr_free (-d₀) r i d
      -- the image of the free presentation has finite dimensional cohomology
      haveI himg : Module.Finite k (((imgMod M d₀ y).cechHgr i).obj d) :=
        finiteDimensional_of_exact
          ((cechHgrMap (freeGenToImg M d₀ y) i).app d).hom
          (cechδ (shortExact_freeGenToImg M d₀ y) i d).hom
          (cech_exact_map_δ (shortExact_freeGenToImg M d₀ y) i d)
      -- and `M` has the same cohomology as that image
      exact Module.Finite.of_surjective ((cechHgrMap (imgIota M d₀ y) i).app d).hom
        (bijective_cechHgrMap_imgIota M d₀ y hyspan hgen i d).2

/-- **Serre finiteness** (Hartshorne III.5.2(a) for the graded Čech model): the Čech
cohomology of a finitely generated graded module is finite dimensional in every
cohomological degree and every twist. -/
theorem finiteDimensional_cechHgr_of_isFG (M : GradedModule k n) (hM : IsFG M)
    (i : ℕ) (d : ℤ) : Module.Finite k ((M.cechHgr i).obj d) :=
  finiteDimensional_cechHgr_of_isFG_aux (n + 1) M hM i (by omega) d

/-! ## Serre vanishing by dévissage -/

omit [IsNoetherianRing k] in
/-- Subsingletons pass to the middle term of an exact sequence. -/
lemma subsingleton_of_exact {A B C : Type*} [AddCommGroup A] [Module k A]
    [AddCommGroup B] [Module k B] [AddCommGroup C] [Module k C]
    (f : A →ₗ[k] B) (g : B →ₗ[k] C) (hfg : Function.Exact f g)
    [Subsingleton A] [Subsingleton C] : Subsingleton B := by
  have hzero : ∀ b : B, b = 0 := by
    intro b
    obtain ⟨a, rfl⟩ := (hfg b).mp (Subsingleton.elim _ _)
    rw [Subsingleton.elim a 0, map_zero]
  exact ⟨fun x z => by rw [hzero x, hzero z]⟩

omit [IsNoetherianRing k] in
/-- Being a subsingleton transports along an isomorphism of `ModuleCat`. -/
lemma subsingleton_of_iso {A B : ModuleCat.{u} k} (e : A ≅ B) [Subsingleton A] :
    Subsingleton B := by
  have h : ∀ y : B, y = e.hom.hom (e.inv.hom y) := fun y => by
    simpa using (congrArg (fun f : B ⟶ B => f.hom y) e.inv_hom_id).symm
  exact ⟨fun x z => by
    rw [h x, h z, Subsingleton.elim (e.inv.hom x) (e.inv.hom z)]⟩

omit [IsNoetherianRing k] in
/-- Serre vanishing for a finite direct sum of twists of the twisting sheaves. -/
lemma subsingleton_cechHgr_free (a : ℤ) (r i : ℕ) (hi : 1 ≤ i) (d : ℤ)
    (hd : -(n : ℤ) - a ≤ d) :
    Subsingleton (((((structureModule k n).twist a).pow r).cechHgr i).obj d) := by
  haveI : Subsingleton (((structureModule k n).cechHgr i).obj (d + a)) :=
    subsingleton_cechHgr_structureModule i (d + a) hi (Or.inr (by omega))
  haveI : Subsingleton ((((structureModule k n).twist a).cechHgr i).obj d) :=
    subsingleton_of_iso (cechHgrTwistIso (structureModule k n) a i d).symm
  haveI : Subsingleton (((((structureModule k n).twist a).cechHgr i).pow r).obj d) :=
    inferInstanceAs (Subsingleton
      (Fin r → ((((structureModule k n).twist a).cechHgr i)).obj d))
  exact subsingleton_of_iso
    (cechHgrPowIso ((structureModule k n).twist a) r i d).symm

/-- The descending induction behind Serre vanishing. -/
theorem exists_subsingleton_cechHgr_of_isFG_aux (j : ℕ) :
    ∀ (M : GradedModule k n), IsFG M → ∀ i : ℕ, 1 ≤ i → n + 1 ≤ i + j →
      ∃ e₀ : ℤ, ∀ d : ℤ, e₀ ≤ d → Subsingleton ((M.cechHgr i).obj d) := by
  classical
  induction j with
  | zero =>
      intro M _ i _ hij
      exact ⟨0, fun d _ => subsingleton_cechHgr M i (by omega) d⟩
  | succ j ih =>
      intro M hM i hi hij
      rcases lt_or_ge n i with hni | hni
      · exact ⟨0, fun d _ => subsingleton_cechHgr M i hni d⟩
      obtain ⟨hfd, hlow, d₀, hgen⟩ := hM
      haveI : Module.Finite k (M.obj d₀) := hfd d₀
      obtain ⟨r, y, hyspan⟩ := Module.Finite.exists_fin (R := k) (M := (M.obj d₀ : Type u))
      have hK : IsFG (ker (freeGenHom M d₀ y)) :=
        IsFG.of_injective (kerι (freeGenHom M d₀ y))
          (fun _ _ _ h => Subtype.val_injective h) (isFG_free (-d₀) r)
      obtain ⟨eK, heK⟩ := ih _ hK (i + 1) (by omega) (by omega)
      refine ⟨max eK (-(n : ℤ) + d₀), fun d hd => ?_⟩
      haveI : Subsingleton (((ker (freeGenHom M d₀ y)).cechHgr (i + 1)).obj d) :=
        heK d (le_trans (le_max_left _ _) hd)
      haveI : Subsingleton
          (((((structureModule k n).twist (-d₀)).pow r).cechHgr i).obj d) := by
        refine subsingleton_cechHgr_free (-d₀) r i hi d ?_
        have := le_trans (le_max_right _ _) hd
        omega
      haveI : Subsingleton (((imgMod M d₀ y).cechHgr i).obj d) :=
        subsingleton_of_exact
          ((cechHgrMap (freeGenToImg M d₀ y) i).app d).hom
          (cechδ (shortExact_freeGenToImg M d₀ y) i d).hom
          (cech_exact_map_δ (shortExact_freeGenToImg M d₀ y) i d)
      exact ((bijective_cechHgrMap_imgIota M d₀ y hyspan hgen i d).2).subsingleton

/-- **Serre vanishing** (Hartshorne III.5.2(b) for the graded Čech model): the higher
Čech cohomology of a finitely generated graded module vanishes in all large twists. -/
theorem exists_subsingleton_cechHgr_of_isFG (M : GradedModule k n) (hM : IsFG M)
    (i : ℕ) (hi : 1 ≤ i) :
    ∃ d₀ : ℤ, ∀ d : ℤ, d₀ ≤ d → Subsingleton ((M.cechHgr i).obj d) :=
  exists_subsingleton_cechHgr_of_isFG_aux (n + 1) M hM i hi (by omega)

end AlgebraicGeometry.ProjectiveSpace.GradedModule

end
