module

public import StacksAndModuli.API.ProjectiveLineBinaryDehomogenization

/-!
# Persistence for quotients of binary-form vectors

The binary-form growth theorem is naturally stated in terms of relation spaces.  A
field-valued point of the Hilbert Grassmannian, however, is a quotient of a finite
space of homogeneous vectors.  This file translates between those two formulations
without natural-number subtraction and iterates the resulting one-step theorem.

If the quotient dimensions in degrees `e` and `e + 1` are `q₀` and `q₁`, their
increment is `a`, and the ambient vector rank is `a + s`, then the quotient dimension
continues to grow by `a` under the usual Gotzmann largeness inequality.  The endpoint
`s = 0` is included: in that case the relation space has zero growth, which persists
without a strict largeness argument.

This is a theorem about the graded quotient generated by a field-valued relation
space.  Applying it to reconstructed Quot families still requires a comparison between
that graded quotient and the twisted pushforwards of its sheafification.  On the
projective line, the missing comparison is equivalently the relevant relation-kernel
`H¹` vanishing (or reconstruction saturation); it is not implied merely by the two
adjacent algebraic ranks.

Main declarations:

* `MvPolynomial.finrank_binaryHomogeneousVector`;
* `MvPolynomial.finrank_quotient_binaryNextSpan_eq_add_of_large_or_full`;
* `MvPolynomial.binaryNextSpanIterate`;
* `MvPolynomial.finrank_quotient_binaryNextSpanIterate_eq`.
-/

@[expose] public section

noncomputable section

set_option linter.style.haveILetI false

namespace MvPolynomial

variable (K : Type*) [Field K]

/-- A binary successor span of a finite-dimensional relation space is again
finite-dimensional. -/
theorem binaryNextSpan_finiteDimensional
    (I : Type*) (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e))
    [FiniteDimensional K V] :
    FiniteDimensional K (binaryNextSpan K V) := by
  dsimp only [binaryNextSpan]
  infer_instance

/-- Zero growth of a binary successor span persists for one further degree. -/
theorem finrank_binaryNextSpan_eq_of_eq
    (I : Type*) [Finite I] (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e))
    [FiniteDimensional K V]
    (hgrowth : Module.finrank K (binaryNextSpan K V) =
      Module.finrank K V) :
    Module.finrank K (binaryNextSpan K (binaryNextSpan K V)) =
      Module.finrank K (binaryNextSpan K V) := by
  letI : FiniteDimensional K (binaryNextSpan K V) :=
    binaryNextSpan_finiteDimensional K I e V
  by_cases hzero : Module.finrank K (binaryNextSpan K V) = 0
  · have hbot : binaryNextSpan K V = ⊥ :=
      Submodule.finrank_eq_zero.mp hzero
    rw [hbot]
    have hnextBot : binaryNextSpan K
        (⊥ : Submodule K
          (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1))) = ⊥ := by
      change
        ((⊥ : Submodule K
            (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1))).map
              (binaryMulVector K I (e + 1) 0)) ⊔
          ((⊥ : Submodule K
            (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1))).map
              (binaryMulVector K I (e + 1) 1)) = ⊥
      rw [Submodule.map_bot (binaryMulVector K I (e + 1) 0),
        Submodule.map_bot (binaryMulVector K I (e + 1) 1), bot_sup_eq]
    rw [hnextBot]
    simp only [finrank_bot]
  · have hlarge : (0 - 1) * (e + 2) <
        Module.finrank K (binaryNextSpan K V) := by
      simpa only [Nat.zero_sub, zero_mul, Nat.pos_iff_ne_zero] using hzero
    simpa only [add_zero] using
      finrank_binaryNextSpan_eq_add_of_large K I e V 0
        (by simpa only [add_zero] using hgrowth) hlarge

/-- The dimension of `I`-valued binary forms of degree `e`. -/
theorem finrank_binaryHomogeneousVector
    (I : Type*) [Fintype I] (e : ℕ) :
    Module.finrank K
        (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) =
      Fintype.card I * (e + 1) := by
  letI : Module.Finite K
      (MvPolynomial.homogeneousSubmodule (Fin 2) K e) :=
    Module.Finite.of_basis
      (MvPolynomial.homogeneousSubmoduleFinBasis 1 K e)
  calc
    Module.finrank K
        (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) =
        ∑ _ : I,
          Module.finrank K
            (MvPolynomial.homogeneousSubmodule (Fin 2) K e) :=
      Module.finrank_pi_fintype K
    _ = ∑ _ : I, (e + 1) := by
      apply Finset.sum_congr rfl
      intro i hi
      rw [finrank_binaryDehomogenizeDegree K e,
        Module.finrank_eq_card_basis (Polynomial.degreeLT.basis K (e + 1))]
      simp
    _ = Fintype.card I * (e + 1) := by simp

/-- Subtraction-free persistence for complementary ranks, including the full-slope
endpoint where the relation-space growth is zero. -/
theorem finrank_binaryNextSpan_add_nextQuotientRank_of_large_or_full
    (I : Type*) [Fintype I] (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e))
    [FiniteDimensional K V] (q₀ q₁ a s : ℕ)
    (hV : Module.finrank K V + q₀ = Fintype.card I * (e + 1))
    (hnext : Module.finrank K (binaryNextSpan K V) + q₁ =
      Fintype.card I * (e + 2))
    (hquotientGrowth : q₁ = q₀ + a)
    (hambientSplit : Fintype.card I = a + s)
    (hcase : s = 0 ∨ q₁ < (a + 1) * (e + 2)) :
    Module.finrank K (binaryNextSpan K (binaryNextSpan K V)) +
        (q₁ + a) =
      Fintype.card I * (e + 3) := by
  rcases Nat.eq_zero_or_pos s with rfl | hs
  · have hambientStep :
        Fintype.card I * (e + 2) =
          Fintype.card I * (e + 1) + Fintype.card I := by
      ring
    have hgrowth : Module.finrank K (binaryNextSpan K V) =
        Module.finrank K V := by
      apply Nat.add_right_cancel (m := q₁)
      calc
        Module.finrank K (binaryNextSpan K V) + q₁ =
            Fintype.card I * (e + 2) := hnext
        _ = Fintype.card I * (e + 1) + Fintype.card I := hambientStep
        _ = (Module.finrank K V + q₀) + (a + 0) := by
          rw [hV, hambientSplit]
        _ = Module.finrank K V + (q₀ + a) := by omega
        _ = Module.finrank K V + q₁ := by rw [hquotientGrowth]
    have hpersist := finrank_binaryNextSpan_eq_of_eq K I e V hgrowth
    calc
      Module.finrank K (binaryNextSpan K (binaryNextSpan K V)) +
          (q₁ + a) =
          Module.finrank K (binaryNextSpan K V) + (q₁ + a) := by
        rw [hpersist]
      _ = (Module.finrank K (binaryNextSpan K V) + q₁) + a := by
        omega
      _ = Fintype.card I * (e + 2) + a := by rw [hnext]
      _ = Fintype.card I * (e + 2) + Fintype.card I := by
        rw [hambientSplit]
        simp
      _ = Fintype.card I * (e + 3) := by ring
  · exact finrank_binaryNextSpan_add_nextQuotientRank_of_large
      K I e V q₀ q₁ a s hV hnext hquotientGrowth hambientSplit hs
        (hcase.resolve_left (Nat.ne_of_gt hs))

/-- Field-valued quotient-rank form of one-step binary Gotzmann persistence.

The slack `s` is allowed to vanish, so the statement also covers quotients whose
eventual linear growth equals the full ambient vector rank.  The largeness inequality
is required only in the complementary case `s ≠ 0`. -/
theorem finrank_quotient_binaryNextSpan_eq_add_of_large_or_full
    (I : Type*) [Fintype I] (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e))
    [FiniteDimensional K V] (q₀ q₁ a s : ℕ)
    (hV : Module.finrank K
      ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) ⧸ V) = q₀)
    (hnext : Module.finrank K
      ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
        binaryNextSpan K V) = q₁)
    (hquotientGrowth : q₁ = q₀ + a)
    (hambientSplit : Fintype.card I = a + s)
    (hcase : s = 0 ∨ q₁ < (a + 1) * (e + 2)) :
    Module.finrank K
      ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 2)) ⧸
        binaryNextSpan K (binaryNextSpan K V)) = q₁ + a := by
  letI : Module.Finite K
      (MvPolynomial.homogeneousSubmodule (Fin 2) K e) :=
    Module.Finite.of_basis
      (MvPolynomial.homogeneousSubmoduleFinBasis 1 K e)
  letI : Module.Finite K
      (MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) :=
    Module.Finite.of_basis
      (MvPolynomial.homogeneousSubmoduleFinBasis 1 K (e + 1))
  letI : Module.Finite K
      (MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 2)) :=
    Module.Finite.of_basis
      (MvPolynomial.homogeneousSubmoduleFinBasis 1 K (e + 2))
  letI : Module.Finite K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) := by
    infer_instance
  letI : Module.Finite K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) := by
    infer_instance
  letI : Module.Finite K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 2)) := by
    infer_instance
  have hVComplement : Module.finrank K V + q₀ =
      Fintype.card I * (e + 1) := by
    calc
      Module.finrank K V + q₀ = q₀ + Module.finrank K V := by omega
      _ = Module.finrank K
            ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) ⧸ V) +
          Module.finrank K V := by rw [hV]
      _ = Module.finrank K
          (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) :=
        Submodule.finrank_quotient_add_finrank V
      _ = Fintype.card I * (e + 1) :=
        finrank_binaryHomogeneousVector K I e
  have hnextComplement :
      Module.finrank K (binaryNextSpan K V) + q₁ =
        Fintype.card I * (e + 2) := by
    calc
      Module.finrank K (binaryNextSpan K V) + q₁ =
          q₁ + Module.finrank K (binaryNextSpan K V) := by omega
      _ = Module.finrank K
            ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
              binaryNextSpan K V) +
          Module.finrank K (binaryNextSpan K V) := by rw [hnext]
      _ = Module.finrank K
          (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) :=
        Submodule.finrank_quotient_add_finrank (binaryNextSpan K V)
      _ = Fintype.card I * (e + 2) :=
        finrank_binaryHomogeneousVector K I (e + 1)
  have hpersist :=
    finrank_binaryNextSpan_add_nextQuotientRank_of_large_or_full
      K I e V q₀ q₁ a s hVComplement hnextComplement
        hquotientGrowth hambientSplit hcase
  have htotal :=
    Submodule.finrank_quotient_add_finrank
      (binaryNextSpan K (binaryNextSpan K V))
  have htotal' :
      Module.finrank K
          ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 2)) ⧸
            binaryNextSpan K (binaryNextSpan K V)) +
        Module.finrank K (binaryNextSpan K (binaryNextSpan K V)) =
      Fintype.card I * (e + 3) := by
    calc
      _ = Module.finrank K
          (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 2)) :=
        htotal
      _ = Fintype.card I * (e + 2 + 1) :=
        finrank_binaryHomogeneousVector K I (e + 2)
      _ = Fintype.card I * (e + 3) := by ring
  omega

/-- Iterate the span by the two projective variables, starting with relations in
degree `e`. -/
noncomputable def binaryNextSpanIterate {I : Type*} (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e)) :
    (k : ℕ) → Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k))
  | 0 => V
  | k + 1 => binaryNextSpan K (binaryNextSpanIterate e V k)

@[simp]
theorem binaryNextSpanIterate_zero {I : Type*} (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e)) :
    binaryNextSpanIterate K e V 0 = V := rfl

@[simp]
theorem binaryNextSpanIterate_succ {I : Type*} (e k : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e)) :
    binaryNextSpanIterate K e V (k + 1) =
      binaryNextSpan K (binaryNextSpanIterate K e V k) := rfl

/-- Every iterated binary successor span is finite-dimensional. -/
theorem binaryNextSpanIterate_finiteDimensional
    (I : Type*) (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e))
    [FiniteDimensional K V] (k : ℕ) :
    FiniteDimensional K (binaryNextSpanIterate K e V k) := by
  induction k with
  | zero => simpa
  | succ k hk =>
      letI : FiniteDimensional K (binaryNextSpanIterate K e V k) := hk
      rw [binaryNextSpanIterate_succ]
      exact binaryNextSpan_finiteDimensional K I (e + k)
        (binaryNextSpanIterate K e V k)

/-- All later field-valued quotient dimensions have the same linear growth once the
first two dimensions satisfy the binary Gotzmann inequality. -/
theorem finrank_quotient_binaryNextSpanIterate_eq
    (I : Type*) [Fintype I] (e : ℕ)
    (V : Submodule K
      (I → MvPolynomial.homogeneousSubmodule (Fin 2) K e))
    [FiniteDimensional K V] (q₀ q₁ a s : ℕ)
    (hV : Module.finrank K
      ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K e) ⧸ V) = q₀)
    (hnext : Module.finrank K
      ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
        binaryNextSpan K V) = q₁)
    (hquotientGrowth : q₁ = q₀ + a)
    (hambientSplit : Fintype.card I = a + s)
    (hcase : s = 0 ∨ q₁ < (a + 1) * (e + 2)) :
    ∀ k : ℕ,
      Module.finrank K
        ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + k)) ⧸
          binaryNextSpanIterate K e V k) = q₀ + k * a := by
  intro k
  induction k using Nat.twoStepInduction with
  | zero =>
      rw [binaryNextSpanIterate_zero]
      simpa only [Nat.add_zero, Nat.zero_mul] using hV
  | one =>
      calc
        Module.finrank K
            ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + 1)) ⧸
              binaryNextSpanIterate K e V 1) = q₁ := by
          rw [binaryNextSpanIterate_succ, binaryNextSpanIterate_zero]
          exact hnext
        _ = q₀ + 1 * a := by rw [hquotientGrowth]; ring
  | more k hk hkone =>
      let W := binaryNextSpanIterate K e V k
      letI : FiniteDimensional K W :=
        binaryNextSpanIterate_finiteDimensional K I e V k
      have hstepGrowth : q₀ + (k + 1) * a =
          (q₀ + k * a) + a := by ring
      have hkGrowth : k * a ≤ k * (a + 1) :=
        Nat.mul_le_mul_left k (Nat.le_succ a)
      have hstepCase : s = 0 ∨ q₀ + (k + 1) * a <
          (a + 1) * ((e + k) + 2) := by
        rcases hcase with hszero | hlarge
        · exact Or.inl hszero
        · right
          calc
            q₀ + (k + 1) * a = q₁ + k * a := by
              rw [hquotientGrowth]
              ring
            _ < (a + 1) * (e + 2) + k * (a + 1) :=
              Nat.add_lt_add_of_lt_of_le hlarge hkGrowth
            _ = (a + 1) * ((e + k) + 2) := by ring
      have hpersist := finrank_quotient_binaryNextSpan_eq_add_of_large_or_full
        K I (e + k) W (q₀ + k * a) (q₀ + (k + 1) * a) a s
          hk hkone hstepGrowth hambientSplit hstepCase
      calc
        Module.finrank K
            ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K (e + (k + 2))) ⧸
              binaryNextSpanIterate K e V (k + 2)) =
            (q₀ + (k + 1) * a) + a := by
          change Module.finrank K
            ((I → MvPolynomial.homogeneousSubmodule (Fin 2) K ((e + k) + 2)) ⧸
              binaryNextSpan K (binaryNextSpan K W)) =
                (q₀ + (k + 1) * a) + a
          exact hpersist
        _ = q₀ + (k + 2) * a := by ring

end MvPolynomial

end
