module

public import StacksAndModuli.API.ProjectiveGradedFlatFinitePresentationFull

/-!
# Relative Serre vanishing over a local coefficient ring

This file proves Serre vanishing for finitely generated, degreewise-flat graded modules over
an arbitrary local coefficient ring.  The relation module in the standard eventual shifted-free
presentation is finitely generated by the local graded finite-presentation theorem corresponding
to Stacks Project tag 053C.  It is degreewise flat by short exactness, so the usual descending
devissage applies without a noetherian hypothesis on the coefficient ring.
-/

@[expose] public section

noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

universe u

namespace AlgebraicGeometry.ProjectiveSpace.GradedModule

open CategoryTheory MvPolynomial

variable {R : Type u} [CommRing R] {n : ℕ}

/-- The descending induction behind relative Serre vanishing for finitely generated,
degreewise-flat graded modules over a local coefficient ring. -/
theorem exists_subsingleton_cechHgr_of_isFG_of_isFlat_of_isLocalRing_aux
    [IsLocalRing R] (j : ℕ) :
    ∀ (M : GradedModule R n), IsFG M → IsFlat M →
      ∀ i : ℕ, 1 ≤ i → n + 1 ≤ i + j →
        ∃ e₀ : ℤ, ∀ d : ℤ, e₀ ≤ d → Subsingleton ((M.cechHgr i).obj d) := by
  classical
  induction j with
  | zero =>
      intro M _ _ i _ hij
      exact ⟨0, fun d _ => subsingleton_cechHgr M i (by omega) d⟩
  | succ j ih =>
      intro M hM hMflat i hi hij
      rcases lt_or_ge n i with hni | hni
      · exact ⟨0, fun d _ => subsingleton_cechHgr M i hni d⟩
      obtain ⟨hfd, hlow, d₀, hgen⟩ := hM
      haveI : Module.Finite R (M.obj d₀) := hfd d₀
      obtain ⟨r, y, hyspan⟩ :=
        Module.Finite.exists_fin (R := R) (M := (M.obj d₀ : Type u))
      have hK : IsFG (ker (freeGenHom M d₀ y)) :=
        isFG_kernel_freeGenHom_of_isFlat_of_isLocalRing hMflat d₀ y hyspan hgen
      have himgFlat : IsFlat (imgMod M d₀ y) :=
        hMflat.freeGenImage d₀ y hyspan hgen
      have hfreeFlat : IsFlat (((structureModule R n).twist (-d₀)).pow r) :=
        (isFlat_structureModule.twist (-d₀)).pow r
      have hKflat : IsFlat (ker (freeGenHom M d₀ y)) :=
        IsFlat.of_shortExact (shortExact_freeGenToImg M d₀ y) hfreeFlat himgFlat
      obtain ⟨eK, heK⟩ := ih _ hK hKflat (i + 1) (by omega) (by omega)
      refine ⟨max eK (-(n : ℤ) + d₀), fun d hd => ?_⟩
      haveI : Subsingleton (((ker (freeGenHom M d₀ y)).cechHgr (i + 1)).obj d) :=
        heK d (le_trans (le_max_left _ _) hd)
      haveI : Subsingleton
          (((((structureModule R n).twist (-d₀)).pow r).cechHgr i).obj d) := by
        refine subsingleton_cechHgr_free (-d₀) r i hi d ?_
        have := le_trans (le_max_right _ _) hd
        omega
      haveI : Subsingleton (((imgMod M d₀ y).cechHgr i).obj d) :=
        subsingleton_of_exact
          ((cechHgrMap (freeGenToImg M d₀ y) i).app d).hom
          (cechδ (shortExact_freeGenToImg M d₀ y) i d).hom
          (cech_exact_map_δ (shortExact_freeGenToImg M d₀ y) i d)
      exact ((bijective_cechHgrMap_imgIota M d₀ y hyspan hgen i d).2).subsingleton

/-- Relative Serre vanishing for finitely generated, degreewise-flat graded modules over an
arbitrary local coefficient ring. -/
theorem exists_subsingleton_cechHgr_of_isFG_of_isFlat_of_isLocalRing
    [IsLocalRing R] (M : GradedModule R n)
    (hM : IsFG M) (hMflat : IsFlat M) (i : ℕ) (hi : 1 ≤ i) :
    ∃ d₀ : ℤ, ∀ d : ℤ, d₀ ≤ d → Subsingleton ((M.cechHgr i).obj d) :=
  exists_subsingleton_cechHgr_of_isFG_of_isFlat_of_isLocalRing_aux
    (n + 1) M hM hMflat i hi (by omega)

end AlgebraicGeometry.ProjectiveSpace.GradedModule

end
