module

public import StacksAndModuli.API.MvPolynomialDegreeZero
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
public import Mathlib.AlgebraicGeometry.Pullbacks
public import Mathlib.AlgebraicGeometry.Limits
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.RingTheory.TensorProduct.MvPolynomial
public import «StacksProject».«Constructions».«InvertibleSheavesOnProj».«definition-twist»

/-!
# Base change for polynomial projective space

This file develops the coefficient-change morphism between projective spectra of standard
graded multivariate polynomial rings.  It records the irrelevant-ideal hypothesis required by
`Proj.map`, compatibility with the structure morphism, and the standard-chart algebra needed
to prove that polynomial projective space commutes with base change.

Main declarations:

* `MvPolynomial.mapGradedRingHom`: coefficient change as a graded ring homomorphism.
* `Proj.polynomialMap`: the induced contravariant morphism on polynomial `Proj`.
* `Proj.polynomialToSpec`: the structure morphism to the coefficient ring.
* `Proj.projectiveChartPolynomialEquivAway`: the standard-chart coordinate-ring equivalence.
* `Proj.polynomialMap_isPullback`: arbitrary coefficient change gives a cartesian square.
* `Proj.polynomialProjOverSpecIso`: the affine specialization of relative projective space.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 10

open CategoryTheory Graded HomogeneousIdeal HomogeneousLocalization TopologicalSpace
open CategoryTheory.Limits
open AlgebraicGeometry ProjectiveSpectrum

universe u

namespace MvPolynomial

attribute [local instance] MvPolynomial.gradedAlgebra

variable {ι : Type} {R S T : Type u} [CommRing R] [CommRing S] [CommRing T]

/-- Coefficient change on a polynomial ring preserves the standard total-degree grading. -/
noncomputable def mapGradedRingHom (f : R →+* S) :
    homogeneousSubmodule ι R →+*ᵍ homogeneousSubmodule ι S where
  __ := MvPolynomial.map f
  map_mem hp := hp.map f

@[simp]
theorem mapGradedRingHom_apply (f : R →+* S) (p : MvPolynomial ι R) :
    mapGradedRingHom f p = MvPolynomial.map f p := rfl

@[simp]
theorem mapGradedRingHom_C (f : R →+* S) (r : R) :
    mapGradedRingHom (ι := ι) f (C r) = C (f r) := by
  simp [mapGradedRingHom]

@[simp]
theorem mapGradedRingHom_X (f : R →+* S) (i : ι) :
    mapGradedRingHom f (X i) = X i := by
  simp [mapGradedRingHom]

@[simp]
theorem mapGradedRingHom_id :
    mapGradedRingHom (ι := ι) (RingHom.id R) = GradedRingHom.id _ := by
  apply GradedRingHom.ext
  intro p
  exact MvPolynomial.map_id p

theorem mapGradedRingHom_comp (f : R →+* S) (g : S →+* T) :
    mapGradedRingHom (ι := ι) (g.comp f) =
      (mapGradedRingHom g).comp (mapGradedRingHom f) := by
  apply GradedRingHom.ext
  intro p
  exact (MvPolynomial.map_map (f := f) g p).symm

/-- On degree zero, the graded coefficient map is the original coefficient map under the
canonical identifications with constant polynomials. -/
theorem gradedZeroRingHom_comp_degreeZeroRingEquiv (f : R →+* S) :
    (mapGradedRingHom (ι := ι) f).gradedZeroRingHom.comp
        (degreeZeroRingEquiv ι R).toRingHom =
      (degreeZeroRingEquiv ι S).toRingHom.comp f := by
  apply RingHom.ext
  intro r
  apply Subtype.ext
  simp

/-- The irrelevant ideal of a standard graded polynomial ring is contained in the ideal
generated by its variables. -/
theorem irrelevant_toIdeal_le_idealOfVars (ι : Type) (R : Type u) [CommRing R] :
    (HomogeneousIdeal.irrelevant (homogeneousSubmodule ι R)).toIdeal ≤
      idealOfVars ι R := by
  rw [HomogeneousIdeal.irrelevant_eq_span, Ideal.span_le]
  intro p hp
  simp only [Set.mem_iUnion] at hp
  obtain ⟨k, hk, hp⟩ := hp
  rw [idealOfVars_eq_restrictSupportIdeal]
  intro m hm
  have hdeg : m.degree = k :=
    ((show p.IsHomogeneous k from hp).degree_eq_sum_deg_support hm).symm
  exact Nat.one_le_iff_ne_zero.mpr (by rw [hdeg]; exact Nat.ne_of_gt hk)

/-- Coefficient change satisfies the irrelevant-ideal hypothesis in `Proj.map`: variables
remain variables, so their images generate the target irrelevant ideal even when the
coefficient homomorphism is not surjective. -/
theorem irrelevant_le_map_mapGradedRingHom (f : R →+* S) :
    HomogeneousIdeal.irrelevant (homogeneousSubmodule ι S) ≤
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule ι R)).map
        (mapGradedRingHom f) := by
  change (HomogeneousIdeal.irrelevant (homogeneousSubmodule ι S)).toIdeal ≤
    Ideal.map (mapGradedRingHom f)
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule ι R)).toIdeal
  refine (irrelevant_toIdeal_le_idealOfVars ι S).trans ?_
  rw [Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  simpa using Ideal.mem_map_of_mem (mapGradedRingHom f)
    (HomogeneousIdeal.mem_irrelevant_of_mem
      (homogeneousSubmodule ι R) Nat.one_pos (isHomogeneous_X R i))

end MvPolynomial

namespace AlgebraicGeometry.Proj

attribute [local instance] MvPolynomial.gradedAlgebra

variable {ι : Type} {R S T : Type u} [CommRing R] [CommRing S] [CommRing T]

section GradedMap

variable {A B σ τ : Type u} [CommRing A] [CommRing B]
  [SetLike σ A] [AddSubgroupClass σ A] [SetLike τ B] [AddSubgroupClass τ B]
  {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ]

/-- Mapping a homogeneous localization carries constants from the degree-zero piece to
constants from the mapped degree-zero piece. -/
theorem awayMap_comp_fromZeroRingHom (f : 𝒜 →+*ᵍ ℬ) (s : A) :
    (Away.map f s).comp (fromZeroRingHom 𝒜 (Submonoid.powers s)) =
      (fromZeroRingHom ℬ (Submonoid.powers (f s))).comp f.gradedZeroRingHom := by
  ext r
  simp [RingHom.comp_apply, fromZeroRingHom, Away.map, HomogeneousLocalization.map_mk]

/-- The functorial morphism on `Proj` commutes with the structure maps to the spectra of
the degree-zero pieces. -/
@[reassoc]
theorem map_toSpecZero (f : 𝒜 →+*ᵍ ℬ) (hf : ℬ₊ ≤ 𝒜₊.map f) :
    Proj.map f hf ≫ Proj.toSpecZero 𝒜 =
      Proj.toSpecZero ℬ ≫ Spec.map (CommRingCat.ofHom f.gradedZeroRingHom) := by
  refine (Proj.mapAffineOpenCover f hf).openCover.hom_ext _ _ fun s ↦ ?_
  change (Σ i : PNat, 𝒜 i) at s
  change Proj.awayι ℬ (f s.2) (f.2 s.2.2) s.1.2 ≫
      (Proj.map f hf ≫ Proj.toSpecZero 𝒜) =
    Proj.awayι ℬ (f s.2) (f.2 s.2.2) s.1.2 ≫
      (Proj.toSpecZero ℬ ≫ Spec.map (CommRingCat.ofHom f.gradedZeroRingHom))
  rw [← Category.assoc, Proj.awayι_comp_map f hf s.1.2 _ s.2.2,
    Category.assoc, Proj.awayι_toSpecZero, ← Category.assoc,
    Proj.awayι_toSpecZero]
  simp only [← Spec.map_comp, ← CommRingCat.ofHom_comp]
  congr 2
  exact awayMap_comp_fromZeroRingHom f s.2

end GradedMap

/-- The morphism of polynomial projective spectra induced contravariantly by changing
coefficients along `f : R → S`. -/
noncomputable def polynomialMap (ι : Type) (f : R →+* S) :
    Proj (MvPolynomial.homogeneousSubmodule ι S) ⟶
      Proj (MvPolynomial.homogeneousSubmodule ι R) :=
  Proj.map (MvPolynomial.mapGradedRingHom f)
    (MvPolynomial.irrelevant_le_map_mapGradedRingHom f)

/-- Successive changes of coefficients induce the composite morphism on
polynomial projective spectra. -/
theorem polynomialMap_comp (ι : Type) (f : R →+* S) (g : S →+* T) :
    polynomialMap ι g ≫ polynomialMap ι f = polynomialMap ι (g.comp f) := by
  unfold polynomialMap
  rw [← AlgebraicGeometry.Proj.map_comp]
  congr 1
  exact (MvPolynomial.mapGradedRingHom_comp f g).symm

@[simp]
theorem polynomialMap_preimage_basicOpen (ι : Type) (f : R →+* S)
    (p : MvPolynomial ι R) :
    polynomialMap ι f ⁻¹ᵁ Proj.basicOpen (MvPolynomial.homogeneousSubmodule ι R) p =
      Proj.basicOpen (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.map f p) := rfl

/-- The structure morphism from polynomial `Proj` to the spectrum of its coefficient ring. -/
noncomputable def polynomialToSpec (ι : Type) (R : Type u) [CommRing R] :
    Proj (MvPolynomial.homogeneousSubmodule ι R) ⟶ Spec (.of R) :=
  Proj.toSpecZero (MvPolynomial.homogeneousSubmodule ι R) ≫
    (Scheme.Spec.mapIso (MvPolynomial.degreeZeroRingEquiv ι R).toCommRingCatIso.op).hom

/-- Coefficient change on polynomial `Proj` is a morphism over the corresponding map of
coefficient spectra. -/
@[reassoc]
theorem polynomialMap_toSpec (ι : Type) (f : R →+* S) :
    polynomialMap ι f ≫ polynomialToSpec ι R =
      polynomialToSpec ι S ≫ Spec.map (CommRingCat.ofHom f) := by
  unfold polynomialMap
  rw [polynomialToSpec, polynomialToSpec, ← Category.assoc,
    map_toSpecZero, Category.assoc, Category.assoc]
  have h :
      Spec.map (CommRingCat.ofHom
          (MvPolynomial.mapGradedRingHom (ι := ι) f).gradedZeroRingHom) ≫
          (Scheme.Spec.mapIso
            (MvPolynomial.degreeZeroRingEquiv ι R).toCommRingCatIso.op).hom =
        (Scheme.Spec.mapIso
            (MvPolynomial.degreeZeroRingEquiv ι S).toCommRingCatIso.op).hom ≫
          Spec.map (CommRingCat.ofHom f) := by
    change Spec.map (CommRingCat.ofHom
        (MvPolynomial.mapGradedRingHom (ι := ι) f).gradedZeroRingHom) ≫
        Spec.map (CommRingCat.ofHom
          (MvPolynomial.degreeZeroRingEquiv ι R).toRingHom) =
      Spec.map (CommRingCat.ofHom
          (MvPolynomial.degreeZeroRingEquiv ι S).toRingHom) ≫
        Spec.map (CommRingCat.ofHom f)
    rw [← Spec.map_comp, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
      ← CommRingCat.ofHom_comp]
    congr 1
    exact congrArg
      (fun h : R →+* (MvPolynomial.homogeneousSubmodule ι S 0) ↦ CommRingCat.ofHom h)
      (MvPolynomial.gradedZeroRingHom_comp_degreeZeroRingEquiv (ι := ι) f)
  rw [h]

section StandardChart

variable (ι : Type) [DecidableEq ι] (i : ι)

/-- The non-pivot affine coordinate `j` on `D₊(Xᵢ)`, represented by `Xⱼ / Xᵢ`. -/
noncomputable def polynomialChartCoordinate (R : Type u) [CommRing R]
    (j : {j : ι // j ≠ i}) :
    Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) :=
  Away.mk (MvPolynomial.homogeneousSubmodule ι R)
    (MvPolynomial.isHomogeneous_X R i) 1 (MvPolynomial.X j.1)
      (by simpa using MvPolynomial.isHomogeneous_X R j.1)

/-- The affine polynomial coordinates map to the degree-zero homogeneous localization by
`Yⱼ ↦ Xⱼ / Xᵢ`. -/
noncomputable def polynomialChartToAway (R : Type u) [CommRing R] :
    MvPolynomial {j : ι // j ≠ i} R →+*
      Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) :=
  MvPolynomial.eval₂Hom
    ((fromZeroRingHom (MvPolynomial.homogeneousSubmodule ι R)
      (Submonoid.powers (MvPolynomial.X i))).comp
        (MvPolynomial.degreeZeroRingEquiv ι R).toRingHom)
    (polynomialChartCoordinate ι i R)

@[simp]
theorem polynomialChartToAway_X (R : Type u) [CommRing R]
    (j : {j : ι // j ≠ i}) :
    polynomialChartToAway ι i R (MvPolynomial.X j) =
      polynomialChartCoordinate ι i R j := by
  simp [polynomialChartToAway]

@[simp]
theorem polynomialChartCoordinate_val (R : Type u) [CommRing R]
    (j : {j : ι // j ≠ i}) :
    (polynomialChartCoordinate ι i R j).val =
      Localization.mk (MvPolynomial.X j.1)
        ⟨MvPolynomial.X i ^ 1, by use 1⟩ := by
  rfl

@[simp]
theorem polynomialChartCoordinate_pow_val (R : Type u) [CommRing R]
    (j : {j : ι // j ≠ i}) (e : ℕ) :
    ((polynomialChartCoordinate ι i R j) ^ e).val =
      Localization.mk (MvPolynomial.X j.1 ^ e)
        ⟨MvPolynomial.X i ^ e, by use e⟩ := by
  rw [HomogeneousLocalization.val_pow, polynomialChartCoordinate_val,
    Localization.mk_pow]
  congr 1
  apply Subtype.ext
  simp

@[simp]
theorem polynomialChartToAway_C_val (R : Type u) [CommRing R] (r : R) :
    (polynomialChartToAway ι i R (MvPolynomial.C r)).val =
      Localization.mk (MvPolynomial.C r) ⟨1, Submonoid.one_mem _⟩ := by
  simp only [polynomialChartToAway, fromZeroRingHom, MvPolynomial.eval₂Hom_C]
  refine (HomogeneousLocalization.val_mk _).trans ?_
  simp [MvPolynomial.degreeZeroRingEquiv_apply_coe]

/-- Dehomogenization sets the pivot coordinate to one and renames every other variable by
its non-pivot subtype. -/
noncomputable def polynomialDehomogenize (R : Type u) [CommRing R] :
    MvPolynomial ι R →+* MvPolynomial {j : ι // j ≠ i} R :=
  MvPolynomial.eval₂Hom MvPolynomial.C fun j ↦
    if h : j = i then 1 else MvPolynomial.X ⟨j, h⟩

@[simp]
theorem polynomialDehomogenize_X_pivot (R : Type u) [CommRing R] :
    polynomialDehomogenize ι i R (MvPolynomial.X i) = 1 := by
  simp [polynomialDehomogenize]

@[simp]
theorem polynomialDehomogenize_X_nonpivot (R : Type u) [CommRing R]
    (j : ι) (h : j ≠ i) :
    polynomialDehomogenize ι i R (MvPolynomial.X j) = MvPolynomial.X ⟨j, h⟩ := by
  simp [polynomialDehomogenize, h]

@[simp]
theorem polynomialDehomogenize_C (R : Type u) [CommRing R] (r : R) :
    polynomialDehomogenize ι i R (MvPolynomial.C r) = MvPolynomial.C r := by
  simp [polynomialDehomogenize]

/-- Reinterpret a chart polynomial as a homogeneous-coordinate polynomial using only
non-pivot variables. -/
noncomputable def polynomialChartToHomogeneous (R : Type u) [CommRing R] :
    MvPolynomial {j : ι // j ≠ i} R →+* MvPolynomial ι R :=
  (MvPolynomial.rename fun j ↦ j.1).toRingHom

theorem polynomialChartToHomogeneous_comp_dehomogenize
    (R : Type u) [CommRing R] :
    (polynomialDehomogenize ι i R).comp (polynomialChartToHomogeneous ι i R) =
      RingHom.id _ := by
  apply MvPolynomial.ringHom_ext
  · intro r
    simp [polynomialChartToHomogeneous, polynomialDehomogenize]
  · intro j
    simp [polynomialChartToHomogeneous, polynomialDehomogenize, j.2]

theorem polynomialDehomogenize_surjective (R : Type u) [CommRing R] :
    Function.Surjective (polynomialDehomogenize ι i R) := by
  intro p
  refine ⟨polynomialChartToHomogeneous ι i R p, ?_⟩
  exact DFunLike.congr_fun (polynomialChartToHomogeneous_comp_dehomogenize ι i R) p

/-- Homogenize a chart polynomial by inserting the needed pivot-coordinate power in each
homogeneous component. -/
noncomputable def polynomialChartHomogenize (R : Type u) [CommRing R]
    (p : MvPolynomial {j : ι // j ≠ i} R) : MvPolynomial ι R :=
  ∑ d ∈ Finset.range (p.totalDegree + 1),
    polynomialChartToHomogeneous ι i R (MvPolynomial.homogeneousComponent d p) *
      MvPolynomial.X i ^ (p.totalDegree - d)

theorem polynomialChartHomogenize_isHomogeneous (R : Type u) [CommRing R]
    (p : MvPolynomial {j : ι // j ≠ i} R) :
    (polynomialChartHomogenize ι i R p).IsHomogeneous p.totalDegree := by
  apply MvPolynomial.IsHomogeneous.sum
  intro d hd
  rw [Finset.mem_range] at hd
  have hdle : d ≤ p.totalDegree := Nat.lt_succ_iff.mp hd
  convert ((MvPolynomial.homogeneousComponent_isHomogeneous (n := d) (φ := p)).rename_isHomogeneous
      (f := fun j : {j : ι // j ≠ i} ↦ j.1)).mul
        (MvPolynomial.isHomogeneous_X_pow i (p.totalDegree - d)) using 1
  · rfl
  · exact (Nat.add_sub_of_le hdle).symm

theorem polynomialDehomogenize_chartHomogenize (R : Type u) [CommRing R]
    (p : MvPolynomial {j : ι // j ≠ i} R) :
    polynomialDehomogenize ι i R (polynomialChartHomogenize ι i R p) = p := by
  have hcomp (q : MvPolynomial {j : ι // j ≠ i} R) :
      polynomialDehomogenize ι i R (polynomialChartToHomogeneous ι i R q) = q :=
    DFunLike.congr_fun (polynomialChartToHomogeneous_comp_dehomogenize ι i R) q
  simp only [polynomialChartHomogenize, map_sum, map_mul, map_pow,
    polynomialDehomogenize_X_pivot, one_pow, mul_one, hcomp]
  exact MvPolynomial.sum_homogeneousComponent p

theorem isUnit_polynomialDehomogenize_X_pivot (R : Type u) [CommRing R] :
    IsUnit (polynomialDehomogenize ι i R (MvPolynomial.X i)) := by
  rw [polynomialDehomogenize_X_pivot]
  exact isUnit_one

/-- Dehomogenization descends from the homogeneous localization at `Xᵢ` to the chart
polynomial ring. -/
noncomputable def polynomialAwayToChart (R : Type u) [CommRing R] :
    Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) →+*
      MvPolynomial {j : ι // j ≠ i} R :=
  (Localization.awayLift (polynomialDehomogenize ι i R) (MvPolynomial.X i)
      (isUnit_polynomialDehomogenize_X_pivot ι i R)).comp (algebraMap _ _)

theorem polynomialAwayToChart_apply (R : Type u) [CommRing R]
    (z : Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)) :
    polynomialAwayToChart ι i R z =
      Localization.awayLift (polynomialDehomogenize ι i R) (MvPolynomial.X i)
        (isUnit_polynomialDehomogenize_X_pivot ι i R) z.val := rfl

theorem polynomialAwayLift_mk (R : Type u) [CommRing R]
    (a : MvPolynomial ι R) (m : ℕ) :
    Localization.awayLift (polynomialDehomogenize ι i R) (MvPolynomial.X i)
        (isUnit_polynomialDehomogenize_X_pivot ι i R)
        (Localization.mk a ⟨MvPolynomial.X i ^ m, by use m⟩) =
      polynomialDehomogenize ι i R a := by
  set L := Localization.awayLift (polynomialDehomogenize ι i R) (MvPolynomial.X i)
    (isUnit_polynomialDehomogenize_X_pivot ι i R) with hL
  have hden : L ((algebraMap (MvPolynomial ι R)
      (Localization (Submonoid.powers (MvPolynomial.X i)))) (MvPolynomial.X i ^ m)) = 1 := by
    rw [hL, Localization.awayLift, IsLocalization.Away.lift_eq, map_pow,
      polynomialDehomogenize_X_pivot, one_pow]
  have hmk : (Localization.mk a ⟨MvPolynomial.X i ^ m, by use m⟩ :
        Localization (Submonoid.powers (MvPolynomial.X i))) *
      (algebraMap (MvPolynomial ι R) _) (MvPolynomial.X i ^ m) =
        (algebraMap (MvPolynomial ι R) _) a := by
    rw [Localization.mk_eq_mk']
    exact IsLocalization.mk'_spec _ a ⟨MvPolynomial.X i ^ m, by use m⟩
  have happ : L (Localization.mk a ⟨MvPolynomial.X i ^ m, by use m⟩) * 1 =
      polynomialDehomogenize ι i R a := by
    rw [← hden, ← map_mul, hmk, hL, Localization.awayLift,
      IsLocalization.Away.lift_eq]
  rw [← happ, mul_one]

theorem polynomialAwayToChart_mk (R : Type u) [CommRing R]
    (m : ℕ) (a : MvPolynomial ι R)
    (ha : a ∈ MvPolynomial.homogeneousSubmodule ι R (m • 1)) :
    polynomialAwayToChart ι i R
        (Away.mk (MvPolynomial.homogeneousSubmodule ι R)
          (MvPolynomial.isHomogeneous_X R i) m a ha) =
      polynomialDehomogenize ι i R a := by
  have hval : (Away.mk (MvPolynomial.homogeneousSubmodule ι R)
      (MvPolynomial.isHomogeneous_X R i) m a ha).val =
      Localization.mk a ⟨MvPolynomial.X i ^ m, by use m⟩ :=
    Away.val_mk _ _ _ _ _
  rw [polynomialAwayToChart_apply, hval]
  exact polynomialAwayLift_mk ι i R a m

/-- Dehomogenizing the canonical chart coordinates is the identity on the chart polynomial
ring. -/
theorem polynomialAwayToChart_comp_toAway (R : Type u) [CommRing R] :
    (polynomialAwayToChart ι i R).comp (polynomialChartToAway ι i R) =
      RingHom.id _ := by
  apply MvPolynomial.ringHom_ext
  · intro r
    rw [RingHom.comp_apply, RingHom.id_apply]
    have hval := polynomialChartToAway_C_val ι i R r
    rw [polynomialAwayToChart_apply, hval,
      show (⟨1, Submonoid.one_mem _⟩ : Submonoid.powers (MvPolynomial.X i)) =
        ⟨MvPolynomial.X i ^ 0, by use 0⟩ from Subtype.ext (pow_zero _).symm,
      polynomialAwayLift_mk, polynomialDehomogenize_C]
  · intro j
    rw [RingHom.comp_apply, RingHom.id_apply, polynomialChartToAway_X]
    have hval := polynomialChartCoordinate_val ι i R j
    rw [polynomialAwayToChart_apply, hval,
      polynomialAwayLift_mk, polynomialDehomogenize_X_nonpivot ι i R j.1 j.2]

end StandardChart

section LocalizationSums

/-- A finite product of localization fractions is represented by the products of their
numerators and denominators. -/
theorem localization_prod_mk {A : Type*} [CommRing A] (M : Submonoid A)
    {κ : Type*} (s : Finset κ) (a : κ → A) (b : κ → M) :
    ∏ j ∈ s, Localization.mk (a j) (b j) =
      Localization.mk (∏ j ∈ s, a j) (∏ j ∈ s, b j) := by
  classical
  induction s using Finset.induction_on with
  | empty => exact Localization.mk_one.symm
  | @insert j s hj ih =>
      simp only [Finset.prod_insert hj]
      rw [ih, Localization.mk_mul]

/-- A finite sum of localization fractions with one denominator has the sum of the
numerators as numerator. -/
theorem localization_sum_mk {A : Type*} [CommRing A] (M : Submonoid A)
    {κ : Type*} (s : Finset κ) (a : κ → A) (b : M) :
    ∑ j ∈ s, Localization.mk (a j) b =
      Localization.mk (∑ j ∈ s, a j) b := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      simp only [Finset.sum_empty]
      rw [Localization.mk_eq_mk', IsLocalization.mk'_zero]
  | @insert j s hj ih =>
      simp only [Finset.sum_insert hj]
      rw [ih, Localization.add_mk_self]

theorem homogeneousLocalization_val_prod {A σ : Type*} [CommRing A] [SetLike σ A]
    [AddSubgroupClass σ A] {𝒜 : ℕ → σ} [GradedRing 𝒜] (M : Submonoid A)
    {κ : Type*} (s : Finset κ) (f : κ → HomogeneousLocalization 𝒜 M) :
    HomogeneousLocalization.val (∏ j ∈ s, f j) =
      ∏ j ∈ s, HomogeneousLocalization.val (f j) := by
  classical
  induction s using Finset.induction_on with
  | empty => exact HomogeneousLocalization.val_one
  | @insert j s hj ih =>
      simp only [Finset.prod_insert, hj, not_false_eq_true,
        HomogeneousLocalization.val_mul, ih]

theorem homogeneousLocalization_val_sum {A σ : Type*} [CommRing A] [SetLike σ A]
    [AddSubgroupClass σ A] {𝒜 : ℕ → σ} [GradedRing 𝒜] (M : Submonoid A)
    {κ : Type*} (s : Finset κ) (f : κ → HomogeneousLocalization 𝒜 M) :
    HomogeneousLocalization.val (∑ j ∈ s, f j) =
      ∑ j ∈ s, HomogeneousLocalization.val (f j) := by
  classical
  induction s using Finset.induction_on with
  | empty => exact HomogeneousLocalization.val_zero
  | @insert j s hj ih =>
      simp only [Finset.sum_insert, hj, not_false_eq_true,
        HomogeneousLocalization.val_add, ih]

end LocalizationSums

section StandardChartInverse

variable (ι : Type) [DecidableEq ι] (i : ι)

@[simp]
theorem polynomialChartMonomialFactor_val (R : Type u) [CommRing R]
    (j : ι) (e : ℕ) :
    ((polynomialChartToAway ι i R)
      (if h : j = i then 1 else MvPolynomial.X ⟨j, h⟩) ^ e).val =
      Localization.mk (MvPolynomial.X j ^ e)
        ⟨MvPolynomial.X i ^ e, by use e⟩ := by
  by_cases h : j = i
  · subst j
    rw [Localization.mk_eq_mk', IsLocalization.mk'_self]
    simp [polynomialChartToAway]
  · rw [dite_eq_right h, polynomialChartToAway_X, polynomialChartCoordinate_pow_val]

theorem polynomialChartToAway_dehomogenize_monomial
    (R : Type u) [CommRing R] (d : ι →₀ ℕ) (r : R) (m : ℕ)
    (hd : d.degree = m) :
    (polynomialChartToAway ι i R
        (polynomialDehomogenize ι i R (MvPolynomial.monomial d r))).val =
      Localization.mk (MvPolynomial.monomial d r)
        ⟨MvPolynomial.X i ^ m, by use m⟩ := by
  classical
  have hdehom : polynomialDehomogenize ι i R (MvPolynomial.monomial d r) =
      MvPolynomial.C r * ∏ j ∈ d.support,
        (if h : j = i then 1 else MvPolynomial.X ⟨j, h⟩) ^ d j := by
    rw [show (MvPolynomial.monomial d r : MvPolynomial ι R) =
      MvPolynomial.C r * d.prod fun j e ↦ MvPolynomial.X j ^ e from
        MvPolynomial.monomial_eq]
    rw [map_mul, polynomialDehomogenize_C]
    congr 1
    rw [Finsupp.prod, map_prod]
    apply Finset.prod_congr rfl
    intro j _
    rw [map_pow]
    by_cases h : j = i
    · subst j
      rw [polynomialDehomogenize_X_pivot]
      simp
    · rw [polynomialDehomogenize_X_nonpivot ι i R j h]
      simp [h]
  rw [hdehom, map_mul, map_prod, HomogeneousLocalization.val_mul,
    homogeneousLocalization_val_prod]
  have hfactor : ∀ j ∈ d.support,
      ((polynomialChartToAway ι i R)
        ((if h : j = i then 1 else MvPolynomial.X ⟨j, h⟩) ^ d j)).val =
      Localization.mk (MvPolynomial.X j ^ d j)
        ⟨MvPolynomial.X i ^ d j, by use d j⟩ := by
    intro j _
    rw [map_pow]
    exact polynomialChartMonomialFactor_val ι i R j (d j)
  rw [Finset.prod_congr rfl hfactor, polynomialChartToAway_C_val,
    localization_prod_mk, Localization.mk_mul]
  have hnum : MvPolynomial.C r * ∏ j ∈ d.support,
      (MvPolynomial.X j : MvPolynomial ι R) ^ d j = MvPolynomial.monomial d r := by
    rw [show (MvPolynomial.monomial d r : MvPolynomial ι R) =
      MvPolynomial.C r * d.prod fun j e ↦ MvPolynomial.X j ^ e from
        MvPolynomial.monomial_eq]
    rfl
  have hsum : ∑ j ∈ d.support, d j = m := hd
  have hden : ((1 : Submonoid.powers (MvPolynomial.X i : MvPolynomial ι R)) *
      ∏ j ∈ d.support,
        (⟨MvPolynomial.X i ^ d j, by use d j⟩ :
          Submonoid.powers (MvPolynomial.X i : MvPolynomial ι R))) =
      ⟨MvPolynomial.X i ^ m, by use m⟩ := by
    apply Subtype.ext
    push_cast
    rw [one_mul, Finset.prod_pow_eq_pow_sum, hsum]
  rw [show (⟨1, Submonoid.one_mem _⟩ :
      Submonoid.powers (MvPolynomial.X i : MvPolynomial ι R)) = 1 from rfl,
    hden, hnum]

theorem polynomialChartToAway_dehomogenize (R : Type u) [CommRing R]
    (a : MvPolynomial ι R) (m : ℕ) (ha : a.IsHomogeneous m) :
    (polynomialChartToAway ι i R (polynomialDehomogenize ι i R a)).val =
      Localization.mk a ⟨MvPolynomial.X i ^ m, by use m⟩ := by
  classical
  conv_lhs => rw [a.as_sum]
  rw [map_sum, map_sum, homogeneousLocalization_val_sum]
  have hterm : ∀ d ∈ a.support,
      ((polynomialChartToAway ι i R)
        (polynomialDehomogenize ι i R
          (MvPolynomial.monomial d (MvPolynomial.coeff d a)))).val =
      Localization.mk (MvPolynomial.monomial d (MvPolynomial.coeff d a))
        ⟨MvPolynomial.X i ^ m, by use m⟩ := by
    intro d hd
    apply polynomialChartToAway_dehomogenize_monomial
    exact (ha.degree_eq_sum_deg_support hd).symm
  rw [Finset.sum_congr rfl hterm, localization_sum_mk]
  congr 1
  exact a.as_sum.symm

theorem polynomialChartToAway_surjective (R : Type u) [CommRing R] :
    Function.Surjective (polynomialChartToAway ι i R) := by
  intro z
  obtain ⟨m, a, ha, rfl⟩ := Away.mk_surjective
    (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.isHomogeneous_X R i) z
  refine ⟨polynomialDehomogenize ι i R a, ?_⟩
  apply HomogeneousLocalization.val_injective
  rw [polynomialChartToAway_dehomogenize ι i R a m (by
    simpa [MvPolynomial.mem_homogeneousSubmodule] using ha), Away.val_mk]

theorem polynomialChartToAway_injective (R : Type u) [CommRing R] :
    Function.Injective (polynomialChartToAway ι i R) := by
  have hleft := polynomialAwayToChart_comp_toAway ι i R
  intro p q hpq
  have h := congrArg (polynomialAwayToChart ι i R) hpq
  rwa [← RingHom.comp_apply, ← RingHom.comp_apply, hleft, RingHom.id_apply,
    RingHom.id_apply] at h

/-- The polynomial ring on the non-pivot variables is the coordinate ring of the standard
projective chart `D₊(Xᵢ)`. -/
noncomputable def projectiveChartPolynomialEquivAway (R : Type u) [CommRing R] :
    MvPolynomial {j : ι // j ≠ i} R ≃+*
      Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) :=
  RingEquiv.ofBijective (polynomialChartToAway ι i R)
    ⟨polynomialChartToAway_injective ι i R,
      polynomialChartToAway_surjective ι i R⟩

@[simp]
theorem projectiveChartPolynomialEquivAway_apply (R : Type u) [CommRing R]
    (p : MvPolynomial {j : ι // j ≠ i} R) :
    projectiveChartPolynomialEquivAway ι i R p = polynomialChartToAway ι i R p := rfl

/-- The homogeneous-localization map on the standard chart, with its target rewritten using
the fact that coefficient change fixes `Xᵢ`. -/
noncomputable def polynomialAwayMap {R S : Type u} [CommRing R] [CommRing S]
    (f : R →+* S) :
    Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) →+*
      Away (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.X i) := by
  let F := MvPolynomial.mapGradedRingHom (ι := ι) f
  let hP : Submonoid.powers (MvPolynomial.X i : MvPolynomial ι R) ≤
      (Submonoid.powers (MvPolynomial.X i : MvPolynomial ι S)).comap F := by
    rintro _ ⟨n, rfl⟩
    exact ⟨n, by simp [F]⟩
  exact
    { toFun := Quotient.map'
        (fun x ↦ ⟨x.1, ⟨_, map_mem F x.2.2⟩, ⟨_, map_mem F x.3.2⟩, hP x.4⟩)
        (fun x y (e : x.embedding = y.embedding) ↦ by
          apply_fun IsLocalization.map
            (Localization (Submonoid.powers (MvPolynomial.X i : MvPolynomial ι S)))
              F.toRingHom hP at e
          simp_rw [HomogeneousLocalization.NumDenSameDeg.embedding,
            Localization.mk_eq_mk', IsLocalization.map_mk', ← Localization.mk_eq_mk'] at e
          exact e)
      map_add' := Quotient.ind₂' fun x y ↦ by
        simp only [← HomogeneousLocalization.mk_add, Quotient.map'_mk'',
          HomogeneousLocalization.NumDenSameDeg.num_add, map_add,
          HomogeneousLocalization.NumDenSameDeg.den_add, map_mul]
        rfl
      map_mul' := Quotient.ind₂' fun x y ↦ by
        simp only [← HomogeneousLocalization.mk_mul, Quotient.map'_mk'',
          HomogeneousLocalization.NumDenSameDeg.num_mul, map_mul,
          HomogeneousLocalization.NumDenSameDeg.den_mul]
        rfl
      map_zero' := by
        simp only [← HomogeneousLocalization.mk_zero, Quotient.map'_mk'',
          HomogeneousLocalization.NumDenSameDeg.deg_zero,
          HomogeneousLocalization.NumDenSameDeg.num_zero, ZeroMemClass.coe_zero, map_zero,
          HomogeneousLocalization.NumDenSameDeg.den_zero, map_one]
        rfl
      map_one' := by
        simp only [← HomogeneousLocalization.mk_one, Quotient.map'_mk'',
          HomogeneousLocalization.NumDenSameDeg.num_one,
          HomogeneousLocalization.NumDenSameDeg.den_one, map_one]
        rfl }

@[simp]
theorem polynomialAwayMap_mk {R S : Type u} [CommRing R] [CommRing S]
    (f : R →+* S) (m : ℕ) (a : MvPolynomial ι R)
    (ha : a ∈ MvPolynomial.homogeneousSubmodule ι R (m • 1)) :
    polynomialAwayMap ι i f
        (Away.mk (MvPolynomial.homogeneousSubmodule ι R)
          (MvPolynomial.isHomogeneous_X R i) m a ha) =
      Away.mk (MvPolynomial.homogeneousSubmodule ι S)
        (MvPolynomial.isHomogeneous_X S i) m (MvPolynomial.map f a)
          ((show a.IsHomogeneous (m • 1) from ha).map f) := by
  apply HomogeneousLocalization.val_injective
  simp [polynomialAwayMap, Away.mk, MvPolynomial.mapGradedRingHom]

/-- Equal localization elements give canonically isomorphic homogeneous localizations. -/
noncomputable def awayRingEquivOfEq {A σ : Type u} [CommRing A] [SetLike σ A]
    [AddSubgroupClass σ A] {𝒜 : ℕ → σ} [GradedRing 𝒜] {x y : A} (h : x = y) :
    Away 𝒜 x ≃+* Away 𝒜 y := by
  subst y
  exact RingEquiv.refl _

@[simp]
theorem awayRingEquivOfEq_mk {A σ : Type u} [CommRing A] [SetLike σ A]
    [AddSubgroupClass σ A] {𝒜 : ℕ → σ} [GradedRing 𝒜] {x y : A} (h : x = y)
    {d : ℕ} (hx : x ∈ 𝒜 d) (m : ℕ) (a : A) (ha : a ∈ 𝒜 (m • d)) :
    awayRingEquivOfEq h (Away.mk 𝒜 hx m a ha) =
      Away.mk 𝒜 (h ▸ hx) m a ha := by
  subst y
  rfl

/-- Changing the chosen homogeneous generator by equality does not change the corresponding
standard open immersion. -/
@[reassoc]
theorem SpecMap_awayRingEquivOfEq_comp_awayι
    {A σ : Type u} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
    {𝒜 : ℕ → σ} [GradedRing 𝒜] {x y : A} (hxy : x = y) {d : ℕ}
    (hx : x ∈ 𝒜 d) (hy : y ∈ 𝒜 d) (hd : 0 < d) :
    Spec.map (CommRingCat.ofHom (awayRingEquivOfEq hxy).toRingHom) ≫
        Proj.awayι 𝒜 x hx hd =
      Proj.awayι 𝒜 y hy hd := by
  subst y
  simp [awayRingEquivOfEq]

/-- Transporting the target of a homogeneous localization map across equality sends a
standard fraction to the corresponding standard fraction. -/
theorem awayRingEquivOfEq_awayMap_mk
    {A B σ τ : Type u} [CommRing A] [CommRing B]
    [SetLike σ A] [AddSubgroupClass σ A] [SetLike τ B] [AddSubgroupClass τ B]
    {𝒜 : ℕ → σ} [GradedRing 𝒜] {ℬ : ℕ → τ} [GradedRing ℬ]
    (g : 𝒜 →+*ᵍ ℬ) {x : A} {y : B} (hxy : g x = y) {d : ℕ}
    (hx : x ∈ 𝒜 d) (hy : y ∈ ℬ d) (m : ℕ) (a : A) (ha : a ∈ 𝒜 (m • d)) :
    awayRingEquivOfEq hxy
        (Away.map g x (Away.mk 𝒜 hx m a ha)) =
      Away.mk ℬ hy m (g a) (map_mem g ha) := by
  subst y
  rw [Away.map_mk, awayRingEquivOfEq_mk]

/-- The same chart map, factored through Mathlib's generic
`HomogeneousLocalization.Away.map` and the equality `map(Xᵢ) = Xᵢ`. -/
noncomputable def polynomialAwayMapViaProj {R S : Type u} [CommRing R] [CommRing S]
    (f : R →+* S) :
    Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) →+*
      Away (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.X i) :=
  let F := MvPolynomial.mapGradedRingHom (ι := ι) f
  (awayRingEquivOfEq (MvPolynomial.mapGradedRingHom_X f i)).toRingHom.comp
    (Away.map F (MvPolynomial.X i))

theorem polynomialAwayMapViaProj_mk {R S : Type u} [CommRing R] [CommRing S]
    (f : R →+* S) (m : ℕ) (a : MvPolynomial ι R)
    (ha : a ∈ MvPolynomial.homogeneousSubmodule ι R (m • 1)) :
    polynomialAwayMapViaProj ι i f
        (Away.mk (MvPolynomial.homogeneousSubmodule ι R)
          (show MvPolynomial.X i ∈ MvPolynomial.homogeneousSubmodule ι R 1 from
            (MvPolynomial.mem_homogeneousSubmodule _ _).mpr
              (MvPolynomial.isHomogeneous_X R i)) m a
          (show a.IsHomogeneous (m • 1) from
            (MvPolynomial.mem_homogeneousSubmodule _ _).mp ha)) =
      Away.mk (MvPolynomial.homogeneousSubmodule ι S)
        (show MvPolynomial.X i ∈ MvPolynomial.homogeneousSubmodule ι S 1 from
          (MvPolynomial.mem_homogeneousSubmodule _ _).mpr
            (MvPolynomial.isHomogeneous_X S i)) m (MvPolynomial.map f a)
          ((show a.IsHomogeneous (m • 1) from ha).map f) := by
  unfold polynomialAwayMapViaProj
  dsimp only [RingHom.comp_apply]
  exact awayRingEquivOfEq_awayMap_mk
    (MvPolynomial.mapGradedRingHom f)
    (MvPolynomial.mapGradedRingHom_X f i)
    ((MvPolynomial.mem_homogeneousSubmodule _ _).mpr
      (MvPolynomial.isHomogeneous_X R i))
    ((MvPolynomial.mem_homogeneousSubmodule _ _).mpr
      (MvPolynomial.isHomogeneous_X S i)) m a ha

theorem polynomialAwayMap_eq_viaProj {R S : Type u} [CommRing R] [CommRing S]
    (f : R →+* S) :
    polynomialAwayMap ι i f = polynomialAwayMapViaProj ι i f := by
  ext z
  obtain ⟨m, a, ha, rfl⟩ := Away.mk_surjective
    (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.isHomogeneous_X R i) z
  rw [polynomialAwayMap_mk, polynomialAwayMapViaProj_mk]
  exact ha

/-- The standard-open immersion commutes with coefficient change. -/
@[reassoc]
theorem awayι_comp_polynomialMap
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) :
    Proj.awayι (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X S i) Nat.one_pos ≫ polynomialMap ι f =
      Spec.map (CommRingCat.ofHom (polynomialAwayMap ι i f)) ≫
        Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
          (MvPolynomial.isHomogeneous_X R i) Nat.one_pos := by
  let F := MvPolynomial.mapGradedRingHom (ι := ι) f
  let hF := MvPolynomial.irrelevant_le_map_mapGradedRingHom (ι := ι) f
  let e : Away (MvPolynomial.homogeneousSubmodule ι S) (F (MvPolynomial.X i)) ≃+*
      Away (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.X i) :=
    awayRingEquivOfEq (MvPolynomial.mapGradedRingHom_X f i)
  rw [polynomialAwayMap_eq_viaProj]
  change Proj.awayι (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.X i)
      (MvPolynomial.isHomogeneous_X S i) Nat.one_pos ≫ Proj.map F hF =
    Spec.map (CommRingCat.ofHom (e.toRingHom.comp (Away.map F (MvPolynomial.X i)))) ≫
      Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X R i) Nat.one_pos
  rw [← SpecMap_awayRingEquivOfEq_comp_awayι
      (MvPolynomial.mapGradedRingHom_X f i)
      (map_mem F (MvPolynomial.isHomogeneous_X R i))
      (MvPolynomial.isHomogeneous_X S i) Nat.one_pos,
    Category.assoc, Proj.awayι_comp_map F hF Nat.one_pos
      (MvPolynomial.X i) (MvPolynomial.isHomogeneous_X R i)]
  simp only [← Category.assoc, ← Spec.map_comp, ← CommRingCat.ofHom_comp]
  rfl

/-- The standard-chart coordinate-ring equivalence is natural in the coefficient ring. -/
theorem awayMap_comp_polynomialChartToAway
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) :
    (polynomialAwayMap ι i f).comp (polynomialChartToAway ι i R) =
      (polynomialChartToAway ι i S).comp (MvPolynomial.map f) := by
  apply MvPolynomial.ringHom_ext
  · intro r
    apply HomogeneousLocalization.val_injective
    simp [polynomialChartToAway, polynomialChartCoordinate, polynomialAwayMap,
      MvPolynomial.mapGradedRingHom, fromZeroRingHom]
  · intro j
    simp [polynomialChartToAway, polynomialChartCoordinate, polynomialAwayMap_mk]

/-- The coefficient ring maps to a standard projective chart through constant homogeneous
fractions. -/
noncomputable def polynomialChartBaseRingHom (R : Type u) [CommRing R] :
    R →+* Away (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i) :=
  (fromZeroRingHom (MvPolynomial.homogeneousSubmodule ι R)
    (Submonoid.powers (MvPolynomial.X i))).comp
      (MvPolynomial.degreeZeroRingEquiv ι R).toRingHom

@[simp]
theorem polynomialChartBaseRingHom_apply (R : Type u) [CommRing R] (r : R) :
    polynomialChartBaseRingHom ι i R r = polynomialChartToAway ι i R (MvPolynomial.C r) := by
  simp [polynomialChartBaseRingHom, polynomialChartToAway]

/-- On a standard chart, the structure morphism of polynomial `Proj` is induced by the
inclusion of the coefficient ring into the chart ring. -/
@[reassoc]
theorem awayι_comp_polynomialToSpec (R : Type u) [CommRing R] :
    Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X R i) Nat.one_pos ≫ polynomialToSpec ι R =
      Spec.map (CommRingCat.ofHom (polynomialChartBaseRingHom ι i R)) := by
  rw [polynomialToSpec, ← Category.assoc, Proj.awayι_toSpecZero]
  change Spec.map (CommRingCat.ofHom
      (fromZeroRingHom (MvPolynomial.homogeneousSubmodule ι R)
        (Submonoid.powers (MvPolynomial.X i)))) ≫
      Spec.map (CommRingCat.ofHom
        (MvPolynomial.degreeZeroRingEquiv ι R).toRingHom) =
    Spec.map (CommRingCat.ofHom (polynomialChartBaseRingHom ι i R))
  rw [← Spec.map_comp, ← CommRingCat.ofHom_comp]
  rfl

/-- The square of coefficient rings and standard projective-chart rings is a pushout. -/
theorem isPushout_polynomialAwayMap
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) :
    IsPushout (CommRingCat.ofHom f)
      (CommRingCat.ofHom (polynomialChartBaseRingHom ι i R))
      (CommRingCat.ofHom (polynomialChartBaseRingHom ι i S))
      (CommRingCat.ofHom (polynomialAwayMap ι i f)) := by
  letI : Algebra R S := f.toAlgebra
  letI : Algebra (MvPolynomial {j : ι // j ≠ i} R)
      (MvPolynomial {j : ι // j ≠ i} S) :=
    (MvPolynomial.map (σ := {j : ι // j ≠ i}) f).toAlgebra
  let h := CommRingCat.isPushout_of_isPushout R S
    (MvPolynomial {j : ι // j ≠ i} R) (MvPolynomial {j : ι // j ≠ i} S)
  refine h.of_iso (Iso.refl _) (Iso.refl _)
    (projectiveChartPolynomialEquivAway ι i R).toCommRingCatIso
    (projectiveChartPolynomialEquivAway ι i S).toCommRingCatIso ?_ ?_ ?_ ?_
  · rfl
  · ext r
    simp [polynomialChartBaseRingHom_apply]
  · ext s
    simp [polynomialChartBaseRingHom_apply]
  · change CommRingCat.ofHom (MvPolynomial.map f) ≫
        CommRingCat.ofHom (polynomialChartToAway ι i S) =
      CommRingCat.ofHom (polynomialChartToAway ι i R) ≫
        CommRingCat.ofHom (polynomialAwayMap ι i f)
    rw [← CommRingCat.ofHom_comp, ← CommRingCat.ofHom_comp]
    exact congrArg CommRingCat.ofHom (awayMap_comp_polynomialChartToAway ι i f).symm

/-- On a standard chart, the coefficient-change square of affine schemes is cartesian. -/
theorem isPullback_Spec_polynomialAwayMap
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) :
    IsPullback (Spec.map (CommRingCat.ofHom (polynomialAwayMap ι i f)))
      (Spec.map (CommRingCat.ofHom (polynomialChartBaseRingHom ι i S)))
      (Spec.map (CommRingCat.ofHom (polynomialChartBaseRingHom ι i R)))
      (Spec.map (CommRingCat.ofHom f)) :=
  (isPullback_SpecMap_of_isPushout _ _ _ _
    (isPushout_polynomialAwayMap ι i f)).flip

/-- The cartesian coefficient-change square on one standard projective chart, expressed
with its open immersions into the two polynomial projective spectra. -/
theorem isPullback_awayι_polynomialMap
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) :
    IsPullback (Spec.map (CommRingCat.ofHom (polynomialAwayMap ι i f)))
      (Proj.awayι (MvPolynomial.homogeneousSubmodule ι S) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X S i) Nat.one_pos)
      (Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X R i) Nat.one_pos)
      (polynomialMap ι f) := by
  apply IsOpenImmersion.isPullback
  · exact awayι_comp_polynomialMap ι i f
  · rw [Proj.opensRange_awayι, Proj.opensRange_awayι,
      polynomialMap_preimage_basicOpen]
    simp

end StandardChartInverse

section StandardCover

variable (ι : Type) (R : Type u) [CommRing R]

/-- The standard affine cover of polynomial `Proj` by the opens `D₊(Xᵢ)`. -/
noncomputable def polynomialAffineOpenCover :
    (Proj (MvPolynomial.homogeneousSubmodule ι R)).AffineOpenCover :=
  Proj.affineOpenCoverOfIrrelevantLESpan
    (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X : ι → MvPolynomial ι R)
    (fun i ↦ MvPolynomial.isHomogeneous_X R i) (fun _ ↦ Nat.one_pos)
      (MvPolynomial.irrelevant_toIdeal_le_idealOfVars ι R)

@[simp]
theorem polynomialAffineOpenCover_f (i : ι) :
    (polynomialAffineOpenCover ι R).f i =
      Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X R i) Nat.one_pos := rfl

/-- Polynomial projective spectra commute with arbitrary change of coefficient ring. -/
theorem polynomialMap_isPullback [DecidableEq ι]
    {S : Type u} [CommRing S] (f : R →+* S) :
    IsPullback (polynomialMap ι f) (polynomialToSpec ι S)
      (polynomialToSpec ι R) (Spec.map (CommRingCat.ofHom f)) := by
  refine Scheme.isPullback_of_openCover (polynomialMap ι f) (polynomialToSpec ι S)
    (polynomialToSpec ι R) (Spec.map (CommRingCat.ofHom f))
    (polynomialAffineOpenCover ι R).openCover fun i ↦ ?_
  change ι at i
  change IsPullback
    (pullback.snd (polynomialMap ι f)
      (Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X R i) Nat.one_pos))
    (pullback.fst (polynomialMap ι f)
        (Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
          (MvPolynomial.isHomogeneous_X R i) Nat.one_pos) ≫ polynomialToSpec ι S)
    (Proj.awayι (MvPolynomial.homogeneousSubmodule ι R) (MvPolynomial.X i)
        (MvPolynomial.isHomogeneous_X R i) Nat.one_pos ≫ polynomialToSpec ι R)
    (Spec.map (CommRingCat.ofHom f))
  let hchart := (isPullback_awayι_polynomialMap ι i f).flip
  let e := hchart.isoPullback
  refine (isPullback_Spec_polynomialAwayMap ι i f).of_iso e
    (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_ ?_ ?_
  · simp [e]
  · have hfst := hchart.isoPullback_hom_fst
    exact (by
      simpa only [Iso.refl_hom, Category.comp_id, ← Category.assoc] using
        (awayι_comp_polynomialToSpec ι i S).symm.trans
          (congrArg (fun k ↦ k ≫ polynomialToSpec ι S) hfst.symm))
  · simpa only [Iso.refl_hom, Category.comp_id, Category.id_comp] using
      (awayι_comp_polynomialToSpec ι i R).symm
  · simp

/-- The canonical identification of the base change of polynomial projective space along a
coefficient-ring map with polynomial projective space over the new coefficient ring. -/
noncomputable def polynomialBaseChangeIso [DecidableEq ι]
    {S : Type u} [CommRing S] (f : R →+* S) :
    pullback (polynomialToSpec ι R) (Spec.map (CommRingCat.ofHom f)) ≅
      Proj (MvPolynomial.homogeneousSubmodule ι S) :=
  (polynomialMap_isPullback ι R f).isoPullback.symm

@[reassoc (attr := simp)]
theorem polynomialBaseChangeIso_hom_polynomialMap [DecidableEq ι]
    {S : Type u} [CommRing S] (f : R →+* S) :
    (polynomialBaseChangeIso ι R f).hom ≫ polynomialMap ι f =
      pullback.fst (polynomialToSpec ι R) (Spec.map (CommRingCat.ofHom f)) := by
  simp [polynomialBaseChangeIso]

@[reassoc (attr := simp)]
theorem polynomialBaseChangeIso_hom_toSpec [DecidableEq ι]
    {S : Type u} [CommRing S] (f : R →+* S) :
    (polynomialBaseChangeIso ι R f).hom ≫ polynomialToSpec ι S =
      pullback.snd (polynomialToSpec ι R) (Spec.map (CommRingCat.ofHom f)) := by
  simp [polynomialBaseChangeIso]

/-- The canonical coefficient homomorphism from the universe lift of the integers. -/
noncomputable def uliftIntCastRingHom : ULift.{u} ℤ →+* R :=
  (Int.castRingHom R).comp ULift.ringEquiv.toRingHom

/-- The coefficient map from the universe lift of the integers is natural in
the target ring. -/
theorem uliftIntCastRingHom_naturality (f : R →+* S) :
    f.comp (uliftIntCastRingHom R) = uliftIntCastRingHom S := by
  ext ⟨z⟩
  simp [uliftIntCastRingHom]

/-- Projective space obtained by base-changing polynomial `Proj` over the integers to an
affine scheme is canonically the polynomial `Proj` over that affine ring.

The source is written in the raw pullback form used by
`AlgebraicGeometry.Scheme.projectiveSpaceOver`; the first projection is therefore its
structure morphism to `Spec R`. -/
noncomputable def polynomialProjOverSpecIso [DecidableEq ι] :
    pullback ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
        ((AlgebraicGeometry.specULiftZIsTerminal).from
          (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))) ≅
      Proj (MvPolynomial.homogeneousSubmodule ι R) :=
  pullback.congrHom
      ((AlgebraicGeometry.specULiftZIsTerminal).hom_ext _
        (Spec.map (CommRingCat.ofHom (uliftIntCastRingHom R))))
      ((AlgebraicGeometry.specULiftZIsTerminal).hom_ext _
        (polynomialToSpec ι (ULift.{u} ℤ))) ≪≫
    pullbackSymmetry
      (Spec.map (CommRingCat.ofHom (uliftIntCastRingHom R)))
      (polynomialToSpec ι (ULift.{u} ℤ)) ≪≫
    polynomialBaseChangeIso ι (ULift.{u} ℤ) (uliftIntCastRingHom R)

@[reassoc (attr := simp)]
theorem polynomialProjOverSpecIso_hom_toSpec [DecidableEq ι] :
    (polynomialProjOverSpecIso ι R).hom ≫ polynomialToSpec ι R =
      pullback.fst ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
        ((AlgebraicGeometry.specULiftZIsTerminal).from
          (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))) := by
  simp [polynomialProjOverSpecIso]

@[reassoc (attr := simp)]
theorem polynomialProjOverSpecIso_hom_polynomialMap [DecidableEq ι] :
    (polynomialProjOverSpecIso ι R).hom ≫
        polynomialMap ι (uliftIntCastRingHom R) =
      pullback.snd ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
        ((AlgebraicGeometry.specULiftZIsTerminal).from
          (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))) := by
  simp [polynomialProjOverSpecIso]

@[reassoc (attr := simp)]
theorem polynomialProjOverSpecIso_inv_absoluteProjection [DecidableEq ι] :
    (polynomialProjOverSpecIso ι R).inv ≫
        pullback.snd ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
          ((AlgebraicGeometry.specULiftZIsTerminal).from
            (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))) =
      polynomialMap ι (uliftIntCastRingHom R) := by
  exact (Iso.inv_comp_eq (polynomialProjOverSpecIso ι R)).mpr
    (polynomialProjOverSpecIso_hom_polynomialMap ι R).symm

/-- Transporting a module pulled back from absolute polynomial projective space across
`polynomialProjOverSpecIso` identifies it with pullback along coefficient change. -/
noncomputable def polynomialProjOverSpec_pullbackAbsoluteIso [DecidableEq ι]
    (M : (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ))).Modules) :
    (Scheme.Modules.pullback (polynomialProjOverSpecIso ι R).inv).obj
        ((Scheme.Modules.pullback
          (pullback.snd ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
            ((AlgebraicGeometry.specULiftZIsTerminal).from
              (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))))).obj M) ≅
      (Scheme.Modules.pullback
        (polynomialMap ι (uliftIntCastRingHom R))).obj M :=
  (Scheme.Modules.pullbackComp (polynomialProjOverSpecIso ι R).inv
      (pullback.snd ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
        ((AlgebraicGeometry.specULiftZIsTerminal).from
          (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))))).app M ≪≫
    (Scheme.Modules.pullbackCongr
      (polynomialProjOverSpecIso_inv_absoluteProjection ι R)).app M

/-- The preceding transport specialized to the Stacks 01MN twisting sheaf.  This reduces
compatibility of the Chapter 2 relative twist with the intrinsic twist over `R` to the one
remaining statement that `Proj.polynomialMap` pulls back polynomial twists. -/
noncomputable def polynomialProjOverSpec_pullbackAbsoluteTwistIso [DecidableEq ι]
    (d : ℤ) :
    (Scheme.Modules.pullback (polynomialProjOverSpecIso ι R).inv).obj
        ((Scheme.Modules.pullback
          (pullback.snd ((AlgebraicGeometry.specULiftZIsTerminal).from (Spec (.of R)))
            ((AlgebraicGeometry.specULiftZIsTerminal).from
              (Proj (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)))))).obj
          (ProjectiveSpectrum.Twist.twist
            (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)) d)) ≅
      (Scheme.Modules.pullback
        (polynomialMap ι (uliftIntCastRingHom R))).obj
          (ProjectiveSpectrum.Twist.twist
            (MvPolynomial.homogeneousSubmodule ι (ULift.{u} ℤ)) d) :=
  polynomialProjOverSpec_pullbackAbsoluteIso ι R _

end StandardCover

end AlgebraicGeometry.Proj
