module

public import Mathlib.CategoryTheory.Bicategory.Functor.Cat.ObjectProperty
public import Mathlib.CategoryTheory.Sites.Descent.IsStack
public import Mathlib.CategoryTheory.Sites.PrecoverageToGrothendieck

/-!
# Site-local object properties of pseudofunctors

This file supplies the missing descent API for full subpseudofunctors cut out by
site-local properties of objects.  If `F` is a stack and `P` is preserved by pullback,
closed under isomorphisms, and local for covering sieves, then `P.fullsubcategory` is a
stack.

The proof forgets the property from descent data, uses effectiveness for `F`, recovers
the property on the global object by locality, and lifts the resulting descent
isomorphism back to the full subcategory.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory CategoryTheory.Bicategory Opposite

namespace CategoryTheory.Pseudofunctor.DescentData

universe t v' v u' u

variable {C : Type u} [Category.{v} C]
variable {F : Pseudofunctor (LocallyDiscrete Cᵒᵖ) Cat.{v', u'}}
variable {ι : Type t} {S : C} {X : ι → C} {f : ∀ i, X i ⟶ S}

/-- Evaluate an isomorphism of descent data at one member of the covering family. -/
@[simps]
def isoApp {D E : F.DescentData f} (e : D ≅ E) (i : ι) : D.obj i ≅ E.obj i where
  hom := e.hom.hom i
  inv := e.inv.hom i
  hom_inv_id := congrArg (fun k => k.hom i) e.hom_inv_id
  inv_hom_id := congrArg (fun k => k.hom i) e.inv_hom_id

end CategoryTheory.Pseudofunctor.DescentData

namespace CategoryTheory.Pseudofunctor.ObjectProperty

universe t v' v u' u

variable {C : Type u} [Category.{v} C]
variable {F : Pseudofunctor (LocallyDiscrete Cᵒᵖ) Cat.{v', u'}}

/-- A property of objects of a pseudofunctor is site-local if it is preserved by
pullback, invariant under isomorphism, and descends from every covering sieve. -/
class IsLocal (P : F.ObjectProperty) (J : GrothendieckTopology C) : Prop
    extends P.IsClosedUnderMapObj, P.IsClosedUnderIsomorphisms where
  /-- An object whose restrictions to a covering sieve have the property has the
  property globally. -/
  of_sieve {S : C} (R : Sieve S) (hR : R ∈ J S)
    (M : F.obj (.mk (op S)))
    (hM : ∀ f : R.arrows.category,
      P.prop _ ((F.map f.obj.hom.op.toLoc).toFunctor.obj M)) :
    P.prop _ M

/-- Locality for a finer topology implies locality for every coarser topology. -/
theorem IsLocal.of_le (P : F.ObjectProperty) {J K : GrothendieckTopology C}
    (hJK : J ≤ K) [P.IsLocal K] : P.IsLocal J where
  of_sieve R hR M hM := IsLocal.of_sieve R (hJK _ hR) M hM

/-- To prove that an object property is local for the topology generated by a
precoverage, it suffices to descend the property from the covering presieves of the
precoverage itself. -/
theorem IsLocal.of_precoverage
    (P : F.ObjectProperty) [P.IsClosedUnderMapObj]
    [P.IsClosedUnderIsomorphisms]
    (K : Precoverage C) [K.IsStableUnderComposition]
    [K.IsStableUnderBaseChange] [K.HasPullbacks] [K.HasIsos]
    (h : ∀ {S : C} (R : Presieve S), R ∈ K S →
      ∀ (M : F.obj (.mk (op S))),
        (∀ ⦃X : C⦄ (f : X ⟶ S), R f →
          P.prop _ ((F.map f.op.toLoc).toFunctor.obj M)) →
        P.prop _ M) :
    P.IsLocal K.toGrothendieck where
  of_sieve {S} R hR M hM := by
    rw [K.mem_toGrothendieck_iff_of_isStableUnderComposition] at hR
    obtain ⟨R₀, hR₀, hle⟩ := hR
    apply h R₀ hR₀ M
    intro X f hf
    let q : R.arrows.category :=
      R.arrows.categoryMk f (hle X f hf)
    exact hM q

namespace DescentData

variable (P : F.ObjectProperty) [P.IsClosedUnderMapObj]
variable {ι : Type t} {S : C} {X : ι → C} (f : ∀ i, X i ⟶ S)

/-- Forget a site-local object property from descent data for the corresponding full
subpseudofunctor. -/
def forget (D : P.fullsubcategory.DescentData f) : F.DescentData f where
  obj i := (D.obj i).obj
  hom Y q i₁ i₂ f₁ f₂ hf₁ hf₂ := (D.hom q f₁ f₂ hf₁ hf₂).hom
  pullHom_hom Y' Y g q q' hq i₁ i₂ f₁ f₂ hf₁ hf₂ gf₁ gf₂ hgf₁ hgf₂ := by
    have h := congrArg InducedCategory.Hom.hom
      (D.pullHom_hom g q q' hq f₁ f₂ hf₁ hf₂ gf₁ gf₂ hgf₁ hgf₂)
    change LocallyDiscreteOpToCat.pullHom (D.hom q f₁ f₂ hf₁ hf₂).hom
      g gf₁ gf₂ hgf₁ hgf₂ = (D.hom q' gf₁ gf₂).hom at h
    exact h
  hom_self Y q i g hg := by
    have h := congrArg InducedCategory.Hom.hom (D.hom_self q g hg)
    change (D.hom q g g).hom = 𝟙 _ at h
    exact h
  hom_comp Y q i₁ i₂ i₃ f₁ f₂ f₃ hf₁ hf₂ hf₃ := by
    have h := congrArg InducedCategory.Hom.hom
      (D.hom_comp q f₁ f₂ f₃ hf₁ hf₂ hf₃)
    change (D.hom q f₁ f₂).hom ≫ (D.hom q f₂ f₃).hom =
      (D.hom q f₁ f₃).hom at h
    exact h

/-- Forget a morphism of descent data for a full subpseudofunctor. -/
def forgetHom {D E : P.fullsubcategory.DescentData f} (φ : D ⟶ E) :
    forget P f D ⟶ forget P f E where
  hom i := (φ.hom i).hom
  comm Y q i₁ i₂ f₁ f₂ hf₁ hf₂ := by
    have h := congrArg InducedCategory.Hom.hom (φ.comm q f₁ f₂ hf₁ hf₂)
    change (F.map f₁.op.toLoc).toFunctor.map (φ.hom i₁).hom ≫
      (E.hom q f₁ f₂).hom = (D.hom q f₁ f₂).hom ≫
        (F.map f₂.op.toLoc).toFunctor.map (φ.hom i₂).hom at h
    exact h

/-- Descent for morphisms passes from a pseudofunctor to a full subpseudofunctor. -/
noncomputable def fullyFaithfulToDescentData
    (hF : (F.toDescentData f).FullyFaithful) :
    (P.fullsubcategory.toDescentData f).FullyFaithful where
  preimage {M N} φ := ObjectProperty.homMk
    (hF.preimage (forgetHom P f φ))
  map_preimage {M N} φ := by
    apply Pseudofunctor.DescentData.hom_ext
    intro i
    apply ObjectProperty.hom_ext
    exact congrArg (fun k => k.hom i) (hF.map_preimage (forgetHom P f φ))
  preimage_map {M N} φ := by
    apply ObjectProperty.hom_ext
    exact hF.preimage_map φ.hom

end DescentData

section Local

variable (P : F.ObjectProperty) {J : GrothendieckTopology C} [P.IsLocal J]

/-- Effective descent passes from a stack to the full subpseudofunctor cut out by a
site-local property. -/
theorem DescentData.essSurjToDescentData [F.IsStack J]
    {S : C} (R : Sieve S) (hR : R ∈ J S) :
    (P.fullsubcategory.toDescentData
      (fun q : R.arrows.category => q.obj.hom)).EssSurj where
  mem_essImage D := by
    let f : ∀ q : R.arrows.category, q.obj.left ⟶ S := fun q => q.obj.hom
    let D₀ : F.DescentData f := DescentData.forget P f D
    have hstack : F.IsStackFor R.arrows := F.isStackFor _ (by simpa)
    let _ : (F.toDescentData f).EssSurj := hstack.essSurj
    let M := (F.toDescentData f).objPreimage D₀
    let e : (F.toDescentData f).obj M ≅ D₀ :=
      (F.toDescentData f).objObjPreimageIso D₀
    have hM : P.prop _ M := IsLocal.of_sieve R hR M (fun q =>
      ObjectProperty.prop_of_iso (P := P.prop _)
        (Pseudofunctor.DescentData.isoApp e q).symm
        (D.obj q).property)
    let MP : P.Obj (.mk (op S)) := ⟨M, hM⟩
    let eP : (P.fullsubcategory.toDescentData f).obj MP ≅ D :=
      Pseudofunctor.DescentData.isoMk
        (fun q => ObjectProperty.isoMk (P := P.prop _)
          (Pseudofunctor.DescentData.isoApp e q))
        (fun Y q i₁ i₂ f₁ f₂ hf₁ hf₂ => by
          apply ObjectProperty.hom_ext
          exact e.hom.comm q f₁ f₂ hf₁ hf₂)
    exact ⟨MP, ⟨eP⟩⟩

/-- A full subpseudofunctor cut out by a site-local property of objects is a stack
whenever the ambient pseudofunctor is a stack. -/
theorem fullsubcategory_isStack [F.IsStack J] : P.fullsubcategory.IsStack J := by
  apply Pseudofunctor.IsStack.of_isStackFor
  intro S R hR
  rw [Pseudofunctor.isStackFor_iff]
  let f : ∀ q : R.arrows.category, q.obj.left ⟶ S := fun q => q.obj.hom
  change (P.fullsubcategory.toDescentData f).IsEquivalence
  have hf : Sieve.ofArrows (fun q : R.arrows.category => q.obj.left) f = R := by
    rw [Sieve.ofArrows_category']
    simp
  have hRf : Sieve.ofArrows (fun q : R.arrows.category => q.obj.left) f ∈ J S := by
    rwa [hf]
  exact
    { faithful := (DescentData.fullyFaithfulToDescentData P f
        (F.fullyFaithfulToDescentData f hRf)).faithful
      full := (DescentData.fullyFaithfulToDescentData P f
        (F.fullyFaithfulToDescentData f hRf)).full
      essSurj := DescentData.essSurjToDescentData P R hR }

end Local

end CategoryTheory.Pseudofunctor.ObjectProperty
