module

public import Mathlib.CategoryTheory.Adjunction.Additive
public import StacksAndModuli.API.OpenCoverQuotient
public import StacksAndModuli.API.ExteriorPowerPullback

/-!
# The pullback of a sheaf of modules is generated by unit sections

Supporting API with no Stacks Project counterpart of its own, consumed by the relative
Plücker embedding of **Theorem 2.1.1**: for a morphism of schemes `f : T ⟶ S` and a sheaf
of modules `V` on `S`, every section of `(pullback f).obj V` lies locally in the span of
restrictions of unit sections (images of sections of `V` under the pullback-adjunction
unit).

The proof is completely formal: the locally-spanned sections form a subsheaf (via
`localSubmoduleSheaf`), the quotient map kills all unit sections, and a morphism out of
the pullback killing all unit sections is zero, because its adjoint transpose vanishes
sectionwise.  Hence the quotient vanishes and the inclusion is an isomorphism.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 10
set_option linter.style.haveILetI false

universe u

open CategoryTheory TopologicalSpace

namespace AlgebraicGeometry

open AlgebraicGeometry.Scheme

variable {T S : Scheme.{u}} (f : T ⟶ S) (V : S.Modules)

/-- The unit sections of the pullback over an open `W ⊆ T`: restrictions of images of
sections of `V` over opens `U ⊆ S` with `W ⊆ f⁻¹U` under the pullback-adjunction
unit. -/
def pullbackUnitSet (W : T.Opens) :
    Set Γ((Scheme.Modules.pullback f).obj V, W) :=
  ⋃ (U : S.Opens) (h : W ≤ f ⁻¹ᵁ U),
    Set.range (fun v : Γ(V, U) ↦
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map (homOfLE h).op
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v))

/-- The presheaf of spans of unit sections. -/
noncomputable def pullbackUnitRawSpan :
    ((Scheme.Modules.pullback f).obj V).val.Submodule where
  obj W := Submodule.span Γ(T, W.unop) (pullbackUnitSet f V W.unop)
  map {W W'} g := by
    rw [Submodule.span_le]
    rintro s hs
    refine Submodule.mem_comap.mpr ?_
    obtain ⟨SU, ⟨U, rfl⟩, hSU⟩ := hs
    obtain ⟨SV, ⟨hWU, rfl⟩, hmem⟩ := hSU
    obtain ⟨v, rfl⟩ := hmem
    have hW'U : W'.unop ≤ f ⁻¹ᵁ U := (leOfHom g.unop).trans hWU
    have hcomp := _root_.PresheafOfModules.map_comp_apply
      (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE hWU).op g
      ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v)
    refine Submodule.subset_span ?_
    exact Set.mem_iUnion.mpr ⟨U, Set.mem_iUnion.mpr ⟨hW'U, ⟨v, hcomp⟩⟩⟩

/-- The presheaf of sections locally in the span of unit sections. -/
noncomputable def pullbackUnitLocalSpan :
    ((Scheme.Modules.pullback f).obj V).val.Submodule where
  obj W :=
    { carrier := { s | ∀ x ∈ W.unop, ∃ (W' : T.Opens) (h : W' ≤ W.unop), x ∈ W' ∧
        (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
          (homOfLE h).op s ∈ (pullbackUnitRawSpan f V).obj (Opposite.op W') }
      add_mem' := by
        rintro s t hs ht x hx
        obtain ⟨W₁, h₁, hx₁, hm₁⟩ := hs x hx
        obtain ⟨W₂, h₂, hx₂, hm₂⟩ := ht x hx
        refine ⟨W₁ ⊓ W₂, inf_le_left.trans h₁, ⟨hx₁, hx₂⟩, ?_⟩
        rw [map_add]
        refine Submodule.add_mem _ ?_ ?_
        · have hc : (Scheme.Modules.presheaf
              ((Scheme.Modules.pullback f).obj V)).map
                (homOfLE (inf_le_left.trans h₁ :
                  W₁ ⊓ W₂ ≤ W.unop)).op s =
              (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
                (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op
                ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
                  (homOfLE h₁).op s) :=
            _root_.PresheafOfModules.map_comp_apply
              (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE h₁).op
              (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op s
          exact hc ▸ (pullbackUnitRawSpan f V).map_mem
            (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op hm₁
        · have hc : (Scheme.Modules.presheaf
              ((Scheme.Modules.pullback f).obj V)).map
                (homOfLE (inf_le_left.trans h₁ :
                  W₁ ⊓ W₂ ≤ W.unop)).op t =
              (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
                (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op
                ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
                  (homOfLE h₂).op t) :=
            _root_.PresheafOfModules.map_comp_apply
              (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE h₂).op
              (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op t
          exact hc ▸ (pullbackUnitRawSpan f V).map_mem
            (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op hm₂
      zero_mem' := by
        intro x hx
        exact ⟨W.unop, le_rfl, hx, by rw [map_zero]; exact Submodule.zero_mem _⟩
      smul_mem' := by
        rintro c s hs x hx
        obtain ⟨W₁, h₁, hx₁, hm₁⟩ := hs x hx
        refine ⟨W₁, h₁, hx₁, ?_⟩
        have hsm := Scheme.Modules.map_smul
          (M := (Scheme.Modules.pullback f).obj V) (homOfLE h₁) c s
        exact hsm ▸ Submodule.smul_mem _ _ hm₁ }
  map {W W'} g := by
    intro s hs
    refine Submodule.mem_comap.mpr ?_
    intro x hx
    obtain ⟨W₁, h₁, hx₁, hm₁⟩ := hs x ((leOfHom g.unop) hx)
    refine ⟨W₁ ⊓ W'.unop, inf_le_right, ⟨hx₁, hx⟩, ?_⟩
    have hc₁ : (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE (inf_le_right : W₁ ⊓ W'.unop ≤ W'.unop)).op
          ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map g s) =
        (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
          (homOfLE (inf_le_left : W₁ ⊓ W'.unop ≤ W₁)).op
            ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
              (homOfLE h₁).op s) := by
      refine Eq.trans (_root_.PresheafOfModules.map_comp_apply
        (M := ((Scheme.Modules.pullback f).obj V).val) g
        (homOfLE (inf_le_right : W₁ ⊓ W'.unop ≤ W'.unop)).op s).symm ?_
      exact _root_.PresheafOfModules.map_comp_apply
        (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE h₁).op
        (homOfLE (inf_le_left : W₁ ⊓ W'.unop ≤ W₁)).op s
    exact hc₁ ▸ (pullbackUnitRawSpan f V).map_mem
      (homOfLE (inf_le_left : W₁ ⊓ W'.unop ≤ W₁)).op hm₁

/-- The local-span condition is local. -/
lemma pullbackUnitLocalSpan_isLocal :
    Scheme.Modules.PresheafSubmoduleIsLocal (pullbackUnitLocalSpan f V) := by
  intro ι Wl W hW hl s h
  intro x hx
  obtain ⟨l, hxl⟩ := TopologicalSpace.Opens.mem_iSup.mp (hW hx)
  obtain ⟨W₁, h₁, hx₁, hm₁⟩ := h l x hxl
  refine ⟨W₁, h₁.trans (hl l), hx₁, ?_⟩
  have hc : (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
      (homOfLE (h₁.trans (hl l))).op s =
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h₁).op
        ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
          (homOfLE (hl l)).op s) :=
    _root_.PresheafOfModules.map_comp_apply
      (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE (hl l)).op
      (homOfLE h₁).op s
  exact hc ▸ hm₁

/-- The subsheaf of sections locally spanned by unit sections. -/
noncomputable def pullbackUnitSubsheaf : T.Modules :=
  Scheme.Modules.localSubmoduleSheaf (pullbackUnitLocalSpan f V)
    (pullbackUnitLocalSpan_isLocal f V)

/-- A morphism out of a pullback that kills all unit sections is zero. -/
lemma eq_zero_of_unit_sections_zero {K : T.Modules}
    (v : (Scheme.Modules.pullback f).obj V ⟶ K)
    (h : ∀ (U : S.Opens) (s : Γ(V, U)),
      (v.app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s) = 0) :
    v = 0 := by
  have hT : (Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv V K v = 0 := by
    refine Scheme.Modules.hom_ext _ _ fun U ↦ ?_
    ext s
    have hcomp : ((Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv V K v).app U s =
        (v.app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s) := by
      have := (Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv_unit
        (X := V) (Y := K) (f := v)
      rw [this]
      rfl
    rw [hcomp, h U s]
    rfl
  have hsym := congrArg
    ((Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv V K).symm hT
  rw [Equiv.symm_apply_apply] at hsym
  rw [hsym, Adjunction.homEquiv_counit]
  haveI : (Scheme.Modules.pullback f).Additive :=
    (Scheme.Modules.pullbackPushforwardAdjunction f).left_adjoint_additive
  rw [Functor.map_zero, Limits.zero_comp]

set_option maxHeartbeats 1600000 in
-- the cokernel argument crosses defeq spellings of sections of the subsheaf
/-- **The pullback of a sheaf of modules is generated by unit sections**: every section
of `(pullback f).obj V` lies, locally at each point, in the span of restrictions of
images of sections of `V` under the pullback-adjunction unit. -/
theorem pullback_sections_locally_spanned (W : T.Opens)
    (s : Γ((Scheme.Modules.pullback f).obj V, W)) (x : ↥T) (hx : x ∈ W) :
    ∃ (W' : T.Opens) (h : W' ≤ W), x ∈ W' ∧
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h).op s ∈ (pullbackUnitRawSpan f V).obj (Opposite.op W') := by
  set ι := Scheme.Modules.localSubmoduleSheafι (pullbackUnitLocalSpan f V)
    (pullbackUnitLocalSpan_isLocal f V) with hι
  -- unit sections belong to the local-span subsheaf
  have hunitmem : ∀ (U : S.Opens) (v : Γ(V, U)),
      ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v) ∈
        (pullbackUnitLocalSpan f V).obj (Opposite.op (f ⁻¹ᵁ U)) := by
    intro U v
    intro y hy
    refine ⟨f ⁻¹ᵁ U, le_rfl, hy, ?_⟩
    refine Submodule.subset_span ?_
    exact Set.mem_iUnion.mpr ⟨U, Set.mem_iUnion.mpr ⟨le_rfl, ⟨v, rfl⟩⟩⟩
  -- the cokernel projection kills the unit sections, hence vanishes
  have hkill : ∀ (U : S.Opens) (v : Γ(V, U)),
      ((Limits.cokernel.π ι).app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v) = 0 := by
    intro U v
    have hfac : (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v =
        (ι.app (f ⁻¹ᵁ U))
          (show Γ(pullbackUnitSubsheaf f V, f ⁻¹ᵁ U) from
            ⟨(((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v,
              hunitmem U v⟩) := rfl
    rw [hfac]
    have hcond := Scheme.Modules.Hom.comp_app
      (φ := ι) (ψ := Limits.cokernel.π ι) (U := f ⁻¹ᵁ U)
    have hzero : (ι ≫ Limits.cokernel.π ι).app (f ⁻¹ᵁ U) = 0 := by
      rw [Limits.cokernel.condition]
      rfl
    have := CategoryTheory.congr_fun (hcond.symm.trans hzero)
      (show Γ(pullbackUnitSubsheaf f V, f ⁻¹ᵁ U) from
        ⟨(((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v,
          hunitmem U v⟩)
    exact this.trans rfl
  have hπ : Limits.cokernel.π ι = 0 := eq_zero_of_unit_sections_zero f V _ hkill
  haveI : Epi ι := Abelian.epi_of_cokernel_π_eq_zero _ hπ
  haveI : IsIso ι := isIso_of_mono_of_epi ι
  -- surjectivity of the inclusion on sections gives the local-span condition
  haveI : IsIso (ι.app W) := Scheme.Modules.Hom.isIso_iff_isIso_app.mp inferInstance W
  obtain ⟨t, ht⟩ := (ConcreteCategory.bijective_of_isIso (ι.app W)).2 s
  obtain ⟨W', h, hxW', hmem⟩ := t.2 x hx
  refine ⟨W', h, hxW', ?_⟩
  have hnat : (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
      (homOfLE h).op s =
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h).op ((ι.app W) t) := by rw [ht]
  rw [hnat]
  exact hmem

/-- The unit-section characterization, packaged as membership in the span. -/
lemma mem_span_unitSet_of_mem_rawSpan {W : T.Opens}
    {s : Γ((Scheme.Modules.pullback f).obj V, W)}
    (h : s ∈ (pullbackUnitRawSpan f V).obj (Opposite.op W)) :
    s ∈ Submodule.span Γ(T, W) (pullbackUnitSet f V W) := h

/-- Sections of a pullback are locally in the span of the unit sections. -/
theorem pullback_mem_span_unitSet (W : T.Opens)
    (s : Γ((Scheme.Modules.pullback f).obj V, W)) (x : ↥T) (hx : x ∈ W) :
    ∃ (W' : T.Opens) (h : W' ≤ W), x ∈ W' ∧
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h).op s ∈ Submodule.span Γ(T, W') (pullbackUnitSet f V W') := by
  obtain ⟨W', h, hxW', hmem⟩ := pullback_sections_locally_spanned f V W s x hx
  exact ⟨W', h, hxW', mem_span_unitSet_of_mem_rawSpan f V hmem⟩

/-- Restriction of a unit section is a unit section. -/
lemma pullbackUnitSet_restrict {W W' : T.Opens} (h : W' ≤ W)
    {s : Γ((Scheme.Modules.pullback f).obj V, W)} (hs : s ∈ pullbackUnitSet f V W) :
    (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map (homOfLE h).op s
      ∈ pullbackUnitSet f V W' := by
  obtain ⟨SU, ⟨U, rfl⟩, hSU⟩ := hs
  obtain ⟨SV, ⟨hWU, rfl⟩, ⟨v, rfl⟩⟩ := hSU
  refine Set.mem_iUnion.mpr ⟨U, Set.mem_iUnion.mpr ⟨h.trans hWU, ⟨v, ?_⟩⟩⟩
  show (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
      (homOfLE (h.trans hWU)).op
      ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v) =
    (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map (homOfLE h).op
      ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map (homOfLE hWU).op
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v))
  exact _root_.PresheafOfModules.map_comp_apply
    (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE hWU).op (homOfLE h).op
    ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v)

/-- Unit sections restrict compatibly: the unit section from `U` restricted to a smaller
open is the unit section of the restricted section. -/
lemma unit_app_restrict {U U' : S.Opens} (h : U' ≤ U) (v : Γ(V, U)) :
    (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE ((Opens.map f.base).map (homOfLE h)).le).op
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v) =
      (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U')
        ((Scheme.Modules.presheaf V).map (homOfLE h).op v) := by
  exact (_root_.PresheafOfModules.naturality_apply
    ((SheafOfModules.forget _).map
      ((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V))
    (homOfLE h).op v).symm

/-- A finite family of unit sections comes from a common open of the base. -/
lemma exists_common_open_of_unitSet {q : ℕ} {W : T.Opens}
    (g : Fin q → Γ((Scheme.Modules.pullback f).obj V, W))
    (hg : ∀ i, g i ∈ pullbackUnitSet f V W) :
    ∃ (U : S.Opens) (h : W ≤ f ⁻¹ᵁ U) (v : Fin q → Γ(V, U)), ∀ i,
      g i = (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h).op
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) (v i)) := by
  classical
  have hchoice : ∀ i, ∃ (U : S.Opens) (h : W ≤ f ⁻¹ᵁ U) (v : Γ(V, U)),
      g i = (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h).op
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) v) := by
    intro i
    obtain ⟨SU, ⟨U, rfl⟩, hSU⟩ := hg i
    obtain ⟨SV, ⟨hWU, rfl⟩, ⟨v, hv⟩⟩ := hSU
    exact ⟨U, hWU, v, hv.symm⟩
  choose U hU v hv using hchoice
  refine ⟨⨅ i, U i, ?_, fun i ↦ (Scheme.Modules.presheaf V).map
    (homOfLE (iInf_le U i)).op (v i), fun i ↦ ?_⟩
  · intro y hy
    show f.base y ∈ ((⨅ i, U i : S.Opens) : Set S)
    rw [TopologicalSpace.Opens.coe_iInf]
    exact Set.mem_iInter.mpr fun i ↦ hU i hy
  · have hle : (⨅ i, U i) ≤ U i := iInf_le U i
    have hWinf : W ≤ f ⁻¹ᵁ (⨅ i, U i) := by
      intro y hy
      show f.base y ∈ ((⨅ j, U j : S.Opens) : Set S)
      rw [TopologicalSpace.Opens.coe_iInf]
      exact Set.mem_iInter.mpr fun j ↦ hU j hy
    have hnat := unit_app_restrict f V hle (v i)
    have hcomp := _root_.PresheafOfModules.map_comp_apply
      (M := ((Scheme.Modules.pullback f).obj V).val)
      (homOfLE ((Opens.map f.base).map (homOfLE hle)).le).op (homOfLE hWinf).op
      ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app (U i)) (v i))
    rw [hv i]
    refine Eq.trans ?_ (congrArg (ConcreteCategory.hom
      (((_root_.PresheafOfModules.toPresheaf _).obj
        ((Scheme.Modules.pullback f).obj V).val).map (homOfLE hWinf).op)) hnat)
    exact hcomp


/-- **Extensionality for morphisms out of a pullback**: two morphisms agreeing on all
unit sections are equal. -/
lemma hom_ext_of_unit {K : T.Modules}
    (a b : (Scheme.Modules.pullback f).obj V ⟶ K)
    (h : ∀ (U : S.Opens) (s : Γ(V, U)),
      (a.app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s) =
        (b.app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s)) :
    a = b := by
  have hzero : a - b = 0 := by
    refine eq_zero_of_unit_sections_zero f V (a - b) ?_
    intro U s
    have happ : ((a - b).app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s) =
        (a.app (f ⁻¹ᵁ U))
            ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s) -
          (b.app (f ⁻¹ᵁ U))
            ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) s) := rfl
    rw [happ, h U s, sub_self]
  exact sub_eq_zero.mp hzero


section PullbackExteriorPowerEpi

variable (q : ℕ)

/-- The pullback comparison, evaluated on unit sections of the exterior power, is the
wedge comparison. -/
lemma pullbackExteriorPower_app_unit (U : S.Opens)
    (w : (⋀[Γ(S, U)]^q Γ(V, U) :
      Submodule Γ(S, U) (ExteriorAlgebra Γ(S, U) Γ(V, U)))) :
    ((pullbackExteriorPower f V q).app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
          (Scheme.Modules.exteriorPower V q)).app U)
          (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom w)) =
      pullbackWedgeApp f V q U w := by
  -- the transpose relation: `homEquiv P = C`
  have htr : (Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv
      (Scheme.Modules.exteriorPower V q)
      (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback f).obj V) q)
      (pullbackExteriorPower f V q) = exteriorPowerPushforwardComparison f V q := by
    rw [pullbackExteriorPower, Equiv.apply_symm_apply]
  have hcomp := (Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv_unit
    (X := Scheme.Modules.exteriorPower V q)
    (Y := Scheme.Modules.exteriorPower ((Scheme.Modules.pullback f).obj V) q)
    (f := pullbackExteriorPower f V q)
  rw [hcomp] at htr
  -- evaluate at `U` on the unit-of-sheafification of `w`
  have hev := CategoryTheory.congr_fun (congrArg
    (fun (k : Scheme.Modules.exteriorPower V q ⟶
        (Scheme.Modules.pushforward f).obj
          (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback f).obj V) q)) ↦
      k.app U) htr)
    (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom w)
  refine Eq.trans ?_ (Eq.trans hev ?_)
  · rfl
  · -- the comparison is the sheafification transpose of the wedge comparison
    have hfac := _root_.PresheafOfModules.comp_toPresheaf_map_sheafifyHomEquiv'_symm_hom
      (𝟙 S.ringCatSheaf.val)
      (CategoryTheory.toSheafify (Opens.grothendieckTopology S)
        (Scheme.Modules.exteriorPowerPresheaf V q).presheaf)
      ((Scheme.Modules.pushforward f).obj
        (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback f).obj V) q)).isSheaf
      (pullbackWedge f V q)
    exact CategoryTheory.congr_fun (NatTrans.congr_app hfac (Opposite.op U)) w

set_option maxHeartbeats 1600000 in
-- the range membership crosses the pullback and sheafification transposes
/-- The sheafification unit of a wedge of unit sections is in the image of the pullback
comparison. -/
lemma unit_ιMulti_mem_range (W : T.Opens)
    (g : Fin q → Γ((Scheme.Modules.pullback f).obj V, W))
    (hg : ∀ i, g i ∈ pullbackUnitSet f V W) :
    ((Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q).app
        (Opposite.op W)).hom
        (exteriorPower.ιMulti Γ(T, W) q g) ∈
      LinearMap.range (((pullbackExteriorPower f V q).val.app (Opposite.op W)).hom) := by
  obtain ⟨U, hWU, v, hv⟩ := exists_common_open_of_unitSet f V g hg
  -- the wedge of the unit sections is the restriction of the wedge over `f⁻¹U`
  have hrestr : exteriorPower.ιMulti Γ(T, W) q g =
      ((Scheme.Modules.exteriorPowerPresheaf ((Scheme.Modules.pullback f).obj V) q).map
        (homOfLE hWU).op).hom
        (exteriorPower.ιMulti Γ(T, f ⁻¹ᵁ U) q
          (fun i ↦ show Γ((Scheme.Modules.pullback f).obj V, f ⁻¹ᵁ U) from
            (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U)
              (v i))) := by
    refine Eq.trans (congrArg (exteriorPower.ιMulti Γ(T, W) q) (funext hv)) ?_
    exact (_root_.PresheafOfModules.exteriorPowerObjMap_ιMulti (R := T.sheaf.val)
      (M := (((Scheme.Modules.pullback f).obj V).val : _root_.PresheafOfModules.{u}
        (T.sheaf.val ⋙ forget₂ CommRingCat RingCat))) q (homOfLE hWU).op
      (fun i ↦ show Γ((Scheme.Modules.pullback f).obj V, f ⁻¹ᵁ U) from
        (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) (v i))).symm
  -- move the sheafification unit past the restriction
  have hnat := _root_.PresheafOfModules.naturality_apply
    (Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q)
    (homOfLE hWU).op
    (exteriorPower.ιMulti Γ(T, f ⁻¹ᵁ U) q
      (fun i ↦ show Γ((Scheme.Modules.pullback f).obj V, f ⁻¹ᵁ U) from
        (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) (v i)))
  -- over `f⁻¹U` the section is `P` of a unit section, by the two compatibility lemmas
  have hwedge := pullbackWedgeApp_ιMulti f V q U v
  have hkey := pullbackExteriorPower_app_unit f V q U
    (exteriorPower.ιMulti Γ(S, U) q v)
  refine ⟨(Scheme.Modules.presheaf
      ((Scheme.Modules.pullback f).obj (Scheme.Modules.exteriorPower V q))).map
        (homOfLE hWU).op
      ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
        (Scheme.Modules.exteriorPower V q)).app U)
        (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
          (exteriorPower.ιMulti Γ(S, U) q v))), ?_⟩
  -- naturality of `P` moves it back
  have hPnat := _root_.PresheafOfModules.naturality_apply
    ((SheafOfModules.forget _).map (pullbackExteriorPower f V q)) (homOfLE hWU).op
    ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
      (Scheme.Modules.exteriorPower V q)).app U)
      (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
        (exteriorPower.ιMulti Γ(S, U) q v)))
  refine hPnat.trans ?_
  refine Eq.trans (congrArg (ConcreteCategory.hom
    (((_root_.PresheafOfModules.toPresheaf _).obj
      ((SheafOfModules.forget _).obj
        (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback f).obj V) q))).map
          (homOfLE hWU).op)) (hkey.trans hwedge)) ?_
  refine hnat.symm.trans ?_
  exact congrArg (ConcreteCategory.hom
    ((Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q).app
      (Opposite.op W))) hrestr.symm

/-- A finite family of sections of a pullback is simultaneously in the span of unit
sections on a small enough open. -/
lemma exists_common_shrink (W : T.Opens)
    (m : Fin q → Γ((Scheme.Modules.pullback f).obj V, W)) (x : ↥T) (hx : x ∈ W) :
    ∃ (W₂ : T.Opens) (h : W₂ ≤ W), x ∈ W₂ ∧ ∀ i,
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map (homOfLE h).op
        (m i) ∈ (pullbackUnitRawSpan f V).obj (Opposite.op W₂) := by
  classical
  have hloc : ∀ i, ∃ (Wi : T.Opens) (h : Wi ≤ W), x ∈ Wi ∧
      (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map (homOfLE h).op
        (m i) ∈ (pullbackUnitRawSpan f V).obj (Opposite.op Wi) := fun i ↦
    pullback_sections_locally_spanned f V W (m i) x hx
  choose Wi hWi hxi hmi using hloc
  refine ⟨W ⊓ ⨅ i, Wi i, inf_le_left, ⟨hx, ?_⟩, fun i ↦ ?_⟩
  · show x ∈ ((⨅ i, Wi i : T.Opens) : Set T)
    rw [TopologicalSpace.Opens.coe_iInf]
    exact Set.mem_iInter.mpr hxi
  · have hle : W ⊓ ⨅ j, Wi j ≤ Wi i :=
      le_trans inf_le_right (iInf_le _ i)
    have hc : (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE (inf_le_left : W ⊓ ⨅ j, Wi j ≤ W)).op (m i) =
        (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
          (homOfLE hle).op
          ((Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
            (homOfLE (hWi i)).op (m i)) :=
      _root_.PresheafOfModules.map_comp_apply
        (M := ((Scheme.Modules.pullback f).obj V).val) (homOfLE (hWi i)).op
        (homOfLE hle).op (m i)
    exact hc ▸ (pullbackUnitRawSpan f V).map_mem (homOfLE hle).op (hmi i)

set_option maxHeartbeats 3200000 in
-- the span induction crosses the exterior-power presheaf and sheafification spellings
/-- Every element of the exterior-power presheaf of a pullback maps, locally, into the
image of the pullback comparison. -/
lemma exteriorPowerPresheaf_locally_mem_range (W : T.Opens)
    (w : (⋀[Γ(T, W)]^q Γ((Scheme.Modules.pullback f).obj V, W) :
      Submodule Γ(T, W)
        (ExteriorAlgebra Γ(T, W) Γ((Scheme.Modules.pullback f).obj V, W))))
    (x : ↥T) (hx : x ∈ W) :
    ∃ (W' : T.Opens) (h : W' ≤ W), x ∈ W' ∧
      ((Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q).app
        (Opposite.op W')).hom
        (((Scheme.Modules.exteriorPowerPresheaf
          ((Scheme.Modules.pullback f).obj V) q).map (homOfLE h).op).hom w) ∈
      LinearMap.range
        (((pullbackExteriorPower f V q).val.app (Opposite.op W')).hom) := by
  have hw : w ∈ Submodule.span Γ(T, W)
      (Set.range (exteriorPower.ιMulti Γ(T, W) q
        (M := Γ((Scheme.Modules.pullback f).obj V, W)))) := by
    rw [exteriorPower.ιMulti_span]
    trivial
  induction hw using Submodule.span_induction with
  | mem w hw =>
    obtain ⟨m, rfl⟩ := hw
    obtain ⟨W₂, h₂, hx₂, hm₂⟩ := exists_common_shrink f V q W m x hx
    refine ⟨W₂, h₂, hx₂, ?_⟩
    -- the restricted wedge is a wedge of sections in the span of unit sections
    have hrestr := _root_.PresheafOfModules.exteriorPowerObjMap_ιMulti
      (R := T.sheaf.val)
      (M := (((Scheme.Modules.pullback f).obj V).val : _root_.PresheafOfModules.{u}
        (T.sheaf.val ⋙ forget₂ CommRingCat RingCat))) q (homOfLE h₂).op m
    -- expand into the span of wedges of unit sections
    have hspan := exteriorPower.ιMulti_mem_span_of_forall_mem_span
      (R₀ := Γ(T, W₂)) (M₀ := Γ((Scheme.Modules.pullback f).obj V, W₂)) q
      (pullbackUnitSet f V W₂)
      (fun i ↦ (Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj V)).map
        (homOfLE h₂).op (m i)) hm₂
    -- the unit maps that span into the image of the comparison
    have hmaps : Submodule.span Γ(T, W₂)
        {y : (⋀[Γ(T, W₂)]^q Γ((Scheme.Modules.pullback f).obj V, W₂) :
            Submodule Γ(T, W₂)
              (ExteriorAlgebra Γ(T, W₂) Γ((Scheme.Modules.pullback f).obj V, W₂))) |
          ∃ g : Fin q → Γ((Scheme.Modules.pullback f).obj V, W₂),
            (∀ i, g i ∈ pullbackUnitSet f V W₂) ∧
              y = exteriorPower.ιMulti Γ(T, W₂) q g} ≤
        Submodule.comap
          (((Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q).app
            (Opposite.op W₂)).hom)
          (LinearMap.range
            (((pullbackExteriorPower f V q).val.app (Opposite.op W₂)).hom)) := by
      rw [Submodule.span_le]
      rintro y ⟨g, hgU, rfl⟩
      exact unit_ιMulti_mem_range f V q W₂ g hgU
    have hmem := hmaps hspan
    refine Submodule.mem_comap.mp ?_
    exact hrestr ▸ hmem
  | zero =>
    refine ⟨W, le_rfl, hx, ?_⟩
    rw [map_zero, map_zero]
    exact Submodule.zero_mem _
  | add u v hu hv h1 h2 =>
    obtain ⟨W₁, k₁, hx₁, hm₁⟩ := h1
    obtain ⟨W₂, k₂, hx₂, hm₂⟩ := h2
    refine ⟨W₁ ⊓ W₂, inf_le_left.trans k₁, ⟨hx₁, hx₂⟩, ?_⟩
    rw [map_add, map_add]
    refine Submodule.add_mem _ ?_ ?_
    · have hc : ((Scheme.Modules.exteriorPowerPresheaf
          ((Scheme.Modules.pullback f).obj V) q).map
            (homOfLE (inf_le_left.trans k₁ : W₁ ⊓ W₂ ≤ W)).op).hom u =
          ((Scheme.Modules.exteriorPowerPresheaf
            ((Scheme.Modules.pullback f).obj V) q).map
              (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op).hom
            (((Scheme.Modules.exteriorPowerPresheaf
              ((Scheme.Modules.pullback f).obj V) q).map (homOfLE k₁).op).hom u) :=
        _root_.PresheafOfModules.map_comp_apply
          (M := Scheme.Modules.exteriorPowerPresheaf
            ((Scheme.Modules.pullback f).obj V) q)
          (homOfLE k₁).op (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op u
      rw [hc]
      obtain ⟨z, hz⟩ := hm₁
      refine ⟨(Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj
        (Scheme.Modules.exteriorPower V q))).map
          (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op z, ?_⟩
      have hPnat := _root_.PresheafOfModules.naturality_apply
        ((SheafOfModules.forget _).map (pullbackExteriorPower f V q))
        (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op z
      have hunat := _root_.PresheafOfModules.naturality_apply
        (Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q)
        (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op
        (((Scheme.Modules.exteriorPowerPresheaf
          ((Scheme.Modules.pullback f).obj V) q).map (homOfLE k₁).op).hom u)
      refine hPnat.trans (Eq.trans ?_ hunat.symm)
      exact congrArg (ConcreteCategory.hom
        (((_root_.PresheafOfModules.toPresheaf _).obj
          ((SheafOfModules.forget _).obj
            (Scheme.Modules.exteriorPower
              ((Scheme.Modules.pullback f).obj V) q))).map
                (homOfLE (inf_le_left : W₁ ⊓ W₂ ≤ W₁)).op)) hz
    · have hc : ((Scheme.Modules.exteriorPowerPresheaf
          ((Scheme.Modules.pullback f).obj V) q).map
            (homOfLE (inf_le_left.trans k₁ : W₁ ⊓ W₂ ≤ W)).op).hom v =
          ((Scheme.Modules.exteriorPowerPresheaf
            ((Scheme.Modules.pullback f).obj V) q).map
              (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op).hom
            (((Scheme.Modules.exteriorPowerPresheaf
              ((Scheme.Modules.pullback f).obj V) q).map (homOfLE k₂).op).hom v) :=
        _root_.PresheafOfModules.map_comp_apply
          (M := Scheme.Modules.exteriorPowerPresheaf
            ((Scheme.Modules.pullback f).obj V) q)
          (homOfLE k₂).op (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op v
      rw [hc]
      obtain ⟨z, hz⟩ := hm₂
      refine ⟨(Scheme.Modules.presheaf ((Scheme.Modules.pullback f).obj
        (Scheme.Modules.exteriorPower V q))).map
          (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op z, ?_⟩
      have hPnat := _root_.PresheafOfModules.naturality_apply
        ((SheafOfModules.forget _).map (pullbackExteriorPower f V q))
        (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op z
      have hunat := _root_.PresheafOfModules.naturality_apply
        (Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q)
        (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op
        (((Scheme.Modules.exteriorPowerPresheaf
          ((Scheme.Modules.pullback f).obj V) q).map (homOfLE k₂).op).hom v)
      refine hPnat.trans (Eq.trans ?_ hunat.symm)
      exact congrArg (ConcreteCategory.hom
        (((_root_.PresheafOfModules.toPresheaf _).obj
          ((SheafOfModules.forget _).obj
            (Scheme.Modules.exteriorPower
              ((Scheme.Modules.pullback f).obj V) q))).map
                (homOfLE (inf_le_right : W₁ ⊓ W₂ ≤ W₂)).op)) hz
  | smul r u hu h1 =>
    obtain ⟨W₁, k₁, hx₁, hm₁⟩ := h1
    refine ⟨W₁, k₁, hx₁, ?_⟩
    have hsm := _root_.PresheafOfModules.map_smul
      (M := Scheme.Modules.exteriorPowerPresheaf ((Scheme.Modules.pullback f).obj V) q)
      (homOfLE k₁).op r u
    rw [hsm, map_smul]
    exact Submodule.smul_mem _ _ hm₁

set_option maxHeartbeats 1600000 in
-- the local-surjectivity assembly crosses the sheafification and pullback transposes
/-- **The pullback comparison for exterior powers is an epimorphism**: the canonical map
`f^*(⋀^q V) ⟶ ⋀^q(f^*V)` is epi for every morphism of schemes `f` and every sheaf of
modules `V`. -/
theorem epi_pullbackExteriorPower : Epi (pullbackExteriorPower f V q) := by
  refine SheafOfModules.epi_of_isLocallySurjective (pullbackExteriorPower f V q) ?_
  constructor
  intro W t x hx
  -- the sheafification unit is locally surjective
  obtain ⟨W₁, g₁, hg₁, hxW₁⟩ := Presheaf.imageSieve_mem (Opens.grothendieckTopology ↥T)
    ((_root_.PresheafOfModules.toPresheaf _).map
      (Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q))
    (U := Opposite.op W)
    (show ToType (((_root_.PresheafOfModules.toPresheaf _).obj
      ((_root_.PresheafOfModules.restrictScalars (𝟙 T.ringCatSheaf.val)).obj
        (Scheme.Modules.exteriorPower
          ((Scheme.Modules.pullback f).obj V) q).val)).obj (Opposite.op W)) from t)
    x hx
  obtain ⟨w, hw⟩ := hg₁
  -- the presheaf element is locally in the image of the comparison
  obtain ⟨W₂, h₂, hxW₂, hmem⟩ :=
    exteriorPowerPresheaf_locally_mem_range f V q W₁ w x hxW₁
  refine ⟨W₂, homOfLE h₂ ≫ g₁, ?_, hxW₂⟩
  obtain ⟨z, hz⟩ := hmem
  refine ⟨z, ?_⟩
  -- transport the equality along the two restrictions
  have hunat := _root_.PresheafOfModules.naturality_apply
    (Scheme.Modules.toExteriorPower ((Scheme.Modules.pullback f).obj V) q)
    (homOfLE h₂).op w
  have hres := congrArg (ConcreteCategory.hom
    (((_root_.PresheafOfModules.toPresheaf _).obj
      ((_root_.PresheafOfModules.restrictScalars (𝟙 T.ringCatSheaf.val)).obj
        (Scheme.Modules.exteriorPower
          ((Scheme.Modules.pullback f).obj V) q).val)).map (homOfLE h₂).op)) hw
  have hsplit := _root_.PresheafOfModules.map_comp_apply
    (M := (_root_.PresheafOfModules.restrictScalars (𝟙 T.ringCatSheaf.val)).obj
      (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback f).obj V) q).val)
    g₁.op (homOfLE h₂).op
    (show ToType (((_root_.PresheafOfModules.toPresheaf _).obj
      ((_root_.PresheafOfModules.restrictScalars (𝟙 T.ringCatSheaf.val)).obj
        (Scheme.Modules.exteriorPower
          ((Scheme.Modules.pullback f).obj V) q).val)).obj (Opposite.op W)) from t)
  refine hz.trans ?_
  refine hunat.trans ?_
  refine Eq.trans ?_ hsplit.symm
  exact hres


/-- **Extensionality for morphisms out of the pullback of an exterior power**: two
morphisms agreeing on the unit sections of wedges are equal. -/
lemma hom_ext_of_unit_ιMulti {Z : T.Modules}
    (a b : (Scheme.Modules.pullback f).obj (Scheme.Modules.exteriorPower V q) ⟶ Z)
    (h : ∀ (U : S.Opens) (m : Fin q → Γ(V, U)),
      (a.app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
            (Scheme.Modules.exteriorPower V q)).app U)
            (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
              (exteriorPower.ιMulti Γ(S, U) q m))) =
        (b.app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
            (Scheme.Modules.exteriorPower V q)).app U)
            (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
              (exteriorPower.ιMulti Γ(S, U) q m)))) :
    a = b := by
  -- transpose: the two adjoint morphisms out of `⋀^q V` agree on unit wedges
  refine ((Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv
    (Scheme.Modules.exteriorPower V q) Z).injective ?_
  rw [Adjunction.homEquiv_unit, Adjunction.homEquiv_unit]
  refine Scheme.Modules.exteriorPower_hom_ext _ _ ?_
  intro U m
  exact h U m


set_option maxHeartbeats 3200000 in
-- the naturality square is checked on unit wedges through the compatibility lemmas
/-- **Naturality of the exterior-power pullback comparison in the sheaf variable.** -/
theorem pullbackExteriorPower_naturality {W : S.Modules} (φ : V ⟶ W) :
    pullbackExteriorPower f V q ≫
        Scheme.Modules.exteriorPowerMap ((Scheme.Modules.pullback f).map φ) q =
      (Scheme.Modules.pullback f).map (Scheme.Modules.exteriorPowerMap φ q) ≫
        pullbackExteriorPower f W q := by
  refine hom_ext_of_unit_ιMulti f V q _ _ ?_
  intro U m
  -- evaluate the left-hand side on a unit wedge
  have hLa : ((pullbackExteriorPower f V q ≫
        Scheme.Modules.exteriorPowerMap ((Scheme.Modules.pullback f).map φ) q).app
          (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
          (Scheme.Modules.exteriorPower V q)).app U)
          (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
            (exteriorPower.ιMulti Γ(S, U) q m))) =
      ((Scheme.Modules.exteriorPowerMap ((Scheme.Modules.pullback f).map φ) q).app
        (f ⁻¹ᵁ U))
        (((pullbackExteriorPower f V q).app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
            (Scheme.Modules.exteriorPower V q)).app U)
            (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
              (exteriorPower.ιMulti Γ(S, U) q m)))) := rfl
  have hLb := pullbackExteriorPower_app_unit f V q U (exteriorPower.ιMulti Γ(S, U) q m)
  have hLc := pullbackWedgeApp_ιMulti f V q U m
  have hLd := Scheme.Modules.exteriorPowerMap_app_unit_ιMulti
    ((Scheme.Modules.pullback f).map φ) q (f ⁻¹ᵁ U)
    (fun i ↦ show Γ((Scheme.Modules.pullback f).obj V, f ⁻¹ᵁ U) from
      (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) (m i))
  -- evaluate the right-hand side on the same unit wedge
  have hRa : (((Scheme.Modules.pullback f).map (Scheme.Modules.exteriorPowerMap φ q) ≫
        pullbackExteriorPower f W q).app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
          (Scheme.Modules.exteriorPower V q)).app U)
          (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
            (exteriorPower.ιMulti Γ(S, U) q m))) =
      ((pullbackExteriorPower f W q).app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullback f).map
          (Scheme.Modules.exteriorPowerMap φ q)).app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
            (Scheme.Modules.exteriorPower V q)).app U)
            (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
              (exteriorPower.ιMulti Γ(S, U) q m)))) := rfl
  -- the unit is natural in the sheaf: move it past `f^*(⋀^q φ)`
  have hunitnat := congrArg
    (fun (k : Scheme.Modules.exteriorPower V q ⟶
        (Scheme.Modules.pushforward f).obj
          ((Scheme.Modules.pullback f).obj (Scheme.Modules.exteriorPower W q))) ↦
      (k.app U) (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
        (exteriorPower.ιMulti Γ(S, U) q m)))
    ((Scheme.Modules.pullbackPushforwardAdjunction f).unit.naturality
      (Scheme.Modules.exteriorPowerMap φ q))
  -- the unit is natural for `φ` itself: this matches the entries of the two wedges
  have hunitφ : ∀ (i : Fin q),
      (((Scheme.Modules.pullback f).map φ).app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app V).app U) (m i)) =
        (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app W).app U)
          ((φ.app U) (m i)) := by
    intro i
    exact (congrArg
      (fun (k : V ⟶ (Scheme.Modules.pushforward f).obj
          ((Scheme.Modules.pullback f).obj W)) ↦ (k.app U) (m i))
      ((Scheme.Modules.pullbackPushforwardAdjunction f).unit.naturality φ)).symm
  -- the exterior-power functoriality on the base
  have hbase := Scheme.Modules.exteriorPowerMap_app_unit_ιMulti φ q U m
  have hRc := pullbackExteriorPower_app_unit f W q U
    (exteriorPower.ιMulti Γ(S, U) q (fun i ↦ show Γ(W, U) from (φ.app U) (m i)))
  have hRd := pullbackWedgeApp_ιMulti f W q U (fun i ↦ show Γ(W, U) from (φ.app U) (m i))
  -- assemble both sides in term mode (the spellings defeat `rw`)
  have hun : (((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
        (Scheme.Modules.exteriorPower W q)).app U)
        (((Scheme.Modules.exteriorPowerMap φ q).app U)
          (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
            (exteriorPower.ιMulti Γ(S, U) q m))) =
      (((Scheme.Modules.pullback f).map
        (Scheme.Modules.exteriorPowerMap φ q)).app (f ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
          (Scheme.Modules.exteriorPower V q)).app U)
          (((Scheme.Modules.toExteriorPower V q).app (Opposite.op U)).hom
            (exteriorPower.ιMulti Γ(S, U) q m))) := hunitnat
  refine hLa.trans (Eq.trans ?_ hRa.symm)
  have hL := (congrArg (fun y ↦
      ((Scheme.Modules.exteriorPowerMap ((Scheme.Modules.pullback f).map φ) q).app
        (f ⁻¹ᵁ U)) y) hLb).trans
    ((congrArg (fun y ↦
        ((Scheme.Modules.exteriorPowerMap ((Scheme.Modules.pullback f).map φ) q).app
          (f ⁻¹ᵁ U)) y) hLc).trans
      (hLd.trans (congrArg (ConcreteCategory.hom
        ((Scheme.Modules.toExteriorPower
          ((Scheme.Modules.pullback f).obj W) q).app (Opposite.op (f ⁻¹ᵁ U))))
        (congrArg (exteriorPower.ιMulti Γ(T, f ⁻¹ᵁ U) q) (funext hunitφ)))))
  have hR := (congrArg (fun y ↦
      ((pullbackExteriorPower f W q).app (f ⁻¹ᵁ U)) y) hun).symm.trans
    ((congrArg (fun y ↦
        ((pullbackExteriorPower f W q).app (f ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction f).unit.app
            (Scheme.Modules.exteriorPower W q)).app U) y)) hbase).trans
      (hRc.trans hRd))
  exact hL.trans hR.symm


section CompatibilityWithComposition

variable {X Y Z : Scheme.{u}} (a : X ⟶ Y) (b : Y ⟶ Z)

set_option maxHeartbeats 1600000 in
-- the mate identity for `pullbackComp` unfolds heavy functor composites
/-- **The pullback-adjunction units compose**: the unit for a composite morphism, followed
by the comparison of iterated pullbacks, is the composite of the two units. -/
lemma unit_app_comp (W : Z.Modules) (U : Z.Opens) (s : Γ(W, U)) :
    (((Scheme.Modules.pullbackComp a b).inv.app W).app ((a ≫ b) ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction (a ≫ b)).unit.app W).app U) s) =
      (((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
        ((Scheme.Modules.pullback b).obj W)).app (b ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction b).unit.app W).app U) s) := by
  have hconj := CategoryTheory.unit_conjugateEquiv
    ((Scheme.Modules.pullbackPushforwardAdjunction b).comp
      (Scheme.Modules.pullbackPushforwardAdjunction a))
    (Scheme.Modules.pullbackPushforwardAdjunction (a ≫ b))
    (Scheme.Modules.pullbackComp a b).inv W
  rw [Scheme.Modules.conjugateEquiv_pullbackComp_inv] at hconj
  -- evaluate the identity of morphisms of sheaves on `Z` at `U`, on `s`
  have hev := congrArg
    (fun (k : W ⟶ (Scheme.Modules.pushforward a ⋙
        Scheme.Modules.pushforward b).obj
        ((Scheme.Modules.pullback b ⋙ Scheme.Modules.pullback a).obj W)) ↦
      (k.app U) s) hconj
  exact hev.symm


set_option maxHeartbeats 3200000 in
-- the composite comparison is checked on unit wedges, one factor at a time
/-- **Compatibility of the exterior-power pullback comparison with composition.** -/
theorem pullbackExteriorPower_comp (W : Z.Modules) (q : ℕ) :
    pullbackExteriorPower (a ≫ b) W q =
      (Scheme.Modules.pullbackComp a b).inv.app (Scheme.Modules.exteriorPower W q) ≫
        (Scheme.Modules.pullback a).map (pullbackExteriorPower b W q) ≫
        pullbackExteriorPower a ((Scheme.Modules.pullback b).obj W) q ≫
        Scheme.Modules.exteriorPowerMap
          ((Scheme.Modules.pullbackComp a b).hom.app W) q := by
  refine hom_ext_of_unit_ιMulti (a ≫ b) W q _ _ ?_
  intro U m
  -- the left-hand side is the wedge of the composite unit sections
  have hL := (pullbackExteriorPower_app_unit (a ≫ b) W q U
    (exteriorPower.ιMulti Γ(Z, U) q m)).trans
    (pullbackWedgeApp_ιMulti (a ≫ b) W q U m)
  -- the right-hand side, factor by factor
  have h1 := unit_app_comp a b (Scheme.Modules.exteriorPower W q) U
    (((Scheme.Modules.toExteriorPower W q).app (Opposite.op U)).hom
      (exteriorPower.ιMulti Γ(Z, U) q m))
  have h2 : ∀ (z : Γ((Scheme.Modules.pullback b).obj
      (Scheme.Modules.exteriorPower W q), b ⁻¹ᵁ U)),
      (((Scheme.Modules.pullback a).map (pullbackExteriorPower b W q)).app
          (a ⁻¹ᵁ (b ⁻¹ᵁ U)))
        ((((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
          ((Scheme.Modules.pullback b).obj
            (Scheme.Modules.exteriorPower W q))).app (b ⁻¹ᵁ U)) z) =
        (((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
          (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback b).obj W) q)).app
            (b ⁻¹ᵁ U))
          (((pullbackExteriorPower b W q).app (b ⁻¹ᵁ U)) z) := by
    intro z
    exact (congrArg
      (fun (k : (Scheme.Modules.pullback b).obj (Scheme.Modules.exteriorPower W q) ⟶
          (Scheme.Modules.pushforward a).obj ((Scheme.Modules.pullback a).obj
            (Scheme.Modules.exteriorPower ((Scheme.Modules.pullback b).obj W) q))) ↦
        (k.app (b ⁻¹ᵁ U)) z)
      ((Scheme.Modules.pullbackPushforwardAdjunction a).unit.naturality
        (pullbackExteriorPower b W q))).symm
  have h3 := (pullbackExteriorPower_app_unit b W q U
    (exteriorPower.ιMulti Γ(Z, U) q m)).trans
    (pullbackWedgeApp_ιMulti b W q U m)
  have h4 := (pullbackExteriorPower_app_unit a ((Scheme.Modules.pullback b).obj W) q
    (b ⁻¹ᵁ U)
    (exteriorPower.ιMulti Γ(Y, b ⁻¹ᵁ U) q
      (fun i ↦ show Γ((Scheme.Modules.pullback b).obj W, b ⁻¹ᵁ U) from
        (((Scheme.Modules.pullbackPushforwardAdjunction b).unit.app W).app U) (m i)))).trans
    (pullbackWedgeApp_ιMulti a ((Scheme.Modules.pullback b).obj W) q (b ⁻¹ᵁ U)
      (fun i ↦ show Γ((Scheme.Modules.pullback b).obj W, b ⁻¹ᵁ U) from
        (((Scheme.Modules.pullbackPushforwardAdjunction b).unit.app W).app U) (m i)))
  have h5 := Scheme.Modules.exteriorPowerMap_app_unit_ιMulti
    ((Scheme.Modules.pullbackComp a b).hom.app W) q (a ⁻¹ᵁ (b ⁻¹ᵁ U))
    (fun i ↦ show Γ((Scheme.Modules.pullback a).obj
        ((Scheme.Modules.pullback b).obj W), a ⁻¹ᵁ (b ⁻¹ᵁ U)) from
      (((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
        ((Scheme.Modules.pullback b).obj W)).app (b ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction b).unit.app W).app U) (m i)))
  -- the comparison sends the iterated unit back to the composite unit
  have hback : ∀ (i : Fin q),
      (((Scheme.Modules.pullbackComp a b).hom.app W).app (a ⁻¹ᵁ (b ⁻¹ᵁ U)))
          ((((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
            ((Scheme.Modules.pullback b).obj W)).app (b ⁻¹ᵁ U))
            ((((Scheme.Modules.pullbackPushforwardAdjunction b).unit.app W).app U)
              (m i))) =
        (((Scheme.Modules.pullbackPushforwardAdjunction (a ≫ b)).unit.app W).app U)
          (m i) := by
    intro i
    have hcomp := unit_app_comp a b W U (m i)
    have happ := congrArg
      (fun y ↦ (((Scheme.Modules.pullbackComp a b).hom.app W).app
        ((a ≫ b) ⁻¹ᵁ U)) y) hcomp
    refine happ.symm.trans ?_
    exact congrArg
      (fun (k : (Scheme.Modules.pullback (a ≫ b)).obj W ⟶
          (Scheme.Modules.pullback (a ≫ b)).obj W) ↦
        (k.app ((a ≫ b) ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction (a ≫ b)).unit.app W).app U)
            (m i)))
      ((Scheme.Modules.pullbackComp a b).inv_hom_id_app W)
  -- assemble
  refine hL.trans ?_
  show _ =
    ((Scheme.Modules.exteriorPowerMap
        ((Scheme.Modules.pullbackComp a b).hom.app W) q).app (a ⁻¹ᵁ b ⁻¹ᵁ U))
      (((pullbackExteriorPower a ((Scheme.Modules.pullback b).obj W) q).app
          (a ⁻¹ᵁ b ⁻¹ᵁ U))
        ((((Scheme.Modules.pullback a).map (pullbackExteriorPower b W q)).app
            (a ⁻¹ᵁ b ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackComp a b).inv.app
              (Scheme.Modules.exteriorPower W q)).app (a ⁻¹ᵁ b ⁻¹ᵁ U))
            ((((Scheme.Modules.pullbackPushforwardAdjunction (a ≫ b)).unit.app
                (Scheme.Modules.exteriorPower W q)).app U)
              (((Scheme.Modules.toExteriorPower W q).app (Opposite.op U)).hom
                (exteriorPower.ιMulti Γ(Z, U) q m))))))
  have h1' : (((Scheme.Modules.pullbackComp a b).inv.app
        (Scheme.Modules.exteriorPower W q)).app (a ⁻¹ᵁ b ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction (a ≫ b)).unit.app
          (Scheme.Modules.exteriorPower W q)).app U)
          (((Scheme.Modules.toExteriorPower W q).app (Opposite.op U)).hom
            (exteriorPower.ιMulti Γ(Z, U) q m))) =
      (((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
        ((Scheme.Modules.pullback b).obj (Scheme.Modules.exteriorPower W q))).app
          (b ⁻¹ᵁ U))
        ((((Scheme.Modules.pullbackPushforwardAdjunction b).unit.app
          (Scheme.Modules.exteriorPower W q)).app U)
          (((Scheme.Modules.toExteriorPower W q).app (Opposite.op U)).hom
            (exteriorPower.ιMulti Γ(Z, U) q m))) := h1
  rw [h1', h2]
  -- the remaining steps go through `congrArg` (the spellings defeat `rw`)
  refine Eq.trans ?_ ((congrArg (fun y ↦
      ((Scheme.Modules.exteriorPowerMap
          ((Scheme.Modules.pullbackComp a b).hom.app W) q).app (a ⁻¹ᵁ b ⁻¹ᵁ U))
        (((pullbackExteriorPower a ((Scheme.Modules.pullback b).obj W) q).app
            (a ⁻¹ᵁ b ⁻¹ᵁ U))
          ((((Scheme.Modules.pullbackPushforwardAdjunction a).unit.app
              (Scheme.Modules.exteriorPower
                ((Scheme.Modules.pullback b).obj W) q)).app (b ⁻¹ᵁ U)) y))) h3).symm)
  refine Eq.trans ?_ ((congrArg (fun y ↦
      ((Scheme.Modules.exteriorPowerMap
          ((Scheme.Modules.pullbackComp a b).hom.app W) q).app
            (a ⁻¹ᵁ b ⁻¹ᵁ U)) y) h4).symm)
  refine Eq.trans ?_ h5.symm
  exact congrArg (ConcreteCategory.hom
    ((Scheme.Modules.toExteriorPower
      ((Scheme.Modules.pullback (a ≫ b)).obj W) q).app
        (Opposite.op (a ⁻¹ᵁ b ⁻¹ᵁ U))))
    (congrArg (exteriorPower.ιMulti Γ(X, a ⁻¹ᵁ b ⁻¹ᵁ U) q) (funext hback)).symm


/-- The exterior-power pullback comparison transports along an equality of morphisms. -/
lemma pullbackExteriorPower_congr {X Y : Scheme.{u}} {c d : X ⟶ Y} (h : c = d)
    (W : Y.Modules) (q : ℕ) :
    pullbackExteriorPower d W q =
      (Scheme.Modules.pullbackCongr h).inv.app (Scheme.Modules.exteriorPower W q) ≫
        pullbackExteriorPower c W q ≫
        Scheme.Modules.exteriorPowerMap
          ((Scheme.Modules.pullbackCongr h).hom.app W) q := by
  subst h
  have hcongr : Scheme.Modules.pullbackCongr (rfl : c = c) = Iso.refl _ := rfl
  rw [hcongr]
  rw [show (Iso.refl (Scheme.Modules.pullback c)).inv.app
      (Scheme.Modules.exteriorPower W q) = 𝟙 _ from rfl,
    show (Iso.refl (Scheme.Modules.pullback c)).hom.app W = 𝟙 _ from rfl,
    Scheme.Modules.exteriorPowerMap_id, Category.comp_id, Category.id_comp]


end CompatibilityWithComposition


end PullbackExteriorPowerEpi

end AlgebraicGeometry

end
