module

public import StacksAndModuli.API.RelativeFibreRegularSequenceLocusOver

/-!
# Relative regular-sequence loci over a field

For a finite-type algebra over a ring with nonempty subsingleton prime spectrum, the
fixed-fibre openness theorem for regular sequences is already an ambient openness theorem:
its only set-theoretic fibre is the whole source spectrum.  In particular this applies over
a field.

This file constructs the required homeomorphism on the zero locus of a finite sequence and
uses it to prove openness of the relative regular-sequence predicate in the exact subtype
form consumed by the determinantal grade-locus API.

Main declarations:

* `Matrix.FiniteFreeComplex.zeroLocus_homeomorph_fixedFibreZeroLocus_of_subsingleton`;
* `Matrix.FiniteFreeComplex.isOpen_relativeFibreRegularSequenceOnZeroLocus_of_subsingleton`;
* `Matrix.FiniteFreeComplex.isOpen_relativeFibreRegularSequenceOnZeroLocus_of_isField`;
* `Matrix.FiniteFreeComplex.isOpen_relativeFibreBuchsbaumEisenbudLocus_of_subsingleton`;
* `Matrix.FiniteFreeComplex.isOpen_relativeFibreBuchsbaumEisenbudLocus_of_isField`.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

noncomputable section

universe u

namespace Matrix.FiniteFreeComplex

variable {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]

/-- If the base has subsingleton prime spectrum, the zero locus of a sequence is
homeomorphic to that zero locus inside its unique set-theoretic fibre. -/
def zeroLocus_homeomorph_fixedFibreZeroLocus_of_subsingleton
    [Subsingleton (PrimeSpectrum R)] (p : PrimeSpectrum R) (rs : List S) :
    PrimeSpectrum.zeroLocus (Ideal.ofList rs : Set S) ≃ₜ
      Ideal.Fiber.fixedFibreZeroLocus p rs where
  toFun q := ⟨⟨q.1, Subsingleton.elim _ p⟩, q.2⟩
  invFun q := ⟨q.1.1, q.2⟩
  left_inv q := rfl
  right_inv q := by
    ext
    rfl
  continuous_toFun := by
    apply Continuous.subtype_mk
    apply Continuous.subtype_mk
    exact continuous_subtype_val
  continuous_invFun := by
    apply Continuous.subtype_mk
    exact continuous_subtype_val.comp continuous_subtype_val

/-- The zero locus of a finite family agrees with the zero locus of the ideal generated by
its `List.ofFn` enumeration. -/
theorem zeroLocus_range_eq_zeroLocus_ofList {d : ℕ} (f : Fin d → S) :
    PrimeSpectrum.zeroLocus (Set.range f) =
      PrimeSpectrum.zeroLocus (Ideal.ofList (List.ofFn f) : Set S) := by
  have hrange : Set.range f = {x | x ∈ List.ofFn f} := by
    ext x
    simp
  rw [hrange]
  exact (PrimeSpectrum.zeroLocus_span (R := S) _).symm

/-- If the base has subsingleton prime spectrum, the zero locus of a finite family is
homeomorphic to the corresponding zero locus inside its unique set-theoretic fibre. -/
noncomputable def zeroLocus_range_homeomorph_fixedFibreZeroLocus_of_subsingleton
    [Subsingleton (PrimeSpectrum R)]
    {d : ℕ} (p : PrimeSpectrum R) (f : Fin d → S) :
    PrimeSpectrum.zeroLocus (Set.range f) ≃ₜ
      Ideal.Fiber.fixedFibreZeroLocus p (List.ofFn f) :=
  (Homeomorph.setCongr
    (zeroLocus_range_eq_zeroLocus_ofList f)).trans
      (zeroLocus_homeomorph_fixedFibreZeroLocus_of_subsingleton p (List.ofFn f))

/-- For a finite-type algebra over a base with subsingleton prime spectrum, the relative
regular-sequence predicate is open on the zero locus of every fixed finite sequence. -/
theorem isOpen_relativeFibreRegularSequenceOnZeroLocus_of_subsingleton
    [Subsingleton (PrimeSpectrum R)] [Algebra.FiniteType R S]
    {d : ℕ} (p : PrimeSpectrum R) (f : Fin d → S) :
    IsOpen {q : PrimeSpectrum.zeroLocus (Set.range f) |
      IsRelativeFibreRegularSequenceAt (R := R) q.1 f} := by
  let e := zeroLocus_range_homeomorph_fixedFibreZeroLocus_of_subsingleton p f
  have hset :
      {q : PrimeSpectrum.zeroLocus (Set.range f) |
        IsRelativeFibreRegularSequenceAt (R := R) q.1 f} =
      e ⁻¹' relativeFibreRegularSequenceLocusOver (R := R) p f := by
    ext q
    change IsRelativeFibreRegularSequenceAt (R := R) q.1 f ↔
      IsRelativeFibreRegularSequenceAt (R := R) (e q).1.1 f
    simp [e, zeroLocus_range_homeomorph_fixedFibreZeroLocus_of_subsingleton,
      zeroLocus_homeomorph_fixedFibreZeroLocus_of_subsingleton, Homeomorph.setCongr]
  rw [hset]
  exact (isOpen_relativeFibreRegularSequenceLocusOver p f).preimage e.continuous

/-- For a finite-type algebra over a field, the relative regular-sequence predicate is open
on the zero locus of every fixed finite sequence. -/
theorem isOpen_relativeFibreRegularSequenceOnZeroLocus_of_isField
    {K : Type u} [Field K] [Algebra K S] [Algebra.FiniteType K S]
    {d : ℕ} (f : Fin d → S) :
    IsOpen {q : PrimeSpectrum.zeroLocus (Set.range f) |
      IsRelativeFibreRegularSequenceAt (R := K) q.1 f} := by
  let p : PrimeSpectrum K := ⟨⊥, Ideal.isPrime_bot⟩
  exact isOpen_relativeFibreRegularSequenceOnZeroLocus_of_subsingleton p f

/-- For a finite-type algebra over a base with subsingleton prime spectrum, the simultaneous
expected-minor grade locus of a bounded finite free complex is open. -/
theorem isOpen_relativeFibreBuchsbaumEisenbudLocus_of_subsingleton
    [Subsingleton (PrimeSpectrum R)] [Algebra.FiniteType R S]
    (p : PrimeSpectrum R)
    (C : FiniteFreeComplex S) {N : ℕ} (r : C.ExpectedRanks N) :
    IsOpen (relativeFibreBuchsbaumEisenbudLocus (R := R) C r) := by
  apply C.isOpen_relativeFibreBuchsbaumEisenbudLocus r
  intro i hi f hf
  exact isOpen_relativeFibreRegularSequenceOnZeroLocus_of_subsingleton p f

/-- For a finite-type algebra over a field, the simultaneous expected-minor grade locus of
a bounded finite free complex is open. -/
theorem isOpen_relativeFibreBuchsbaumEisenbudLocus_of_isField
    {K : Type u} [Field K] [Algebra K S] [Algebra.FiniteType K S]
    (C : FiniteFreeComplex S) {N : ℕ} (r : C.ExpectedRanks N) :
    IsOpen (relativeFibreBuchsbaumEisenbudLocus (R := K) C r) := by
  let p : PrimeSpectrum K := ⟨⊥, Ideal.isPrime_bot⟩
  exact isOpen_relativeFibreBuchsbaumEisenbudLocus_of_subsingleton p C r

end Matrix.FiniteFreeComplex

end
