module

public import StacksAndModuli.API.RelativeFibreRegularSequenceClosedPointDimension

/-!
# Quotient dimension at a closed relative-fibre point

Let `q` be a prime of a finite-type `R`-algebra `S`, closed in its residue fibre, and let
`I` be generated by a finite list contained in `q`.  The relative dimension of `S / I` at
the point induced by `q` is the Krull dimension of the quotient of the local fibre ring at
`q` by the image of that list.

This is the dimension-comparison bridge used in the converse direction of the
regular-sequence dimension criterion.  It does not assume that the sequence is regular.

Main declaration:

* `Algebra.relativeKrullDimAt_quotient_eq_ringKrullDim_localizedFibreQuotient_of_closedFibrePoint`.
-/

@[expose] public section

noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

universe u v

open TensorProduct

namespace Algebra

/-- At a point closed in its residue fibre, the relative dimension after quotienting by a
finite list is the dimension of the corresponding quotient of the local fibre ring. -/
theorem
    relativeKrullDimAt_quotient_eq_ringKrullDim_localizedFibreQuotient_of_closedFibrePoint
    {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.FiniteType R S]
    (q : PrimeSpectrum S) (rs : List S)
    (hmem : ∀ x ∈ rs, x ∈ q.asIdeal)
    (hclosed :
      (PrimeSpectrum.relativeFibrePrime (R := R) q).asIdeal.IsMaximal) :
    let I := Ideal.ofList rs
    let hIq : I ≤ q.asIdeal := Ideal.span_le.mpr hmem
    let qbar := PrimeSpectrum.quotientOfLE I q hIq
    let p := q.comap (algebraMap R S)
    let T := p.asIdeal.Fiber S
    let qF := PrimeSpectrum.relativeFibrePrime (R := R) q
    let rsF := rs.map
      (Algebra.TensorProduct.includeRight : S →ₐ[R] T)
    let L := Localization.AtPrime qF.asIdeal
    let commRingL : CommRing L := inferInstance
    letI : CommRing L := commRingL
    letI : CommSemiring L := commRingL.toCommSemiring
    letI : Semiring L := commRingL.toCommSemiring.toSemiring
    let rsL := rsF.map (algebraMap T L)
    Algebra.relativeKrullDimAt R (S ⧸ I) qbar =
      ringKrullDim (L ⧸ Ideal.ofList rsL) := by
  let I : Ideal S := Ideal.ofList rs
  have hIq : I ≤ q.asIdeal := Ideal.span_le.mpr hmem
  let qbar : PrimeSpectrum (S ⧸ I) :=
    PrimeSpectrum.quotientOfLE I q hIq
  let p : PrimeSpectrum R := q.comap (algebraMap R S)
  let K := p.asIdeal.ResidueField
  let T := p.asIdeal.Fiber S
  let qF : PrimeSpectrum T :=
    PrimeSpectrum.relativeFibrePrime (R := R) q
  let rsF : List T :=
    rs.map (Algebra.TensorProduct.includeRight : S →ₐ[R] T)
  let IF : Ideal T := Ideal.ofList rsF
  have hrsF_mem : ∀ x ∈ rsF, x ∈ qF.asIdeal := by
    intro x hx
    obtain ⟨s, hs, rfl⟩ := List.mem_map.mp hx
    change s ∈ qF.asIdeal.comap
      (Algebra.TensorProduct.includeRight : S →ₐ[R] T).toRingHom
    rw [PrimeSpectrum.relativeFibrePrime_comap_includeRight (R := R) q]
    exact hmem s hs
  have hIFq : IF ≤ qF.asIdeal := Ideal.span_le.mpr hrsF_mem
  let qFbar : PrimeSpectrum (T ⧸ IF) :=
    PrimeSpectrum.quotientOfLE IF qF hIFq
  have hp : qbar.comap (algebraMap R (S ⧸ I)) = p := by
    calc
      qbar.comap (algebraMap R (S ⧸ I)) =
          qbar.comap
            ((Ideal.Quotient.mk I).comp (algebraMap R S)) := rfl
      _ = (qbar.comap (Ideal.Quotient.mk I)).comap
            (algebraMap R S) := rfl
      _ = q.comap (algebraMap R S) := by
        rw [PrimeSpectrum.comap_quotientOfLE]
      _ = p := rfl
  let U := p.asIdeal.Fiber (S ⧸ I)
  let e : U ≃ₐ[K] T ⧸ IF := by
    exact Ideal.Fiber.quotientOfListAlgEquiv p.asIdeal rs
  let xbar : PrimeSpectrum U :=
    PrimeSpectrum.comap e.toRingEquiv.toRingHom qFbar
  have hxbar_comap :
      xbar.asIdeal.comap
          (Algebra.TensorProduct.includeRight : (S ⧸ I) →ₐ[R] U).toRingHom =
        qbar.asIdeal := by
    ext sbar
    obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective sbar
    change e
        (Algebra.TensorProduct.includeRight
          (Ideal.Quotient.mk I s)) ∈ qFbar.asIdeal ↔
      Ideal.Quotient.mk I s ∈ qbar.asIdeal
    rw [show e
        (Algebra.TensorProduct.includeRight
          (Ideal.Quotient.mk I s)) =
          Ideal.Quotient.mk IF
            (Algebra.TensorProduct.includeRight s) by
      exact Ideal.Fiber.quotientOfListAlgEquiv_includeRight_mk
        p.asIdeal rs s]
    calc
      Ideal.Quotient.mk IF
            (Algebra.TensorProduct.includeRight s) ∈ qFbar.asIdeal ↔
          Algebra.TensorProduct.includeRight s ∈ qF.asIdeal := by
        rw [← Ideal.mem_comap]
        exact iff_of_eq <| congrArg
          (Algebra.TensorProduct.includeRight s ∈ ·)
          (Ideal.comap_map_mk (I := IF) (J := qF.asIdeal) hIFq)
      _ ↔ s ∈ q.asIdeal := by
        change s ∈
          (PrimeSpectrum.relativeFibrePrime (R := R) q).asIdeal.comap
              (Algebra.TensorProduct.includeRight : S →ₐ[R] T).toRingHom ↔
            s ∈ q.asIdeal
        rw [PrimeSpectrum.relativeFibrePrime_comap_includeRight (R := R) q]
      _ ↔ Ideal.Quotient.mk I s ∈ qbar.asIdeal := by
        rw [← Ideal.mem_comap]
        exact (iff_of_eq <| congrArg (s ∈ ·)
          (Ideal.comap_map_mk (I := I) (J := q.asIdeal) hIq)).symm
  let E := PrimeSpectrum.preimageEquivFiber R (S ⧸ I) p
  let qbarF : PrimeSpectrum U := E ⟨qbar, hp⟩
  have hxbar_eq : xbar = qbarF := by
    apply E.symm.injective
    calc
      E.symm xbar = ⟨qbar, hp⟩ := by
        apply Subtype.ext
        exact PrimeSpectrum.ext hxbar_comap
      _ = E.symm qbarF := (E.symm_apply_apply ⟨qbar, hp⟩).symm
  let eSpec : PrimeSpectrum U ≃ₜ PrimeSpectrum (T ⧸ IF) :=
    PrimeSpectrum.homeomorphOfRingEquiv e.toRingEquiv
  have heSpec : eSpec xbar = qFbar := by
    change eSpec (eSpec.symm qFbar) = qFbar
    exact eSpec.apply_symm_apply qFbar
  have hpoint :
      topologicalKrullDimAtPoint (PrimeSpectrum U) qbarF =
        topologicalKrullDimAtPoint (PrimeSpectrum (T ⧸ IF)) qFbar := by
    rw [← hxbar_eq, ← heSpec]
    exact eSpec.isOpenEmbedding.topologicalKrullDimAtPoint_eq xbar
  letI : qF.asIdeal.IsMaximal := hclosed
  letI : qFbar.asIdeal.IsMaximal := by
    dsimp only [qFbar, PrimeSpectrum.quotientOfLE,
      PrimeSpectrum.asIdeal]
    exact Ideal.IsMaximal.map_of_surjective_of_ker_le
      Ideal.Quotient.mk_surjective
      (by simpa only [IF, Ideal.mk_ker] using hIFq)
  letI : Nontrivial (T ⧸ IF) := qFbar.nontrivial
  have hclosedDimension :
      topologicalKrullDimAtPoint (PrimeSpectrum (T ⧸ IF)) qFbar =
        ringKrullDim (Localization.AtPrime qFbar.asIdeal) := by
    exact PrimeSpectrum.topologicalKrullDimAtPoint_eq_ringKrullDim_localizationAtPrime
      K (T ⧸ IF) qFbar
  letI : qFbar.asIdeal.LiesOver qF.asIdeal := ⟨by
    dsimp only [qFbar, PrimeSpectrum.quotientOfLE,
      PrimeSpectrum.asIdeal]
    exact (Ideal.comap_map_mk
      (I := IF) (J := qF.asIdeal) hIFq).symm⟩
  let L := Localization.AtPrime qF.asIdeal
  let commRingL : CommRing L := inferInstance
  letI : CommRing L := commRingL
  letI : CommSemiring L := commRingL.toCommSemiring
  letI : Semiring L := commRingL.toCommSemiring.toSemiring
  let rsL : List L := rsF.map (algebraMap T L)
  let eLoc := Ideal.localizationAtPrimeQuotientEquiv
    IF qF.asIdeal qFbar.asIdeal
  have hmap : IF.map (algebraMap T L) = Ideal.ofList rsL := by
    exact Ideal.map_ofList (algebraMap T L) rsF
  change Algebra.relativeKrullDimAt R (S ⧸ I) qbar =
    ringKrullDim (L ⧸ Ideal.ofList rsL)
  rw [relativeKrullDimAt_eq_topologicalKrullDimAtPoint_fibre_of_comap_eq
      qbar p hp,
    hpoint,
    hclosedDimension,
    ringKrullDim_eq_of_ringEquiv eLoc.toRingEquiv,
    hmap]

end Algebra

end

end
