module

public import StacksAndModuli.API.SmoothStalkReduced
public import StacksAndModuli.API.StalkKrullDimension
public import StacksAndModuli.«Section6.1-Smooth».«part6.1.1-curves»
public import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
public import Mathlib.AlgebraicGeometry.ResidueField
public import Mathlib.LinearAlgebra.Dimension.FreeAndStrongRankCondition
public import Mathlib.RingTheory.DiscreteValuationRing.TFAE

/-!
# Rational points on smooth curves

A rational section of a curve over a field determines a closed point of residue
degree one.  If the curve is smooth and integral, its local ring at this point is a
discrete valuation ring, so the maximal ideal has a uniformizer.

This is the point-local divisor input in the pointed genus-zero classification.  It
proves that a rational point is closed of residue degree one and that its maximal
ideal in the stalk is generated by a regular uniformizer.  Constructing the global
invertible ideal sheaf, its dual, its complete linear system, and the resulting
morphism to the projective line remains a separate Riemann--Roch step.

## Main results

* `AlgebraicGeometry.Scheme.isClosed_singleton_map_closedPoint_of_section`;
* `AlgebraicGeometry.Scheme.ker_stalkMap_closedPoint_eq_maximalIdeal_of_section`;
* `AlgebraicGeometry.Scheme.residueDegree_map_closedPoint_eq_one_of_section`;
* `AlgebraicGeometry.Scheme.isDiscreteValuationRing_stalk_of_smooth_curve_of_isClosed`;
* `AlgebraicGeometry.Scheme.exists_uniformizer_stalk_map_closedPoint_of_section`;
* `AlgebraicGeometry.Scheme.exists_regular_generator_ker_stalkMap_closedPoint_of_section`;
* `AlgebraicGeometry.Scheme.exists_closed_residueDegree_one_dvr_point_of_section`.
-/

@[expose] public section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false

open CategoryTheory TopologicalSpace

universe u

namespace AlgebraicGeometry.Scheme

attribute [local instance] specializationOrder

/-- The image of the closed point under a section of a scheme over a field is a
closed point. -/
theorem isClosed_singleton_map_closedPoint_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    IsClosed ({s (IsLocalRing.closedPoint k)} : Set C) := by
  have hsOver : s.IsOver (Spec (CommRingCat.of k)) := by
    rw [Hom.isOver_iff]
    simpa using hs
  let _ : s.IsOver (Spec (CommRingCat.of k)) := hsOver
  let _ : IsClosedImmersion s := inferInstance
  have hrange : Set.range s = {s (IsLocalRing.closedPoint k)} := by
    ext y
    constructor
    · rintro ⟨z, rfl⟩
      simp only [Set.mem_singleton_iff]
      exact congrArg s (Subsingleton.elim z (IsLocalRing.closedPoint k))
    · intro hy
      rw [Set.mem_singleton_iff] at hy
      exact ⟨IsLocalRing.closedPoint k, hy.symm⟩
  rw [← hrange]
  exact s.isClosedEmbedding.isClosed_range

/-- The kernel of the map on stalks induced by a rational section is the maximal
ideal at the image point. -/
theorem ker_stalkMap_closedPoint_eq_maximalIdeal_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    RingHom.ker (s.stalkMap (IsLocalRing.closedPoint k)).hom =
      IsLocalRing.maximalIdeal
        (C.presheaf.stalk (s (IsLocalRing.closedPoint k))) := by
  have hsOver : s.IsOver (Spec (CommRingCat.of k)) := by
    rw [Hom.isOver_iff]
    simpa using hs
  let _ : s.IsOver (Spec (CommRingCat.of k)) := hsOver
  let _ : IsClosedImmersion s := inferInstance
  let _ : Field
      ((Spec (CommRingCat.of k)).presheaf.stalk
        (IsLocalRing.closedPoint k)) :=
    ((stalkClosedPointIso (CommRingCat.of k)).commRingCatIsoToRingEquiv.isField
      (Field.toIsField k)).toField
  exact IsLocalRing.ker_eq_maximalIdeal _
    (s.stalkMap_surjective (IsLocalRing.closedPoint k))

/-- At a rational section, the structure morphism induces an isomorphism on residue
fields. -/
theorem isIso_residueFieldMap_map_closedPoint_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    IsIso ((C ↘ Spec (CommRingCat.of k)).residueFieldMap
      (s (IsLocalRing.closedPoint k))) := by
  let p := C ↘ Spec (CommRingCat.of k)
  let z := IsLocalRing.closedPoint k
  let x := s z
  let _ : IsIso ((s ≫ p).residueFieldMap z) := by
    rw [Hom.residueFieldMap_congr hs z]
    infer_instance
  let _ : IsIso (p.residueFieldMap x ≫ s.residueFieldMap z) := by
    rw [← residueFieldMap_comp]
    infer_instance
  have hsSurjective : Function.Surjective (s.residueFieldMap z) :=
    Function.Surjective.of_comp
      (ConcreteCategory.bijective_of_isIso
        (p.residueFieldMap x ≫ s.residueFieldMap z)).2
  let _ : IsIso (s.residueFieldMap z) :=
    (ConcreteCategory.isIso_iff_bijective _).mpr
      ⟨RingHom.injective _, hsSurjective⟩
  exact IsIso.of_isIso_comp_right (p.residueFieldMap x)
    (s.residueFieldMap z)

/-- The image of a rational section has residue degree one over the ground field. -/
theorem residueDegree_map_closedPoint_eq_one_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    (C ↘ Spec (CommRingCat.of k)).residueDegree
      (s (IsLocalRing.closedPoint k)) = 1 := by
  let p := C ↘ Spec (CommRingCat.of k)
  let x := s (IsLocalRing.closedPoint k)
  let _ : IsIso (p.residueFieldMap x) :=
    isIso_residueFieldMap_map_closedPoint_of_section C s hs
  let _ := (p.residueFieldMap x).hom.toAlgebra
  change Module.finrank _ _ = 1
  rw [Algebra.finrank_eq_one_iff_bijective_algebraMap]
  simpa only [RingHom.algebraMap_toAlgebra] using
    ConcreteCategory.bijective_of_isIso (p.residueFieldMap x)

/-- A closed point on an integral curve has coheight one. -/
theorem coheight_eq_one_of_isCurveOver_of_isIntegral_of_isClosed
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] [IsCurveOver k C] [IsIntegral C]
    (x : C) (hx : IsClosed ({x} : Set C)) : Order.coheight x = 1 := by
  have hle' := C.ringKrullDim_stalk_le_topologicalKrullDim x
  rw [ringKrullDim_stalk_eq_coheight,
    IsCurveOver.topologicalKrullDim_eq (k := k) (C := C)] at hle'
  have hle : Order.coheight x ≤ 1 := by
    exact_mod_cast hle'
  have hpos : 0 < Order.coheight x := by
    rw [Order.coheight_pos]
    intro hmax
    have hxtop : x = genericPoint C :=
      hmax.eq_of_le (le_top : x ≤ genericPoint C)
    have huniv : ({x} : Set C) = Set.univ := by
      calc
        ({x} : Set C) = closure ({x} : Set C) := hx.closure_eq.symm
        _ = Set.univ := by
          rw [hxtop]
          exact genericPoint_closure C
    have hsub : Subsingleton C := ⟨fun a b ↦ by
      have ha : a ∈ ({x} : Set C) := huniv.symm.subset (Set.mem_univ a)
      have hb : b ∈ ({x} : Set C) := huniv.symm.subset (Set.mem_univ b)
      simpa only [Set.mem_singleton_iff] using ha.trans hb.symm⟩
    let _ : Subsingleton C := hsub
    let _ : DiscreteTopology C := ⟨Subsingleton.elim _ _⟩
    have hdim := topologicalKrullDim_zero_of_discreteTopology C
    rw [IsCurveOver.topologicalKrullDim_eq (k := k) (C := C)] at hdim
    norm_num at hdim
  exact le_antisymm hle (Order.one_le_iff_pos.mpr hpos)

/-- The local ring at a closed point of a smooth integral curve is a discrete
valuation ring. -/
theorem isDiscreteValuationRing_stalk_of_smooth_curve_of_isClosed
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] [IsCurveOver k C]
    [Smooth (C ↘ Spec (CommRingCat.of k))] [IsIntegral C]
    (x : C) (hx : IsClosed ({x} : Set C)) :
    IsDiscreteValuationRing (C.presheaf.stalk x) := by
  let _ : IsLocallyNoetherian C :=
    LocallyOfFiniteType.isLocallyNoetherian (C ↘ Spec (CommRingCat.of k))
  let _ : IsRegularLocalRing (C.presheaf.stalk x) :=
    isRegularLocalRing_stalk_of_formallySmooth_toSpec_field
      (C ↘ Spec (CommRingCat.of k)) x (by
        rw [← Scheme.Hom.mem_smoothLocus,
          (C ↘ Spec (CommRingCat.of k)).smoothLocus_eq_top]
        exact Set.mem_univ x)
  let _ : IsDomain (C.presheaf.stalk x) := IsRegularLocalRing.isDomain
  have hdim : ringKrullDim (C.presheaf.stalk x) = 1 := by
    rw [ringKrullDim_stalk_eq_coheight,
      coheight_eq_one_of_isCurveOver_of_isIntegral_of_isClosed
        (k := k) (C := C) x hx]
    norm_num
  have hregular :
      (Module.finrank (IsLocalRing.ResidueField (C.presheaf.stalk x))
        (IsLocalRing.CotangentSpace (C.presheaf.stalk x)) : WithBot ℕ∞) =
          ringKrullDim (C.presheaf.stalk x) :=
    (IsRegularLocalRing.iff_finrank_cotangentSpace
      (C.presheaf.stalk x)).mp inferInstance
  have hfinrank : Module.finrank (IsLocalRing.ResidueField (C.presheaf.stalk x))
      (IsLocalRing.CotangentSpace (C.presheaf.stalk x)) = 1 := by
    exact_mod_cast hregular.trans hdim
  exact IsLocalRing.finrank_CotangentSpace_eq_one_iff.mp hfinrank

/-- The local ring at the image of a rational section of a smooth integral curve is a
discrete valuation ring. -/
theorem isDiscreteValuationRing_stalk_map_closedPoint_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] [IsCurveOver k C]
    [Smooth (C ↘ Spec (CommRingCat.of k))] [IsIntegral C]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    IsDiscreteValuationRing
      (C.presheaf.stalk (s (IsLocalRing.closedPoint k))) := by
  apply isDiscreteValuationRing_stalk_of_smooth_curve_of_isClosed
    (k := k) C
  exact isClosed_singleton_map_closedPoint_of_section C s hs

/-- A rational point on a smooth integral curve has a local uniformizer generating
the maximal ideal. -/
theorem exists_uniformizer_stalk_map_closedPoint_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] [IsCurveOver k C]
    [Smooth (C ↘ Spec (CommRingCat.of k))] [IsIntegral C]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    ∃ ϖ : C.presheaf.stalk (s (IsLocalRing.closedPoint k)),
      Irreducible ϖ ∧ IsRegular ϖ ∧
        IsLocalRing.maximalIdeal
            (C.presheaf.stalk (s (IsLocalRing.closedPoint k))) =
          Ideal.span {ϖ} := by
  let _ : IsDiscreteValuationRing
      (C.presheaf.stalk (s (IsLocalRing.closedPoint k))) :=
    isDiscreteValuationRing_stalk_map_closedPoint_of_section C s hs
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible
    (C.presheaf.stalk (s (IsLocalRing.closedPoint k)))
  exact ⟨ϖ, hϖ, isRegular_iff_ne_zero'.mpr hϖ.ne_zero, hϖ.maximalIdeal_eq⟩

/-- The closed immersion defined by a rational point on a smooth integral curve has
a stalk kernel generated by a regular uniformizer at that point. -/
theorem exists_regular_generator_ker_stalkMap_closedPoint_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] [IsCurveOver k C]
    [Smooth (C ↘ Spec (CommRingCat.of k))] [IsIntegral C]
    (s : Spec (CommRingCat.of k) ⟶ C)
    (hs : s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    ∃ ϖ : C.presheaf.stalk (s (IsLocalRing.closedPoint k)),
      Irreducible ϖ ∧ IsRegular ϖ ∧
        RingHom.ker (s.stalkMap (IsLocalRing.closedPoint k)).hom =
          Ideal.span {ϖ} := by
  obtain ⟨ϖ, hϖ, hreg, hspan⟩ :=
    exists_uniformizer_stalk_map_closedPoint_of_section C s hs
  exact ⟨ϖ, hϖ, hreg,
    (ker_stalkMap_closedPoint_eq_maximalIdeal_of_section C s hs).trans hspan⟩

/-- A rational section of a smooth integral curve supplies a closed point of residue
degree one whose local ring is a DVR. -/
theorem exists_closed_residueDegree_one_dvr_point_of_section
    {k : Type u} [Field k] (C : Scheme.{u})
    [C.Over (Spec (CommRingCat.of k))] [IsCurveOver k C]
    [Smooth (C ↘ Spec (CommRingCat.of k))] [IsIntegral C]
    (hpoint : ∃ s : Spec (CommRingCat.of k) ⟶ C,
      s ≫ (C ↘ Spec (CommRingCat.of k)) = 𝟙 _) :
    ∃ x : C, IsClosed ({x} : Set C) ∧
      (C ↘ Spec (CommRingCat.of k)).residueDegree x = 1 ∧
      IsDiscreteValuationRing (C.presheaf.stalk x) := by
  obtain ⟨s, hs⟩ := hpoint
  exact ⟨s (IsLocalRing.closedPoint k),
    isClosed_singleton_map_closedPoint_of_section C s hs,
    residueDegree_map_closedPoint_eq_one_of_section C s hs,
    isDiscreteValuationRing_stalk_map_closedPoint_of_section C s hs⟩

end AlgebraicGeometry.Scheme

end
