module

public import StacksAndModuli.API.ProjGammaStarQuotientChart
public import StacksAndModuli.API.ProjGammaStarKernelVanishing
public import StacksAndModuli.API.ProjGammaStarBaseChange
public import StacksAndModuli.API.ProjectiveGradedCechBaseChange
public import StacksAndModuli.API.ProjectiveSpaceTwistSurjectivityAffine
public import StacksAndModuli.API.ProjTwistModuleQuasicoherentOfQuasicoherent

/-!
# Fixed-degree Quot cohomology over arbitrary bases

The Quot-to-Grassmannian construction must be compatible with pullback to an arbitrary
test scheme, even though the uniform regularity argument itself is proved over noetherian
rings.  The bridge is fibrewise: after base change to a field, the kernel-quotient graded
model can be compared with the pulled-back quotient without imposing any noetherian
hypothesis on the original base ring.

This file removes the spurious noetherian hypothesis from the all-degree local comparison.
The subsequent fixed-degree finite-projectivity argument applies regularity only over the
residue fields, where noetherianity is automatic.
-/

@[expose] public section

noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option maxSynthPendingDepth 10
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits Opposite
open AlgebraicGeometry ProjectiveSpectrum.Twist

namespace AlgebraicGeometry.ProjectiveSpace

attribute [local instance] MvPolynomial.gradedAlgebra

/-! ## Finite graded pieces without a noetherian base -/

/-- The kernel-route model of a twisted-free quotient is finitely generated over an
arbitrary coefficient ring.  Only the target of the defining cokernel matters: it is
`Gamma_*` of the fixed finite twisted-free ambient sheaf, hence a finite direct sum of
shifts of the polynomial structure module. -/
theorem isFG_kernelQuotientModule_twistedFree_arbitrary
    (n r : ℕ) (hn : 0 < n) (l : ℤ) (R : Type u) [CommRing R]
    (Q : (Scheme.projectiveSpaceOver n (Spec (.of R))).Modules)
    (q : (∐ fun _ : ULift.{u} (Fin r) =>
      Scheme.projectiveSpaceOverTwist n (Spec (.of R)) (-l)) ⟶ Q) :
    let p := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).map q
    GradedModule.IsFG (Proj.kernelQuotientModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      (projSpecπ n R) (stdVars n R) p) := by
  dsimp only
  exact GradedModule.IsFG.coker _
    (isFG_gammaStarPullTwistedFree n R hn (-l) r)

/-- The kernel-route model of a twisted-free quotient is generated by degree-one
multiplication in every degree at least `l`, uniformly over arbitrary coefficient rings.

Unlike the existential generation bound carried by `GradedModule.IsFG`, this records the
explicit bound inherited from `S(-l)^{⊕r}`.  Passing to the cokernel cannot increase that
bound. -/
theorem mulSpan_kernelQuotientModule_twistedFree_arbitrary
    (n r : ℕ) (hn : 0 < n) (l : ℤ) (R : Type u) [CommRing R]
    (Q : (Scheme.projectiveSpaceOver n (Spec (.of R))).Modules)
    (q : (∐ fun _ : ULift.{u} (Fin r) =>
      Scheme.projectiveSpaceOverTwist n (Spec (.of R)) (-l)) ⟶ Q)
    (d : ℤ) (hd : l ≤ d) :
    let p := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).map q
    (Proj.kernelQuotientModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      (projSpecπ n R) (stdVars n R) p).mulSpan d (d + 1) = ⊤ := by
  dsimp only
  let p := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).map q
  let E := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).obj
    (∐ fun _ : ULift.{u} (Fin r) =>
      Scheme.projectiveSpaceOverTwist n (Spec (.of R)) (-l))
  let M := Proj.gammaStar
    (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
    (projSpecπ n R) E (stdVars n R)
  have htwist : ((GradedModule.structureModule R n).twist (-l)).mulSpan
      d (d + 1) = ⊤ := by
    rw [GradedModule.twist_mulSpan]
    have key : ∀ e e' : ℤ, e = e' →
        (GradedModule.structureModule R n).mulSpan (d + -l) e = ⊤ →
        (GradedModule.structureModule R n).mulSpan (d + -l) e' = ⊤ := by
      intro e e' he h
      subst he
      exact h
    exact key _ _ (by ring)
      (GradedModule.structureModule_mulSpan_succ (d + -l) (by omega))
  have hpow : (((GradedModule.structureModule R n).twist (-l)).pow r).mulSpan
      d (d + 1) = ⊤ := by
    refine eq_top_iff.mpr fun x _ ↦ ?_
    have hx : x = ∑ t : Fin r,
        ((((GradedModule.structureModule R n).twist (-l)).powCoord r t).app
          (d + 1)).hom (x t) := (Finset.univ_sum_single x).symm
    rw [hx]
    refine Submodule.sum_mem _ fun t _ ↦ ?_
    refine GradedModule.mulSpan_map_le
      (((GradedModule.structureModule R n).twist (-l)).powCoord r t)
      d (d + 1) ⟨x t, ?_, rfl⟩
    rw [htwist]
    trivial
  have hM : M.mulSpan d (d + 1) = ⊤ :=
    GradedModule.mulSpan_eq_top_of_iso
      (gammaStarPullTwistedFreeIso n R hn (-l) r).symm d (d + 1) hpow
  exact GradedModule.mulSpan_eq_top_of_surjective
    (GradedModule.toCoker (Proj.gammaStarMap _ (projSpecπ n R) (kernel.ι p)
      (stdVars n R)))
    (fun e ↦ GradedModule.surjective_toCoker_app _ e) d (d + 1) hM

/-- In particular, every degree of the arbitrary-base kernel-route model is a finite
module over the coefficient ring. -/
theorem finite_kernelQuotientModule_twistedFree_obj_arbitrary
    (n r : ℕ) (hn : 0 < n) (l : ℤ) (R : Type u) [CommRing R]
    (Q : (Scheme.projectiveSpaceOver n (Spec (.of R))).Modules)
    (q : (∐ fun _ : ULift.{u} (Fin r) =>
      Scheme.projectiveSpaceOverTwist n (Spec (.of R)) (-l)) ⟶ Q) (d : ℤ) :
    let p := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).map q
    Module.Finite R ((Proj.kernelQuotientModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      (projSpecπ n R) (stdVars n R) p).obj d) := by
  exact (isFG_kernelQuotientModule_twistedFree_arbitrary n r hn l R Q q).1 d

set_option synthInstance.maxHeartbeats 1000000 in
-- The explicit polynomial `Proj` and twist instances make this local comparison expensive.
/-- Base change of the kernel-route comparison computes every graded Cech cohomology
group over an arbitrary base ring.  No noetherian hypothesis is involved: the comparison
is already an isomorphism after localizing at one homogeneous coordinate, and localization
commutes with arbitrary scalar extension. -/
theorem isIso_cechHgrMap_baseChangeMap_kernelQuotientToGammaStar_all_arbitrary
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A] {n : ℕ}
    {E G : (Proj (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)).Modules}
    (p : E ⟶ G) [Epi p]
    [∀ e : ℤ, (twistModule (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      E e).IsQuasicoherent]
    [∀ e : ℤ, (twistModule (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      G e).IsQuasicoherent]
    [∀ e : ℤ, (twistModule (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      (kernel p) e).IsQuasicoherent]
    (q : ℕ) (d : ℤ) :
    IsIso ((GradedModule.cechHgrMap (GradedModule.baseChangeMap
      (Proj.kernelQuotientToGammaStar _ (projSpecπ n R) (stdVars n R) p) A) q).app d) := by
  refine GradedModule.isIso_cechHgrMap_app_of_singleton_bijective _ q d (fun a t => ?_)
  exact GradedModule.bijective_locMap_baseChangeMap_app A _ [a] (d + (t : ℤ))
    (Proj.bijective_locMap_kernelQuotientToGammaStar
      (projSpecπ n R) p a (d + (t : ℤ)))

set_option synthInstance.maxHeartbeats 1000000 in
-- The explicit polynomial `Proj` and twist instances make this local comparison expensive.
/-- The `Gamma_*` coefficient-change comparison induces an isomorphism on every graded
Cech cohomology group in nonnegative degree, over an arbitrary source ring. -/
theorem isIso_cechHgrMap_gammaStarBaseChangeHom_app_all_arbitrary
    {R A : Type u} [CommRing R] [CommRing A] (n : ℕ) (f : R →+* A)
    (F : (Proj (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)).Modules)
    [F.IsFinitePresentation] (q d : ℕ) :
    letI : Algebra R A := f.toAlgebra
    IsIso ((GradedModule.cechHgrMap (gammaStarBaseChangeHom n f F) q).app (d : ℤ)) := by
  letI : Algebra R A := f.toAlgebra
  refine GradedModule.isIso_cechHgrMap_app_of_singleton_bijective _ q (d : ℤ)
    (fun a t => ?_)
  refine GradedModule.bijective_locMap_app_of_eq _ [a] ?_
    (bijective_locMap_gammaStarBaseChangeHom_app n f F a (d + t))
  push_cast
  ring

set_option synthInstance.maxHeartbeats 1000000 in
set_option maxHeartbeats 2000000 in
-- Fibre normalization across polynomial `Proj` is elaboration-heavy but deterministic.
/-- A uniform fixed degree kills the positive Cech cohomology of the fibre of the
kernel-quotient model over every field, without a noetherian hypothesis on the original
base ring.  Uniform regularity is invoked only after passing to the field. -/
theorem exists_bound_subsingleton_cechHgr_kernelQuotientModule_baseChange_arbitrary
    (n r : ℕ) (hn : 0 < n) (l : ℤ) (P : Polynomial ℚ) :
    ∃ d₀ : ℤ, 0 ≤ d₀ ∧ ∀ (R : Type u) [CommRing R]
      (Q : (Scheme.projectiveSpaceOver n (Spec (.of R))).Modules)
      (_ : Q.IsFinitePresentation)
      (q : (∐ fun _ : ULift.{u} (Fin r) =>
        Scheme.projectiveSpaceOverTwist n (Spec (.of R)) (-l)) ⟶ Q)
      (_ : Epi q)
      (_ : Q.FlatOver (Scheme.projectiveSpaceOverπ n (Spec (.of R))))
      (_ : Scheme.HasFiberwiseHilbertPolynomial Q P)
      (d : ℕ), d₀ ≤ (d : ℤ) →
      let E := projAmbient n r l (R := R)
      let G := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).obj Q
      let p := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).map q
      let M := Proj.kernelQuotientModule
        (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
        (projSpecπ n R) (stdVars n R) p
      ∀ (κ : Type u) [Field κ] [Algebra R κ] (i : ℕ), 1 ≤ i →
        Subsingleton (((M.baseChange κ).cechHgr i).obj (d : ℤ)) := by
  obtain ⟨dK, hdK0, hK⟩ :=
    exists_bound_subsingleton_cechHgr_gammaStar_kernel n r l P
  refine ⟨max dK (max (l - (n : ℤ)) 0), by omega, ?_⟩
  intro R _ Q hQfp q hq hflat hHP d hd
  haveI := hQfp
  haveI := hq
  let E := projAmbient n r l (R := R)
  let G := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).obj Q
  let p := (Scheme.Modules.pullback (projectiveSpaceOverSpecIso n R).inv).map q
  let M := Proj.kernelQuotientModule
    (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
    (projSpecπ n R) (stdVars n R) p
  dsimp only
  intro κ _ hAlg i hi
  letI : Algebra R κ := hAlg
  have halg : (algebraMap R κ).toAlgebra = hAlg :=
    Algebra.algebra_ext _ _ (fun x => rfl)
  have hdK : dK ≤ (d : ℤ) := le_trans (le_max_left _ _) hd
  have hdl : l - (n : ℤ) ≤ (d : ℤ) :=
    le_trans (le_max_left _ _) (le_trans (le_max_right _ _) hd)
  haveI hAmb : (∐ fun _ : ULift.{u} (Fin r) =>
      Scheme.projectiveSpaceOverTwist n (Spec (.of R)) (-l)).IsFinitePresentation :=
    Scheme.twistedFreeAmbient_isFinitePresentation n (Spec (.of R)) l r
  haveI hEfp : E.IsFinitePresentation :=
    Scheme.Modules.isFinitePresentation_pullback_of_isFinitePresentation _ inferInstance
  haveI hGfp : G.IsFinitePresentation :=
    Scheme.Modules.isFinitePresentation_pullback_of_isFinitePresentation _ inferInstance
  haveI hp : Epi p := inferInstance
  haveI hEqc : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R) E e).IsQuasicoherent :=
    fun e => twistModule_std_isQuasicoherent _ e
  haveI hGqc : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R) G e).IsQuasicoherent :=
    fun e => twistModule_std_isQuasicoherent _ e
  have hKqc0 : (kernel p).IsQuasicoherent := Scheme.Modules.kernel_isQuasicoherent p
  letI hKqc0' : (kernel p).IsQuasicoherent := hKqc0
  haveI hKqc : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R)
      (kernel p) e).IsQuasicoherent := fun e =>
    twistModule_std_isQuasicoherent_of_isQuasicoherent n _ e
  let pκ := (Scheme.Modules.pullback (coeffMap n (algebraMap R κ))).map p
  haveI hpκ : Epi pκ := inferInstance
  let Qκ := Scheme.Modules.projectiveSpaceBaseChangeOfRingHom Q (algebraMap R κ)
  haveI hQκfp : Qκ.IsFinitePresentation :=
    Scheme.Modules.isFinitePresentation_pullback_of_isFinitePresentation _ inferInstance
  have hQκflat : Qκ.FlatOver
      (Scheme.projectiveSpaceOverπ n (Spec (.of κ))) := by
    exact Scheme.Modules.FlatOver.pullback_of_isPullback
      (Scheme.projectiveSpaceOverMap n
        (Spec.map (CommRingCat.ofHom (algebraMap R κ))))
      (Scheme.projectiveSpaceOverπ n (Spec (.of κ)))
      (Scheme.projectiveSpaceOverπ n (Spec (.of R)))
      (Spec.map (CommRingCat.ofHom (algebraMap R κ)))
      (Scheme.isPullback_projectiveSpaceOverMap n
        (Spec.map (CommRingCat.ofHom (algebraMap R κ)))).flip Q hflat
  have hQκHP : Scheme.HasFiberwiseHilbertPolynomial Qκ P := by
    exact Scheme.HasFiberwiseHilbertPolynomial.pullback
      (Spec.map (CommRingCat.ofHom (algebraMap R κ))) hHP
  let eE := projAmbientFibreIso n r l (algebraMap R κ)
  let eQ := pullbackPolynomialTransportIso n (algebraMap R κ) Q
  let pκstd := eE.inv ≫ pκ ≫ eQ.hom
  haveI hpκstd : Epi pκstd := epi_comp _ _
  haveI hAmbκfp : (∐ fun _ : ULift.{u} (Fin r) =>
      Scheme.projectiveSpaceOverTwist n (Spec (.of κ)) (-l)).IsFinitePresentation :=
    Scheme.twistedFreeAmbient_isFinitePresentation n (Spec (.of κ)) l r
  haveI hStdEfp : (projAmbient n r l (R := κ)).IsFinitePresentation :=
    Scheme.Modules.isFinitePresentation_pullback_of_isFinitePresentation _ inferInstance
  haveI hStdGfp : ((Scheme.Modules.pullback
      (projectiveSpaceOverSpecIso n κ).inv).obj Qκ).IsFinitePresentation :=
    Scheme.Modules.isFinitePresentation_pullback_of_isFinitePresentation _ inferInstance
  haveI hStdGfp' : ((Scheme.Modules.pullback
      (Proj.polynomialProjOverSpecIso (Fin (n + 1)) κ).inv).obj
        ((Scheme.Modules.pullback (Scheme.projectiveSpaceOverMap n
          (Spec.map (CommRingCat.ofHom (algebraMap R κ))))).obj Q)
      ).IsFinitePresentation :=
    Scheme.Modules.isFinitePresentation_pullback_of_isFinitePresentation _ inferInstance
  haveI hStdKfp : (kernel pκstd).IsFinitePresentation :=
    Scheme.Modules.kernel_isFinitePresentation pκstd
  haveI hStdEqc : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ)
      (projAmbient n r l (R := κ)) e).IsQuasicoherent :=
    fun e => twistModule_std_isQuasicoherent _ e
  haveI hStdGqc : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ)
      ((Scheme.Modules.pullback (projectiveSpaceOverSpecIso n κ).inv).obj Qκ)
      e).IsQuasicoherent := fun e => twistModule_std_isQuasicoherent _ e
  haveI hStdGqc' : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ)
      ((Scheme.Modules.pullback
        (Proj.polynomialProjOverSpecIso (Fin (n + 1)) κ).inv).obj
          ((Scheme.Modules.pullback (Scheme.projectiveSpaceOverMap n
            (Spec.map (CommRingCat.ofHom (algebraMap R κ))))).obj Q))
      e).IsQuasicoherent := fun e => twistModule_std_isQuasicoherent _ e
  haveI hStdKqc : ∀ e : ℤ, (twistModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ)
      (kernel pκstd) e).IsQuasicoherent := fun e => twistModule_std_isQuasicoherent _ e
  haveI hKstd : Subsingleton (((Proj.gammaStar
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ) (projSpecπ n κ)
      (kernel pκstd) (stdVars n κ)).cechHgr (i + 1)).obj (d : ℤ)) :=
    hK κ Qκ hQκfp hAmbκfp pκstd hpκstd hQκflat hQκHP
      (i + 1) (by omega) (d : ℤ) hdK
  haveI hEstd : Subsingleton (((Proj.gammaStar
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ) (projSpecπ n κ)
      (projAmbient n r l (R := κ)) (stdVars n κ)).cechHgr i).obj (d : ℤ)) := by
    haveI : Subsingleton (((((GradedModule.structureModule κ n).twist (-l)).pow r
      ).cechHgr i).obj (d : ℤ)) :=
      GradedModule.subsingleton_cechHgr_free (-l) r i hi (d : ℤ) (by omega)
    exact (GradedModule.isoApp (GradedModule.cechHgrIso
      (gammaStarPullTwistedFreeIso n κ hn (-l) r) i) (d : ℤ)
        ).toLinearEquiv.toEquiv.subsingleton
  haveI hNstd : Subsingleton (((Proj.kernelQuotientModule
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ)
      (projSpecπ n κ) (stdVars n κ) pκstd).cechHgr i).obj (d : ℤ)) :=
    GradedModule.subsingleton_of_exact _ _
      (GradedModule.cech_exact_map_δ
        (Proj.shortExact_gammaStar_toCoker_kernel (projSpecπ n κ) pκstd)
        i (d : ℤ))
  haveI hQstd : Subsingleton (((Proj.gammaStar
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ) (projSpecπ n κ)
      ((Scheme.Modules.pullback
        (Proj.polynomialProjOverSpecIso (Fin (n + 1)) κ).inv).obj
          ((Scheme.Modules.pullback (Scheme.projectiveSpaceOverMap n
            (Spec.map (CommRingCat.ofHom (algebraMap R κ))))).obj Q))
      (stdVars n κ)).cechHgr i).obj (d : ℤ)) := by
    haveI : IsIso ((GradedModule.cechHgrMap
        (Proj.kernelQuotientToGammaStar
          (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ)
          (projSpecπ n κ) (stdVars n κ) pκstd) i).app (d : ℤ)) := by
      refine GradedModule.isIso_cechHgrMap_app_of_singleton_bijective
        _ i (d : ℤ) (fun a t => ?_)
      exact Proj.bijective_locMap_kernelQuotientToGammaStar
        (projSpecπ n κ) pκstd a ((d : ℤ) + (t : ℤ))
    exact (asIso ((GradedModule.cechHgrMap
      (Proj.kernelQuotientToGammaStar _ (projSpecπ n κ) (stdVars n κ) pκstd)
      i).app (d : ℤ))).symm.toLinearEquiv.toEquiv.subsingleton
  haveI hGκ : Subsingleton (((Proj.gammaStar
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) κ) (projSpecπ n κ)
      ((Scheme.Modules.pullback (coeffMap n (algebraMap R κ))).obj G)
      (stdVars n κ)).cechHgr i).obj (d : ℤ)) := by
    let eΓ := Proj.gammaStarMapIso _ (projSpecπ n κ) (stdVars n κ) eQ
    exact (GradedModule.isoApp (GradedModule.cechHgrIso eΓ i) (d : ℤ)
      ).toLinearEquiv.toEquiv.subsingleton
  haveI hGbc : Subsingleton ((((Proj.gammaStar
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) R) (projSpecπ n R)
      G (stdVars n R)).baseChange κ).cechHgr i).obj (d : ℤ)) := by
    haveI := isIso_cechHgrMap_gammaStarBaseChangeHom_app_all_arbitrary
      n (algebraMap R κ) G i d
    let eG := (asIso ((GradedModule.cechHgrMap
      (gammaStarBaseChangeHom n (algebraMap R κ) G) i).app (d : ℤ))).toLinearEquiv
    rw [halg] at eG
    exact eG.toEquiv.subsingleton
  haveI := isIso_cechHgrMap_baseChangeMap_kernelQuotientToGammaStar_all_arbitrary
    (A := κ) p i (d : ℤ)
  exact (asIso ((GradedModule.cechHgrMap (GradedModule.baseChangeMap
    (Proj.kernelQuotientToGammaStar _ (projSpecπ n R) (stdVars n R) p) κ) i
    ).app (d : ℤ))).toLinearEquiv.toEquiv.subsingleton

end AlgebraicGeometry.ProjectiveSpace

end

end
