module

public import StacksAndModuli.API.TwistedFreeQuotGrassmannianNextDegreeComparison
public import StacksAndModuli.API.TwistedFreeQuotGrassmannianNextDegreeFlattening

/-!
# A saturation criterion for the algebraic next-degree quotient

The algebraic next-degree module maps canonically to the degree-`d+1` twisted
pushforward of the reconstructed quotient.  This file isolates two precise
hypotheses under which that comparison is an isomorphism:

* the degree-`d+1` monomial sections surject onto the reconstructed pushforward;
* the degree-one multiples of `ker(u)` surject onto the kernel of that monomial map.

The first hypothesis alone makes the comparison an epimorphism.  Together they
identify both sides as the same cokernel.  The resulting rank equivalence is then
combined with separate regularity and Gotzmann-persistence callbacks to produce
`TwistedFreeQuotUniversalNextDegreeFlatteningData` for the universal Grassmannian
quotient.  No projective pushforward base-change assertion is used.
-/

@[expose] public section

noncomputable section

set_option backward.isDefEq.respectTransparency.types false
set_option backward.isDefEq.respectTransparency false
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits Opposite AlgebraicGeometry

namespace AlgebraicGeometry.Scheme

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The degree-one-generated algebraic relations, regarded as relations in the
kernel of the reconstructed degree-`d+1` monomial map. -/
noncomputable def twistedFreeNextDegreeReconstructedKernelLift
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E) :
    (∐ fun _ : ULift.{u} (Fin (n + 1)) ↦ kernel u) ⟶
      kernel (quotGrassmannianFreeMap n T l r
        (reconstructedQuotientMap' n T l r d e he u)
        (d + 1) (e + 1) (by omega)) :=
  kernel.lift _ (twistedFreeNextDegreeRelation n T r e u)
    (twistedFreeNextDegreeRelation_comp_reconstructedPushforwardMap
      n T l r d e he u)

/-- The reconstructed kernel lift followed by the kernel inclusion is the
algebraic next-degree relation map. -/
@[reassoc]
theorem twistedFreeNextDegreeReconstructedKernelLift_comp
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E) :
    twistedFreeNextDegreeReconstructedKernelLift n T l r d e he u ≫
        kernel.ι (quotGrassmannianFreeMap n T l r
          (reconstructedQuotientMap' n T l r d e he u)
          (d + 1) (e + 1) (by omega)) =
      twistedFreeNextDegreeRelation n T r e u :=
  kernel.lift_ι _ _ _

/-- A degree-`d+1` global-generation and relation-generation condition for a
reconstructed twisted-free quotient.

The first field says that the standard degree-`d+1` monomials generate the
twisted pushforward.  The second says that every relation among these monomials
is generated by multiplying the degree-`d` kernel by the projective variables.
This is the exact saturation input needed to identify the algebraic next-degree
cokernel with the geometric pushforward. -/
structure TwistedFreeNextDegreeReconstructionSaturation
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E) : Prop where
  /-- The reconstructed degree-`d+1` monomial map is an epimorphism. -/
  reconstructedPushforwardMap_epi :
    Epi (quotGrassmannianFreeMap n T l r
      (reconstructedQuotientMap' n T l r d e he u)
      (d + 1) (e + 1) (by omega))
  /-- Degree-one multiples of the degree-`d` kernel generate the full kernel
  of the reconstructed degree-`d+1` monomial map. -/
  relationKernelLift_epi :
    Epi (twistedFreeNextDegreeReconstructedKernelLift
      n T l r d e he u)

/-- Surjectivity of the reconstructed degree-`d+1` monomial map makes the
algebraic-to-geometric next-degree comparison an epimorphism. -/
theorem twistedFreeNextDegreeModuleToReconstructedPushforward_epi_of_epi
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E)
    (h : Epi (quotGrassmannianFreeMap n T l r
      (reconstructedQuotientMap' n T l r d e he u)
      (d + 1) (e + 1) (by omega))) :
    Epi (twistedFreeNextDegreeModuleToReconstructedPushforward
      n T l r d e he u) := by
  letI := h
  dsimp only [twistedFreeNextDegreeModuleToReconstructedPushforward]
  infer_instance

/-- Under next-degree global generation and relation generation, the algebraic
next-degree cokernel is canonically isomorphic to the reconstructed pushforward. -/
noncomputable def twistedFreeNextDegreeSaturationIso
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E)
    (h : TwistedFreeNextDegreeReconstructionSaturation
      n T l r d e he u) :
    twistedFreeNextDegreeModule n T r e u ≅
      Modules.projectiveTwistedPushforward n
        (reconstructedQuotient' n T l r d e he u) (d + 1) := by
  let q := quotGrassmannianFreeMap n T l r
    (reconstructedQuotientMap' n T l r d e he u)
    (d + 1) (e + 1) (by omega)
  let g := twistedFreeNextDegreeReconstructedKernelLift
    n T l r d e he u
  letI : Epi q := h.reconstructedPushforwardMap_epi
  letI : Epi g := h.relationKernelLift_epi
  let hrel : twistedFreeNextDegreeRelation n T r e u =
      g ≫ kernel.ι q :=
    (twistedFreeNextDegreeReconstructedKernelLift_comp
      n T l r d e he u).symm
  exact cokernel.mapIso
      (twistedFreeNextDegreeRelation n T r e u)
      (g ≫ kernel.ι q) (Iso.refl _) (Iso.refl _) (by simpa using hrel) ≪≫
    cokernelEpiCompKernelIsoOfEpi q g

/-- The saturation isomorphism is induced by the reconstructed degree-`d+1`
monomial map. -/
theorem twistedFreeNextDegreeSaturationIso_hom_fac
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E)
    (h : TwistedFreeNextDegreeReconstructionSaturation
      n T l r d e he u) :
    cokernel.π (twistedFreeNextDegreeRelation n T r e u) ≫
        (twistedFreeNextDegreeSaturationIso n T l r d e he u h).hom =
      quotGrassmannianFreeMap n T l r
        (reconstructedQuotientMap' n T l r d e he u)
        (d + 1) (e + 1) (by omega) := by
  let q := quotGrassmannianFreeMap n T l r
    (reconstructedQuotientMap' n T l r d e he u)
    (d + 1) (e + 1) (by omega)
  let g := twistedFreeNextDegreeReconstructedKernelLift
    n T l r d e he u
  letI : Epi q := h.reconstructedPushforwardMap_epi
  letI : Epi g := h.relationKernelLift_epi
  let M := cokernel.mapIso
    (twistedFreeNextDegreeRelation n T r e u)
    (g ≫ kernel.ι q) (Iso.refl _) (Iso.refl _)
      (by simpa using
        (twistedFreeNextDegreeReconstructedKernelLift_comp
          n T l r d e he u).symm)
  let C := cokernelEpiCompKernelIsoOfEpi q g
  have hM : cokernel.π (twistedFreeNextDegreeRelation n T r e u) ≫ M.hom =
      cokernel.π (g ≫ kernel.ι q) := by
    dsimp only [M, cokernel.mapIso_hom]
    exact (cokernel.π_desc _ _ _).trans (Category.id_comp _)
  have hC : cokernel.π (g ≫ kernel.ι q) ≫ C.hom = q :=
    cokernel_π_comp_cokernelEpiCompKernelIsoOfEpi_hom q g
  change cokernel.π (twistedFreeNextDegreeRelation n T r e u) ≫
      (M.hom ≫ C.hom) = q
  calc
    cokernel.π (twistedFreeNextDegreeRelation n T r e u) ≫
          (M.hom ≫ C.hom) =
        (cokernel.π (twistedFreeNextDegreeRelation n T r e u) ≫ M.hom) ≫
          C.hom := (Category.assoc _ _ _).symm
    _ = cokernel.π (g ≫ kernel.ι q) ≫ C.hom :=
      congrArg (fun z ↦ z ≫ C.hom) hM
    _ = q := hC

/-- The canonical algebraic-to-geometric comparison is the hom of the
saturation isomorphism. -/
theorem twistedFreeNextDegreeModuleToReconstructedPushforward_eq_iso_hom
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E)
    (h : TwistedFreeNextDegreeReconstructionSaturation
      n T l r d e he u) :
    twistedFreeNextDegreeModuleToReconstructedPushforward
        n T l r d e he u =
      (twistedFreeNextDegreeSaturationIso n T l r d e he u h).hom := by
  apply (cancel_epi
    (cokernel.π (twistedFreeNextDegreeRelation n T r e u))).1
  exact (twistedFreeNextDegreeModuleToReconstructedPushforward_fac
    n T l r d e he u).trans
      (twistedFreeNextDegreeSaturationIso_hom_fac
        n T l r d e he u h).symm

/-- The canonical algebraic-to-geometric next-degree comparison is an
isomorphism under next-degree saturation. -/
theorem twistedFreeNextDegreeModuleToReconstructedPushforward_isIso
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E)
    (h : TwistedFreeNextDegreeReconstructionSaturation
      n T l r d e he u) :
    IsIso (twistedFreeNextDegreeModuleToReconstructedPushforward
      n T l r d e he u) := by
  rw [twistedFreeNextDegreeModuleToReconstructedPushforward_eq_iso_hom
    n T l r d e he u h]
  infer_instance

/-- Under next-degree saturation, the algebraic next-degree module has rank
`k` exactly when the reconstructed twisted pushforward has rank `k`. -/
theorem twistedFreeNextDegreeModule_isProjectiveOfRank_iff_pushforward
    (n : ℕ) (T : Scheme.{u}) (l : ℤ) (r d e k : ℕ)
    (he : (d : ℤ) - l = (e : ℤ)) {E : T.Modules}
    (u : SheafOfModules.free (R := T.ringCatSheaf)
      (ULift.{u} (Fin r) × Fin ((n + e).choose n)) ⟶ E)
    (h : TwistedFreeNextDegreeReconstructionSaturation
      n T l r d e he u) :
    Modules.IsProjectiveOfRank k (twistedFreeNextDegreeModule n T r e u) ↔
      Modules.IsProjectiveOfRank k
        (Modules.projectiveTwistedPushforward n
          (reconstructedQuotient' n T l r d e he u) (d + 1)) := by
  letI := twistedFreeNextDegreeModuleToReconstructedPushforward_isIso
    n T l r d e he u h
  let C := asIso (twistedFreeNextDegreeModuleToReconstructedPushforward
    n T l r d e he u)
  exact ⟨fun hM ↦ hM.of_iso C, fun hQ ↦ hQ.of_iso C.symm⟩

variable {S : Scheme.{u}} {n r m q : ℕ} {l : ℤ} {P : Polynomial ℚ}
  {d e : ℕ} {he : (d : ℤ) - l = (e : ℤ)}
  {σ : ULift.{u} (Fin m) ≃
    ULift.{u} (Fin r) × Fin ((n + e).choose n)}

/-- Saturation, regularity, and Gotzmann-persistence inputs reducing the
universal next-degree rank condition to projective flattening.

The saturation field identifies the finite algebraic cokernel with the geometric
degree-`d+1` pushforward after every normalized base change.  The two remaining
fields isolate the forward regularity statement and the reverse Gotzmann statement
for that geometric pushforward. -/
structure TwistedFreeQuotUniversalNextDegreeSaturationData
    (S : Scheme.{u}) (n r q m : ℕ) (l : ℤ) (P : Polynomial ℚ)
    (d e : ℕ) (he : (d : ℤ) - l = (e : ℤ))
    (σ : ULift.{u} (Fin m) ≃
      ULift.{u} (Fin r) × Fin ((n + e).choose n)) : Prop where
  /-- The normalized reconstructed quotient is saturated in degree `d+1`. -/
  saturation (A : Over (grassmannianOverRepresentation S q m).left) :
    TwistedFreeNextDegreeReconstructionSaturation n A.left l r d e he
      (pullbackFreeQuotientMap A.hom
        (grassmannianPointMonomialQuotientMap
          (n := n) (r := r) (q := q) (e := e) (σ := σ)
          (grassmannianOverRepresentation S q m)
          (freeGrassmannianUniversalPoint S q m)))
  /-- Flatness with Hilbert polynomial `P` gives the expected rank of the
  reconstructed degree-`d+1` pushforward. -/
  flatHilbert_implies_pushforwardRank
      (A : Over (grassmannianOverRepresentation S q m).left) :
    (Modules.projectiveFamilyAt n
        (freeGrassmannianUniversalReconstructedQuotient
          S n r q m l d e he σ) A).FlatOver
        (projectiveSpaceOverπ n A.left) ∧
      HasFiberwiseHilbertPolynomial
        (Modules.projectiveFamilyAt n
          (freeGrassmannianUniversalReconstructedQuotient
            S n r q m l d e he σ) A) P →
      Modules.IsProjectiveOfRank (P.hilbertNatValue (d + 1))
        (Modules.projectiveTwistedPushforward n
          (reconstructedQuotient' n A.left l r d e he
            (pullbackFreeQuotientMap A.hom
              (grassmannianPointMonomialQuotientMap
                (n := n) (r := r) (q := q) (e := e) (σ := σ)
                (grassmannianOverRepresentation S q m)
                (freeGrassmannianUniversalPoint S q m)))) (d + 1))
  /-- The expected rank of the reconstructed degree-`d+1` pushforward implies
  flatness and the prescribed fibrewise Hilbert polynomial. -/
  pushforwardRank_implies_flatHilbert
      (A : Over (grassmannianOverRepresentation S q m).left) :
    Modules.IsProjectiveOfRank (P.hilbertNatValue (d + 1))
        (Modules.projectiveTwistedPushforward n
          (reconstructedQuotient' n A.left l r d e he
            (pullbackFreeQuotientMap A.hom
              (grassmannianPointMonomialQuotientMap
                (n := n) (r := r) (q := q) (e := e) (σ := σ)
                (grassmannianOverRepresentation S q m)
                (freeGrassmannianUniversalPoint S q m)))) (d + 1)) →
      (Modules.projectiveFamilyAt n
          (freeGrassmannianUniversalReconstructedQuotient
            S n r q m l d e he σ) A).FlatOver
          (projectiveSpaceOverπ n A.left) ∧
        HasFiberwiseHilbertPolynomial
          (Modules.projectiveFamilyAt n
            (freeGrassmannianUniversalReconstructedQuotient
              S n r q m l d e he σ) A) P

namespace TwistedFreeQuotUniversalNextDegreeSaturationData

/-- The normalized algebraic next-degree module has the prescribed rank exactly
when the reconstructed projective family is flat with Hilbert polynomial `P`. -/
theorem normalizedRank_iff_flatHilbert
    (D : TwistedFreeQuotUniversalNextDegreeSaturationData
      S n r q m l P d e he σ)
    (A : Over (grassmannianOverRepresentation S q m).left) :
    Modules.IsProjectiveOfRank (P.hilbertNatValue (d + 1))
        (twistedFreeNextDegreeModule n A.left r e
          (pullbackFreeQuotientMap A.hom
            (grassmannianPointMonomialQuotientMap
              (n := n) (r := r) (q := q) (e := e) (σ := σ)
              (grassmannianOverRepresentation S q m)
              (freeGrassmannianUniversalPoint S q m)))) ↔
      (Modules.projectiveFamilyAt n
          (freeGrassmannianUniversalReconstructedQuotient
            S n r q m l d e he σ) A).FlatOver
          (projectiveSpaceOverπ n A.left) ∧
        HasFiberwiseHilbertPolynomial
          (Modules.projectiveFamilyAt n
            (freeGrassmannianUniversalReconstructedQuotient
              S n r q m l d e he σ) A) P := by
  let u := pullbackFreeQuotientMap A.hom
    (grassmannianPointMonomialQuotientMap
      (n := n) (r := r) (q := q) (e := e) (σ := σ)
      (grassmannianOverRepresentation S q m)
      (freeGrassmannianUniversalPoint S q m))
  exact (twistedFreeNextDegreeModule_isProjectiveOfRank_iff_pushforward
    n A.left l r d e (P.hilbertNatValue (d + 1)) he u
      (D.saturation A)).trans
    ⟨D.pushforwardRank_implies_flatHilbert A,
      D.flatHilbert_implies_pushforwardRank A⟩

/-- Saturation together with the geometric regularity and persistence callbacks
supplies the universal algebraic next-degree flattening datum. -/
theorem toFlatteningData
    (D : TwistedFreeQuotUniversalNextDegreeSaturationData
      S n r q m l P d e he σ) :
    TwistedFreeQuotUniversalNextDegreeFlatteningData
      S n r q m l P d e he σ where
  rank_iff A := D.normalizedRank_iff_flatHilbert A

end TwistedFreeQuotUniversalNextDegreeSaturationData

end AlgebraicGeometry.Scheme

end

end
