module

public import Mathlib.LinearAlgebra.Dimension.OrzechProperty
public import Mathlib.RingTheory.KrullDimension.NonZeroDivisors
public import Mathlib.RingTheory.LocalRing.Quotient
public import Mathlib.RingTheory.RegularLocalRing.Polynomial
public import Mathlib.RingTheory.Smooth.Field
public import Mathlib.RingTheory.Smooth.Local
public import Mathlib.RingTheory.Smooth.StandardSmoothOfFree

/-!
# Regular local rings and smoothness over a field

Stacks Project tag **00TV**, label `algebra-lemma-separable-smooth`, in `algebra.tex`,
§`00TQ` (Smooth algebras over fields).

The main result formalized here is the direction needed for tag 00TS: a finite type algebra
whose local ring at a prime is regular, and whose residue field is formally smooth over the
base field, is formally smooth at that prime. The proof uses the complete-intersection
description of a surjection between regular local rings. Since pinned Mathlib does not yet
contain that regular-local-ring API, the file also proves the needed domain and kernel
generation results.

Main declarations:

* `IsRegularLocalRing.isDomain`: a regular local ring is a domain (Stacks 00NP).
* `IsRegularLocalRing.exists_span_range_eq_ker`: the kernel of a surjection between regular
  local rings is generated by elements independent in the cotangent space (Stacks 00NR).
* `Algebra.FormallySmooth.of_isRegularLocalRing_localization_atPrime`: the regular-local
  direction of Stacks 00TV.
-/

open TensorProduct IsLocalRing

universe u

@[expose] public section

open Submodule Ideal IsLocalRing

variable {R : Type*} [CommRing R] [IsLocalRing R]

/-- If the maximal ideal of a Noetherian local ring is contained in its square, its Krull
dimension is zero. -/
lemma IsLocalRing.ringKrullDim_eq_zero_of_maximalIdeal_le_pow_two [IsNoetherianRing R]
    (h_le : maximalIdeal R ≤ (maximalIdeal R) ^ 2) : ringKrullDim R = 0 := by
  have h_m_fg : (maximalIdeal R).FG := IsNoetherian.noetherian _
  have h_m_eq_m2 : maximalIdeal R = maximalIdeal R * maximalIdeal R := by
    rw [pow_two] at h_le
    exact le_antisymm h_le Ideal.mul_le_left
  have hm_bot : maximalIdeal R = ⊥ := by
    have h_smul : maximalIdeal R ≤ maximalIdeal R • maximalIdeal R := le_of_eq h_m_eq_m2
    exact @Submodule.eq_bot_of_le_smul_of_le_jacobson_bot R R _ _ _
      (maximalIdeal R) (maximalIdeal R) h_m_fg h_smul
      (IsLocalRing.maximalIdeal_le_jacobson ⊥)
  haveI : Subsingleton (PrimeSpectrum R) := by
    refine ⟨fun ⟨I, hI⟩ ⟨J, hJ⟩ => ?_⟩
    have hI_le : I ≤ maximalIdeal R := IsLocalRing.le_maximalIdeal hI.ne_top
    have hJ_le : J ≤ maximalIdeal R := IsLocalRing.le_maximalIdeal hJ.ne_top
    rw [hm_bot] at hI_le hJ_le
    have h_eq : I = J := le_antisymm (hI_le.trans bot_le) (hJ_le.trans bot_le)
    cases h_eq
    rfl
  exact Order.krullDim_eq_zero (α := PrimeSpectrum R)

/-- A local ring whose maximal ideal is contained in a minimal prime has Krull dimension
zero. -/
lemma IsLocalRing.ringKrullDim_eq_zero_of_maximalIdeal_le_minimalPrime
    (p : Ideal R) (hp_min : p ∈ minimalPrimes R) (h_le : maximalIdeal R ≤ p) :
    ringKrullDim R = 0 := by
  have hp_prime : p.IsPrime := hp_min.1.1
  have hp_eq : maximalIdeal R = p :=
    (IsLocalRing.maximalIdeal.isMaximal R).eq_of_le hp_prime.ne_top h_le
  haveI : Subsingleton (PrimeSpectrum R) := by
    refine ⟨fun ⟨I, hI⟩ ⟨J, hJ⟩ => ?_⟩
    have hI_le : I ≤ maximalIdeal R := IsLocalRing.le_maximalIdeal hI.ne_top
    have hJ_le : J ≤ maximalIdeal R := IsLocalRing.le_maximalIdeal hJ.ne_top
    rw [hp_eq] at hI_le hJ_le
    have hI_eq : I = p := le_antisymm hI_le (hp_min.2 ⟨hI, bot_le⟩ hI_le)
    have hJ_eq : J = p := le_antisymm hJ_le (hp_min.2 ⟨hJ, bot_le⟩ hJ_le)
    subst I
    subst J
    rfl
  exact Order.krullDim_eq_zero (α := PrimeSpectrum R)

/-- Zero in `WithBot ℕ∞` is distinct from every positive finite value. -/
lemma WithBot.zero_ne_coe_succ (d : ℕ) :
    (0 : WithBot ℕ∞) ≠ ((d + 1 : ℕ) : WithBot ℕ∞) := by
  exact_mod_cast Nat.zero_ne_add_one d

/-- In a positive-dimensional Noetherian local ring, there is an element of the maximal ideal
which lies neither in its square nor in any minimal prime. -/
lemma IsLocalRing.exists_mem_maximalIdeal_notMem_pow_two_notMem_minimalPrimes
    [IsNoetherianRing R] {d : ℕ} (hd : ringKrullDim R = (d + 1 : WithBot ℕ∞)) :
    ∃ x ∈ maximalIdeal R,
      x ∉ (maximalIdeal R) ^ 2 ∧ ∀ p ∈ minimalPrimes R, x ∉ p := by
  have h_min_finite : (minimalPrimes R).Finite := minimalPrimes.finite_of_isNoetherianRing R
  let m2 := (maximalIdeal R) ^ 2
  let s : Set (Ideal R) := insert m2 (minimalPrimes R)
  have hs_finite : s.Finite := Set.Finite.insert m2 h_min_finite
  by_contra h_not_exists
  push Not at h_not_exists
  have h_subset : (maximalIdeal R : Set R) ⊆ ⋃ i ∈ s, (i : Set R) := by
    intro x hx
    by_cases h_x_m2 : x ∈ (maximalIdeal R) ^ 2
    · simp only [Set.mem_iUnion, exists_prop]
      exact ⟨m2, Set.mem_insert _ _, h_x_m2⟩
    · obtain ⟨p, hp_min, hx_p⟩ := h_not_exists x hx h_x_m2
      simp only [Set.mem_iUnion, exists_prop]
      exact ⟨p, Set.mem_insert_of_mem _ hp_min, hx_p⟩
  obtain ⟨p, hp_in, hp_le⟩ :=
    (Ideal.subset_union_prime_finite hs_finite m2 m2 (by
      intro i hi h_ne1 _
      have : i ∈ minimalPrimes R := (Set.mem_insert_iff.mp hi).resolve_left h_ne1
      exact this.1.1)).mp h_subset
  rcases Set.mem_insert_iff.mp hp_in with rfl | hp_min
  · have hd_zero := IsLocalRing.ringKrullDim_eq_zero_of_maximalIdeal_le_pow_two hp_le
    exact WithBot.zero_ne_coe_succ d (hd_zero.symm.trans hd)
  · have hd_zero :=
      IsLocalRing.ringKrullDim_eq_zero_of_maximalIdeal_le_minimalPrime p hp_min hp_le
    exact WithBot.zero_ne_coe_succ d (hd_zero.symm.trans hd)

/-- If a principal quotient of a local ring is a domain and its generator avoids every
minimal prime, then the original ring is a domain. -/
lemma IsLocalRing.isDomain_of_quotient_isDomain [IsNoetherianRing R]
    (x : R) (hx_mem : x ∈ maximalIdeal R) (h_prime : (Ideal.span {x}).IsPrime)
    (hx_avoid : ∀ p ∈ minimalPrimes R, x ∉ p) : IsDomain R := by
  haveI := h_prime
  obtain ⟨P, hP_min, hP_le⟩ :=
    Ideal.exists_minimalPrimes_le (I := ⊥) (J := Ideal.span {x}) bot_le
  have hP_prime : P.IsPrime := hP_min.1.1
  have hx_not_in_P : x ∉ P := hx_avoid P hP_min
  have hP_eq_Px : P = maximalIdeal R • P := by
    apply le_antisymm
    · intro y hy
      obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton.mp (hP_le hy)
      have ha_in_P : a ∈ P := by
        rcases hP_prime.mem_or_mem hy with h | h
        · exact (hx_not_in_P h).elim
        · exact h
      exact Submodule.smul_mem_smul hx_mem ha_in_P
    · apply Submodule.smul_le.mpr
      intro r _ p hp
      exact P.smul_mem r hp
  have hP_bot : P = ⊥ := by
    exact @Submodule.eq_bot_of_le_smul_of_le_jacobson_bot R R _ _ _ (maximalIdeal R) P
      (IsNoetherian.noetherian P) (le_of_eq hP_eq_Px)
      (IsLocalRing.maximalIdeal_le_jacobson ⊥)
  have h_bot_prime : (⊥ : Ideal R).IsPrime := hP_bot ▸ hP_prime
  exact IsDomain.of_bot_isPrime R

/-- Krull dimension is at most one more than the dimension of a principal quotient by an
element of the maximal ideal. -/
lemma IsLocalRing.ringKrullDim_le_quotient_add_one [IsNoetherianRing R]
    (x : R) (hx : x ∈ maximalIdeal R) :
    ringKrullDim R ≤ ringKrullDim (R ⧸ Ideal.span {x}) + 1 := by
  have h_sub : ({x} : Set R) ⊆ Ring.jacobson R := by
    rw [← Ideal.jacobson_bot, IsLocalRing.jacobson_eq_maximalIdeal ⊥ bot_ne_top]
    exact Set.singleton_subset_iff.mpr hx
  have h := ringKrullDim_le_ringKrullDim_quotient_add_encard {x} h_sub
  simpa using h

/-- Cancel a finite successor inequality in `WithBot ℕ∞`. -/
lemma WithBot.coe_le_of_add_one_le {d : ℕ} {D : WithBot ℕ∞}
    (h : ((d + 1 : ℕ) : WithBot ℕ∞) ≤ D + 1) : (d : WithBot ℕ∞) ≤ D := by
  cases D with
  | bot => simp at h
  | coe D' =>
      cases D' with
      | top => exact le_top
      | coe D'' =>
          norm_cast at h ⊢
          omega

/-- Extend an element nonzero in the cotangent space to a minimal finite generating family
of the maximal ideal. -/
lemma IsRegularLocalRing.exists_generators_of_notMem_pow_two [IsNoetherianRing R]
    {d : ℕ} (hd : Module.finrank (ResidueField R) (CotangentSpace R) = d + 1)
    (x : R) (hx_mem : x ∈ maximalIdeal R) (hx_not_mem : x ∉ (maximalIdeal R) ^ 2) :
    ∃ (s : Finset R), s.card ≤ d ∧ Ideal.span (insert x (s : Set R)) = maximalIdeal R := by
  classical
  let m := maximalIdeal R
  let k := ResidueField R
  let v : CotangentSpace R := Ideal.toCotangent m ⟨x, hx_mem⟩
  have hv : v ≠ 0 := fun H => hx_not_mem ((Ideal.toCotangent_eq_zero _ _).mp H)
  obtain ⟨W, hW⟩ := Submodule.exists_isCompl (span k {v})
  have h_span_v : Module.finrank k (span k {v}) = 1 := finrank_span_singleton hv
  have h_rank_W : Module.finrank k W = d := by
    have h_sum := Submodule.finrank_add_eq_of_isCompl hW
    rw [h_span_v, hd] at h_sum
    omega
  let BW := Module.finBasis k W
  let vg : Fin d → CotangentSpace R := fun i => (BW (Fin.cast h_rank_W.symm i) : W)
  choose g hg using fun i => Ideal.toCotangent_surjective m (vg i)
  let s : Finset R := Finset.univ.image fun i : Fin d => ((g i : m) : R)
  refine ⟨s, Finset.card_image_le.trans (by simp), ?_⟩
  have h_span_vg : span k (Set.range vg) = W := by
    have h_img : Set.range vg = W.subtype '' Set.range BW := by
      ext y
      constructor
      · rintro ⟨i, rfl⟩
        exact ⟨BW (Fin.cast h_rank_W.symm i), ⟨Fin.cast h_rank_W.symm i, rfl⟩, rfl⟩
      · rintro ⟨y, ⟨j, rfl⟩, rfl⟩
        exact ⟨Fin.cast h_rank_W j, rfl⟩
    rw [h_img, ← Submodule.map_span, BW.span_eq, Submodule.map_top,
      Submodule.range_subtype]
  have h_span_classes : span k (insert v (Set.range vg)) = ⊤ := by
    rw [Submodule.span_insert, h_span_vg]
    exact hW.sup_eq_top
  let lifts : Set m := insert ⟨x, hx_mem⟩ (Set.range g)
  have h_image : Ideal.toCotangent m '' lifts = insert v (Set.range vg) := by
    ext z
    constructor
    · rintro ⟨y, hy, rfl⟩
      rcases hy with rfl | ⟨i, rfl⟩
      · exact Set.mem_insert _ _
      · exact Set.mem_insert_of_mem _ ⟨i, (hg i).symm⟩
    · rintro (rfl | ⟨i, rfl⟩)
      · exact ⟨⟨x, hx_mem⟩, Set.mem_insert _ _, rfl⟩
      · exact ⟨g i, Set.mem_insert_of_mem _ ⟨i, rfl⟩, hg i⟩
  have h_span_lifts : Submodule.span R lifts = ⊤ := by
    rw [← IsLocalRing.CotangentSpace.span_image_eq_top_iff, h_image]
    exact h_span_classes
  have h_map := congrArg (Submodule.map m.subtype) h_span_lifts
  rw [Submodule.map_span, Submodule.map_top, Submodule.range_subtype] at h_map
  change Submodule.span R (insert x (s : Set R)) = (m : Submodule R R)
  rw [← h_map]
  congr 1
  ext y
  simp [lifts, s, eq_comm]

/-- Quotienting a regular local ring by an element nonzero in its cotangent space produces a
regular local ring of dimension one less. -/
lemma IsRegularLocalRing.quotient_of_notMem_pow_two
    [IsNoetherianRing R] [IsRegularLocalRing R]
    {d : ℕ} (h_dim : ringKrullDim R = ((d + 1 : ℕ) : WithBot ℕ∞))
    (x : R) (hx_mem : x ∈ maximalIdeal R) (hx_not_mem : x ∉ (maximalIdeal R) ^ 2)
    [IsLocalRing (R ⧸ Ideal.span {x})] :
    IsRegularLocalRing (R ⧸ Ideal.span {x}) ∧
      ringKrullDim (R ⧸ Ideal.span {x}) = (d : WithBot ℕ∞) := by
  classical
  let I := Ideal.span {x}
  have h_finrank : Module.finrank (ResidueField R) (CotangentSpace R) = d + 1 := by
    have h := (IsRegularLocalRing.iff_finrank_cotangentSpace R).mp inferInstance
    rw [h_dim] at h
    exact_mod_cast h
  obtain ⟨s, hs_card, hs_span⟩ :=
    IsRegularLocalRing.exists_generators_of_notMem_pow_two h_finrank x hx_mem hx_not_mem
  let s_quot : Finset (R ⧸ I) := s.image (Ideal.Quotient.mk I)
  have hI_le : I ≤ maximalIdeal R := by
    rw [Ideal.span_le, Set.singleton_subset_iff]
    exact hx_mem
  letI : IsLocalHom (Ideal.Quotient.mk I) :=
    IsLocalHom.of_surjective (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  have h_map : (maximalIdeal R).map (Ideal.Quotient.mk I) =
      maximalIdeal (R ⧸ I) := by
    ext y
    obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective y
    simp [sup_eq_left.mpr hI_le]
  have h_span_quot : Ideal.span (s_quot : Set (R ⧸ I)) = maximalIdeal (R ⧸ I) := by
    rw [← h_map, ← hs_span, Ideal.map_span, Set.image_insert_eq]
    have h_zero : Ideal.Quotient.mk I x = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr
      (Ideal.subset_span (Set.mem_singleton x))
    rw [h_zero, Ideal.span_insert_zero]
    simp [s_quot]
  have h_card_le : (s_quot.card : WithBot ℕ∞) ≤ d := by
    have hc : s_quot.card ≤ d := by
      exact (Finset.card_image_le.trans hs_card)
    exact_mod_cast hc
  have h_spanFinrank_le :
      ((maximalIdeal (R ⧸ I)).spanFinrank : WithBot ℕ∞) ≤ d := by
    have hle : (maximalIdeal (R ⧸ I)).spanFinrank ≤ s_quot.card := by
      rw [← h_span_quot]
      simpa using Submodule.spanFinrank_span_le_ncard_of_finite
        (R := R ⧸ I) s_quot.finite_toSet
    exact (by exact_mod_cast hle :
      ((maximalIdeal (R ⧸ I)).spanFinrank : WithBot ℕ∞) ≤ s_quot.card).trans h_card_le
  have h_dim_upper : ringKrullDim (R ⧸ I) ≤ d :=
    (ringKrullDim_le_spanFinrank_maximalIdeal _).trans h_spanFinrank_le
  have h_add_one := IsLocalRing.ringKrullDim_le_quotient_add_one x hx_mem
  rw [h_dim] at h_add_one
  have h_dim_lower : (d : WithBot ℕ∞) ≤ ringKrullDim (R ⧸ I) :=
    WithBot.coe_le_of_add_one_le h_add_one
  have h_dim_eq : ringKrullDim (R ⧸ I) = d := le_antisymm h_dim_upper h_dim_lower
  have h_reg : IsRegularLocalRing (R ⧸ I) := by
    apply IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
    simpa only [h_dim_eq] using h_spanFinrank_le
  exact ⟨h_reg, h_dim_eq⟩

/-- A zero-dimensional regular local ring is a domain. -/
lemma IsRegularLocalRing.isDomain_of_ringKrullDim_zero
    (h_dim : ringKrullDim R = 0) (h_reg : IsRegularLocalRing R) : IsDomain R := by
  haveI : IsRegularLocalRing R := h_reg
  have hfin : Module.finrank (ResidueField R) (CotangentSpace R) = 0 := by
    have h := (IsRegularLocalRing.iff_finrank_cotangentSpace R).mp h_reg
    rw [h_dim] at h
    exact_mod_cast h
  have : IsField R := IsLocalRing.finrank_cotangentSpace_eq_zero_iff.mp hfin
  letI := this.toField
  exact inferInstance

/-- A regular local ring of finite Krull dimension is a domain. -/
lemma IsRegularLocalRing.isDomain_of_ringKrullDim [IsNoetherianRing R]
    {d : ℕ} (h_dim : ringKrullDim R = (d : WithBot ℕ∞))
    (h_reg : IsRegularLocalRing R) : IsDomain R := by
  induction d using Nat.strong_induction_on generalizing R with
  | h d ih =>
    cases d with
    | zero => exact IsRegularLocalRing.isDomain_of_ringKrullDim_zero h_dim h_reg
    | succ d' =>
      haveI : IsRegularLocalRing R := h_reg
      obtain ⟨x, hx_m, hx_m2, hx_avoid⟩ :=
        IsLocalRing.exists_mem_maximalIdeal_notMem_pow_two_notMem_minimalPrimes h_dim
      have hI_ne : Ideal.span {x} ≠ (⊤ : Ideal R) :=
        Ideal.span_singleton_ne_top (mem_nonunits_iff.mp hx_m)
      letI : Nontrivial (R ⧸ Ideal.span {x}) :=
        Ideal.Quotient.nontrivial_iff.mpr hI_ne
      letI : IsLocalRing (R ⧸ Ideal.span {x}) :=
        IsLocalRing.of_surjective' (Ideal.Quotient.mk _) Ideal.Quotient.mk_surjective
      obtain ⟨h_reg_quot, h_dim_quot⟩ :=
        IsRegularLocalRing.quotient_of_notMem_pow_two h_dim x hx_m hx_m2
      have h_ih : IsDomain (R ⧸ Ideal.span {x}) :=
        ih d' (Nat.lt_succ_self d') h_dim_quot h_reg_quot
      have h_prime : (Ideal.span {x}).IsPrime :=
        (Ideal.Quotient.isDomain_iff_prime _).mp h_ih
      exact IsLocalRing.isDomain_of_quotient_isDomain x hx_m h_prime hx_avoid

/-- **Stacks 00NP** (`algebra-lemma-regular-domain`): every regular local ring is a
domain. -/
@[stacks 00NP]
lemma IsRegularLocalRing.isDomain [IsRegularLocalRing R] : IsDomain R := by
  have h := (IsRegularLocalRing.iff_finrank_cotangentSpace R).mp inferInstance
  obtain ⟨d, hd⟩ : ∃ d : ℕ, ringKrullDim R = (d : WithBot ℕ∞) :=
    ⟨Module.finrank (ResidueField R) (CotangentSpace R), h.symm⟩
  exact IsRegularLocalRing.isDomain_of_ringKrullDim hd inferInstance

/-- The maximal ideal of a regular local ring admits a finite generating set whose cardinality
is the Krull dimension. -/
lemma IsRegularLocalRing.maximalIdeal_generated_by_dim [IsRegularLocalRing R] :
    ∃ s : Finset R, Ideal.span (s : Set R) = maximalIdeal R ∧
      (s.card : WithBot ℕ∞) = ringKrullDim R := by
  obtain ⟨s, hs_card, hs_span⟩ :=
    (IsNoetherian.noetherian (maximalIdeal R)).exists_span_finset_card_eq_spanFinrank
  refine ⟨s, hs_span, ?_⟩
  rw [hs_card]
  exact_mod_cast IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)

/-- A linearly independent family in the cotangent space of a regular local ring extends to a
minimal generating family of its maximal ideal. -/
lemma IsRegularLocalRing.exists_maximalIdeal_generators_append [IsRegularLocalRing R]
    {c w : ℕ} (h_dim : ringKrullDim R = ((c + w : ℕ) : WithBot ℕ∞))
    (f : Fin c → maximalIdeal R)
    (hf_ind : LinearIndependent (ResidueField R)
      fun i => (maximalIdeal R).toCotangent (f i)) :
    ∃ x : Fin (c + w) → maximalIdeal R,
      Ideal.span (Set.range fun i => (x i : R)) = maximalIdeal R ∧
      ∀ i : Fin c, x (Fin.castAdd w i) = f i := by
  classical
  have h_finrank : Module.finrank (ResidueField R) (CotangentSpace R) = c + w := by
    have h := (IsRegularLocalRing.iff_finrank_cotangentSpace R).mp inferInstance
    rw [h_dim] at h
    exact_mod_cast h
  set k := ResidueField R with hk
  set vf : Fin c → CotangentSpace R := fun i => (maximalIdeal R).toCotangent (f i) with hvf
  obtain ⟨W, hW⟩ := Submodule.exists_isCompl (Submodule.span k (Set.range vf))
  have h_rank_span : Module.finrank k (Submodule.span k (Set.range vf)) = c := by
    rw [finrank_span_eq_card hf_ind, Fintype.card_fin]
  have h_rank_W : Module.finrank k W = w := by
    have h_sum := Submodule.finrank_add_eq_of_isCompl hW
    rw [h_rank_span, h_finrank] at h_sum
    omega
  let BW := Module.finBasis k W
  let vg : Fin w → CotangentSpace R := fun i => (BW (Fin.cast h_rank_W.symm i) : W)
  choose g hg using fun i => (maximalIdeal R).toCotangent_surjective (vg i)
  set x : Fin (c + w) → maximalIdeal R := Fin.append f g with hx
  have h_classes : (fun i => (maximalIdeal R).toCotangent (x i)) = Fin.append vf vg := by
    funext i
    refine Fin.addCases (fun j => ?_) (fun j => ?_) i
    · rw [hx, Fin.append_left, Fin.append_left]
    · rw [hx, Fin.append_right, Fin.append_right, hg]
  have h_span_vg : Submodule.span k (Set.range vg) = W := by
    have h_img : Set.range vg = W.subtype '' Set.range BW := by
      ext y
      constructor
      · rintro ⟨i, rfl⟩
        exact ⟨BW (Fin.cast h_rank_W.symm i), ⟨Fin.cast h_rank_W.symm i, rfl⟩, rfl⟩
      · rintro ⟨y, ⟨j, rfl⟩, rfl⟩
        exact ⟨Fin.cast h_rank_W j, rfl⟩
    rw [h_img, ← Submodule.map_span, BW.span_eq, Submodule.map_top,
      Submodule.range_subtype]
  have h_span_classes :
      Submodule.span k (Set.range fun i => (maximalIdeal R).toCotangent (x i)) = ⊤ := by
    have h_range : Set.range (Fin.append vf vg) = Set.range vf ∪ Set.range vg := by
      ext z
      constructor
      · rintro ⟨i, rfl⟩
        refine Fin.addCases (fun j => ?_) (fun j => ?_) i
        · exact Set.mem_union_left _ ⟨j, (Fin.append_left vf vg j).symm⟩
        · exact Set.mem_union_right _ ⟨j, (Fin.append_right vf vg j).symm⟩
      · rintro (⟨i, rfl⟩ | ⟨i, rfl⟩)
        · exact ⟨Fin.castAdd w i, Fin.append_left vf vg i⟩
        · exact ⟨Fin.natAdd c i, Fin.append_right vf vg i⟩
    rw [h_classes, h_range, Submodule.span_union, h_span_vg]
    exact hW.sup_eq_top
  have h_span_x : Ideal.span (Set.range fun i => (x i : R)) = maximalIdeal R := by
    have h_top : Submodule.span R (Set.range x) = ⊤ := by
      rw [← IsLocalRing.CotangentSpace.span_image_eq_top_iff, ← Set.range_comp]
      exact h_span_classes
    have h_map := congrArg (Submodule.map (maximalIdeal R).subtype) h_top
    rw [Submodule.map_span, Submodule.map_top, Submodule.range_subtype,
      ← Set.range_comp] at h_map
    exact h_map
  exact ⟨x, h_span_x, fun i => Fin.append_left f g i⟩

/-- Membership in a finitely generated ideal gives membership in the span of the corresponding
cotangent classes. -/
lemma IsLocalRing.toCotangent_mem_span_of_mem_span {n : ℕ} {v : Fin n → R}
    (hv : ∀ i, v i ∈ maximalIdeal R) {t : R} (ht : t ∈ maximalIdeal R)
    (htv : t ∈ Ideal.span (Set.range v)) :
    (maximalIdeal R).toCotangent ⟨t, ht⟩ ∈ Submodule.span (ResidueField R)
      (Set.range fun i => (maximalIdeal R).toCotangent ⟨v i, hv i⟩) := by
  rw [← Ideal.submodule_span_eq] at htv
  obtain ⟨a, ha⟩ := (Submodule.mem_span_range_iff_exists_fun R).mp htv
  have h_eq : (⟨t, ht⟩ : maximalIdeal R) =
      ∑ i, a i • (⟨v i, hv i⟩ : maximalIdeal R) := by
    apply Subtype.ext
    push_cast
    simp only [smul_eq_mul]
    exact ha.symm
  rw [h_eq, map_sum]
  refine Submodule.sum_mem _ fun i _ => ?_
  rw [map_smul, ← algebraMap_smul (ResidueField R) (a i)]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- **Stacks 00NR** (`algebra-lemma-regular-quotient-regular`): for a surjection between
regular local rings, the kernel is generated by elements of the maximal ideal whose classes
in the cotangent space are linearly independent. This is the minimal-generator formulation
used in the proof of 00TV. -/
@[stacks 00NR]
lemma IsRegularLocalRing.exists_span_range_eq_ker
    {P A : Type u} [CommRing P] [CommRing A]
    [IsRegularLocalRing P] [IsRegularLocalRing A]
    (rho : P →+* A) (hsurj : Function.Surjective rho) :
    ∃ (c : ℕ) (f : Fin c → maximalIdeal P),
      (∀ i, (f i : P) ∈ RingHom.ker rho) ∧
      Ideal.span (Set.range fun i => (f i : P)) = RingHom.ker rho ∧
      LinearIndependent (ResidueField P)
        fun i => (maximalIdeal P).toCotangent (f i) := by
  classical
  set k := ResidueField P with hk
  set I : Ideal P := RingHom.ker rho with hI
  have hI_ne_top : I ≠ ⊤ := by
    intro h
    have h1 : rho 1 = 0 := RingHom.mem_ker.mp (by
      rw [← hI, h]
      exact Submodule.mem_top)
    simp at h1
  have hI_le : I ≤ maximalIdeal P := IsLocalRing.le_maximalIdeal hI_ne_top
  obtain ⟨sA, hsA_span, hsA_card⟩ :=
    IsRegularLocalRing.maximalIdeal_generated_by_dim (R := A)
  set d := sA.card with hd
  have h_dimA : ringKrullDim A = (d : WithBot ℕ∞) := hsA_card.symm
  obtain ⟨sP, hsP_span, hsP_card⟩ :=
    IsRegularLocalRing.maximalIdeal_generated_by_dim (R := P)
  set e := sP.card with he
  have h_dimP : ringKrullDim P = (e : WithBot ℕ∞) := hsP_card.symm
  have h_finrankP : Module.finrank k (CotangentSpace P) = e := by
    have hreg := (IsRegularLocalRing.iff_finrank_cotangentSpace P).mp inferInstance
    rw [h_dimP] at hreg
    exact_mod_cast hreg
  set SI : Set (CotangentSpace P) :=
    (maximalIdeal P).toCotangent '' {t : maximalIdeal P | (t : P) ∈ I} with hSI
  obtain ⟨b, hb_sub, hb_span, hb_ind⟩ := exists_linearIndependent k SI
  have hb_fin : b.Finite := hb_ind.setFinite
  set c := hb_fin.toFinset.card with hc
  set en : Fin c → b := fun i =>
    (Equiv.subtypeEquivRight fun x => hb_fin.mem_toFinset)
      (hb_fin.toFinset.equivFin.symm i) with hen
  have hen_surj : Function.Surjective en :=
    (Equiv.subtypeEquivRight fun x => hb_fin.mem_toFinset).surjective.comp
      hb_fin.toFinset.equivFin.symm.surjective
  have hen_inj : Function.Injective en :=
    (Equiv.subtypeEquivRight fun x => hb_fin.mem_toFinset).injective.comp
      hb_fin.toFinset.equivFin.symm.injective
  have h_lift : ∀ i : Fin c, ∃ t : maximalIdeal P, (t : P) ∈ I ∧
      (maximalIdeal P).toCotangent t = (en i : CotangentSpace P) := by
    intro i
    obtain ⟨t, ht, hteq⟩ := hb_sub (en i).2
    exact ⟨t, ht, hteq⟩
  choose f hfI hf_class using h_lift
  have hf_class' : (fun i => (maximalIdeal P).toCotangent (f i)) =
      fun i => ((en i : b) : CotangentSpace P) := funext hf_class
  have hf_ind : LinearIndependent k fun i => (maximalIdeal P).toCotangent (f i) := by
    rw [hf_class']
    exact hb_ind.comp en hen_inj
  have h_range_class : Set.range (fun i => (maximalIdeal P).toCotangent (f i)) = b := by
    rw [hf_class']
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      exact (en i).2
    · intro hz
      obtain ⟨i, hi⟩ := hen_surj ⟨z, hz⟩
      exact ⟨i, by simp [hi]⟩
  have h_spanV :
      Submodule.span k (Set.range fun i => (maximalIdeal P).toCotangent (f i)) =
        Submodule.span k SI := by
    rw [h_range_class, hb_span]
  have hce : c ≤ e := by
    have h1 : Module.finrank k
        (Submodule.span k (Set.range fun i => (maximalIdeal P).toCotangent (f i))) = c := by
      rw [finrank_span_eq_card hf_ind, Fintype.card_fin]
    have h2 := (Submodule.span k
      (Set.range fun i => (maximalIdeal P).toCotangent (f i))).finrank_le
    rw [h1, h_finrankP] at h2
    exact h2
  set w := e - c with hw
  have h_dimP' : ringKrullDim P = ((c + w : ℕ) : WithBot ℕ∞) := by
    rw [h_dimP]
    congr 1
    omega
  obtain ⟨xs, hxs_span, hxs_agree⟩ :=
    IsRegularLocalRing.exists_maximalIdeal_generators_append h_dimP' f hf_ind
  have hcle : c ≤ c + w := Nat.le_add_right c w
  set pre : Fin c → P := fun i => (xs (Fin.castLE hcle i) : P) with hpre
  set J0 : Ideal P := Ideal.span (Set.range pre) with hJ0
  have hJ0_eq : J0 = Ideal.span (Set.range fun i : Fin c => (f i : P)) := by
    have hfun : pre = fun i : Fin c => (f i : P) := by
      funext i
      have hcast : Fin.castLE hcle i = Fin.castAdd w i := by ext; simp
      change (xs (Fin.castLE hcle i) : P) = (f i : P)
      rw [hcast, hxs_agree i]
    rw [hJ0, hfun]
  have hJ0_le : J0 ≤ I := by
    rw [hJ0_eq, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact hfI i
  have hJ0_ne : J0 ≠ ⊤ := fun htop => hI_ne_top (top_unique (htop ▸ hJ0_le))
  letI : Nontrivial (P ⧸ J0) := Ideal.Quotient.nontrivial_iff.mpr hJ0_ne
  letI : IsLocalRing (P ⧸ J0) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk J0) Ideal.Quotient.mk_surjective
  letI : IsLocalHom (Ideal.Quotient.mk J0) :=
    IsLocalHom.of_surjective (Ideal.Quotient.mk J0) Ideal.Quotient.mk_surjective
  have h_map_m : (maximalIdeal P).map (Ideal.Quotient.mk J0) =
      maximalIdeal (P ⧸ J0) := by
    ext z
    obtain ⟨z, rfl⟩ := Ideal.Quotient.mk_surjective z
    simp [sup_eq_left.mpr (hJ0_le.trans hI_le)]
  set suffix : Fin w → P := fun i => (xs (Fin.natAdd c i) : P) with hsuffix
  set suffixQ : Fin w → P ⧸ J0 := fun i => Ideal.Quotient.mk J0 (suffix i) with hsuffixQ
  have h_range_x : Set.range (fun i => (xs i : P)) =
      Set.range pre ∪ Set.range suffix := by
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      refine Fin.addCases (fun j => ?_) (fun j => ?_) i
      · exact Set.mem_union_left _ ⟨j, rfl⟩
      · exact Set.mem_union_right _ ⟨j, rfl⟩
    · rintro (⟨i, rfl⟩ | ⟨i, rfl⟩)
      · exact ⟨Fin.castAdd w i, rfl⟩
      · exact ⟨Fin.natAdd c i, rfl⟩
  have h_prefix_bot :
      Ideal.span (Ideal.Quotient.mk J0 '' Set.range pre) = ⊥ := by
    rw [Ideal.span_eq_bot]
    rintro z ⟨y, ⟨i, rfl⟩, rfl⟩
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    rw [hJ0]
    exact Ideal.subset_span ⟨i, rfl⟩
  have h_suffix_image : Ideal.Quotient.mk J0 '' Set.range suffix = Set.range suffixQ := by
    rw [← Set.range_comp]
    rfl
  have h_span_suffixQ : Ideal.span (Set.range suffixQ) = maximalIdeal (P ⧸ J0) := by
    rw [← h_map_m, ← hxs_span, Ideal.map_span, h_range_x, Set.image_union,
      Ideal.span_union, h_prefix_bot, h_suffix_image]
    simp
  have h_spanrank_B : (maximalIdeal (P ⧸ J0)).spanFinrank ≤ w := by
    rw [← h_span_suffixQ]
    refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range suffixQ)).trans ?_
    simpa [← Set.image_univ] using
      (Set.ncard_image_le (f := suffixQ) (s := Set.univ))
  have h_dim_upper : ringKrullDim (P ⧸ J0) ≤ (w : WithBot ℕ∞) :=
    (ringKrullDim_le_spanFinrank_maximalIdeal _).trans (by exact_mod_cast h_spanrank_B)
  have hJ0_rank : J0.spanFinrank ≤ c := by
    rw [hJ0]
    refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range pre)).trans ?_
    simpa [← Set.image_univ] using
      (Set.ncard_image_le (f := pre) (s := Set.univ))
  have h_dim_lower : (w : WithBot ℕ∞) ≤ ringKrullDim (P ⧸ J0) := by
    have h_sum_bound : ((c + w : ℕ) : WithBot ℕ∞) ≤
        ringKrullDim (P ⧸ J0) + c := calc
      (c : WithBot ℕ∞) + w = (e : WithBot ℕ∞) := by
        exact_mod_cast (Nat.add_sub_of_le hce)
      _ = ringKrullDim P := h_dimP.symm
      _ ≤ ringKrullDim (P ⧸ J0) + J0.spanFinrank :=
        ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank J0
          ((hJ0_le.trans hI_le).trans_eq (IsLocalRing.ringJacobson_eq_maximalIdeal P).symm)
      _ ≤ ringKrullDim (P ⧸ J0) + c := by
        gcongr
    obtain ⟨D, hD⟩ := WithBot.ne_bot_iff_exists.mp
      (ringKrullDim_ne_bot (R := P ⧸ J0))
    have h_sum_bound' : (c + w : ℕ∞) ≤ D + c := by
      rw [← hD] at h_sum_bound
      exact_mod_cast h_sum_bound
    have hwD : (w : ℕ∞) ≤ D := by
      apply (ENat.add_le_add_iff_left (k := (c : ℕ∞)) (by simp)).mp
      simpa only [Nat.cast_add, add_comm D (c : ℕ∞)] using h_sum_bound'
    rw [← hD]
    exact_mod_cast hwD
  have h_dimB : ringKrullDim (P ⧸ J0) = (w : WithBot ℕ∞) :=
    le_antisymm h_dim_upper h_dim_lower
  have h_regB : IsRegularLocalRing (P ⧸ J0) := by
    apply IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
    rw [h_dimB]
    exact_mod_cast h_spanrank_B
  -- The remainder of the proof shows that the induced map from this regular quotient to
  -- `A` is injective by comparing dimensions.
  set rhobar : P ⧸ J0 →+* A :=
    Ideal.Quotient.lift J0 rho (fun a ha => RingHom.mem_ker.mp (hJ0_le ha)) with hrhobar
  have hrhobar_surj : Function.Surjective rhobar := by
    intro a
    obtain ⟨p, rfl⟩ := hsurj a
    exact ⟨Ideal.Quotient.mk J0 p, Ideal.Quotient.lift_mk J0 _ _⟩
  have h_dimQ : ringKrullDim ((P ⧸ J0) ⧸ RingHom.ker rhobar) =
      (d : WithBot ℕ∞) := by
    rw [ringKrullDim_eq_of_ringEquiv (RingHom.quotientKerEquivOfSurjective hrhobar_surj)]
    exact h_dimA
  have h_d_le_w : (d : WithBot ℕ∞) ≤ (w : WithBot ℕ∞) := by
    rw [← h_dimQ, ← h_dimB]
    exact ringKrullDim_quotient_le _
  set xA : Fin d → A := fun i => (sA.equivFin.symm i : A) with hxA
  have hxA_range : Set.range xA = (sA : Set A) := by
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      exact (sA.equivFin.symm i).2
    · intro hz
      exact ⟨sA.equivFin ⟨z, hz⟩, by rw [hxA]; simp⟩
  have hxA_span : Ideal.span (Set.range xA) = maximalIdeal A := by
    rw [hxA_range, hsA_span]
  choose y hy using fun i => hsurj (xA i)
  have h_map_mem : ∀ t ∈ maximalIdeal P, rho t ∈ maximalIdeal A := by
    intro t ht
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
    intro hu
    obtain ⟨a, ha⟩ := hu.exists_right_inv
    obtain ⟨u, rfl⟩ := hsurj a
    have hker : t * u - 1 ∈ I := by
      rw [hI, RingHom.mem_ker, map_sub, map_mul, map_one, ha, sub_self]
    have h1 : (1 : P) ∈ maximalIdeal P := by
      have h2 := Ideal.sub_mem _ (Ideal.mul_mem_right u _ ht) (hI_le hker)
      simpa using h2
    exact (IsLocalRing.maximalIdeal.isMaximal P).ne_top
      (Ideal.eq_top_of_isUnit_mem _ h1 isUnit_one)
  have h_comap : ∀ t : P, rho t ∈ maximalIdeal A → t ∈ maximalIdeal P := by
    intro t ht
    by_contra htm
    have hu : IsUnit t := by
      by_contra hnu
      exact htm ((IsLocalRing.mem_maximalIdeal t).mpr hnu)
    rw [IsLocalRing.mem_maximalIdeal] at ht
    exact ht (hu.map rho)
  have hy_mem : ∀ i, y i ∈ maximalIdeal P := fun i => h_comap (y i) (by
    rw [hy i]
    exact hxA_span ▸ Ideal.subset_span ⟨i, rfl⟩)
  have hm_le : maximalIdeal P ≤ I ⊔ Ideal.span (Set.range y) := by
    intro t ht
    have h1 : rho t ∈ Ideal.span (Set.range xA) := hxA_span.symm ▸ h_map_mem t ht
    rw [← Ideal.submodule_span_eq] at h1
    obtain ⟨a, ha⟩ := (Submodule.mem_span_range_iff_exists_fun A).mp h1
    choose bcoef hbcoef using fun i => hsurj (a i)
    have hker : t - ∑ i, bcoef i * y i ∈ I := by
      rw [hI, RingHom.mem_ker, map_sub, map_sum]
      simp only [map_mul, hbcoef, hy]
      rw [sub_eq_zero, ← ha]
      exact Finset.sum_congr rfl fun i _ => (smul_eq_mul _ _).symm
    have hsplit : t = (t - ∑ i, bcoef i * y i) + ∑ i, bcoef i * y i := by ring
    rw [hsplit]
    exact Submodule.add_mem _ (Submodule.mem_sup_left hker) (Submodule.mem_sup_right
      (Ideal.sum_mem _ fun i _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)))
  have h_e_le : e ≤ c + d := by
    have h_span_top : Submodule.span k (Set.range (Sum.elim
        (fun i : Fin c => (maximalIdeal P).toCotangent (f i))
        (fun i : Fin d => (maximalIdeal P).toCotangent ⟨y i, hy_mem i⟩))) = ⊤ := by
      rw [Set.Sum.elim_range, Submodule.span_union, eq_top_iff]
      rintro z -
      obtain ⟨⟨t, ht⟩, rfl⟩ := (maximalIdeal P).toCotangent_surjective z
      obtain ⟨t1, ht1, t2, ht2, hts⟩ := Submodule.mem_sup.mp (hm_le ht)
      have ht1m : t1 ∈ maximalIdeal P := hI_le ht1
      have ht2m : t2 ∈ maximalIdeal P := by
        refine Ideal.span_le.mpr ?_ ht2
        rintro _ ⟨i, rfl⟩
        exact hy_mem i
      have h_eq : (⟨t, ht⟩ : maximalIdeal P) = ⟨t1, ht1m⟩ + ⟨t2, ht2m⟩ := by
        apply Subtype.ext
        exact hts.symm
      rw [h_eq, map_add]
      refine Submodule.add_mem _ (Submodule.mem_sup_left ?_) (Submodule.mem_sup_right ?_)
      · rw [h_spanV]
        exact Submodule.subset_span ⟨⟨t1, ht1m⟩, ht1, rfl⟩
      · exact IsLocalRing.toCotangent_mem_span_of_mem_span hy_mem ht2m ht2
    have h_card := finrank_le_of_span_eq_top h_span_top
    rw [h_finrankP] at h_card
    simpa using h_card
  have h_w_eq_d : w = d := by
    have h_d_le_w' : d ≤ w := by exact_mod_cast h_d_le_w
    omega
  have h_ker_bot : RingHom.ker rhobar = ⊥ := by
    by_contra hne
    obtain ⟨z0, hz0_mem, hz0_ne⟩ := (Submodule.ne_bot_iff _).mp hne
    letI : IsRegularLocalRing (P ⧸ J0) := h_regB
    letI : IsDomain (P ⧸ J0) := IsRegularLocalRing.isDomain
    have hz0_nzd : z0 ∈ nonZeroDivisors (P ⧸ J0) :=
      mem_nonZeroDivisors_of_ne_zero hz0_ne
    have h1 := ringKrullDim_quotient_succ_le_of_nonZeroDivisor hz0_nzd
    have h2 : ringKrullDim ((P ⧸ J0) ⧸ RingHom.ker rhobar) ≤
        ringKrullDim ((P ⧸ J0) ⧸ Ideal.span {z0}) := by
      have hle : Ideal.span {z0} ≤ RingHom.ker rhobar := by
        rw [Ideal.span_le, Set.singleton_subset_iff]
        exact hz0_mem
      rw [← ringKrullDim_eq_of_ringEquiv (DoubleQuot.quotQuotEquivQuotOfLE hle)]
      exact ringKrullDim_quotient_le _
    have h3 : ((d + 1 : ℕ) : WithBot ℕ∞) ≤ ((d : ℕ) : WithBot ℕ∞) := by
      calc
        ((d + 1 : ℕ) : WithBot ℕ∞) = ((d : ℕ) : WithBot ℕ∞) + 1 := by
          push_cast
          ring
        _ ≤ ringKrullDim ((P ⧸ J0) ⧸ Ideal.span {z0}) + 1 := by
          rw [← h_dimQ]
          exact add_le_add h2 le_rfl
        _ ≤ ringKrullDim (P ⧸ J0) := h1
        _ = ((d : ℕ) : WithBot ℕ∞) := by rw [h_dimB, h_w_eq_d]
    have h4 : d + 1 ≤ d := by exact_mod_cast h3
    omega
  have h_I_eq : Ideal.span (Set.range fun i => (f i : P)) = I := by
    refine le_antisymm (Ideal.span_le.mpr ?_) ?_
    · rintro _ ⟨i, rfl⟩
      exact hfI i
    · intro t ht
      have h0 : Ideal.Quotient.mk J0 t ∈ RingHom.ker rhobar := by
        rw [RingHom.mem_ker, hrhobar, Ideal.Quotient.lift_mk]
        exact RingHom.mem_ker.mp ht
      rw [h_ker_bot, Submodule.mem_bot] at h0
      have h5 : t ∈ J0 := Ideal.Quotient.eq_zero_iff_mem.mp h0
      rwa [hJ0_eq] at h5
  exact ⟨c, f, hfI, h_I_eq.trans (by rw [hI]), hf_ind⟩

open KaehlerDifferential

/-- A surjective map from a formally smooth regular local algebra with finite free Kähler
differentials to a regular local algebra is formally smooth when the target residue field is
formally smooth. -/
theorem Algebra.FormallySmooth.of_surjective_of_isRegularLocalRing
    (k : Type u) {P A : Type u}
    [Field k] [CommRing P] [CommRing A] [Algebra k P] [Algebra k A] [Algebra P A]
    [IsScalarTower k P A] [Algebra.FormallySmooth k P]
    [Module.Free P (Ω[P⁄k])] [Module.Finite P (Ω[P⁄k])]
    [IsRegularLocalRing P] [IsRegularLocalRing A]
    (hsurj : Function.Surjective (algebraMap P A))
    [Algebra.FormallySmooth k (ResidueField A)] :
    Algebra.FormallySmooth k A := by
  classical
  set kap := ResidueField P with hkap
  letI : IsLocalHom (algebraMap P A) := IsLocalHom.of_surjective _ hsurj
  have h_res_bij : Function.Bijective (ResidueField.map (algebraMap P A)) := by
    constructor
    · exact (ResidueField.map (algebraMap P A)).injective
    · intro z
      obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective z
      obtain ⟨p, rfl⟩ := hsurj a
      exact ⟨IsLocalRing.residue P p, ResidueField.map_residue _ _⟩
  set eRes : kap ≃+* ResidueField A := RingEquiv.ofBijective _ h_res_bij with heRes
  letI : Algebra A kap :=
    ((eRes.symm : ResidueField A →+* kap).comp (IsLocalRing.residue A)).toAlgebra
  have h_algAkap : ∀ a : A, algebraMap A kap a =
      eRes.symm (IsLocalRing.residue A a) := fun _ => rfl
  letI : IsScalarTower P A kap := IsScalarTower.of_algebraMap_eq fun p => by
    have h1 : algebraMap A kap (algebraMap P A p) =
        eRes.symm (eRes (IsLocalRing.residue P p)) := by
      rw [h_algAkap, ← ResidueField.map_residue (algebraMap P A) p]
      rfl
    rw [h1, eRes.symm_apply_apply]
    rfl
  have h_ker_Akap : maximalIdeal A ≤ RingHom.ker (algebraMap A kap) := by
    intro a ha
    rw [RingHom.mem_ker, h_algAkap]
    have h0 : IsLocalRing.residue A a = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr ha
    rw [h0, map_zero]
  letI : Algebra.FormallySmooth k kap := by
    refine Algebra.FormallySmooth.of_equiv
      (AlgEquiv.ofRingEquiv (f := eRes.symm) fun x => ?_)
    rw [IsScalarTower.algebraMap_apply k A (ResidueField A) x,
      IsScalarTower.algebraMap_apply k P A x]
    have h1 : algebraMap A (ResidueField A) (algebraMap P A (algebraMap k P x)) =
        eRes (IsLocalRing.residue P (algebraMap k P x)) :=
      (ResidueField.map_residue (algebraMap P A) (algebraMap k P x)).symm
    rw [h1, eRes.symm_apply_apply]
    rw [IsScalarTower.algebraMap_apply k P kap x]
    rfl
  have h_res_surj : Function.Surjective (algebraMap P kap) :=
    Ideal.Quotient.mk_surjective
  have h_ker_fg' : (RingHom.ker (algebraMap P kap)).FG := IsNoetherian.noetherian _
  have h_bot : maximalIdeal kap ≤ RingHom.ker (algebraMap kap kap) := by
    rw [IsLocalRing.maximalIdeal_eq_bot]
    exact bot_le
  have hPhikap_inj : Function.Injective (cotangentComplexBaseChange k kap P kap) :=
    (Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange
      (R := k) (S := kap) P kap h_res_surj h_ker_fg' h_bot).mp inferInstance
  have h_ker_fg : (RingHom.ker (algebraMap P A)).FG := IsNoetherian.noetherian _
  rw [Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange
    (R := k) (S := A) P kap hsurj h_ker_fg h_ker_Akap]
  obtain ⟨c, f, hfI, h_span, hf_ind⟩ :=
    IsRegularLocalRing.exists_span_range_eq_ker (algebraMap P A) hsurj
  set g : Fin c → RingHom.ker (algebraMap P A) :=
    fun i => ⟨(f i : P), hfI i⟩ with hg
  have h_span_g : Submodule.span P (Set.range g) = ⊤ := by
    apply Submodule.map_injective_of_injective
      (Submodule.injective_subtype (RingHom.ker (algebraMap P A)))
    rw [Submodule.map_span, Submodule.map_top, Submodule.range_subtype, ← Set.range_comp]
    exact h_span
  have h_span_tensor : Submodule.span kap (Set.range fun i =>
      ((1 : kap) ⊗ₜ[P] g i : kap ⊗[P] RingHom.ker (algebraMap P A))) = ⊤ := by
    rw [Submodule.eq_top_iff']
    intro z
    induction z using TensorProduct.induction_on with
    | zero => exact Submodule.zero_mem _
    | tmul a m =>
      have hm : m ∈ Submodule.span P (Set.range g) := h_span_g.symm ▸ Submodule.mem_top
      obtain ⟨p, hp⟩ := (Submodule.mem_span_range_iff_exists_fun P).mp hm
      rw [← hp, tmul_sum]
      refine Submodule.sum_mem _ fun i _ => ?_
      rw [tmul_smul, ← algebraMap_smul kap (p i)]
      refine Submodule.smul_mem _ _ ?_
      have ha : a ⊗ₜ[P] g i = a • ((1 : kap) ⊗ₜ[P] g i) := by
        rw [TensorProduct.smul_tmul', smul_eq_mul, mul_one]
      rw [ha]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)
    | add x y hx hy => exact Submodule.add_mem _ hx hy
  have h_kerPkap : RingHom.ker (algebraMap P kap) = maximalIdeal P := by
    change RingHom.ker (Ideal.Quotient.mk (maximalIdeal P)) = maximalIdeal P
    exact Ideal.mk_ker
  set g' : Fin c → RingHom.ker (algebraMap P kap) :=
    fun i => ⟨(f i : P), h_kerPkap.symm ▸ (f i).2⟩ with hg'
  have h_ind_g' : LinearIndependent kap fun i =>
      ((1 : kap) ⊗ₜ[P] g' i : kap ⊗[P] RingHom.ker (algebraMap P kap)) := by
    set psi : kap ⊗[P] RingHom.ker (algebraMap P kap) →ₗ[kap] CotangentSpace P :=
      LinearMap.liftBaseChange kap
        ((maximalIdeal P).toCotangent ∘ₗ Submodule.inclusion h_kerPkap.le) with hpsi
    refine LinearIndependent.of_comp psi ?_
    have hpsig : (⇑psi ∘ fun i =>
        ((1 : kap) ⊗ₜ[P] g' i : kap ⊗[P] RingHom.ker (algebraMap P kap))) =
        fun i => (maximalIdeal P).toCotangent (f i) := by
      funext i
      simp only [Function.comp_apply, hpsi, LinearMap.liftBaseChange_tmul, one_smul,
        LinearMap.comp_apply]
      congr 1
    rw [hpsig]
    exact hf_ind
  have h_ind_imgkap : LinearIndependent kap fun i =>
      cotangentComplexBaseChange k kap P kap ((1 : kap) ⊗ₜ[P] g' i) :=
    h_ind_g'.map' _ (LinearMap.ker_eq_bot.mpr hPhikap_inj)
  have h_img_eq : (⇑(cotangentComplexBaseChange k A P kap) ∘
      fun i => (1 : kap) ⊗ₜ[P] g i) =
      fun i => cotangentComplexBaseChange k kap P kap ((1 : kap) ⊗ₜ[P] g' i) := by
    funext i
    simp only [Function.comp_apply, cotangentComplexBaseChange_tmul]
    congr 1
  have h_ind_img : LinearIndependent kap
      (⇑(cotangentComplexBaseChange k A P kap) ∘
        fun i => (1 : kap) ⊗ₜ[P] g i) := by
    rw [h_img_eq]
    exact h_ind_imgkap
  exact LinearMap.injective_of_linearIndependent h_span_tensor h_ind_img

/-- The Kähler differentials of a polynomial ring localized at a prime form a free module. -/
lemma KaehlerDifferential.free_of_isLocalization_atPrime
    {k : Type u} [Field k] (n : ℕ)
    (q : Ideal (MvPolynomial (Fin n) k)) [q.IsPrime] :
    Module.Free (Localization.AtPrime q)
      (Ω[Localization.AtPrime q⁄k]) :=
  Module.free_of_isLocalizedModule q.primeCompl
    (KaehlerDifferential.map k k (MvPolynomial (Fin n) k) (Localization.AtPrime q))

/-- **Stacks 00TV** (`algebra-lemma-separable-smooth`), regular-local direction: if `S` is a
finite type algebra over a field, the residue field at `q` is formally smooth, and `S_q` is a
regular local ring, then `S_q` is formally smooth over the base field. -/
@[stacks 00TV "regular local ring implies smooth at the prime"]
theorem Algebra.FormallySmooth.of_isRegularLocalRing_localization_atPrime
    (k S : Type u) [Field k] [CommRing S] [Algebra k S] [Algebra.FiniteType k S]
    (q : Ideal S) [q.IsPrime]
    [Algebra.FormallySmooth k q.ResidueField]
    [IsRegularLocalRing (Localization.AtPrime q)] :
    Algebra.FormallySmooth k (Localization.AtPrime q) := by
  classical
  obtain ⟨n, phi, hphi_surj⟩ := Algebra.FiniteType.iff_quotient_mvPolynomial''.mp
    (inferInstance : Algebra.FiniteType k S)
  set R0 := MvPolynomial (Fin n) k with hR0
  set q0 : Ideal R0 := q.comap (phi : R0 →+* S) with hq0
  letI : q0.IsPrime := Ideal.IsPrime.comap _
  set P := Localization.AtPrime q0 with hP
  set rho : P →+* Localization.AtPrime q :=
    Localization.localRingHom q0 q (phi : R0 →+* S) rfl with hrho
  have hrho_surj : Function.Surjective rho := by
    intro z
    obtain ⟨x, y, rfl⟩ := IsLocalization.exists_mk'_eq q.primeCompl z
    obtain ⟨x', rfl⟩ := hphi_surj x
    obtain ⟨y', hy'⟩ := hphi_surj (y : S)
    have hy'_mem : y' ∈ q0.primeCompl := fun hmem => y.2 (by rw [← hy']; exact hmem)
    refine ⟨IsLocalization.mk' P x' ⟨y', hy'_mem⟩, ?_⟩
    rw [hrho, Localization.localRingHom_mk']
    congr 1
    exact Subtype.ext hy'
  letI : Algebra P (Localization.AtPrime q) := rho.toAlgebra
  have h_algMap : algebraMap P (Localization.AtPrime q) = rho := rfl
  letI : IsScalarTower k P (Localization.AtPrime q) :=
    IsScalarTower.of_algebraMap_eq fun x => by
      rw [IsScalarTower.algebraMap_apply k S (Localization.AtPrime q) x, h_algMap,
        IsScalarTower.algebraMap_apply k R0 P x, hrho, Localization.localRingHom_to_map]
      exact congrArg (algebraMap S (Localization.AtPrime q)) (phi.commutes x).symm
  letI : Algebra.FormallySmooth R0 P :=
    Algebra.FormallySmooth.of_isLocalization q0.primeCompl
  letI : Algebra.FormallySmooth k P := Algebra.FormallySmooth.comp k R0 P
  letI : Algebra.EssFiniteType R0 P :=
    Algebra.EssFiniteType.of_isLocalization (S := P) q0.primeCompl
  letI : Algebra.EssFiniteType k P := Algebra.EssFiniteType.comp k R0 P
  letI : Module.Free P (Ω[P⁄k]) :=
    KaehlerDifferential.free_of_isLocalization_atPrime n q0
  letI : Module.Finite P (Ω[P⁄k]) := KaehlerDifferential.finite k P
  letI : IsRegularLocalRing P := inferInstance
  exact Algebra.FormallySmooth.of_surjective_of_isRegularLocalRing k
    (P := P) (A := Localization.AtPrime q) (h_algMap ▸ hrho_surj)
